soul-common/src/main/java/org/dromara/soul/common/utils/GSONUtils.java
=> fix(GsonUtils): Repair Gson from expressing integers as floats.

soul-bootstrap/src/main/java/org/dromara/soul/bootstrap/cors/HealthFilter.java, soul-web/src/main/java/org/dromara/soul/web/config/SoulConfiguration.java, soul-web/src/main/java/org/dromara/soul/web/filter/ParamWebFilter.java
原先的实现是没有问题的，但是当去掉DispatcherHandler的默认webHander后，所有请求都会被路由到soulWebHandler。会导致body为中requestDTO为空的异常。所以修改下健康检查实现。
=> fix:网关模块健康检查实现

soul-common/src/main/java/org/dromara/soul/common/constant/Constants.java, soul-common/src/main/java/org/dromara/soul/common/utils/GsonUtils.java, soul-web/src/main/java/org/dromara/soul/web/plugin/hystrix/HttpCommand.java
user/listAllUserByPage?page=1&rows=10&term={"departmentId":2,"username":"","name":"","positionId":6}
例如这样的json格式的参数，无法被webclient正常请求，{}会被识别为占位符
=> fix httpcommand doesn't support get request with json format data

soul-web/src/main/java/org/dromara/soul/web/cache/UpstreamCacheManager.java
现在的情况是当diviide插件更新url的时候，回去做check，如果check不成功，这个url不会返回到upstreamList里面；如果upstreamList为空的时候，也只是提示 divide upstream config error,日志没有反映出哪个服务不可用，所以我在check失败后添加了个日志打印；
when check url is fail,make a error message ,like "check the url=127.0.0.1:8080 is fail"
=> when check url is fail,make a error message

soul-extend-demo/pom.xml, soul-test/soul-test-dubbo/soul-test-dubbo-service/pom.xml, soul-test/soul-test-http/pom.xml, soul-test/soul-test-springcloud/pom.xml, soul-web/src/main/java/org/dromara/soul/web/filter/TimeWebFilter.java
1、当前项目的版本是2.1.2-RELEASE，发现soul-test和soul-extend-demo引用的还是2.1.1-RELEASE，更新了一下
2、TimeWebFilter计算耗时的开始时间从客户端上传的timestamp修改为RequestDTO创建时间
=> 更新soul-test使用当前的2.1.2-RELEASE版本

soul-web/src/main/java/org/dromara/soul/web/configuration/DubboConfiguration.java
虽然有GenericParamResolveService接口，但是实现后依然是无效的，因为SoulPlugin dubboPlugin bean是写死的。
=> fix DubboPlugin

.gitignore, soul-admin/pom.xml, soul-admin/src/main/java/org/dromara/soul/admin/config/DataSyncConfiguration.java, soul-admin/src/main/java/org/dromara/soul/admin/listener/nacos/NacosDataChangedListener.java, soul-admin/src/main/java/org/dromara/soul/admin/service/impl/AppAuthServiceImpl.java, soul-admin/src/main/java/org/dromara/soul/admin/service/impl/MetaDataServiceImpl.java, soul-admin/src/main/java/org/dromara/soul/admin/service/init/LocalDataSourceLoader.java, soul-admin/src/main/resources/META-INF/schema.sql, soul-admin/src/main/resources/application-local.yml, soul-bootstrap/pom.xml, soul-bootstrap/src/main/resources/application-local.yml, soul-common/pom.xml, soul-common/src/main/java/org/dromara/soul/common/dto/MetaData.java, soul-configuration/pom.xml, soul-configuration/src/main/java/org/dromara/soul/configuration/nacos/NacosACMConfig.java, soul-configuration/src/main/java/org/dromara/soul/configuration/nacos/NacosConfig.java, soul-configuration/src/main/java/org/dromara/soul/configuration/nacos/NacosConfiguration.java, soul-web/src/main/java/org/dromara/soul/web/cache/AbstractLocalCacheManager.java, soul-web/src/main/java/org/dromara/soul/web/cache/NacosCacheHandler.java, soul-web/src/main/java/org/dromara/soul/web/cache/NacosSyncCache.java, soul-web/src/main/java/org/dromara/soul/web/configuration/LocalCacheConfiguration.java, soul-web/src/main/java/org/dromara/soul/web/filter/DubboBodyWebFilter.java, soul-web/src/main/java/org/dromara/soul/web/plugin/config/PluginConfigHandler.java, soul-web/src/main/java/org/dromara/soul/web/spring/SoulPluginBeanPostProcessor.java
1.配置中心支持Nacos和阿里云ACM
2.移除数据库初始化时写死的soul数据库名称，防止误修改原有数据库数据，库名以连接时数据库为准
3.解决metaData无法修改path问题
4.metaData添加id，用于去重
5.local配置添加nacos配置中心配置
=> 配置中心支持Nacos和阿里云ACM

soul-web/src/main/java/org/dromara/soul/web/filter/DubboBodyWebFilter.java
转换有问题，当请求body为空字符串时不报错，也不给错误提示，亦无法进入dubbo插件 因此当mono为empty需要switch
=> dubbo插件当body为空无法进去

soul-common/src/main/java/org/dromara/soul/common/utils/UrlQuerys.java, soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/param/BodyParamPlugin.java, soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/param/BodyParamPlugin.java
=> dubbo支持query转body

soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java, soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessor.java, soul-client/soul-client-dubbo/soul-client-dubbo-common/pom.xml
* It will cause bootstrap get dubbo service throws no provider exception.
* Upload metadata on ApplicationReadyEvent to make sure when bootstrap get dubbo reference, the dubbo service has been exported.
=> Fix bug(#415)

soul-test/soul-test-eureka/pom.xml
spring-cloud版本与spring-boot版本不匹配导致
<details>
<summary>异常点击展开</summary>
```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.2.RELEASE.jar:5.2.2.RELEASE]
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
at …
```
=> Fix soul-test-eureka bug

soul-client/soul-client-http/soul-client-springcloud/src/main/java/org/dromara/soul/client/springcloud/config/SoulSpringCloudConfig.java, soul-client/soul-client-http/soul-client-springcloud/src/main/java/org/dromara/soul/client/springcloud/init/ContextRegisterListener.java, soul-client/soul-client-http/soul-client-springcloud/src/main/java/org/dromara/soul/client/springcloud/init/SpringCloudClientBeanPostProcessor.java, soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-springcloud/src/main/java/org/dromara/soul/springboot/starter/client/springcloud/SoulSpringCloudClientConfiguration.java
```java
mvn clean install  ： [INFO] BUILD SUCCESS
```
```yaml
soul:
springcloud:
admin-url: http://localhost:9095
context-path: /sb-demo7-api
full: true
```
```xml
2020-12-01 14:18:17.215  INFO 2964 --- [           main] o.d.s.c.s.init.ContextRegisterListener   : http context register success :{"appName":"sb-demo7-service","context":"/sb-demo7-api","path":"/sb-demo7-api/**","rpcType":"springCloud","ruleName":"/sb-demo7-api/**","enabled":true} 
```
```yaml
soul:
springcloud:
admin-url: http://localhost:9095
context-path: /sb-demo6-api
```
```xml
2020-12-01 14:21:24.470  INFO 2200 --- [pool-1-thread-1] c.s.i.SpringCloudClientBeanPostProcessor : http client register success :{"appName":"sb-demo6-service","context":"/sb-demo6-api","path":"/sb-demo6-api/user/**","pathDesc":"","rpcType":"springC …
```
=> springmvc 中有 full扫描整个服务的功能，springcloud中没有，我复刻过来的

script/soul_checkstyle.xml, soul-admin/pom.xml, soul-admin/src/test/java/org/dromara/soul/admin/AbstractSpringIntegrationTest.java, soul-admin/src/test/java/org/dromara/soul/admin/controller/SoulDictControllerTest.java, soul-admin/src/test/java/org/dromara/soul/admin/mapper/SoulDictMapperTest.java, soul-admin/src/test/java/org/dromara/soul/admin/service/SoulDictServiceTest.java, soul-admin/src/test/java/org/dromara/soul/admin/utils/AesUtilsTest.java, soul-admin/src/test/resources/META-INF/schema.sql, soul-admin/src/test/resources/application-test.yml
添加一些admin测试的样例, 目前mapper访问数据库测试暂时使用H2, 后面如果使用到mysql特性无法兼容则直接使用testcontainer
=> Add test cases for soul-admin

soul-sync-data-center/soul-sync-data-http/src/test/java/org/dromara/soul/sync/data/http/HttpSyncDataServiceTest.java, soul-sync-data-center/soul-sync-data-http/src/test/java/org/dromara/soul/sync/data/http/refresh/AppAuthDataRefreshTest.java, soul-sync-data-center/soul-sync-data-http/src/test/java/org/dromara/soul/sync/data/http/refresh/MetaDataRefreshTest.java, soul-sync-data-center/soul-sync-data-http/src/test/java/org/dromara/soul/sync/data/http/refresh/PluginDataRefreshTest.java, soul-sync-data-center/soul-sync-data-http/src/test/java/org/dromara/soul/sync/data/http/refresh/RuleDataRefreshTest.java, soul-sync-data-center/soul-sync-data-http/src/test/java/org/dromara/soul/sync/data/http/refresh/SelectorDataRefreshTest.java, soul-sync-data-center/soul-sync-data-nacos/src/test/java/org/dromara/soul/sync/data/nacos/handler/NacosCacheHandlerTest.java, soul-sync-data-center/soul-sync-data-nacos/src/test/java/org/dromara/soul/sync/data/nacos/handler/NacosMockConfigService.java, soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/plugin/sync/data/weboscket/handler/AuthDataHandlerTest.java, soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/plugin/sync/data/weboscket/handler/MetaDataHandlerTest.java, soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/plugin/sync/data/weboscket/handler/PluginDataHandlerTest.java, soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/plugin/sync/data/weboscket/handler/RuleDataHandlerTest.java, soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/plugin/sync/data/weboscket/handler/SelectorDataHandlerTest.java, soul-sync-data-center/soul-sync-data-zookeeper/src/test/java/org/dromara/soul/sync/data/zookeeper/ZookeeperSyncDataServiceTest.java
#945 
assertEquals() has been Modified to assertThat()
Use inline import static class in test case , just like import static org.mockito.Mockito.mock;, import static org.junit.Assert.assertTrue;
Delete unnecessary blank lines.
Optimize the java doc.
There is no obvious yellow warning of IDEA.
Remove the final variable Inside the method.
Use constants for all string variables.
English words should be expressed clearly. for example : setUp maybe to setup.
=> optimize the test code in soul-sync-data-center

soul-spi/src/main/java/org/dromara/soul/spi/ExtensionLoader.java, soul-spi/src/test/java/org/dromara/soul/spi/ExtensionLoaderTest.java
#945
optimize the soul test class in module soul-spi.  
refer to this optimize rules:
1. assertEquals() must be Modified to assertThat()
2. must use inline import static class in test case
3. Delete unnecessary blank lines
4. Optimize the java doc
5. There should be no obvious yellow warning of IDEA
6. remove final variable Inside the method
7. use constants for all string variables
8. English words should be expressed clearly. for example : setUp maybe to setup
9. all test class maybe add final modifier
=> optimize the test class in module soul-spi (issue#945)

soul-metrics/soul-metrics-facade/pom.xml, soul-metrics/soul-metrics-prometheus/pom.xml, soul-plugin/soul-plugin-base/pom.xml, soul-plugin/soul-plugin-divide/pom.xml, soul-plugin/soul-plugin-monitor/pom.xml, soul-web/pom.xml
Below is the removed duplicate dependencies check list：
- soul-web/pom.xml:   				soul-plugin-api
- soul-plugin/soul-plugin-base: 		soul-common
- soul-metrics/soul-metrics-facade:	soul-spi & soul-metrics-spi
- soul-plugin-monitor:				soul-spi & soul-metrics-prometheus
This is the current component dependencies diagram:
I removed the dependency represented by the red line. After removed duplicate dependencies:
=> Remove duplicate dependencies for pom.xml.

soul-admin/src/main/java/org/dromara/soul/admin/listener/http/HttpLongPollingDataChangedListener.java, soul-web/src/test/java/org/dromara/soul/web/filter/FileSizeFilterTest.java
Fixes #867 
Add test for FileSizeFilter, and change the initialCapacity for the changedGroup list (because ConfigGroupEnum has 5 elements).
=> Add test for FileSizeFilter, and change the initialCapacity for the changedGroup list.

soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-springcloud/pom.xml, soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-springcloud/src/test/java/org/dromara/soul/springboot/starter/plugin/springcloud/SpringCloudPluginConfigurationTest.java
test: Add test case for SpringCloudPluginConfiguration.
#878 
=> test: Add test case for SpringCloudPluginConfiguration.

soul-examples/soul-examples-grpc/pom.xml, soul-examples/soul-examples-tars/src/main/java/org/dromara/soul/examples/tars/servant/testapp/HelloServant.java, soul-examples/soul-examples-tars/src/main/java/org/dromara/soul/examples/tars/servant/testapp/impl/HelloServantImpl.java, soul-examples/soul-examples-tars/src/main/resources/test.tars, soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/cache/ApplicationConfigCache.java, soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/util/ReturnValueResolver.java
Now, It will occur the follow exception when the return value of `tars ` method is `int`:
```
@SoulTarsClient(path = "/helloInt")
public int helloInt(int no, String name) {
return 1;
}
```
<details>
<summary>Click to see error log</summary>
```
java.lang.ClassNotFoundException: int
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.dromara.soul.plugin.tars.cache.ApplicationConfigCache.initPrx(ApplicationConfigCache.java:132)
at org.dromara.soul.plugin.tars.subscriber.TarsMetaDataSubscriber.onSubscribe(TarsMetaDa …
```
=> Make the return value of tars compatible with primitive types

soul-bootstrap/src/main/resources/application-local.yml
the configuration item for soul-bootstrap about cross is not correct, so can not register CrossFilter and do not support cors.
```
/**
* Cross filter web filter.
* if you application has cross-domain.
* this is demo.
* 1. Customize webflux's cross-domain requests.
* 2. Spring bean Sort is greater than -1.
*
* @return the web filter
*/
@Bean
@Order(-100)
@ConditionalOnProperty(name = "soul.cross.enabled", havingValue = "true")
public WebFilter crossFilter() {
return new CrossFilter();
}
```
=> Cross-domain configuration correction

soul-admin/src/main/java/org/dromara/soul/admin/listener/websocket/WebsocketCollector.java, soul-admin/src/main/java/org/dromara/soul/admin/listener/websocket/WebsocketConfigurator.java, soul-admin/src/main/java/org/dromara/soul/admin/listener/websocket/WebsocketListener.java, soul-sync-data-center/soul-sync-data-websocket/src/main/java/org/dromara/soul/plugin/sync/data/websocket/WebsocketSyncDataService.java
=> fix issue1212

soul-register-center/soul-register-client/soul-register-client-nacos/src/test/java/nacos/NacosClientRegisterRepositoryTest.java
=> add test for nacos register center client

soul-common/src/main/java/org/dromara/soul/common/dto/SelectorData.java
Fixes #1238
Fix the problem in OpenJDK (for example, version 1.8.0_65-b17): Caused by: org.I0Itec.zkclient.exception.ZkMarshallingError: java.io.InvalidClassException: org.dromara.soul.common.dto.SelectorData; local class incompatible: stream classdesc serialVersionUID = 6055627969752212141, local class serialVersionUID = 760613690421794874
=> Add serialVersionUID to SelectorData 

.github/actions/skip-ci/action.yml, .github/release-drafter-config.yml, .github/workflows/ci.yml
Currently we simply configure the `paths-ignore` property to skip the workflows. but we make ci action "required" for status check while saving resources for some changes like "*.md". so the committer can't merge pr because of the required status. This patch check the changed files of a pull request and set SKIP_CI to skip the workflows.
reference: [skywalking](https://github.com/apache/skywalking/blob/master/.github/workflows/ci-it.yaml)
=> Add skip ci action script

soul-admin/src/main/java/org/dromara/soul/admin/service/impl/MetaDataServiceImpl.java
fix: In the meta data form, the path description field is not required, but in the database table , the path_desc field is not null. #1363
=> fix issue 1363

.gitmodules, pom.xml, soul-admin/pom.xml
Currently soul and soul-dashboard were released separately. Avoid to update the submodule every time the `soul-dashboard` changed. I suggest that remove it for now.
=> Remove soul-dashboard submodule

soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/algorithm/ConcurrentRateLimiterAlgorithm.java, soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/executor/RedisRateLimiter.java
update RedisRateLimiter error log.
and
because AbstractRateLimiterAlgorithm#getKeys
```java
@Override
public List<String> getKeys(final String id) {
String prefix = getKeyName() + ".{" + id;
String tokenKey = prefix + "}.tokens";
String timestampKey = prefix + "}.timestamp";
return Arrays.asList(tokenKey, timestampKey);
}
```
keep ConcurrentRateLimiterAlgorithm have same rateLimiter KeyResolver
=> update RedisRateLimiter error log.

shenyu-examples/shenyu-examples-dubbo/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/TestAlibabaDubboAnnotationApplication.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/resources/application.yml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/TestApacheDubboAnnotationApplication.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/resources/application.yml
Associate with issues #1466
* Add alibaba dubbo example with annotation.
* Add apache dubbo example with annotation.
=> Add dubbo example with annotation

shenyu-web/src/main/java/org/apache/shenyu/web/filter/support/BodyInserterContext.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/support/CachedBodyOutputMessage.java
Fixes #1475 The hyperlinks of BodyInserterContext and CachedBodyOutputMessage are wrong.
=> fixes #1475 the wrong hyperlinks 

shenyu-admin/src/main/resources/META-INF/schema.h2.sql, shenyu-admin/src/main/resources/META-INF/schema.sql
As the front page has bean refactored in https://github.com/dromara/shenyu-dashboard/pull/123, the dic type `ruleHandlePageType` is no longer useful.
=> Clean unused resource for shenyu-dashbord

.github/workflows/integrated-test-http.yml
Using while loop to wait and check if docker compose start up all containers.
On Ubuntu, the `docker compose up -d` only create all containers but do not start them up. So sometimes the integrated tests failed.
=> Update integrated CI to make sure docker compose start up all containers

shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/test/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataServiceTest.java
Fix bug(#1717), when sync data by zookeeper, it will throw ClassCastException.
=> [ISSUE #1717]Fix bug(#1717), when sync data by zookeeper, it will throw ClassCastException

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/SecretProperties.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/AesUtils.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/CipherUtils.java, shenyu-admin/src/main/resources/META-INF/schema.h2.sql, shenyu-admin/src/main/resources/META-INF/schema.sql, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/DashboardUserControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/DashboardUserMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DashboardUserServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/utils/AesUtilsTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/utils/CipherUtilsTest.java, shenyu-dist/shenyu-admin-dist/src/main/resources/application.yml
1. Duplicate alignment of plaintext is not reflected in ciphertext
2. Support parallel computation (decryption only)
3. Ability to decrypt any ciphertext grouping
4. CBC is Widely used
1. PKCS5Padding and PKCS7Padding are basically the same
2. PKCS7Padding does  not support native java , need to add dependency
=> [ISSUE #1740] Fix bug #1740. Replace The Risky Cryptographic Algorithm  ECB to CBC

shenyu-admin/src/main/resources/application.yml
- fix shenyu-admin: application.yml add `aes.secret. iv` configuration.
=> [ISSUE #1749] Add missing `aes.secret.iv` configuration.

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
fix #1770 
The webclient will encode the incoming string type parameters, which will cause an error, we need to use the URI object.
=> [ISSUE #1770] Solve the problem of duplicate URL-encoding

shenyu-dist/shenyu-admin-dist/entrypoint.sh
When I try to setup integrated test environment on Windows, I got error:
```
shenyu-admin exited with code 1
shenyu-admin                 | Please check the log files: /opt/shenyu-admin/logs
': No such file or directory | tail: can't open '/opt/shenyu-admin/logs/shenyu-admin.log
shenyu-admin                 | tail: no files
```
But actually shenyu-admin has already created this file. The root cause is that, when we try to run `tail -f`, it can not read the file which was not created even shenyu-admin created it later.
So we must create the file and update the file mod to make sure it works as expected on Windows platform, specially on Docker based on Windows WSL.
=> Fix BUG: Cannot startup shenyu-admin docker on Windows

pom.xml, shenyu-common/src/main/java/org/apache/shenyu/common/healthcheck/HealthCheckTask.java, shenyu-common/src/test/java/org/apache/shenyu/common/healthcheck/HealthCheckTaskTest.java
1. Fix the deadlock bug of HealthCheckTask.
2. Add test of HealthCheckTask of issue [#1827](https://github.com/apache/incubator-shenyu/issues/1827)
Add awaitility dependency for synchronizing asynchronous operations, it's a very common test tools.
=> [ISSUE #1827] Fix deadlock bug of HealthCheckTask and add HealthCheckTaskTest.

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java
- Add close method to cleanup relative resource when container destroy.
- Reduce the scheduled thread count from CPU count to 1.
=> Add close method to cleanup resource and reduce the scheduled thread count

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java
##Motivation
- Fix flaky test UpstreamCheckServiceTest#testScheduled
UpstreamCheckServiceTest will setup below config:
```
Properties properties = new Properties();
properties.setProperty(Constants.IS_CHECKED, "true");
shenyuRegisterCenterConfig.setProps(properties);
```
UpstreamCheckServiceTest will init UpstreamCheckService and invoke UpstreamCheckService#scheduled with fix delay.
UpstreamCheckServiceTest#testScheduled will invoke method `scheduled` manually which may be potential simultaneous with fix delay. this means:
```
zombieSet.clear();    // called by test thread.
setupZombieSet();     //  after here,  zombieSet is 2
upstreamMap.clear(); 
setupUpstreamMap();   // this will fill upstreamMap with 2 DivideUpstream objects. If `executor fix delay` called method `scheduled` before …
```
=> Fix flaky test UpstreamCheckServiceTest#testScheduled

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DataPermissionController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PermissionController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java, shenyu-plugin/shenyu-plugin-monitor/src/main/java/org/apache/shenyu/plugin/monitor/MonitorPlugin.java, shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/RateLimiterAlgorithmFactory.java
##Motivation
- Replace orElse with orElseGet to avoid calling too many times if the else is not a constant variable.
=> refactor : replace orElse with orElseGet to avoid calling too many times

shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfiguration.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java, shenyu-web/src/test/java/org/apache/shenyu/web/filter/CrossFilterTest.java, shenyu-web/src/test/java/org/apache/shenyu/web/filter/WebSocketParamFilterTest.java, shenyu-web/src/test/java/org/apache/shenyu/web/handler/ShenyuWebHandlerTest.java
using `shenyu.cros-filter-config.*` config the cors filter:
```yml
shenyu:
cros-filter-config:
allowed-headers: qicz, custom
allowed-expose: *
allowed-methods: *
allowed-origin: *
max-age: 18000
```
the `allowed-headers` default is `x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN, token, username, client`.
the external config will append to the `allowed-headers`.  the example of `allowed-headers` = `x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN, token, username, client,  qicz, custom`.
=> [ISSUE #2001] support external cros filter config. 

shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java
Fix #2014 , validate the `context path` before `buildContextPath`.
if the `context path` is invalid response follow error:
```json
{
"code": -111,
"message": "The context path illegal, please check the context path mapping plugin! [invalid context path:'/**']",
"data": null
}
```
=> [ISSUE #2014] validate the context path, fix "String index out of range" bug.

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/sign/DefaultSignProvider.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/sign/ShenyuSignProviderWrap.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/sign/SignProvider.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/sign/SignService.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/SignPlugin.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/service/DefaultSignService.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/SignPluginTest.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/sign/DefaultSignProviderTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sign/src/main/java/org/apache/shenyu/springboot/starter/plugin/sign/SignPluginConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sign/src/test/java/org/apache/shenyu/springboot/starter/plugin/sign/SignPluginConfigurationTest.java
this pr is optimized for #2015 .
you can implement the `org.apache.shenyu.plugin.api.sign.SignProvider` define the custom sign provider sign logic. 
the `org.apache.shenyu.plugin.api.sign.DefaultSignProvider` use the `org.apache.shenyu.common.utils.SignUtils#generateSign`.
=> [ISSUE #2015] Support sign plugin custom dynamic sign provider.

shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/ThreadShare.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/ThreadShareUtils.java, shenyu-plugin/shenyu-plugin-global/src/test/java/org/apache/shenyu/plugin/global/GlobalPluginTest.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/service/DefaultSignService.java, shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java, shenyu-web/src/main/java/org/apache/shenyu/web/logo/ShenyuLogo.java
Provide `ThreadShareUtils`. 
the `ThreadShareUtils` can share data for the same thread with a different name and two different threads with the same name.
the `ThreadShare` is a subclass for `ThreadLocal` and provides the `getRemove` function that does `get` and `remove` same time.
reset the plugin order, spaced by ten. `shenyu` users can insert the custom plugin between `shenyu` plugin a and `shenyu` another plugin b.
=> [type: refactor]Provide "ThreadShareUtils" and reset plugin default order.

shenyu-common/src/main/java/org/apache/shenyu/common/utils/IpUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/IpUtilsTest.java
-------------------------------------------test code----------------------------------------------------------
The original code: 
if (!ip.isLoopbackAddress()){
System.out.print(ip.getHostAddress());
System.out.print("-------");
System.out.print(netInterface.getDisplayName());
System.out.print("-------");
System.out.print(netInterface.getName());
System.out.println();
}
fe80:0:0:0:3507:b35:d4e4:ebf3%eth2-------Bluetooth Device (Personal Area Network)-------eth2
fe80:0:0:0:7881:df0f:e380:188b%wlan2-------Microsoft Wi-Fi Direct Virtual Adapter-------wlan2
172.23.39.81-------Intel(R) Ethernet Connection (3) I218-LM-------eth3
fe80:0:0:0:58b0:4f02:d55e:4f32%eth3-------Intel(R) Ethernet Connection (3) I218-LM-------eth3 …
=> Fix the IP address retrieval error

shenyu-web/src/main/java/org/apache/shenyu/web/fallback/DefaultFallbackController.java, shenyu-web/src/test/java/org/apache/shenyu/web/fallback/DefaultFallbackControllerTest.java
the default fallback `DefaultFallbackController` uses the`DefaultShenyuEntity` that can not use custom `ShenyuResult`.  fixed it by `ShenyuResultWrap`.
=> fix default fallback controller handler by "ShenyuResultWrap".

shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java, shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
the `modify response` order must be before the `response` plugin.
the `clientResponse` should be using `exchange.getAttribute(Constants.CLIENT_RESPONSE_ATTR)`. and the `modify response` plugin must be executed after `httpclient` plugin.
=> fix "modify response" plugin order bug and optimize the "clientResponse"

shenyu-common/src/main/java/org/apache/shenyu/common/utils/JsonUtils.java, shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java, shenyu-web/src/test/java/org/apache/shenyu/web/handler/GlobalErrorHandlerTest.java
fix "GlobalErrorHandler" error object to map bug by JacksonUtils.toMap.
when the "error" is complex, Gson will parse the "complex" to `Gson JsonObject`, but Spring Boot uses `jaskson` which can not process the `Gson JsonObject`.
=> fix "GlobalErrorHandler" error object to map bug by JacksonUtils.toMap.

shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java
fix bug
`2021-11-17 22:29:54 [ZkClient-EventThread-53-10.255.198.19:2181,10.255.198.16:2181,10.255.198.6:2181] ERROR org.I0Itec.zkclient.ZkEventThread - Error handling event ZkEvent[Data of /shenyu/selector/contextPath/1460961927473303552 changed sent to org.apache.shenyu.sync.data.zookeeper.ZookeeperSyncDataService$2@3d196372]
java.lang.NullPointerException: null
at org.apache.shenyu.sync.data.zookeeper.ZookeeperSyncDataService$2.handleDataChange(ZookeeperSyncDataService.java:271)
at org.I0Itec.zkclient.ZkClient$9.run(ZkClient.java:823)
at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:72)`
=> [type: bug] fix zk sync error handling event bug.

shenyu-common/src/test/java/org/apache/shenyu/common/utils/PathMatchUtilsTest.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/ExcludeOperatorJudge.java
When using the'exclude' function, users can use regular judgments, and use the 'excludePathPattern' of 'springBoot' close to the user Habit.
For example, use '/test/**' to filter the entire 'test' module.
=> [type: refactor] ExcludeOperatorJudge

shenyu-admin/src/test/java/org/apache/shenyu/admin/disruptor/subscriber/MetadataExecutorSubscriberTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/disruptor/subscriber/URIRegisterExecutorSubscriberTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/shiro/bean/StatelessAuthFilterTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/shiro/bean/StatelessTokenTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/shiro/config/ShiroConfigurationTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/shiro/config/ShiroRealmTest.java
About #1824
About #2420
following classes test code coverage:
org.apache.shenyu.admin.shiro.bean.StatelessAuthFilter(6%)
org.apache.shenyu.admin.shiro.bean.StatelessToken(0%)
org.apache.shenyu.admin.shiro.config.ShiroRealm(0%)
org.apache.shenyu.admin.disruptor.subscriber.URIRegisterExecutorSubscriber(12%)
org.apache.shenyu.admin.disruptor.subscriber.MetadataExecutorSubscriber(60%)
=> [ISSUE #1824] shenyu-admin module test coverage improvement 

.github/workflows/integrated-test.yml
Since #2393 added the `examples` module to parent pom, we can build `examples` with other module by `./mvnw -B clean install -Prelease,docker -Dmaven.javadoc.skip=true -Dmaven.test.skip=true` (Build with Maven).
But now the docker image of `examples` is build twice.
=> [type: Integration-Test] Simplify the integration test process

shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdClient.java
org.apache.shenyu.sync.data.etcd.EtcdClient method [getSubNodeKeyName] throw “StringIndexOutOfBoundsException”
Add protection measures and return null.
Fixes #2588 
=> [ISSUE #2588] org.apache.shenyu.sync.data.etcd.EtcdClient method [getSubNodeKeyName] throw “StringIndexOutOfBoundsException”

shenyu-integrated-test/shenyu-integrated-test-https/script/services.list, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCache.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java
1 . Dubbo ReferenceConfig when removed from the cache, call ReferenceConfig destroy method.
2. update services.list
=> [type:refactor]Dubbo ReferenceConfig when removed from the cache, call ReferenceConfig destroy method.

shenyu-examples/pom.xml
Let people who has mac with `apple m1 silicon` can easily compile. Otherwise the grpc plugin will error.
Compile on my `m1` and `intel` computer.
=> Adapt grpc plugin compile requirement with apple m1 silicon

pom.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/exception/ExceptionHandlersTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/websocket/WebsocketCollectorTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/zookeeper/HttpServiceDiscoveryTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/MetaDataServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDubboServiceImplTest.java, shenyu-register-center/shenyu-register-server/shenyu-register-server-consul/src/test/java/org/apache/shenyu/register/server/consul/ConsulServerRegisterRepositoryTest.java
fixes #2695 
remove powermock from the follow class:
org/apache/shenyu/admin/listener/websocket/WebsocketCollectorTest.java
org/apache/shenyu/admin/service/MetaDataServiceTest.java
org/apache/shenyu/admin/service/register/ShenyuClientRegisterDubboServiceImplTest.java 
org/apache/shenyu/register/server/consul/ConsulServerRegisterRepositoryTest.java 
org/apache/shenyu/admin/exception/ExceptionHandlersTest.java
org/apache/shenyu/admin/listener/zookeeper/HttpServiceDiscoveryTest.java
=> [ISSUE #2695]  in jdk16, PowerMock internal error: Should never throw exception at this level 

shenyu-dist/shenyu-bootstrap-dist/pom.xml, shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh
About #2699 
Changes in this pr:
1. Remove `shenyu-agent-bootstrap` in dist for 2 reasons:
- This is no necessary import `shenyu-agent-bootstrap` here.
- This will lead to some errors in `ShenyuAgentLocator.java`
2. Change `-Xss256k` in `start.sh` to `-Xss512k`:
- Beacuse with `256k`, it start failed with following logs:
- ![image](https://user-images.githubusercontent.com/62384022/148034087-adbe0372-0a99-4f2d-ac9a-73e367e07cfc.png)
3. Support starting with `shenyu-agent`.
- User can start with `shenyu-agent` using `bin/start.sh agent`
=> [ISSUE #2699] Bootstrap start.sh script support starting with `shenyu-agent`

shenyu-dist/shenyu-admin-dist/Dockerfile, shenyu-dist/shenyu-bootstrap-dist/Dockerfile, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/Dockerfile, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/Dockerfile, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/Dockerfile, shenyu-examples/shenyu-examples-eureka/Dockerfile, shenyu-examples/shenyu-examples-grpc/Dockerfile, shenyu-examples/shenyu-examples-http/Dockerfile, shenyu-examples/shenyu-examples-https/Dockerfile, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/Dockerfile, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/Dockerfile, shenyu-examples/shenyu-examples-springcloud/Dockerfile, shenyu-examples/shenyu-examples-springmvc/Dockerfile, shenyu-examples/shenyu-examples-websocket/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-opentelemetry/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-combination/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-grpc/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-http/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-https/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-motan/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-sofa/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-spring-cloud/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-websocket/Dockerfile, shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/Dockerfile, shenyu-integrated-test/shenyu-integration-test-apache-dubbo/Dockerfile
=> [ISSUE #2719] Docker image support arm architecture

.github/workflows/integrated-test-agent-tracing.yml, pom.xml, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/pom.xml
1. shade for opentelemetry plugin in agent
2. remove `okhttp` in dependencyManagement, because it will cause opentelemetry-jaeger-exporter to rely on the wrong version of okhttp.
=> [type: refactor] shade for opentelemetry plugin in agent

shenyu-integrated-test/shenyu-integrated-test-alibaba-dubbo/src/test/java/org/apache/shenyu/integrated/test/alibaba/dubbo/AlibabaDubboPluginMultiParamTest.java, shenyu-integrated-test/shenyu-integrated-test-apache-dubbo/src/test/java/org/apache/shenyu/integrated/test/alibaba/dubbo/ApacheDubboPluginMultiParamTest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/ComplexBeanTest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/ComplexBeanTestWithNameRequest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/DubboTestListRequest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/DubboTestListWithIdAndNameRequest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/IdStringArrayRequest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/IdStringListRequest.java
#2680 
1. Add integrated test for DubboMultiParamService in shenyu-examples-apache-dubbo-service
2. Add integrated test for DubboMultiParamService in shenyu-examples-alibaba-dubbo-service
=> [Task #2680] Add integration test for more dubbo api DubboMultiParamService

pom.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/AbstractDataChangedListenerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java
powermock doesn't work anymore in Java 17. In java 16, you must add --illegal-access=permit to ensure powerMock executes successfully. otherwise, "RuntimeException: PowerMock internal error: Should never throw exception at this level" will occurs.
we need to get rid of PowerMock in unit tests.
this issue will remove powermock in shenyu pom.xml.
remove powermock in pom.xml
remove AbstractDataChangedListenerTest Whitebox
remove UpstreamCheckService @PrepareForTest
=> [ISSUE #2793] remove powermock in shenyu pom.xml #2793

script/shenyu_checkstyle.xml
In junit 5,Some new annotations have be used, such as:
@ BeforeEach, @ AfterEach, @ BeforeAll, @ AfterAll, @ ParameterizedTest, @ TestMethodOrder.
Therefore, the shenyu_checkstyle.xml file must be modified.
Fixes #2827 
=> [ISSUE 2827] shenyu_checkstyle.xml does not support annotations from junit5

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDivideServiceImpl.java
This bug has been fixed in version 2.4.2. But the code can still be optimized, because when the handler is [], there is no need to iterate and compare again to get diffList.
=> [ISSUE 2754] refactor admin buildHandle about register uri.

shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/test/java/org/apache/shenyu/register/client/http/OkHttpToolsTest.java, shenyu-sync-data-center/shenyu-sync-data-consul/pom.xml, shenyu-sync-data-center/shenyu-sync-data-etcd/pom.xml, shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/HttpSyncDataServiceTest.java, shenyu-sync-data-center/shenyu-sync-data-websocket/pom.xml, shenyu-sync-data-center/shenyu-sync-data-zookeeper/pom.xml
About #2830 , remove dup dependencies in sub-moduels.
=> [ISSUE 2830] Update junit4 to junit5 - remove dup dependencies in sub-modules and make wire-mock compatible

shenyu-admin/src/main/java/org/apache/shenyu/admin/transfer/PluginTransfer.java, shenyu-common/src/main/java/org/apache/shenyu/common/dto/PluginData.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriber.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/SortPluginEvent.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfiguration.java, shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/PluginDataRefresh.java, shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java
Synchronize sorting of plugins. #2892 
1. update plugin sort in admin, the order of ShenyuWebHandler’s plugins have changed.
2. After the plug-in sequence changes. After restart, the sequence is the same.
3. When the plugins of ShenyuWebhandler changes, the ongoing requests will not be affected.
1. admin use mysql and run admin.
2. Run gateway ShenyuBootstrapApplication.
3. Run test demo of ShenyuTestHttpApplication.
4. now send a request to gateway.
`curl --location --request POST 'http://localhost:9195/http/order/save?a=1' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=302C524F06306C42AE4DB7A7D9716BF4' \
--data-raw '{
"id":666,
"name": "hello world"
}'`
debug ShenyuWebHander handler method, we find the sign plugin is before jwt plugin.
5. now we change jwt …
=> [Volunteer #2892] Synchronize sorting of plugins.

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/WebsocketSyncProperties.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketCollector.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketConfigurator.java, shenyu-admin/src/main/resources/application.yml
1. config admin prop:   shenyu.sync.websocket.messageMaxSize=**10240**
2. setup admin:run ShenyuAdminBootstrap
3. setup gateway: run ShenyuBootstrapApplication
4. you can see: admin log output: websocket on client[127.0.0.1] open successful,maxTextMessageBufferSize:**10240**
=> [type: bug]The trouble of big data in Websocket. #2891

shenyu-plugin/shenyu-plugin-monitor/src/main/java/org/apache/shenyu/plugin/monitor/handler/MonitorPluginDataHandler.java
Remove the host checksum so that the gateway in the cluster can start the monitoring service.
The location of the image displayed in the above configuration plugin is possible without the configuration of host.
Checking the source code also allows not to configure the host.
But this line of code checks that the host must be configured, which is obviously not correct
=> Remove the  host checksum

shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/Executor.java, shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutorTest.java
For #2937 , 
- fixed the redirect issue.
- verified if the `fallbackUri` is the same with request uri to avoid redirect loop.
After this PR, it will redirect to the real `fallbackUri` set in `admin` portal.
=> fix fallbackUri only works for APIs in `shenyu-bootstrap` in resilience4j plugin issue

shenyu-common/src/main/java/org/apache/shenyu/common/utils/UriUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/UriUtilsTest.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SentinelPluginTest.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/fallback/FallbackHandler.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/fallback/FallbackHandlerTest.java, shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/Resilience4JPlugin.java, shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/Executor.java, shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutorTest.java, shenyu-plugin/shenyu-plugin-sentinel/src/main/java/org/apache/shenyu/plugin/sentinel/fallback/SentinelFallbackHandler.java, shenyu-plugin/shenyu-plugin-sentinel/src/test/java/org/apache/shenyu/plugin/sentinel/fallback/SentinelFallbackHandlerTest.java
…to reduce dup code
For #2966 . Finished below items. After this change, the fallback URI in `sentinel` plugin can support redirecting to external URIs.
- support redirect to URIs not in bootstrap.
- refactor to reduce dup codes in resilience4j and sentinel plugin.
- add related unit test.
- add related integrated test.
=> [ISSUE #2966] support redirecting to URIs outside of bootstrap and refactoring code.

pom.xml
https://www.mail-archive.com/announce@apache.org/msg06740.html
We should update to Apache Shiro 1.8.0.
=> [type:fix] fix CVE-2021-41303

shenyu-common/src/test/java/org/apache/shenyu/common/utils/GsonUtilsTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/JsonUtilsTest.java
**Description**
2 flaky(possible to fail under different OS's / future Java versions) tests are found using Nondex when running commands ```mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest={test}``` , where the 2 tests are `common.utils.GsonUtilsTest.testToJson` and `common.utils.JsonUtilsTest.toJson`. The test flakiness is due to direct comparisons between Json Strings and outputs from `JsonUtils.toJson()` and `GsonUtils.getInstance().toJson()`. However, JsonObject-likes do not guarantee entry orders (set-like construction), and internal permutations may occur in the output from `toJson()`. 
**Proposed Fixes**
Using `JsonParser.parse()` to convert string-formed Json's into rigid `JsonElement` before direct comparison.
=> Fixed Possible Json Ordering Permutations in Tests

shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
#3002 fix failed to register Dubbo protocol interface with Shenyu Admin in specific scenario. 
For example：After using the third-party jar(redisson-spring-boot-starter),failed to register Dubbo protocol interface with Shenyu Admin.
=> #3002 fix failed to register Dubbo protocol interface with Shenyu Admin in specific scenario.

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultWrap.java, shenyu-web/src/main/java/org/apache/shenyu/web/fallback/DefaultFallbackController.java
part of #2990 supplement
In the previous code, the system can only be blown, but it cannot achieve fallback  
```
2022-03-11 15:21:19 [boundedElastic-1] ERROR org.apache.shenyu.plugin.hystrix.HystrixPlugin - hystrix execute have circuitBreaker is Open! groupKey:/http,commandKey:/test/waf/pass
2022-03-11 15:21:19 [boundedElastic-3] ERROR org.apache.shenyu.plugin.hystrix.HystrixPlugin - hystrix execute have circuitBreaker is Open! groupKey:/http,commandKey:/test/waf/pass
2022-03-11 15:21:19 [boundedElastic-1] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - hystrix selector success match , selector name :testHy
2022-03-11 15:21:19 [boundedElastic-3] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - hystrix selector success match , selector name :testHy
2022-03-11 15:21:19 …
```
=> [ISSUE #2931]The URL returned by default after adding the hystrix and resilience4j

shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimitedLinkedBlockingQueue.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimiter.java, shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/MemoryLimitedLinkedBlockingQueueTest.java
see #3026 , in `org.apache.shenyu.common.concurrent.MemoryLimitedLinkedBlockingQueueTest`, I write a simple example to tell what it can do. In short, for example, it can limit the maximum memory of the queue used by the `ThreadPoolExecutor` to `100MB`, which is more reliable than the traditional queue(like `LinkedBlockingQueue`) to control the memory through the number of queues.
=> [ISSUE #3026] part1: support MemoryLimitedLinkedBlockingQueue

shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml
=> [ISSUE #3088]Standardize sql statement format in xml file

shenyu-admin/src/main/resources/mappers/user-role-sqlmap.xml
=> [ISSUE:3088] format SQL 

shenyu-admin/src/main/resources/mappers/auth-path-sqlmap.xml
=> fix #3088,format SQL

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractContextPathRegisterService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImpl.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/PathUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/PathUtilsTest.java
For #2969 , mainly done following things.
1. moved `PathUtils` from shenyu-admin to shenyu-common.
2. changed path from `contextPath` to `PathUtils.decoratorPath(contextPath)` to make it using `matches` operator.
After this change, when setting `isFull` to true, the condition in rule will use `matches` operator like below.
```
uri mathces /springcloud/**
// or
uri matches /http/**
```
=> [ISSUE #2969] fix isFull not working in springcloud and http application

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/SwaggerConfiguration.java
Related pr, https://github.com/apache/incubator-shenyu/pull/905/files
And we don't have maven build-info goal in shenyu-admin, so I use VersionUtil.getVersion to replace and simplify it.
=> [refactor ]fix swagger version, and use VersionUtils to replace and simplify it

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/MetaDataMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/transfer/MetaDataTransfer.java, shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/MetaDataMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/MetaDataServiceTest.java
Fix bug, when disable metaData.
```java
public String enabled(final List<String> ids, final Boolean enabled) {
Set<String> idSet = Optional.ofNullable(ids).orElseGet(ArrayList::new)
.stream().filter(StringUtils::isNotEmpty).collect(Collectors.toSet());
if (CollectionUtils.isEmpty(idSet)) {
return AdminConstants.ID_NOT_EXIST;
}
List<MetaDataDO> metaDataDoList = Optional.ofNullable(metaDataMapper.selectByIdSet(idSet)).orElseGet(ArrayList::new);
if (idSet.size() != metaDataDoList.size()) {
return AdminConstants.ID_NOT_EXIST;
}
List<MetaData> metaDataList = metaDataDoList.stream()
.map(MetaDataTransfer.INSTANCE::mapToData)
.collect(Collectors.toList());
metaDataMapper.updateEnableBatch(idSet, enabled);
// the element in metaDataList still be enabled when disable metaData …
```
=> [type:bug]Sync data error when disable metaData.

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/HystrixPluginTest.java
related pr: #2985 
With Jooks-me's reminder, I noticed an occasional bug in the integration tests of the hystrix plugin.
From my research, I think this is a bug inside hystrix. The overall logic of the test case is correct. The semaphore in the test case is limited to 1. When there is a new request for access, it will be directly blown and the corresponding prompt information will be returned. Other friends are also welcome to help review this issue.
I submitted a patch pr, perhaps this will reduce the probability of testing errors. If anyone's CI is having issues with the hystrix plugin test bug, please @erdengk on GitHub.
thank you very much
=> [tpye:refactor #2985]Fix Hystrix-plugin tests failure

shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimitCalculator.java
this PR optimize the performance of `MemoryLimitCalculator#maxAvailable`.
=> [type:refactor] optimize the performance of MemoryLimitCalculator#maxAvailable

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemorySafeLinkedBlockingQueue.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemorySafeTaskQueue.java, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/MemorySafeLinkedBlockingQueueTest.java, shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/cache/MetaDataCache.java, shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ShenyuThreadPoolConfiguration.java
=> [ISSUE #3303] [type:refactor] add MemorySafeTaskQueue

shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimiter.java, shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/MemoryLimiterTest.java
Issue #3318 , fix `MemoryLimiter.acquireInterruptibly` keep waiting unexpectedly error. Add an unit test class `MemoryLimiterTest`
=> [ISSUE #3318] Fix keep waiting for acquiring memory unexpectedly 

shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonServerServiceInterceptor.java, shenyu-integrated-test/shenyu-integrated-test-grpc/src/test/java/org/apache/shenyu/integrated/test/grpc/GrpcPluginTest.java, shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/proto/MessageWriter.java, shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/proto/ShenyuGrpcResponse.java
Fixes #3374 
Compatible with low version and output standard format json
```java 
if (requestMarshaller instanceof MethodDescriptor.PrototypeMarshaller) {
MethodDescriptor.PrototypeMarshaller<?> prototypeMarshaller = (PrototypeMarshaller<?>) requestMarshaller;
if (Objects.isNull(prototypeMarshaller.getMessagePrototype())) {
throw new ShenyuException(String.format("can not get defaultInstance Field of %s", requestMarshaller.getClass()));
}
grpcRequestParamClass = prototypeMarshaller.getMessagePrototype().getClass();
}
```
Lower versions do not have this field `serviceName` to throw exceptions
No exception is thrown if the field is empty, and the service name is set if the field is not empty.
=> [fix:compatibility #3374]grpc plugin compatible with low version and output standard format json

shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcClientBeanPostProcessor.java, shenyu-examples/shenyu-examples-grpc/src/main/http/grpc-class-annotation-test-api.http, shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/demo/EventServiceImpl.java, shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/demo/HelloServiceImpl.java, shenyu-examples/shenyu-examples-grpc/src/main/resources/proto/event.proto, shenyu-examples/shenyu-examples-grpc/src/main/resources/proto/hello.proto
Task #3407
add the logic of annotation on the splicing class for all rpc shenyu client: subtask-grpc
---
test:
1.startup admin,startup gateway, startup example grpc
case in file: `shenyu-examples/shenyu-examples-grpc/src/main/http/grpc-class-annotation-test-api.http`
`
curl --location --request POST 'http://localhost:9195/grpc/helloService/hello' \
--header 'Content-Type: application/json' \
--data-raw '{
"data":[
{
"data": "zhangsan"
}
]
}'
`
---
`curl --location --request POST 'http://localhost:9195/grpc/helloService/helloEveryOne' \
--header 'Content-Type: application/json' \
--data-raw '{
"data": [
{
"data": "zhangsan"
},
{
"data": "lisi"
}
]
}'`
`
curl --location --request POST 'http://localhost:9195/grpc/unaryFun' \
--header 'Content-Type: application/json' \ …
=> [Task #3407] add the logic of annotation on the splicing class: gRPC

shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperClient.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java
For #3475 , related issue and PR links: #3461  #3470.
This PR has done following things,
- replace `CuratorCache` with `TreeCache`, which class is both exists in ver 4.0.1 and 5.2.1.
- test and make sure all works well for bootstrap zk data sync in my local machine.
Welcome to test and let me know if any comment. Thank you!
=> [ISSUE #3475] Fix sofa, motan and dubbo don't work issue caused by Curator version incompatible in bootstrap

.github/workflows/docker-publish.yml
This PR is intended to build docker image for every PR and publish it to `ghrc.io`.
it is helpful for building CI in sub-repos, like shenyu-nginx.
=> [type:feature] add github flow to publish docker image to ghcr.io

pom.xml, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/zookeeper/HttpServiceDiscovery.java, shenyu-bootstrap/pom.xml, shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/pom.xml, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-zookeeper/src/main/java/org/apache/shenyu/register/client/server/zookeeper/ZookeeperClient.java, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-zookeeper/src/main/java/org/apache/shenyu/register/client/server/zookeeper/ZookeeperClientServerRegisterRepository.java, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-zookeeper/src/test/java/org/apache/shenyu/register/client/server/zookeeper/ZookeeperClientTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/pom.xml, shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClient.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/test/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientTest.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/main/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperClient.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/test/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperClientTest.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/pom.xml
For #3556 , all tasks should be finished and the pom should be cleaned. I also changed `zookeeper` dep to `3.5.7` because the curator ver `4.3.0` depends on it. I've tested below functions and they're works well. Welcome to help to test these or others test cases!
=> [ISSUE #3556] downgrade curator version to 4.3.0 to compatible with some plugin like sofa

.github/workflows/integrated-test.yml, shenyu-integrated-test/shenyu-integrated-test-http/config/broker.conf, shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-http/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RocketMqPluginTest.java
This pr is used to test whether rocketmq is integrated into shenyu.
The test case steps are as follows:
1. Add a message to rocketmq
2. Consume this information
If the consumption is successful, it means that rocketmq is integrated into shenyu. If the consumption fails, an exception will be thrown, indicating that there is a problem with rocketmq.
=> [type:Integration Test] add integrated-test of logging-rocketmq-plugin

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java, shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
Fixes #3686 and #3687 
through exchange is deprecated, this can use normally and can't NPE and cause file can't open.
ExchangeToMono has two questions: #3686 and #3687
=> [type:fixbug] fix exchange NPE and file cannot open

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/pom.xml
Fix Shenyu plugin logging aliyun SLS duplicate declaration org.springframework: spring-test.
=> [type:bug] Fix Shenyu plugin logging aliyun SLS duplicate declaration org.springframework: spring-test

pom.xml, script/shenyu_checkstyle.xml
task1 also. [#3697](https://github.com/apache/incubator-shenyu/issues/3697)
=> [type:bug] fix not find license-header path in child module.

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java
Dear Community:
I have finished task [#3741](https://github.com/apache/shenyu/issues/3741)
please review code.
like this  test case ,request uri `/http/shenyu/client/hi` can match 3 rule result. please review to confirm whether it is allowed
```java
PathPatternPredicateJudge:ConditionData{paramType='uri', operator='pathPatter', paramName='/', paramValue='/http/test/**'},realData:/http/shenyu/client/hi
PathPatternPredicateJudge:ConditionData{paramType='uri', operator='pathPatter', paramName='/', paramValue='/http/request/**'},realData:/http/shenyu/client/hi
PathPatternPredicateJudge:ConditionData{paramType='uri', operator='pathPatter', paramName='/', paramValue='/http/order/path/**'},realData:/http/shenyu/client/hi
```
=> [ISSUE #3741] use pathPatter as default rule condition operator

.github/workflows/docker-publish-dockerhub.yml, .github/workflows/docker-publish.yml
~[docker-publish workflow](https://github.com/apache/incubator-shenyu/actions/workflows/docker-publish.yml) run every time new commits merged into master.~ And this workflow can only push image to "ghcr.io", which means that images need pushed to dockerhub manually if there is a new release.
~Additionally, images on ghcr.io use "github.sha" as label.~
Update as below:
* Add new workflow to publish image to dockerhub.
* Use "release published" as trigger event.
* Use "github.ref_name" instead of "github.sha" in new workflow. ref: [get-the-current-pushed-tag-in-github-actions](https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions).
* ~Still use "build-push-action", push images to multi-registries. ref: [build-push-action : …
=> [type: feat] update docker-publish workflow, make it only push image when release

shenyu-plugin/shenyu-plugin-mock/src/test/java/org/apache/shenyu/plugin/mock/generator/CurrentTimeGeneratorTest.java
Fix the problem that the unit test of CurrentTimeGenerator is unstable.
=> [type:test] Fix the unit test for CurrentTimeGenerator

shenyu-register-center/shenyu-register-client/shenyu-register-client-consul/src/main/java/org/apache/shenyu/register/client/consul/ConsulClientRegisterRepository.java
For #3796 , fix consul registration can only register 1 metadata issue.
=> [ISSUE #3796] [fix] Shenyu client registration by consul only register 1 metadata

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/WebsocketSyncProperties.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketConfigurator.java, shenyu-admin/src/main/resources/application.yml, shenyu-bootstrap/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-alibaba-dubbo/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-apache-dubbo/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-combination/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-https/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-motan/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-sofa/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-websocket/src/main/resources/application-local.yml, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/WebsocketSyncDataService.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/client/ShenyuWebsocketClient.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/config/WebsocketConfig.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/test/java/org/apache/shenyu/plugin/sync/data/websocket/config/WebsocketConfigTest.java
Dear Community:
I have finished  [#3794](https://github.com/apache/shenyu/issues/3794)
please review code.
=> [ISSUE #3794] websocket datasync can chose allow origin to avoid CSRF

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java, shenyu-common/src/main/java/org/apache/shenyu/common/enums/OperatorEnum.java, shenyu-common/src/test/java/org/apache/shenyu/common/enums/OperatorEnumTest.java, shenyu-plugin/shenyu-plugin-base/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.base.condition.judge.PredicateJudge, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/judge/PredicateJudgeFactoryTest.java
Spi does not match sql script config, therefore selector or ruler that added in admin with 'pathPattern' value cannot work.
=> [ BUG ] bug fix: spi does not match sql script config.

shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/annotation/ShenyuDubboService.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/annotation/ShenyuService.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboClassTestServiceImpl.java
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Fixes #3805
=> [ISSUE #3805] Add `ShenyuService` and `ShenyuDubboService` annotations for shenyu-client-apache-dubbo

shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/config/ShenyuClientConfig.java
=> [ISSUE #3862] Change NullPointException to be explicit

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/converter/AbstractSelectorHandleConverter.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/LoadServiceDocEntryImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/SwaggerDocParser.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/RoleControllerTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/ConfigDataTest.java
=> [type: refactor] Optimize code. 

shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/RequestPlugin.java, shenyu-plugin/shenyu-plugin-request/src/test/java/org/apache/shenyu/plugin/request/RequestPluginTest.java
Fixes #3870
- fix request plugin can't replaceCookie bug
- add test case for request plugin ensure the replacement cookie rules meet expectations
=> [ISSUE #3852] bug fix , request plugin can't replaceCookie 

.github/workflows/codeql-analysis.yml
CodeQL Action v1 will be deprecated on December 7th, 2022.
For more information, see
[Code scanning: deprecation of CodeQL Action v1](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/)
=> upgrade codeql to v2.

.github/workflows/issue-translation.yml
Issue makers use their mother language, and not comment again and edit again fast. Maybe the action is useful. 
[issues-translator](https://github.com/marketplace/actions/issues-translator)
=> issue transtator action.

shenyu-dist/shenyu-admin-dist/Dockerfile, shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.sh, shenyu-dist/shenyu-bootstrap-dist/Dockerfile, shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh
Resolve #3916
Use environment variables to pass JVM parameters, corresponding to `SHENYU_ADMIN_JAVA_OPTS` in `shenyu-admin` and `SHENYU_BOOTSTRAP_JAVA_OPTS` in `shenyu-bootstrap`.
In docker, we just need to add `-e` to set environment variables.
In docker-compose, we just need to add `environment` config.
=> [type: build] Support user-defined jvm param in startup scripts

shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java, shenyu-spi/src/main/java/org/apache/shenyu/spi/Join.java, shenyu-spi/src/test/java/org/apache/shenyu/spi/ExtensionLoaderTest.java, shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/ArrayListSPI.java
- [V] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [V] You submit test cases (unit or integration tests) that back your changes.
- [V] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.
=> [type:fix] Add SPI @Join annotation to the isSingleton() property

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/NettyHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/NettyClientMessageWriter.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/RPCMessageWriter.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java, shenyu-plugin/shenyu-plugin-sentinel/src/main/java/org/apache/shenyu/plugin/sentinel/SentinelPlugin.java, shenyu-plugin/shenyu-plugin-sentinel/src/main/java/org/apache/shenyu/plugin/sentinel/fallback/SentinelFallbackHandler.java, shenyu-plugin/shenyu-plugin-sentinel/src/test/java/org/apache/shenyu/plugin/sentinel/SentinelPluginTest.java
Fixes #3952
`SentinelPlugin` should not use `doOnSuccess`, this method is not called until the response is sent to the client.
After the completion of `respnsePlugin`, the status should be notified to `SentinelPlugin` to determine whether it is abnormal,
We need to transparently transmit the abnormal data that the application responds to the client.
=> [type:bug] Fix sentinel plugin bug

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/DashboardProperties.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ResourceController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ResourceMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/DashboardUserDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PermissionServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ResourceServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RoleServiceImpl.java, shenyu-admin/src/main/resources/application.yml, shenyu-admin/src/main/resources/mappers/dashboard-user-sqlmap.xml, shenyu-admin/src/main/resources/mappers/resouce-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/DashboardUserControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DashboardUserServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PermissionServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ResourceServiceTest.java
ShenYu Admin allows low-privilege low-level administrators to modify high-privilege administrators and low-level passwords, and low-privilege low-level administrators can create users with higher privileges than their own. There are the following fixes for this:
Repair plan：
The system defines the super administrator role, which is used to coordinate other assignments and manage other role administrators. Other role administrators cannot be assigned these super administrator exclusive permissions.
In order to adapt to old users, we also support the following features：
Note: Modifying user passwords and deleting users can only be done by yourself and the super administrator. This is mandatory and does not apply to the configured super administrator privileges.
=> [type fixbug]  Apache ShenYu Admin ultra vires

.github/workflows/docker-publish.yml
`on.push.paths` seem like that cannot start with `'!**'`. 
I change it to `on.push.paths-ignore`, and it is more clear semantics.
See https://github.com/apache/shenyu/actions/workflows/docker-publish.yml, this work has not worked since 23 days ago.
=> [type:bugfix] fix task that publish docker image to ghcr does not work

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/ShenyuDictDTO.java
Fixes #3998.
Because there is no enable item on edit page, an error will occurs when saving Dictionary. So in the application, remove the enable field's NotNull validation and give it a default `true` value. 
=> Fix issue: an error occurs when saving modified Dictionary.

shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalancer.java
=> [type: refactor]Replace with computeIfAbsent.

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDivideServiceImplTest.java
The `org.apache.shenyu.admin.service.register.ShenyuClientRegisterDivideServiceImplTest.testBuildHandle` has flakiness.
The test flakiness is due to comparisons between Json Strings and outputs from` JsonUtils.toJson()` and `GsonUtils.getInstance().toJson()`. 
However, JsonObject does not guarantee entry orders, its object is an unordered set of name/value pairs, and internal permutations may occur in the output from toJson().
There are five more similar tests that also have these kinds of flakiness. This is just an example, I will change the other five if you accept these changes.
Since the JSON tool used in the Project is GSON, so I use the GSON library `JsonParser `to convert the string back to JSON Object and compare them.  
This test avoids nested or different orders of JSON strings …
=> Fixed Possible Json Ordering Permutations Problem in Tests

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/query/TagRelationQuery.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/model/query/TagRelationQueryTest.java
Fixes #4198 update "org.apache.shenyu.admin.model.query.TagRelationQuery#equals" method
=> [ISSUE #4198]Fix the TagRelationQuery.java equals method

shenyu-common/src/test/java/org/apache/shenyu/common/utils/GsonUtilsTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/JsonUtilsTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/PathUtilsTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/SignUtilsTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/UriUtilsTest.java
=> [ISSUE #3275] improve unit test coverage of 'org.apache.shenyu.common.utils'

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AuthPathDTO.java
fix #4049 
Base on `v2.5.0`, the field `enabled` in AuthPathDTO is never used exclude in unit test.
When path update, we will transfer AuthPathDTO to AuthPathDO. 
However, the `enebled` field is always set as `true`.
Therefore, the `@NotNull` on `enabled` is unnecessary.
=> [ISSUE #4049] remove validation of field `enabled`

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorRequestPluginTest.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPlugin.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePlugin.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/JsonUtil.java
1. added more integrated test for CryptorRequestPlugin
2. fix checkParam
checkParam doesnt work because of GsonUtils wouldn't jsonization the field that of value is null or "" 
=> [type:refactor] added more test and fixed checkParam

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDivideServiceImplTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDubboServiceImplTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterGrpcServiceImplTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSofaServiceImplTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImplTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterTarsServiceImplTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/GsonUtilsTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/JsonUtilsTest.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java
The parse method of JsonParser is deprecated, I modified it to parseString.
=> [type:refactor] modify the deprecated parse method of JsonParser to parseString

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/dto/DubboRpcExt.java, shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SignPluginTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCache.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboParam.java
support dubbo3 `tri` and `dubbo` protocol
i add a field on `rpcExt`, on client write the dubbo protocol in the metadata. on shunyu gateway, create reference by the metadata rpcExt protocol.
=> feat(dubbo): support dubbo3 tri protocol

shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
Fixed the ModifyResponsePlugin resetting the configuration of maxInMemorySize in yml to the default value 256K.
=> [type:fix] ModifyResponsePlugin resetting the configuration of maxInMemorySize in yml to the default value 256K

db/init/mysql/schema.sql, db/init/oracle/schema.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/enums/LoadBalanceEnum.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/LeastActiveLoadBalance.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/LeastActiveLoadBalanceTest.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/LeastActivityLoadBalanceTest.java
=> add leastActive load balance

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PlatformController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PermissionServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SandboxServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SyncDataServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/DocManagerImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/FallbackShenyuClientRegisterService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/LocalDataSourceLoader.java
=> optimize shenyu-admin

shenyu-admin/src/main/resources/application-h2.yml
Intelligent access to the user directory of the system, so that Windows and Mac can try it immediately without changing the path through H2.
I tried it on Mac and Windows.
Hope it helps.
=> smart h2 path

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorRequestPluginTest.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorResponsePluginTest.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/support/ResponseDecorator.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/ServerWebExchangeUtils.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPlugin.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePlugin.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java, shenyu-plugin/shenyu-plugin-cryptor/src/test/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePluginTest.java
1. fixed  #4253
2. decoupled 
if Cryptor-Response Plugin had errors when decrypt or encrypt, still rewrite response body 
1. config
2. test in postman
3. view log 
```tex
2023-01-23 15:42:29 [reactor-http-nio-2] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - cryptorResponse selector success match , selector name :/**
2023-01-23 15:42:29 [reactor-http-nio-2] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - cryptorResponse rule success match , rule name :all
2023-01-23 15:42:32 [reactor-http-nio-2] ERROR org.apache.shenyu.plugin.cryptor.strategy.CryptorStrategyFactory - decrypt data error: 
java.lang.IllegalArgumentException: Last unit does not have enough valid bits
at java.base/java.util.Base64$Decoder.decode0(Base64.java:766)
at …
```
=> [type:bugfix] fix #4253 issue in Cryptor-Response Plugin 

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/validation/validator/ExistedValidator.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/MapUtils.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCacheManager.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTask.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalancer.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriber.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java, shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/GrpcClientCache.java, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-nacos/src/main/java/org/apache/shenyu/register/client/server/nacos/NacosClientServerRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-consul/src/main/java/org/apache/shenyu/register/instance/consul/ConsulInstanceRegisterRepository.java, shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandler.java
Fixed jdk8 Map computeIfAbsent performance bug
see https://bugs.openjdk.org/browse/JDK-8161372
=> Fixed jdk8 Map computeIfAbsent performance bug

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java
fix zombieRemovalTimes assignment operation lost.
=> fix zombieRemovalTimes lost

pom.xml
Disabled detectOfflineLinks to resolve the error of fetching package-list file.
[ISSUE #4346](https://github.com/apache/shenyu/issues/4346)
=> [ISSUE #4346] Disabled detectOfflineLinks to resolve the error of fetching package-list file.

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java
Synchronous invocation methods should not be used in LOG invocations of critical links, which can affect performance.
=> Critical link, LOG invoke method, causing performance loss.

shenyu-examples/shenyu-examples-springcloud/src/main/resources/application.yml
A nullpointerEXException occurred when starting example-springcloud with nacos configuration. The associated code is in org.apache.shenyu.register.client.nacos.NacosClientRegisterRepository:nacosProperties.put(PropertyKeyConst.NAMESPACE, properties.getProperty(NAMESPACE));
- [x ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x ] You submit test cases (unit or integration tests) that back your changes.
- [ x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.
=> [bug fiexd]A nullpointerEXException occurred when starting example-springcloud with nacos configuration.

shenyu-examples/shenyu-examples-springcloud/src/main/resources/application.yml, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-consul/src/main/java/org/apache/shenyu/register/client/server/consul/ShenyuConsulConfigWatch.java
=> [type:refactor] refactor code

shenyu-loadbalancer/src/main/resources/META-INF/shenyu/org.apache.shenyu.loadbalancer.spi.LoadBalancer
=> [type:fix] fix loadbalance spi resources

db/init/mysql/schema.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, db/upgrade/2.5.0-upgrade-2.5.1-mysql.sql, db/upgrade/2.5.0-upgrade-2.5.1-oracle.sql, db/upgrade/2.5.0-upgrade-2.5.1-pg.sql
=> [type:fix] fix sql script error

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieRuleListener.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieTest.java, shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java
Refactor some trie ruler codes.
=> [type:refactor] refactor some trie ruler codes.

shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/JwtUtils.java
=> [type:fix] fix JwtUtils

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java
=> [ISSUE #4399]  check rule uri condition on save.

shenyu-client/shenyu-client-brpc/src/main/java/org/apache/shenyu/client/brpc/BrpcContextRefreshedEventListener.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/executor/RegisterClientConsumerExecutor.java, shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonForwardingServerCall.java, shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonServerCallListener.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListener.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientEventListener.java, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/init/SpringWebSocketClientEventListener.java
Optimize code for shenyu-client
=> Optimize code for shenyu-client

shenyu-admin/src/main/java/org/apache/shenyu/admin/transfer/PluginTransfer.java, shenyu-common/src/main/java/org/apache/shenyu/common/dto/PluginData.java
=> modify pluginJar to Base64 String in PluginData

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/cache/WindowTinyLFUMap.java, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MetaDataCache.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/MatchDataCacheTest.java
Fixes #4475 
testcase from #4475, testcase as follows:
```java
public class TestMemoryLeak {
// 1m内存
private static final int M_1 = 1 * 1024 * 1024;
public static void main(String[] args) throws InterruptedException, IOException {
try {
mswtMapTest();
} catch (Exception e) {
e.printStackTrace();
}
TimeUnit.SECONDS.sleep(Long.MAX_VALUE);
}
public static void mswtMapTest() {
for (int i = 0; i < 10; i++) {
WindowTinyLFUMap<String, Byte[]> map = new WindowTinyLFUMap<>(1, 100, Boolean.TRUE);
map.put(String.valueOf(i), new Byte[M_1 * 2]);
// 手动GC
}
}
public static void commonMapTest() {
for (int i = 0; i < 10; i++) {
System.gc();
Map<String, Byte[]> map = new HashMap<>();
map.put(String.valueOf(i), new Byte[M_1 * 2]);
// 手动GC
System.gc();
}
}
}
```
=> [type:fix] fix memory leak

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleConditionMapper.java, shenyu-admin/src/main/resources/mappers/rule-condition-sqlmap.xml
=> [type:bug] fix bug Query failed because there are too many rules

shenyu-common/src/main/java/org/apache/shenyu/common/cache/WindowTinyLFUMap.java, shenyu-common/src/test/java/org/apache/shenyu/common/cache/WindowTinyLFUMapTest.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieNode.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/MatchDataCacheTest.java
tasklist:
```java
Map<String, Object> strongMap = new WindowTinyLFUMap<>(100, 100, Boolean.FALSE);  
strongMap.put(new String("abc"), 1);  
strongMap.put(new String("abc"), 1);  assert strongMap.get("abc") != null;    
Map<String, Object> strongMap = new WindowTinyLFUMap<>(100, 100, Boolean.TRUE);  
strongMap.put(new String("abc"), 1);  
strongMap.put(new String("abc"), 1);  assert strongMap.get("abc") == null;
```
=> [type:fix] fix error cache usage

shenyu-examples/shenyu-examples-http/k8s/shenyu-examples-http-deployment.yml, shenyu-examples/shenyu-examples-http/pom.xml
=> [Fix] missing actuator dependency and port error in examples http

shenyu-common/src/main/java/org/apache/shenyu/common/utils/UpstreamCheckUtils.java
=> [type:bug] fix bug issue #4487.

shenyu-common/src/main/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMap.java, shenyu-common/src/test/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMapTest.java
[ISSUE #4475] fix MemorySafeWindowTinyLFUMap memory leak error fix #4475
=> [type:fix] fix MemorySafeWindowTinyLFUMap memory leak error

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java
=> [type:fix] fix lack separator of path of ApiDoc

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
fix #4530 This is my first pr and I will continue to contribute
=> fix ShenyuTrie NPE

shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-common/src/main/java/org/apache/shenyu/common/enums/TrieMatchModeEnum.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriber.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/AbstractShenyuPluginTest.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriberTest.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfiguration.java, shenyu-web/src/test/java/org/apache/shenyu/web/controller/LocalPluginControllerTest.java
=> [type:refactor] refactor shenyu trie

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/ApiDTO.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ApiControllerTest.java
add validation for ApiDto.
add validation for ApiDto.
=> add validation for ApiDto.

shenyu-admin/src/main/resources/application.yml, shenyu-bootstrap/src/main/resources/application.yml, shenyu-web/src/main/java/org/apache/shenyu/web/filter/HealthFilter.java
This feature is mainly for helm and K8s deployment.
reference: 
* SpringBoot official: https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.kubernetes-probes
* CSDN(zh-CN): https://blog.csdn.net/boling_cavalry/article/details/106605264
=> feat: support k8s probes

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/AbstractContextPathRegisterServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImplTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/FallbackShenyuClientRegisterServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterBrpcServiceImplTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterWebSocketServiceImplTest.java
=> [ISSUE #4540] Added service test cases for admin

shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java
=> Optimized for ShenyuWebHandler#putExtPlugins method

shenyu-bootstrap/pom.xml
When run shenyu-bootstrap in docker, the log file will miss.
The images is build from latest code in master or pull from github packeages(https://github.com/apache/shenyu/pkgs/container/shenyu%2Fbootstrap)
```shell
✘ zhukunshuai@zhukunsaideAir2  ~  docker pull ghcr.io/apache/shenyu/bootstrap:114f1db623a7829c0fed03722bd5bae293587c68
114f1db623a7829c0fed03722bd5bae293587c68: Pulling from apache/shenyu/bootstrap
0362ad1dd800: Already exists
571218f61883: Already exists
62afd1dfc9c3: Already exists
000fc2a40b7f: Pull complete
e923cc9c6361: Pull complete
2ac991a0c4b1: Pull complete
8c72b52de2af: Pull complete
55bdea5bce7d: Pull complete
c43cef8224c0: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:7ed93005f50f1030c753a81743b3d4af66a06c281a80d6506b9a0135f4403191
Status: Downloaded …
```
=> [type: fix] fix missing log in container

shenyu-client/shenyu-client-core/src/test/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientApiDocExecutorSubscriberTest.java
=> add test cases for ShenyuClientApiDocExecutorSubscriber class.

db/init/mysql/schema.sql, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/TagRelationDO.java
=> add tag_relation create table sql

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListener.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientEventListener.java, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/init/SpringWebSocketClientEventListener.java
=> [type:fix] fix springmvc and springcloud client

shenyu-client/shenyu-client-sofa/src/test/java/org/apache/shenyu/client/sofa/SofaServiceEventListenerTest.java
In this PR, the unit tests of buildApiPath, buildMetaDataDTO in the class SofaServiceEventListener were added
=> [ISSUE #4548] Add unit test to the sofa component.

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriber.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java, shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/cache/ServiceInstanceCache.java
=> [type:fix] fix cache exist empty data

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ApiServiceImpl.java
bugfix can not update api detail on api document module.
exception below happen when update api detail.
```
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "DATE_CREATED"; SQL statement:
INSERT INTO tag_relation
(id,date_created,date_updated,api_id,tag_id)VALUES (?,?,?,?,?) [23502-200]
```
=> bugfix api document module update api detail error

shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/dto/MetaDataRegisterDTO.java
I think the `SofaServiceEventListenerTest.testBuildMetaDataDTO` method has a problem.
Sometimes the expected one's timeMillis is diffrent from the actual's ,Because of the difference of creation time
So, Removes comparing timeMillis  in MetaDataRegisterDTO#equals
=> [type:fix]fix SofaServiceEventListenerTest.testBuildMetaDataDTO

shenyu-admin/src/main/java/org/apache/shenyu/admin/exception/ExceptionHandlers.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/exception/ExceptionHandlersTest.java
ignore print some known exception stack log
ISSUE #4733 
=> [ISSUE #4733] ignore print some known exception stack log

shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/AppAuthMapperTest.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/ApiBean.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/extractor/ApiBeansExtractor.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/extractor/BaseAnnotationApiBeansExtractor.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/extractor/BaseApiBeansExtractor.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/registrar/AbstractApiDocRegistrar.java, shenyu-client/shenyu-client-core/src/test/java/org/apache/shenyu/client/core/register/registrar/AbstractApiDocRegistrarTest.java, shenyu-client/shenyu-client-core/src/test/java/org/apache/shenyu/client/core/register/registrar/HttpApiDocRegistrarTest.java, shenyu-client/shenyu-client-core/src/test/java/org/apache/shenyu/client/core/register/registrar/NoHttpApiDocRegistrarTest.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiBeansExtractor.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiMetaRegister.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiBeansExtractorTest.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiMetaRegisterTest.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/register/SpringMvcApiBeansExtractor.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/register/SpringMvcApiMetaRegister.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/test/java/org/apache/shenyu/client/springmvc/register/SpringMvcApiBeansExtractorTest.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/test/java/org/apache/shenyu/client/springmvc/register/SpringMvcApiMetaRegisterTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springcloud/src/main/java/org/apache/shenyu/springboot/starter/client/springcloud/ShenyuSpringCloudClientInfoRegisterConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springmvc/src/main/java/org/apache/shenyu/springboot/starter/client/springmvc/ShenyuSpringMvcClientInfoRegisterConfiguration.java
=> [type Refactor]extractor add BaseAnnotationApiBeansExtractor

shenyu-admin/src/main/java/org/apache/shenyu/admin/discovery/DefaultDiscoveryProcessor.java, shenyu-e2e/pom.xml
The example module and the e2e module are single projects under shenyu, the e2e module needs to add `checkstyle plugin` too. If not, `mvn checkstyle:check` rule is not as the shenyu project rule.
=> add checkstyle plugin into e2e module.

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/MetaDataMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java, shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/MetaDataMapperTest.java
=> [ISSUE #4797] update other rpc_ext for the same service

shenyu-client/shenyu-client-api-docs-annotations/src/main/java/org/apache/shenyu/client/apidocs/annotations/ApiDoc.java, shenyu-client/shenyu-client-api-docs-annotations/src/main/java/org/apache/shenyu/client/apidocs/annotations/ApiModule.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java
api doc client annotation add generated attribute to control whether it is necessary to generate in admin.
=> [type:refactor]api doc client annotation add generated attribute 

shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-apollo/src/main/java/org/apache/shenyu/register/client/server/apollo/ApolloClientServerRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-apollo/src/main/java/org/apache/shenyu/register/client/apollo/ApolloClientRegisterRepository.java, shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/path/RegisterPathConstants.java
1. unified client registration metadata and admin read metadata key
2. unified the data format of admin and client
3. when admin starts, perform a read operation from apollo
4. The registration of metadata is optimized. When the meta data does not change, the metadata write operation is not performed
5. removed useless code
=> [ISSUE #4850] fix apollo as registry, client metadata and uri cannot be synchronized to admin 

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java
fix  #4810
before fix
after fix 
=> [ISSUE #4810] Rule's Operation about path containing '@PathVariable' should be match

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java
=> [ISSUE #4853] Fixed could not update uri in Match mode

shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-apollo/src/main/java/org/apache/shenyu/register/client/server/apollo/ApolloClientServerRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-apollo/src/main/java/org/apache/shenyu/register/client/apollo/ApolloClient.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-apollo/src/main/java/org/apache/shenyu/register/client/apollo/ApolloClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-apollo/src/main/java/org/apache/shenyu/register/client/apollo/ApolloConfig.java
[ISSUE #4686] apolloClientRegisterRepository active offline
=> [ISSUE #4686] apolloClientRegisterRepository active offline

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/shutdown/ShenyuClientShutdownHook.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-api/src/main/java/org/apache/shenyu/register/client/api/ShenyuClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-consul/src/main/java/org/apache/shenyu/register/client/consul/ConsulClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-etcd/src/main/java/org/apache/shenyu/register/client/etcd/EtcdClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-etcd/src/test/java/org/apache/shenyu/register/client/etcd/EtcdClientRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/test/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/test/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepositoryTest.java
The client's close will be called twice when it is closed.
Because of Spring When the bean is destroyed, it will proactively call the `close` or `shutdown` methods. At the same time, Shenyu also defined ShenyuClientShutdownHook. Therefore, renaming the `close` method to ` closeRepository` solves the problem of being called twice.
=> [type: fix] fix client shutdown close method call twice

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientURIExecutorSubscriber.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/shutdown/ShenyuClientShutdownHook.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/shutdown/ShutdownHookManager.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepository.java
this pr can manage the execution order of hooks,
Although the offline interface has been implemented, the org.apache.shenyu.register.client.server.nacos.NacosClientServerRegisterRepository#subscribeRpcTypeService 
still calls when offline, just refreshURIService . and the offline function of Nacos has not yet been fully implemented. We need to discuss how to implement this block.
@dragon-zhang  
=> [ISSUE #4686] nacos client offline

shenyu-dist/shenyu-admin-dist/docker/Dockerfile
Related to #4961.
Comparing to `ghcr.io/apache/shenyu/admin:e8381465caf02063f01abe578c795d90602f3990`
349MB -> 218MB
```
~> docker images ghcr.io/apache/shenyu/admin:e8381465caf02063f01abe578c795d90602f3990                           
REPOSITORY                    TAG                                        IMAGE ID       CREATED          SIZE
ghcr.io/apache/shenyu/admin   e8381465caf02063f01abe578c795d90602f3990   4b71f7e5f494   37 minutes ago   349MB
~> docker history ghcr.io/apache/shenyu/admin:e8381465caf02063f01abe578c795d90602f3990
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
4b71f7e5f494   38 minutes ago   ENTRYPOINT ["/bin/sh" "entrypoint.sh"]          0B        buildkit.dockerfile.v0
<missing>      38 minutes ago …
```
=> Optimize layers of shenyu-admin Docker image

shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/resources/docker-compose.mysql.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/resources/docker-compose.mysql.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-sofa/src/test/resources/docker-compose.mysql.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/resources/docker-compose.mysql.yml
Related to #4934.
There is no `curl` but `nc` in `zookeeper:3.8.0`.
```
$ docker run --rm -d zookeeper:3.8.0                   
e086edb76143feb588e9fc7d71b5dc2633f674cad1a8d2569e991119ece126d5
$ docker ps 
CONTAINER ID   IMAGE             COMMAND                  CREATED         STATUS         PORTS                                    NAMES
e086edb76143   zookeeper:3.8.0   "/docker-entrypoint.…"   3 seconds ago   Up 3 seconds   2181/tcp, 2888/tcp, 3888/tcp, 8080/tcp   compassionate_beaver
$ docker exec -i -t e086edb76143 bash
root@e086edb76143:/apache-zookeeper-3.8.0-bin# curl 
bash: curl: command not found
root@e086edb76143:/apache-zookeeper-3.8.0-bin# echo srvr | nc localhost 2181
Zookeeper version: 3.8.0-5a02a05eddb59aee6ac762f7ea82e92a68eb9c0f, built on 2022-02-25 08:49 …
```
=> [type: test] Fix health check for zookeeper:3.8.0 in E2E

shenyu-e2e/pom.xml
When running `./mvnw clean install -T1C`, the following warning is present.
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are …
```
=> [type: build] Bump apache-rat-plugin to 0.15 to eliminate thread safe warning in parallel build

.github/workflows/codeql-analysis.yml
fix set-java v3 version string
=> [ type:fix ] fix set-java v3 version string

shenyu-protocol/shenyu-protocol-tcp/src/main/java/org/apache/shenyu/protocol/tcp/TcpBootstrapServer.java
=> [ISSUE #5047] Fix thread leak in TCP plugin

pom.xml
There are 1 security vulnerabilities found in org.apache.kafka:kafka-clients 3.2.0
- [CVE-2023-25194](https://www.oscs1024.com/hd/CVE-2023-25194)
Upgrade org.apache.kafka:kafka-clients from 3.2.0 to 3.4.0 for vulnerability fix
Ideally, no insecure libs should be used.
By using the [GitHub Actions](https://github.com/murphysecurity/actions) configurations provided by murphysec, we can conduct automatic code security checks in our CI pipeline.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): upgrade org.apache.kafka:kafka-clients to 3.4.0

pom.xml
New version plugin could find javadoc without setting $JAVA_HOME
Before:
javadoc not work if JAVA_HOME was not properly set. Especially in environment which installed multi versions of java.
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.788 s (Wall Clock)
[INFO] Finished at: 2023-09-21T23:17:47+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (default) on project shenyu-disruptor: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
[ERROR] Failed to execute goal …
```
=> Bump maven-javadoc-plugin to 3.6.0

.github/workflows/integrated-test-k8s-ingress.yml
=> [type:refactor]:Set the maximum time to wait for the k8s cluster to start up

shenyu-bootstrap/src/main/resources/application.yml
To avoid memory leaks, set the netty allocator to unpooled.
=> [type:fix]  Set the netty allocator to unpooled

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/main/java/org/apache/shenyu/plugin/logging/elasticsearch/config/ElasticSearchLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-huawei-lts/src/main/java/org/apache/shenyu/plugin/huawei/lts/config/HuaweiLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/main/java/org/apache/shenyu/plugin/logging/kafka/config/KafkaLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-pulsar/src/main/java/org/apache/shenyu/plugin/logging/pulsar/config/PulsarLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/rocketmq/config/RocketMQLogCollectConfig.java
The config repeat refresh and the `logCollector` repeat start when logging config is not updated.
Call code in `AbstractLogPluginDataHandler`
=> [type:fix] fix bug when refresh config

shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/ConcurrentRateLimiterAlgorithm.java, shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/SlidingWindowRateLimiterAlgorithm.java, shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/resources/META-INF/scripts/sliding_window_request_rate_limiter.lua
fix issue #5100 
in redis cluster mode，Concurrent、SlidingWindow Algorithm，The second key  add  '{id}'.
SlidingWindow lua expire time may be a decimal
=> [type:fix][ISSUE #5100] Redis cluster mode，fix rate limiter[concurrent、slidingwindow] redis key

shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java
=> [ISSUE#5330] Fix ext plugin can't load after admin close the plugin

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AlertDispatchServiceImpl.java
Standardized null detection coding in shenyu-admin
=> [type:refactor][ISSUE #5344] Standardized null detection coding

shenyu-alert/src/main/java/org/apache/shenyu/alert/strategy/AbstractAlertNotifyHandler.java, shenyu-alert/src/main/resources/static/alertNotifyDingTalkRobot.txt, shenyu-bootstrap/src/main/resources/application.yml, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/alert/AlarmSender.java, shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java, shenyu-web/src/test/java/org/apache/shenyu/web/handler/GlobalErrorHandlerTest.java
- send alarm message when gateway global error happen
=> [type: feat] send alarm message when gateway global error happen

shenyu-plugin/shenyu-plugin-security/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/extractor/VersionTwoExtractor.java
Optimize logic to avoid "orElse" execution：
“.orElse(httpRequest.getHeaders().getFirst(HttpHeaders.AUTHORIZATION));”
=> [ISSUE #5416]Optimize logic to avoid "orElse" execution，Update VersionTwoExtractor.java

shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java
=> [type:refactor] refactor plugin lifecycle

shenyu-admin-listener/shenyu-admin-listener-api/src/main/java/org/apache/shenyu/admin/listener/utils/NodeDataPathUtils.java, shenyu-admin-listener/shenyu-admin-listener-api/src/main/java/org/apache/shenyu/admin/listener/utils/NodePathUtils.java, shenyu-admin-listener/shenyu-admin-listener-api/src/test/java/org/apache/shenyu/admin/listener/utils/NodeDataPathUtilsTest.java, shenyu-admin-listener/shenyu-admin-listener-apollo/src/main/java/org/apache/shenyu/admin/listener/apollo/ApolloDataChangedInit.java, shenyu-admin-listener/shenyu-admin-listener-apollo/src/test/java/org/apache/shenyu/admin/listener/apollo/ApolloDataChangedInitTest.java, shenyu-admin-listener/shenyu-admin-listener-nacos/src/main/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedInit.java, shenyu-admin-listener/shenyu-admin-listener-nacos/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedInitTest.java
Optimizing gateway admin apollo/nacos start to load data every time.
if had load data from db, it should not load again next time.
=> [refactor] Optimizing the node type listener

shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml
In `org.apache.shenyu.admin.service.impl.AppAuthServiceImpl#buildByEntity`, we update the `appKey` to register center, but not save it to DB.
=> [BUG] update app_key in db

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/transfer/DiscoveryTransfer.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/handler/GrpcDiscoveryUpstreamDataHandler.java
=> [ISSUE #5311] less concurrency

.github/workflows/e2e-k8s.yml, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketCollector.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-cluster/k8s/script/e2e-cluster-zookeeper.sh, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/WebsocketSyncDataService.java
fix admin cluster e2e failure, link #5448 
=> [type:fix] fix cluster e2e failure

db/init/oracle/schema.sql, db/upgrade/2.6.1-upgrade-2.7.0-mysql.sql, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/NamespacePluginController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/NamespacePluginRelMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/NamespacePluginService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/NamespacePluginServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SyncDataServiceImpl.java, shenyu-admin/src/main/resources/mappers/NamespacePluginRelMapper.xml, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SyncDataServiceTest.java
Fixes #5621 
Fixes the issue where the plugin edit page fails to load due to an incorrect query in the `GET /namespacePlugin/id={id}&namespaceId={namespaceId}` endpoint. The query used `pluginId = {id}`, which resulted in no data being returned.
**Changes Made:**
- **Refactored**: `org.apache.shenyu.admin.service.NamespacePluginService#findById` to `findByPluginId`.
- **Updated**: The frontend request for "namespacePlugin/fetchItem" to use `pluginId` instead of `id`.
- **Modified**: The `plugin_id` field in the `plugin_ns_rel` table from a numeric type to `VARCHAR(128)` to prevent type mismatch errors.
- **Updated**: `org.apache.shenyu.admin.mapper.NamespacePluginRelMapper#existed` to align with the changes in how plugin IDs are handled.
Note that bulk operations such as delete and …
=> [type:fix] Fix Plugin Edit Page Issue by Correcting Plugin ID Query and Updating Data Type

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MetaDataCache.java
when metaData have disable item
uri path match need filter disable metaData
=> Fix metaData disable not filter

shenyu-common/src/main/java/org/apache/shenyu/common/utils/ListUtil.java
"org.apache.shenyu.common.utils.ListUtil#of"  this method return UnmodifiableRandomAccessList
so, "org.apache.shenyu.common.utils.ListUtil#merge" addAll will throw UnsupportedOperationException
question:
when use waf plugin, and rule condition have many,  bootstrap restart, admin will exception
=> [type:fix] fix ListUtil->merge exception

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/NamespaceDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DataPermissionServiceImpl.java
1. "Use `@Length(max =` to validate the length of a String instead of `@Max(value =` because `@Max` only verifies numbers."
2. "Do not query `dataPermission` when `selectorIds` is empty." 
=> [Fix] fix data-permission namespace problem

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
=> [type:feat] add shenyu gateway namespace

shenyu-admin-listener/shenyu-admin-listener-api/src/main/java/org/apache/shenyu/admin/listener/AbstractNodeDataChangedListener.java
[type:fix] Data sync dataId for proxy selector and discovery is not unique. (#5782)
=> fix:Data sync dataId for proxy selector and discovery is not unique

shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/annotation/ShenyuDubboService.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/annotation/ShenyuService.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/test/java/org/apache/shenyu/client/apache/dubbo/annotation/ShenyuDubboServiceDefaultValueTest.java
=> [type:fix] Make the default value of ShenyuDubboService annotation equal to that of DubboService annotation

shenyu-admin/src/main/java/org/apache/shenyu/admin/discovery/AbstractDiscoveryProcessor.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/discovery/DiscoveryProcessor.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/discovery/LocalDiscoveryProcessor.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/discovery/LocalDiscoveryProcessorTest.java
Fix the issue #5844. Delete proxy.selector and discovery  nacos config when delete the divide selector.
=> [type:fix] Delete proxy.selector and discovery  nacos config when delete the divide selector.

shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java
…get method is not a POST request.
=> [ISSUE #5851] Sandbox API debugging, the target API method is not POST, and the response format is JSON. The API returns an exception.

pom.xml, shenyu-admin/pom.xml
fix mysql vulnerability: https://github.com/apache/shenyu/security/dependabot/175
=> [bugfix] fix mysql vulnerability

shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/DiscoveryUpstreamDataRefresh.java
Resolved the issue where the DISCOVER_UPSTREAM configuration item always failed to synchronize in the http-polling configuration data sync mode;
=> fixed some bug when using http-polling mode

shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
=> [type:fix] support dubbo method configure

.gitignore, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/BodyParamUtils.java
- Added Caffeine cache for base type checking
- Improved isBaseType() performance with 5000-entry cache
- Reduced class loading overhead
This PR addresses the performance issue observed in the `isBaseType` method. During performance testing with the `shenyu-examples-apache-dubbo-service` project, using the `dubbo/insert` API on a Linux environment (8 CPU, 32GB memory), the `isBaseType` method was identified as a bottleneck through flame graph analysis.  
By introducing a caching mechanism to `isBaseType`, the TPS (transactions per second) significantly improved from ~1500 to ~18000 during testing with `ab`. This optimization greatly enhances system performance for scenarios involving frequent type checks.  
本 PR 优化了 `isBaseType` 方法的性能问题。通过火焰图分析，在使用 …
=> [type:optimize] Optimize BodyParamUtils with Caffeine cache

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AppAuthMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/NamespaceServiceImpl.java, shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml
=> [type:fix]fix namespace delete error

db/upgrade/2.6.1-upgrade-2.7.0-mysql.sql
[type:fix] remove duplicate entry '1792749362445840479' for key resource.PRIMARY from resource table https://github.com/apache/shenyu/issues/5895
This error only affects mysql and does not occur with pg, og , oracle..
=> [type:fix] remove duplicate entry '1792749362445840479' for key resource.PRIMARY from resource table apache#5895

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/main/java/org/apache/shenyu/plugin/logging/kafka/client/KafkaLogCollectClient.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/main/java/org/apache/shenyu/plugin/logging/kafka/config/KafkaLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/test/java/org/apache/shenyu/plugin/logging/kafka/config/KafkaLogCollectConfigTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/test/java/org/apache/shenyu/plugin/logging/kafka/handler/LoggingKafkaPluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/test/java/org/apache/shenyu/plugin/logging/kafka/kafka/KafkaLogCollectClientTest.java
=>  [Volunteer #5641] Improper word usage in Plugin Logging-Kafka configuration#namesrvAddr  

shenyu-sync-data-center/shenyu-sync-data-api/src/main/java/org/apache/shenyu/sync/data/core/AbstractNodeDataSyncService.java
=> [type:fix] The rule cache can not be deleted in shenyu-bootstrap when use nacos as sync center

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/body/LoggingServerHttpRequest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/body/LoggingServerHttpResponse.java
- Adjust the serialization timing of the request body and response body to avoid unnecessary string operations.
- Perform string conversion only after confirming the need to record logs to reduce resource consumption.
=> perf(logging): Optimize the performance of log collection

shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/dto/DubboRpcExt.java, shenyu-examples/shenyu-examples-dubbo/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboProtobufServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/xml/impl/DubboProtobufServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/resources/spring-dubbo.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/impl/DubboProtobufServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/resources/spring-dubbo.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-dubbo-api/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-dubbo-api/src/main/proto/DubboTestProto.proto, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboParam.java
support #5893 .
add dubbo protobuf serialization example
=> [type:feature] support dubbo protobuf serialization

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-console/src/main/java/org/apache/shenyu/plugin/logging/console/LoggingConsolePlugin.java
when response header have "Content-Encoding: gzip", the LoggingConsolePlugin will print messy codes
=> [fix] fix logging gzip messy

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MetaDataCache.java
Prevent NullPointerException in concurrent update scenarios
=> [type:fix] fix(plugin-base): avoid NPE in MetaDataCache cache

.github/workflows/e2e-k8s.yml, .github/workflows/integrated-test-k8s-ingress.yml, .github/workflows/integrated-test.yml, .github/workflows/k8s-examples-http.yml, shenyu-admin/src/main/resources/sql-script/h2/schema.sql
=> [fix] fix ci

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/main/java/org/apache/shenyu/plugin/logging/elasticsearch/client/ElasticSearchLogCollectClient.java
Supports generating Elasticsearch indices daily and creating an alias for them.
Writing all log data to a single Elasticsearch index can result in a very large index.  Splitting the index by day and creating an alias allows for reducing the data volume in each individual index and enabling queries through the alias.
for example. today is 2025-03-31. the index name were set to be shenyu-access-logging. the real index to write to will be shenyu-access-logging-2025-03-31. and will create alias for shenyu-access-logging-2025-03-31, so user can search shenyu-access-logging
=> [feat] Supports generating Elasticsearch indices daily and creating an alias for them.

shenyu-plugin/shenyu-plugin-ai/shenyu-plugin-ai-token-limiter/src/main/java/org/apache/shenyu/plugin/ai/token/limiter/AiTokenLimiterPlugin.java
Question:
In the appendResponse method,
Processing ByteBuffer in chunks leads to the first ByteBuffer having a gzip response header, which is correctly decompressed. Subsequent ByteBuffers are intermediate segments in the compressed stream and no longer contain a header. When taken out separately and decompressed using GZIPInputStream, they cannot identify the beginning and will report an error when constructing the stream or reading data. If subsequent chunks fail to decompress, the original compressed bytes will be written to BodyWriter unchanged. What accumulates in BodyWriter is a garbled binary stream rather than decompressed text. This leads to inaccurate token statistics.
Solution:
By decompressing across chunks in a streaming manner, memory consumption is reduced while gzip data …
=> fix AiTokenLimiterPlugin appendResponse

shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/strategy/DefaultJwtConvertStrategy.java, shenyu-plugin/shenyu-plugin-security/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/strategy/DefaultJwtConvertStrategyTest.java
When JWT value contains dot notation (e.g., user.name) to access nested properties, the DefaultJwtConvertStrategy.addHeader() method adds HTTP headers twice.
**Cause:**
```java
if (converter.getJwtVal().contains(".")) {
headers.add(headerVal, parse(...)); // adds correct value
}
headers.add(headerVal, body.get(jwtVal)); // always executes, adds null
```
**Result:**
Expected: username: `["john"]`
Actual: username: `["john", "null"]`
=> [fix] resolve duplicate header issue for JWT values with dot notation

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/TagVO.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/TagControllerTest.java
fix: the "name" field of TagVO has been changed. #6184 
The reason for this bug is that when refactor the keyword fields for the tag_sqlmap.xml database, the "name" field of TagVO was also modified, resulting in the front-end can not obtain the "name" field.
=> [fix] The "name" field of TagVO has been changed
