script/docker-compose.yml
soul-admin/Dockerfile
soul-bootstrap/Dockerfile

feat(docker): add Dockerfile.

---

soul-bootstrap/src/test/java/org/dromara/soul/bootstrap/loadbalance/LoadBalanceTest.java
soul-web/src/main/java/org/dromara/soul/web/balance/spi/RoundRobinLoadBalance.java

fix round robin load balance

---

soul-web/src/main/java/org/dromara/soul/web/cache/HttpLongPollSyncCache.java

fix bug: request config data multiple times when config was changed.

fix bug: request config data multiple times

---

soul-web/src/main/java/org/dromara/soul/web/disruptor/publisher/SoulEventPublisher.java
soul-web/src/main/java/org/dromara/soul/web/plugin/function/DubboPlugin.java
soul-web/src/main/java/org/dromara/soul/web/plugin/function/SpringCloudPlugin.java

1. lamda without paremeter declarations  
2. set the size of the task queue in the the thread pool

add some small  modifications

---

soul-test/soul-test-http/src/main/java/org/dromara/soul/test/http/controller/HttpTestController.java
soul-web/src/main/java/org/dromara/soul/web/plugin/hystrix/HttpCommand.java

I find some duplicate code in HttpCommand class .I extract them as new method.

extract duplicate code in HttpCommand

---

soul-client/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/dubbo/spring/DubboListener.java

> 增加关于cglib代理的服务代理判断，修复了无法注册问题

修复关于cglib代理的服务无法注册问题

---

soul-admin/pom.xml
soul-admin/src/main/java/org/dromara/soul/admin/listener/zookeeper/HttpServiceDiscovery.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/MetaDataServiceImpl.java
soul-admin/src/main/resources/application-local.yml
soul-admin/src/main/resources/application.yml
soul-bootstrap/pom.xml
soul-bootstrap/src/main/resources/application-local.yml
soul-bootstrap/src/main/resources/application.yml
soul-test/soul-test-http/src/main/resources/application.yml

1 - fix HTTP请求自动注册时selector选择器创建问题
2 - 添加maven整合spring 开发环境自由切换

1 - fix HTTP请求自动注册时selector选择器创建问题

---

soul-client/soul-client-springmvc3/pom.xml
soul-client/soul-client-springmvc3/src/main/java/org/dromara/soul/client/springmvc3/config/SoulHttpConfig.java
soul-client/soul-client-springmvc3/src/main/java/org/dromara/soul/client/springmvc3/configuration/SoulSpringMvcAutoConfiguration.java
soul-client/soul-client-springmvc3/src/main/java/org/dromara/soul/client/springmvc3/spring/ApplicationStartListener.java
soul-client/soul-client-springmvc3/src/main/java/org/dromara/soul/client/springmvc3/spring/SoulClientBeanPostProcessor.java
soul-client/soul-client-springmvc3/src/main/resources/META-INF/spring.factories
soul-client/soul-client-springmvc3/src/main/resources/META-INF/spring.provides

即将 WebServerInitializedEvent 替换为
EmbeddedServletContainerInitializedEvent
通过@Value获取端口，同时删除只有Spring5中才有的@NonNull注解

添加支持SpringBoot 1.x.x系列的即Spring 5以下的Client

---

soul-test/soul-test-dubbo/soul-test-dubbo-service/src/main/java/org/dromara/soul/test/dubbo/service/service/DubboTestServiceImpl.java
soul-test/soul-test-dubbo/soul-test-dubbo-service/src/main/resources/spring-dubbo.xml
soul-web/src/main/java/org/dromara/soul/web/plugin/dubbo/DubboProxyService.java
soul-web/src/main/java/org/dromara/soul/web/plugin/function/DubboPlugin.java

dubbo调用从同步改为异步，这样才符合soul反应式的定位。

dubbo调用从同步改为异步

---

soul-common/src/main/java/org/dromara/soul/common/config/DubboRegisterConfig.java
soul-web/src/main/java/org/dromara/soul/web/plugin/config/PluginConfigHandler.java
soul-web/src/main/java/org/dromara/soul/web/plugin/dubbo/ApplicationConfigCache.java

https://github.com/Dromara/soul/issues/186
support for registry group config

add support for dubbo registry group

---

soul-web/src/main/java/org/dromara/soul/web/cache/AbstractLocalCacheManager.java

fix typo rubbo to dubbo

---

soul-bootstrap/src/main/resources/application-local.yml

健康检查报错问题修复 

---

soul-test/soul-test-http/pom.xml

修复soul-test-http中soul-spring-boot-starter-client-springmvc版本问题

修复soul-test-http中soul-spring-boot-starter-client-springmvc版本问题

---

soul-test/soul-test-dubbo/soul-test-alibaba-dubbo-service/pom.xml
soul-test/soul-test-dubbo/soul-test-apache-dubbo-service/pom.xml
soul-test/soul-test-springcloud/pom.xml

修复soul-test中jar版本问题[dubbo,springcloud]

dubbo,springcloud自带的demo接入问题

---

pom.xml
soul-admin/pom.xml

替换过时依赖，升级mapstruct依赖到1.3.1.Final

---

soul-admin/src/main/java/org/dromara/soul/admin/exception/ExceptionHandlers.java

Fix #277 优化新建选择器或规则时，命名重复的友好提示

---

script/Docker.md
script/docker-compose.yml

docker使用的步骤说明

---

soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/AlibabaDubboPlugin.java
soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/response/DubboResponsePlugin.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/ApacheDubboPlugin.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/response/DubboResponsePlugin.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/utils/CheckUtils.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/utils/SoulResultWrap.java
soul-plugin/soul-plugin-divide/src/main/java/org/dromara/soul/plugin/divide/DividePlugin.java
soul-plugin/soul-plugin-divide/src/main/java/org/dromara/soul/plugin/divide/websocket/WebSocketPlugin.java
soul-plugin/soul-plugin-httpclient/src/main/java/org/dromara/soul/plugin/httpclient/NettyHttpClientPlugin.java
soul-plugin/soul-plugin-httpclient/src/main/java/org/dromara/soul/plugin/httpclient/WebClientPlugin.java
soul-plugin/soul-plugin-httpclient/src/main/java/org/dromara/soul/plugin/httpclient/response/WebClientResponsePlugin.java
soul-plugin/soul-plugin-hystrix/src/main/java/org/dromara/soul/plugin/hystrix/command/Command.java
soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/RateLimiterPlugin.java
soul-plugin/soul-plugin-sign/src/main/java/org/dromara/soul/plugin/sign/SignPlugin.java
soul-plugin/soul-plugin-springcloud/src/main/java/org/dromara/soul/plugin/springcloud/SpringCloudPlugin.java
soul-plugin/soul-plugin-waf/src/main/java/org/dromara/soul/plugin/waf/WafPlugin.java
soul-web/src/main/java/org/dromara/soul/web/filter/FileSizeFilter.java
soul-web/src/main/java/org/dromara/soul/web/filter/TimeWebFilter.java
soul-web/src/main/java/org/dromara/soul/web/filter/WebSocketParamFilter.java
soul-web/src/main/java/org/dromara/soul/web/handler/GlobalErrorHandler.java

Use onErrorMap instead of imperative catch block

---

pom.xml
soul-dist/bin/admin/shutdown.sh
soul-dist/bin/admin/start.sh
soul-dist/bin/bootstrap/shutdown.sh
soul-dist/bin/bootstrap/start.sh
soul-dist/pom.xml
soul-dist/src/main/assembly/binary.xml

打包后文件名为：dromara-soul-bin.tar.gz
文件列表：
```
dromara-soul-bin
├─soul-admin
│  ├─bin
│  │      shutdown.sh
│  │      start.sh
│  │
│  ├─conf
│  │      application-local.yml
│  │      application.yml
│  │
│  └─lib
│          soul-admin.jar
│
└─soul-bootstrap
├─bin
│      shutdown.sh
│      start.sh
│
├─conf
│      application-local.yml
│      application.yml
│
└─lib
soul-bootstrap.jar
```

Add dist package module

---

soul-dist/bin/admin/start.bat
soul-dist/bin/bootstrap/start.bat
soul-dist/src/main/assembly/binary.xml

closes [https://github.com/dromara/soul/issues/321](https://github.com/dromara/soul/issues/321)

Add start.bat for windows

---

soul-admin/README.md

- soul-admin.md重命名为README.md方便github进入项目目录就可以查看
- 调整了下一些格式错误问题

Update README.md for soul-admin

---

.gitmodules
soul-admin/pom.xml

这里增加soul-dashboard可以方便直接在soul主项目中构建打包前端代码. 
_TODO 打包之后替换soul-admin/src/main/resources/static目录的文件方便提交UI更新_

Add git submodule "soul-dashboard"

---

soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java
soul-admin/src/main/resources/META-INF/schema.sql
soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyService.java
soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/subscriber/AlibabaDubboMetaDataSubscriber.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriber.java

* 修复了Alibaba Dubbo 和 Apache Dubbo中修改元数据但是本地缓存未更新的问题；
* 更新Alibaba Dubbo和Apache Dubbo的缓存元数据的key为元数据的path；
* 设置表meta_data中path为唯一键索引；
* 修改org.dromara.soul.admin.controller.SoulClientController#registerRpc逻辑，以元数据的path为基准判断是新增还是更新元数据；

Fix bug(#355)

---

doc/setup.md
pom.xml
soul-admin/pom.xml
soul-admin/src/main/java/org/dromara/soul/admin/config/SwaggerConfiguration.java
soul-admin/src/main/resources/application-local.yml

#364 soul-admin 增加Swagger用于生成、描述、调用和可视化 Restful 风格的 Web 服务。

---

pom.xml
soul-client/pom.xml

upgraded lombok version

---

doc/metaData.md
doc/plugin-dubbo.md
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-dubbo-common/src/main/java/org/dromara/soul/client/dubbo/common/dto/DubboRpcExt.java
soul-client/soul-client-dubbo/soul-client-dubbo-common/src/main/java/org/dromara/soul/client/dubbo/common/dto/MetaDataDTO.java
soul-common/src/main/java/org/dromara/soul/common/constant/DubboParamConstants.java
soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCache.java

* 新增Dubbo服务提供者直连功能；
* 可以通过在Admin控制台修改Dubbo的扩展参数来指定dubbo的服务提供者；

Add Dubbo reference provider url(#363)

---

script/soul.sql

Synchronization script directory of soul.sql file，keep Soul.sql in sync with schema.sql

update table init sql , keep Soul.sql in sync with schema.sql

---

soul-admin/src/main/java/org/dromara/soul/admin/controller/PlatformController.java
soul-admin/src/main/java/org/dromara/soul/admin/dto/DashboardUserDTO.java
soul-admin/src/main/java/org/dromara/soul/admin/service/DashboardUserService.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/DashboardUserServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/utils/SoulResultMessage.java

soul-admin 全自动适配任何用户任何明文密码登录

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

closes [https://github.com/dromara/soul/issues/391](https://github.com/dromara/soul/issues/391)

Add issue and pr templates

---

soul-client/soul-client-http/soul-client-springmvc/src/main/java/org/dromara/soul/client/springmvc/init/SpringMvcClientBeanPostProcessor.java

Fix log print error

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

Update issue tag

---

soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/config/RateLimiterConfig.java

Fix error value of minIdle

---

soul-sync-data-center/soul-sync-data-http/src/main/java/org/dromara/soul/sync/data/http/HttpSyncDataService.java

Refactor HttpSyncDataService 

---

soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-http/src/main/java/org/dromara/soul/spring/boot/starter/sync/data/http/HttpSyncDataConfiguration.java
soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-nacos/src/main/java/org/dromara/soul/springboot/starter/sync/data/nacos/NacosSyncDataConfiguration.java
soul-sync-data-center/soul-sync-data-websocket/src/main/java/org/dromara/soul/plugin/sync/data/weboscket/WebsocketSyncDataService.java

Add check logic for PluginDataSubscriber in SyncDataService

---

soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessor.java
soul-client/soul-client-http/soul-client-springcloud/src/main/java/org/dromara/soul/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
soul-client/soul-client-http/soul-client-springmvc/src/main/java/org/dromara/soul/client/springmvc/init/ContextRegisterListener.java
soul-client/soul-client-http/soul-client-springmvc/src/main/java/org/dromara/soul/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
soul-client/soul-client-sofa/src/main/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessor.java
soul-sync-data-center/soul-sync-data-websocket/src/main/java/org/dromara/soul/plugin/sync/data/weboscket/WebsocketSyncDataService.java

Fix all log error print

---

soul-bootstrap/src/main/java/org/dromara/soul/bootstrap/configuration/SoulNettyWebServerFactory.java

Remove DEFAULT_IO_WORKER_COUNT

---

README.md

readme update #421

---

soul-common/src/main/java/org/dromara/soul/common/enums/ConfigGroupEnum.java
soul-common/src/main/java/org/dromara/soul/common/enums/DataEventTypeEnum.java
soul-common/src/main/java/org/dromara/soul/common/enums/HttpMethodEnum.java
soul-common/src/main/java/org/dromara/soul/common/enums/OperatorEnum.java
soul-common/src/main/java/org/dromara/soul/common/enums/ParamTypeEnum.java
soul-common/src/main/java/org/dromara/soul/common/enums/RpcTypeEnum.java
soul-common/src/main/java/org/dromara/soul/common/enums/SelectorTypeEnum.java
soul-common/src/main/java/org/dromara/soul/common/enums/SerializeEnum.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/strategy/AndMatchStrategy.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/strategy/MatchStrategy.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/strategy/OrMatchStrategy.java

Fix some docs and format enum error msg

---

soul-client/soul-client-sofa/src/main/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessor.java
soul-client/soul-client-sofa/src/main/java/org/dromara/soul/client/sofa/common/annotation/SoulSofaClient.java
soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/cache/ApplicationConfigCache.java

Issue no#401 sofa plugin code polish and change the config to annotation

---

soul-admin/src/main/java/org/dromara/soul/admin/vo/DashboardUserVO.java
soul-admin/src/main/java/org/dromara/soul/admin/vo/PluginHandleVO.java
soul-admin/src/main/java/org/dromara/soul/admin/vo/PluginVO.java
soul-admin/src/main/java/org/dromara/soul/admin/vo/RuleConditionVO.java
soul-admin/src/main/java/org/dromara/soul/admin/vo/RuleVO.java
soul-admin/src/main/java/org/dromara/soul/admin/vo/SelectorConditionVO.java
soul-admin/src/main/java/org/dromara/soul/admin/vo/SelectorVO.java
soul-admin/src/main/java/org/dromara/soul/admin/vo/SoulDictVO.java
soul-common/src/main/java/org/dromara/soul/common/utils/DateUtils.java

Add common localDateTimeToString method

---

soul-admin/src/main/java/org/dromara/soul/admin/controller/AppAuthController.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/AppAuthServiceImpl.java

原来代码是先根据id删除了之后再查出来发布事件导致空指针异常

Fix AppAuth delete bug

---

soul-plugin/soul-plugin-sofa/pom.xml

[#449]remove the sofa dependency in sofa plugin

---

script/soul.sql
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java

Fix springCloud plugin register

---

soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java

Extract repeated strings to static constants.

Refactor: extract repeated strings to static constants.

---

pom.xml
soul-plugin/soul-plugin-divide/src/test/java/org/dromara/soul/plugin/divide/LoadBalanceTest.java
soul-plugin/soul-plugin-httpclient/pom.xml
soul-plugin/soul-plugin-httpclient/src/test/java/org/dromara/soul/plugin/httpclient/WebclientTest.java
soul-sync-data-center/soul-sync-data-websocket/pom.xml
soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/sync/data/websocket/WebsocketClientTest.java
soul-sync-data-center/soul-sync-data-zookeeper/pom.xml
soul-sync-data-center/soul-sync-data-zookeeper/src/test/java/org/dromara/soul/sync/data/zookeeper/ZookeeperClientTest.java

Enable some unit tests

---

soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java
soul-common/src/main/java/org/dromara/soul/common/enums/RpcTypeEnum.java

Modify generate rpc handler object code as a public  method for RpcTypeEnum's enumerate objects.

Refactor: modify generate rpc handler object method.

---

.github/workflows/main.yml
pom.xml

Compare jacoco vs Cobertura

---

soul-admin/pom.xml
soul-spi/src/main/java/org/dromara/soul/spi/ExtensionLoader.java
soul-spi/src/test/java/org/dromara/soul/spi/ExtensionLoaderTest.java
soul-spi/src/test/java/org/dromara/soul/spi/SpiExtensionFactoryTest.java
soul-spi/src/test/java/org/dromara/soul/spi/fixture/NopSPI.java
soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/sync/data/websocket/WebsocketClientTest.java

Fix spi test

---

soul-plugin/soul-plugin-resilience4j/pom.xml
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/Resilence4JPluginTest.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/core/CircuitBreakerTest.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/core/RateLimiterTest.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/executor/CombinedExecutorTest.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/executor/RatelimiterExecutorTest.java

add Resilience4JPlugin Tests

---

soul-common/src/main/java/org/dromara/soul/common/constant/Constants.java
soul-common/src/main/java/org/dromara/soul/common/dto/convert/SentinelHandle.java
soul-plugin/soul-plugin-sentinel/src/main/java/org/dromara/soul/plugin/sentinel/handler/SentinelRuleHandle.java

[#472]polish sentinel config.

---

soul-metrics/soul-metrics-facade/src/main/java/org/dromara/soul/metrics/facade/MetricsTrackerFacade.java
soul-plugin/soul-plugin-monitor/src/main/java/org/dromara/soul/plugin/monitor/handler/MonitorPluginDataHandler.java

Refactor MetricsTrackerFacade

---

soul-metrics/soul-metrics-facade/src/main/java/org/dromara/soul/metrics/facade/executor/MetricsThreadPoolExecutor.java

Fix MetricsThreadPoolExecutor bug

---

soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/Resilience4JPluginTest.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/core/RateLimiterTest.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/executor/RateLimiterExecutorTest.java

[#469]fix spelling exception.

---

soul-common/src/test/java/org/dromara/soul/common/utils/DateUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/HttpParamConverterTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/Md5UtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/PathMatchUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/ReflectUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/SPI.java
soul-common/src/test/java/org/dromara/soul/common/utils/SignUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/SpiLoadFactoryTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/UpstreamCheckUtilsTest.java
soul-common/src/test/resources/META-INF/services/org.dromara.soul.common.utils.SPI

Add test cases for soul-common

---

soul-common/src/test/java/org/dromara/soul/common/utils/ParamCheckUtilsTest.java

unit test of ParamCheckUtils.dubboBodyIsEmpty

---

soul-common/src/test/java/org/dromara/soul/common/utils/HttpParamConverterTest.java

Update test cases for HttpParamConverter

---

soul-common/src/test/java/org/dromara/soul/common/utils/JsonUtilsTest.java

fix #484 add JsonUtilsTest

---

soul-common/src/test/java/org/dromara/soul/common/enums/MatchModeEnumTest.java

[#485] add test case for MatchModeEnum

---

soul-common/src/test/java/org/dromara/soul/common/utils/VersionUtilsTest.java

git commit -m 'build VersionUtilsTest for VersionUtils.java'

---

soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-httpclient/src/main/java/org/dromara/soul/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java

fixed typo issue of httpclient prefix define

Fix issue 494 of httpclient prefix typo

---

soul-common/src/test/java/org/dromara/soul/common/enums/HttpMethodEnumTest.java

Issue#485 http method enum

---

soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/subscriber/SofaMetaDataSubscriber.java

[#513]SofaMetaDataSubscriber miss unSubscribe method.

---

soul-admin/src/main/java/org/dromara/soul/admin/utils/CipherUtils.java

Remove unnecessary annotation `Component`

---

soul-common/src/test/java/org/dromara/soul/common/constant/ZkPathConstantsTest.java

 add ZKPathConstantTest (#484)

---

soul-common/src/test/java/org/dromara/soul/common/enums/DataSyncEnumTest.java

add test case for DataSyncEnum

---

soul-common/src/main/java/org/dromara/soul/common/constant/ZkPathConstants.java

 optimize ZkPathConstants

---

soul-admin/src/test/java/org/dromara/soul/admin/controller/IndexControllerTest.java

add IndexController Test

---

soul-admin/src/test/java/org/dromara/soul/admin/utils/AesUtilsTest.java
soul-admin/src/test/java/org/dromara/soul/admin/utils/CipherUtilsTest.java

Issue-505: Add a test case for the AesUtils class

---

soul-common/src/main/java/org/dromara/soul/common/concurrent/SoulThreadFactory.java

Enhanced SoulThreadFactory

---

soul-admin/src/test/java/org/dromara/soul/admin/controller/SoulDictControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/SoulDictMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/SoulDictServiceTest.java
soul-admin/src/test/java/org/dromara/soul/admin/utils/AesUtilsTest.java
soul-admin/src/test/java/org/dromara/soul/admin/utils/CipherUtilsTest.java
soul-bootstrap/src/test/java/org/dromara/soul/boostrap/DubboMultiParameterTest.java
soul-bootstrap/src/test/java/org/dromara/soul/boostrap/dubbo/ComplexBeanTest.java
soul-bootstrap/src/test/java/org/dromara/soul/boostrap/dubbo/DubboTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/DateUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/HttpParamConverterTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/JsonUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/Md5UtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/PathMatchUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/ReflectUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/SignUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/SpiLoadFactoryTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/UpstreamCheckUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/VersionUtilsTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/JmxCollectorTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/JmxScraperTest.java
soul-plugin/soul-plugin-divide/src/test/java/org/dromara/soul/plugin/divide/LoadBalanceTest.java
soul-plugin/soul-plugin-ratelimiter/src/test/java/org/dromara/soul/plugin/ratelimiter/RedisRateLimiterTests.java
soul-sync-data-center/soul-sync-data-zookeeper/src/test/java/org/dromara/soul/sync/data/zookeeper/ZookeeperClientTest.java

add final on Test Classes

---

soul-admin/src/test/java/org/dromara/soul/admin/controller/ConfigControllerTest.java

Issue-510: Add test case for the ConfigController class.

---

soul-admin/src/main/resources/META-INF/schema.sql

Issue 2 511

---

soul-admin/src/main/resources/mappers/auth-param-sqlmap.xml
soul-admin/src/test/java/org/dromara/soul/admin/mapper/AuthParamMapperTest.java

I have read the guide and completed.

Add test case for AuthParamMapper.

---

soul-admin/src/test/java/org/dromara/soul/admin/mapper/RuleConditionMapperTest.java

ci: RuleConditionMapper UnitTest

---

soul-admin/src/main/resources/mappers/auth-path-sqlmap.xml
soul-admin/src/test/java/org/dromara/soul/admin/mapper/AuthPathMapperTest.java

Add test cases for AuthPathMapper and fix bugs for auth-path-sqlmap.xml.

---

soul-admin/src/test/java/org/dromara/soul/admin/controller/PluginHandleControllerTest.java

Add test cases for PluginHandleController

---

soul-admin/src/test/java/org/dromara/soul/admin/listener/http/HttpLongPollingDataChangedListenerTest.java

Remove `@date` comment

---

soul-common/src/test/java/org/dromara/soul/common/enums/SerializeEnumTest.java

[#485] add test case for SerializeEnum

---

soul-admin/src/test/java/org/dromara/soul/admin/config/WebsocketSyncPropertiesTest.java

add WebsocketSyncProperties test case

---

soul-admin/src/test/java/org/dromara/soul/admin/AbstractConfigurationTest.java
soul-admin/src/test/java/org/dromara/soul/admin/config/HttpSyncPropertiesTest.java
soul-admin/src/test/java/org/dromara/soul/admin/config/WebsocketSyncPropertiesTest.java

Optimize configuration properties test

---

soul-admin/src/main/resources/mappers/app-auth-sqlmap.xml

Fix AppAuthMapper insertSelective bug

---

soul-admin/src/main/resources/mappers/dashboard-user-sqlmap.xml
soul-admin/src/test/java/org/dromara/soul/admin/mapper/DashboardUserMapperTest.java

- [ yes ] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [ yes ] You submit test cases (unit or integration tests) that back your changes.
- [ yes ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

Add test case for DashboardUserMapper and fix bugs

---

soul-common/src/test/java/org/dromara/soul/common/utils/UUIDUtilsTest.java

Add test cases for soul-common UUIDUtils

---

soul-admin/src/test/java/org/dromara/soul/admin/mapper/AppAuthMapperTest.java

Add test case for AppAuthMapper of soul-admin #509

---

soul-common/src/test/java/org/dromara/soul/common/enums/ParamTypeEnumTest.java

Add test cases for ParamTypeEnum of sour-common

---

soul-common/src/test/java/org/dromara/soul/common/utils/GsonUtilsTest.java

Add test cases for GsonUtils of sour-common (#484)

---

soul-admin/src/test/java/org/dromara/soul/admin/config/SwaggerConfigurationTest.java

create test cases for SwaggerConfiguration

---

soul-admin/src/test/java/org/dromara/soul/admin/controller/SelectorControllerTest.java

add test cases for SelectorController #510

---

soul-common/src/main/java/org/dromara/soul/common/constant/Constants.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/cache/ApplicationConfigCache.java

Add dubbo tag route(#471)

---

soul-admin/src/test/java/org/dromara/soul/admin/mapper/PluginMapperTest.java

Add test cases for PluginMapper of soul-admin (#509)

---

soul-admin/src/test/java/org/dromara/soul/admin/mapper/PluginHandleMapperTest.java

Add test cases for PluginHandleMapper of soul-admin

---

soul-admin/src/test/java/org/dromara/soul/admin/service/MetaDataServiceTest.java

Add test cases to the MetaDataService of the soul-admin module. :D

Add test cases to the MetaDataService of the soul-admin module. (#507)

---

soul-common/src/test/java/org/dromara/soul/common/enums/PluginEnumTest.java

issue#485
add test case for PluginEnum.

add test case for PluginEnum

---

soul-admin/src/main/java/org/dromara/soul/admin/listener/nacos/NacosDataChangedListener.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/nacos/NacosDataChangedListenerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/nacos/NacosMockConfigService.java
soul-common/src/main/java/org/dromara/soul/common/dto/AppAuthData.java
soul-common/src/main/java/org/dromara/soul/common/dto/MetaData.java
soul-common/src/main/java/org/dromara/soul/common/dto/PluginData.java
soul-common/src/main/java/org/dromara/soul/common/dto/RuleData.java
soul-common/src/main/java/org/dromara/soul/common/dto/SelectorData.java

This PR is to add test case for `/soul/admin/listener/nacos/NacosDataChangedListener.java`

[soul-admin] test: add test case for NacosDataChangedListener

---

soul-admin/src/test/java/org/dromara/soul/admin/service/RuleServiceTest.java

Add test cases for RuleService of soul-admin(#507)

---

soul-admin/src/main/java/org/dromara/soul/admin/vo/MetaDataVO.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/MetaDataControllerTest.java

fix #510 
Add test cases for MetaDataController of  soul-admin

Add test cases for MetaDataController of  soul-admin (#510)

---

soul-client/soul-client-common/pom.xml
soul-client/soul-client-common/src/main/java/org/dromara/soul/client/common/utils/RegisterUtils.java
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessor.java
soul-client/soul-client-http/soul-client-springcloud/src/main/java/org/dromara/soul/client/springcloud/init/ContextRegisterListener.java
soul-client/soul-client-http/soul-client-springcloud/src/main/java/org/dromara/soul/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
soul-client/soul-client-http/soul-client-springmvc/src/main/java/org/dromara/soul/client/springmvc/init/ContextRegisterListener.java
soul-client/soul-client-http/soul-client-springmvc/src/main/java/org/dromara/soul/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
soul-client/soul-client-sofa/src/main/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessor.java
soul-common/src/main/java/org/dromara/soul/common/constant/AdminConstants.java

Optimize soul client register code

---

soul-admin/src/test/java/org/dromara/soul/admin/mapper/MetaDataMapperTest.java
soul-common/src/test/java/org/dromara/soul/common/enums/PluginEnumTest.java

Add test case for MetaDataMapper of soul-admin (#509)

Add test case for MetaDataMapper of soul-admin (#509)

---

soul-sync-data-center/soul-sync-data-zookeeper/src/test/java/org/dromara/soul/sync/data/zookeeper/ZookeeperSyncDataServiceTest.java

Update test cases for ZookeeperSyncDataService

---

soul-common/src/main/java/org/dromara/soul/common/utils/DateUtils.java
soul-common/src/test/java/org/dromara/soul/common/utils/DateUtilsTest.java
soul-plugin/soul-plugin-sign/src/main/java/org/dromara/soul/plugin/sign/service/DefaultSignService.java

fix #589 
add 'formatLocalDateTimeFromTimestampBySystemTimezone'  method in DateUtils, then format 'start' in DefaultSignService use this method

fix issue 589 , bug about sign timeout

---

soul-admin/src/test/java/org/dromara/soul/admin/service/SoulClientRegisterServiceTest.java

Add test case for SoulClientRegisterService of soul-admin #507

---

soul-bootstrap/pom.xml
soul-plugin/soul-plugin-sign/pom.xml
soul-plugin/soul-plugin-sign/src/main/java/org/dromara/soul/plugin/sign/service/DefaultSignService.java
soul-plugin/soul-plugin-sign/src/test/java/org/dromara/soul/plugin/sign/SignPluginTest.java
soul-plugin/soul-plugin-sign/src/test/java/org/dromara/soul/plugin/sign/service/DefaultSignServiceTest.java

#460
add test case for sign plug.
**I am not good at writing test cases, Please give me some suggestions**

Add test cases for sign plugin

---

soul-admin/src/main/resources/application-local.yml
soul-admin/src/test/resources/application-test.yml

fix can not get soul.aes.secret.key

---

soul-admin/src/test/java/org/dromara/soul/admin/service/AppAuthServiceTest.java

Add test case for AppAuthService of soul-admin (#507)

---

soul-admin/src/test/java/org/dromara/soul/admin/service/RuleServiceTest.java
soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/handler/ApacheDubboPluginDataHandlerTest.java

Add test for ApacheDubboPluginDataHandler.#590 and remove warning in RuleServiceTest.#507

---

pom.xml
soul-admin/src/main/java/org/dromara/soul/admin/config/SwaggerConfiguration.java
soul-dist/pom.xml
soul-plugin/soul-plugin-hystrix/src/main/java/org/dromara/soul/plugin/hystrix/builder/HystrixBuilder.java

Fix: mvn install warning in IDEA

---

soul-admin/src/test/java/org/dromara/soul/admin/AbstractConfigurationTest.java
soul-admin/src/test/java/org/dromara/soul/admin/AbstractSpringIntegrationTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/ConfigControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/PluginControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/PluginHandleControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/RuleControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/SoulDictControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/nacos/NacosDataChangedListenerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/nacos/NacosMockConfigService.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/AppAuthMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/DashboardUserMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/MetaDataMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/PluginHandleMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/RuleMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/SoulClientRegisterServiceTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/SoulDictServiceTest.java
soul-admin/src/test/java/org/dromara/soul/admin/utils/CipherUtilsTest.java

Fix warning

---

soul-plugin/soul-plugin-alibaba-dubbo/src/test/java/org/dromara/soul/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java

add AlibabaDubboPluginData test case

---

soul-common/src/main/java/org/dromara/soul/common/utils/GsonUtils.java
soul-common/src/test/java/org/dromara/soul/common/utils/GsonUtilsTest.java
soul-metrics/soul-metrics-prometheus/src/main/java/org/dromara/soul/metrics/prometheus/impl/collector/JmxCollector.java

solve GsonUtils's tree issues, and add GsonUtilsTest' method to check toTreeMap().(#595)

solve GsonUtils's tree issues, and add GsonUtilsTest' method to check toTreeMap().(#595)

---

soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/param/BodyParamPluginTest.java
soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/response/ApacheDubboResponsePluginTest.java

Issue-590 add apache dubbo response plugin test

---

soul-admin/src/test/java/org/dromara/soul/admin/config/NacosConfigurationTest.java
soul-admin/src/test/java/org/dromara/soul/admin/config/NacosPropertiesTest.java

Add test cases for NacosPropertiesConfiguration and NacosProperties.

---

.github/workflows/maven-on-macos.yml
.github/workflows/maven-on-ubuntu.yml
.github/workflows/maven-on-windows.yml
.mvn/wrapper/MavenWrapperDownloader.java
.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

Add build for window os and macos

---

soul-client/soul-client-sofa/pom.xml
soul-client/soul-client-sofa/src/test/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessorTest.java

issue-615: Add test case for SofaServiceBeanPostProcessor.

---

soul-client/soul-client-sofa/src/test/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessorTest.java

[#615]fix error port.

---

pom.xml
soul-admin/pom.xml
soul-bootstrap/pom.xml
soul-client/pom.xml
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/pom.xml
soul-client/soul-client-dubbo/soul-client-apache-dubbo/pom.xml
soul-client/soul-client-sofa/pom.xml
soul-common/pom.xml
soul-plugin/soul-plugin-hystrix/pom.xml
soul-plugin/soul-plugin-ratelimiter/pom.xml
soul-plugin/soul-plugin-sentinel/pom.xml
soul-plugin/soul-plugin-springcloud/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-springcloud/pom.xml
soul-sync-data-center/soul-sync-data-nacos/pom.xml
soul-sync-data-center/soul-sync-data-websocket/pom.xml
soul-test/pom.xml
soul-test/soul-test-dubbo/soul-test-alibaba-dubbo-service/pom.xml
soul-test/soul-test-dubbo/soul-test-apache-dubbo-service/pom.xml
soul-test/soul-test-dubbo/soul-test-dubbo-api/pom.xml
soul-test/soul-test-http/pom.xml
soul-test/soul-test-sofa/pom.xml
soul-test/soul-test-springcloud/pom.xml
soul-web/pom.xml

issue-405: Optimize maven pom profiles.

---

soul-admin/pom.xml
soul-admin/src/main/resources/application-local.yml
soul-admin/src/test/java/org/dromara/soul/admin/listener/zookeeper/ZookeeperDataChangedListenerTest.java

506 issue，add testCase for soul-admin ZookeeperDataChangedListener

---

pom.xml
soul-client/soul-client-sofa/src/test/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessorTest.java

Fix codecov

---

soul-admin/pom.xml

Remove duplicate dependencies

---

soul-client/soul-client-http/soul-client-springmvc/src/test/java/org/dromara/soul/client/springmvc/init/ContextRegisterListenerTest.java
soul-client/soul-client-http/soul-client-springmvc/src/test/java/org/dromara/soul/client/springmvc/init/SpringMvcClientBeanPostProcessorTest.java
soul-client/soul-client-sofa/src/test/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessorTest.java

#615 change test case port get method and make wait time longer

---

soul-admin/src/test/java/org/dromara/soul/admin/service/PluginServiceTest.java

Add PluginServerTest

---

soul-admin/src/main/java/org/dromara/soul/admin/controller/AppAuthController.java
soul-common/src/main/java/org/dromara/soul/common/utils/JsonUtils.java
soul-common/src/main/java/org/dromara/soul/common/utils/VersionUtils.java
soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/param/BodyParamPlugin.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/param/BodyParamPlugin.java
soul-plugin/soul-plugin-waf/src/main/java/org/dromara/soul/plugin/waf/WafPlugin.java
soul-web/src/main/java/org/dromara/soul/web/handler/SoulWebHandler.java

Remove the `else` statement, try make the code clear.

Refactor: remove the `else` statement, try make the code clear.

---

soul-admin/src/test/java/org/dromara/soul/admin/service/DashboardUserServiceImplTest.java

add test cases for DashboardUserService(dromara#507)

add test cases for DashboardUserService(dromara#507)

---

soul-common/src/main/java/org/dromara/soul/common/dto/convert/rule/RuleHandleFactory.java
soul-common/src/test/java/org/dromara/soul/common/dto/convert/rule/RuleHandleFactoryTest.java

Add test case for RuleHandleFactory(soul#640)

---

soul-common/src/main/java/org/dromara/soul/common/constant/Constants.java
soul-plugin/soul-plugin-divide/src/main/java/org/dromara/soul/plugin/divide/DividePlugin.java
soul-plugin/soul-plugin-httpclient/pom.xml
soul-plugin/soul-plugin-httpclient/src/main/java/org/dromara/soul/plugin/httpclient/WebClientPlugin.java

Add webClient retry support of dividePlugin set, and issue 70 resolved

Add webClient retry support of dividePlugin set, and issue #70 resolved

---

soul-admin/src/main/java/org/dromara/soul/admin/exception/ExceptionHandlers.java
soul-admin/src/main/java/org/dromara/soul/admin/listener/AbstractDataChangedListener.java
soul-admin/src/main/java/org/dromara/soul/admin/listener/ApplicationStartListener.java
soul-admin/src/main/java/org/dromara/soul/admin/listener/http/HttpLongPollingDataChangedListener.java
soul-admin/src/main/java/org/dromara/soul/admin/listener/websocket/WebsocketCollector.java
soul-admin/src/main/java/org/dromara/soul/admin/listener/zookeeper/HttpServiceDiscovery.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/MetaDataServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/init/LocalDataSourceLoader.java
soul-common/src/main/java/org/dromara/soul/common/utils/DateUtils.java
soul-common/src/main/java/org/dromara/soul/common/utils/JsonUtils.java
soul-common/src/main/java/org/dromara/soul/common/utils/VersionUtils.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/utils/CheckUtils.java
soul-plugin/soul-plugin-divide/src/main/java/org/dromara/soul/plugin/divide/DividePlugin.java
soul-plugin/soul-plugin-httpclient/src/main/java/org/dromara/soul/plugin/httpclient/NettyHttpClientPlugin.java
soul-plugin/soul-plugin-hystrix/src/main/java/org/dromara/soul/plugin/hystrix/command/HystrixCommand.java
soul-plugin/soul-plugin-hystrix/src/main/java/org/dromara/soul/plugin/hystrix/command/HystrixCommandOnThread.java
soul-spi/src/main/java/org/dromara/soul/spi/ExtensionLoader.java
soul-sync-data-center/soul-sync-data-websocket/src/test/java/org/dromara/soul/sync/data/websocket/WebsocketClientTest.java
soul-sync-data-center/soul-sync-data-zookeeper/src/test/java/org/dromara/soul/sync/data/zookeeper/ZookeeperClientTest.java
soul-web/src/main/java/org/dromara/soul/web/forwarde/ForwardedRemoteAddressResolver.java
soul-web/src/main/java/org/dromara/soul/web/handler/GlobalErrorHandler.java

use annotation @Slf4j instead of LoggerFactory.getLogger

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

Update issue template labels

---

soul-plugin/soul-plugin-alibaba-dubbo/src/test/java/org/dromara/soul/plugin/alibaba/dubbo/response/DubboResponsePluginTest.java

add test for soul-plugin-alibaba DubboResponsePlugin #592

---

soul-admin/src/test/java/org/dromara/soul/admin/listener/http/HttpLongPollingDataChangedListenerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/websocket/WebsocketDataChangedListenerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/AuthPathMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/PluginMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/RuleMapperTest.java
soul-common/src/test/java/org/dromara/soul/common/enums/DataSyncEnumTest.java
soul-common/src/test/java/org/dromara/soul/common/enums/ParamTypeEnumTest.java
soul-common/src/test/java/org/dromara/soul/common/enums/PluginEnumTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/GsonUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/SpiLoadFactoryTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/UUIDUtilsTest.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/executor/CombinedExecutorTest.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/executor/RateLimiterExecutorTest.java
soul-plugin/soul-plugin-sign/src/test/java/org/dromara/soul/plugin/sign/SignPluginTest.java

Optimize test cases and fix comment

---

soul-common/src/main/java/org/dromara/soul/common/utils/GsonUtils.java
soul-common/src/test/java/org/dromara/soul/common/utils/GsonUtilsTest.java
soul-sync-data-center/soul-sync-data-nacos/src/main/java/org/dromara/soul/sync/data/nacos/handler/NacosCacheHandler.java

Fix bug #656

---

soul-admin/src/test/java/org/dromara/soul/admin/config/DataSyncConfigurationTest.java
soul-admin/src/test/java/org/dromara/soul/admin/config/WebConfigTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/RuleControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/nacos/NacosMockConfigService.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/zookeeper/ZookeeperDataChangedListenerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/AppAuthMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/RuleConditionMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/SelectorConditionMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/PluginServiceTest.java

eliminate yellow warning for soul admin test code. fix #675

---

soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/PrometheusMetricsTrackerFactoryTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/PrometheusMetricsTrackerManagerTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/counter/HttpRequestCounterMetricsTrackerTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/counter/RequestTotalCounterMetricsTrackerTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/histogram/PrometheusHistogramMetricsTrackerDelegateTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/histogram/RequestLatencyHistogramMetricsTrackerTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/summary/PrometheusSummaryMetricsTrackerDelegateTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/summary/RequestLatencySummaryMetricsTrackerTest.java

// Optimize test cases for soul-metric-prometheus

Optimize test cases for soul-metric-prometheus

---

soul-admin/src/main/java/org/dromara/soul/admin/vo/PluginHandleVO.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/AppAuthVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/AuthParamVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/AuthPathVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/DashboardUserVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/EnumVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/MetaDataVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/PluginHandleVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/PluginVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/RuleConditionVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/RuleVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/SelectorConditionVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/SelectorVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/SoulDictVOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/vo/base/BaseVOTest.java

add test case 4 soul-admin vo #653 

add test case 4 soul-admin vo

---

soul-common/src/test/java/org/dromara/soul/common/enums/OperatorEnumTest.java

// Describe your PR here; eg. Fixes #485 

Add test case for soul-common OperatorEnum

---

soul-common/src/test/java/org/dromara/soul/common/concurrent/SoulThreadFactoryTest.java

Add test case for soul-common SoulThreadFactoryTest 

---

soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/param/BodyParamPluginTest.java

Fix #694 
fix  change PluginEnum.SOFA TO PluginEnum.DUBBO

fix  issue 694

---

soul-common/src/main/java/org/dromara/soul/common/enums/RedisModeEnum.java
soul-common/src/test/java/org/dromara/soul/common/enums/RedisModeEnumTest.java

Add test case for RedisModeEnum (#687)

---

soul-admin/src/test/java/org/dromara/soul/admin/service/SyncDataServiceTest.java

- [] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [] You submit test cases (unit or integration tests) that back your changes.
- [] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

#507 add test cases for SyncDataService

---

soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/ApacheDubboPluginTest.java

add test cases for ApacheDubboPlugin

---

soul-common/src/test/java/org/dromara/soul/common/utils/ReflectUtilsTest.java
soul-common/src/test/java/org/dromara/soul/common/utils/UpstreamCheckUtilsTest.java

* ReflectUtilsTest
* UpstreamCheckUtilsTest

Optimize test cases to improve code coverage. (#668)

---

soul-admin/src/main/java/org/dromara/soul/admin/dto/DashboardUserDTO.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/DashboardUserControllerTest.java

Add test cases for DashboardUserController of soul-admin(#510)

---

soul-admin/src/test/java/org/dromara/soul/admin/listener/zookeeper/HttpServiceDiscoveryTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/zookeeper/ZookeeperDataInitTest.java

Add test case for soul-admin HttpServiceDiscovery & ZookeeperDataInit (#652)

Add test case for soul-admin HttpServiceDiscovery & ZookeeperDataInit (#652)

---

soul-common/src/test/java/org/dromara/soul/common/utils/JsonUtilsTest.java

fix: Optimize test cases to improve code coverage about JsonUtilsTest (fixes #668)

fix: Optimize test cases to improve code coverage about JsonUtilsTest (fixes #668)

---

soul-admin/src/test/java/org/dromara/soul/admin/listener/zookeeper/HttpServiceDiscoveryTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/zookeeper/ZookeeperDataInitTest.java

Add test case for soul-admin HttpServiceDiscovery & ZookeeperDataInit

---

soul-admin/src/test/java/org/dromara/soul/admin/exception/ExceptionHandlersTest.java

Add ExceptionHandlers test case to improve code coverage.#668

---

soul-common/src/test/java/org/dromara/soul/common/utils/UUIDUtilsTest.java

Fix [https://github.com/dromara/soul/runs/1545681744](https://github.com/dromara/soul/runs/1545681744)

Fix testcase failure

---

soul-admin/src/test/java/org/dromara/soul/admin/exception/ExceptionHandlersTest.java

Make the code easier to read.
Fixes #682 

issue-682: Modify the ExceptionHandlersTest class.

---

soul-metrics/soul-metrics-spi/src/test/java/org/dromara/soul/metrics/api/CounterMetricsTrackerTest.java
soul-metrics/soul-metrics-spi/src/test/java/org/dromara/soul/metrics/api/GaugeMetricsTrackerTest.java
soul-metrics/soul-metrics-spi/src/test/java/org/dromara/soul/metrics/api/HistogramMetricsTrackerTest.java
soul-metrics/soul-metrics-spi/src/test/java/org/dromara/soul/metrics/api/SummaryMetricsTrackerTest.java

Add test cases for default method of metric-api

---

soul-common/src/test/java/org/dromara/soul/common/constant/RedisKeyConstantsTest.java

add 'Test cases for RedisKeyConstants'

---

soul-plugin/soul-plugin-sofa/src/test/java/org/dromara/soul/plugin/sofa/SofaPluginTest.java
soul-plugin/soul-plugin-sofa/src/test/java/org/dromara/soul/plugin/sofa/param/BodyParamPluginTest.java
soul-plugin/soul-plugin-sofa/src/test/java/org/dromara/soul/plugin/sofa/proxy/SofaProxyServiceTest.java
soul-plugin/soul-plugin-sofa/src/test/java/org/dromara/soul/plugin/sofa/response/SofaResponsePluginTest.java

#468 polish sofa plugin test,make coverage higher.

---

soul-plugin/soul-plugin-monitor/pom.xml
soul-plugin/soul-plugin-monitor/src/test/java/org/dromara/soul/plugin/monitor/MonitorPluginTest.java
soul-plugin/soul-plugin-monitor/src/test/java/org/dromara/soul/plugin/monitor/handler/MonitorPluginDataHandlerTest.java

[#670] Add test case for soul-plugin-monitor

---

soul-common/src/test/java/org/dromara/soul/common/enums/WafModelEnumTest.java

Test enums in soul-common #687 -WafModuleEnum 

---

soul-plugin/soul-plugin-alibaba-dubbo/src/test/java/org/dromara/soul/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyServiceTest.java
soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java

make dubbo plugin test case coverage higher.

---

soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/proxy/SofaProxyService.java
soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/subscriber/SofaMetaDataSubscriber.java
soul-plugin/soul-plugin-sofa/src/test/java/org/dromara/soul/plugin/sofa/proxy/SofaProxyServiceTest.java

fix wrong sofa cache key.

---

soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessor.java
soul-web/src/main/java/org/dromara/soul/web/configuration/SoulConfiguration.java
soul-web/src/main/java/org/dromara/soul/web/forward/ForwardedRemoteAddressResolver.java
soul-web/src/main/java/org/dromara/soul/web/handler/SoulWebHandler.java
soul-web/src/main/java/org/dromara/soul/web/logo/SoulLogo.java

Simplify some codes

---

soul-admin/src/main/java/org/dromara/soul/admin/query/AppAuthQuery.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/AppAuthControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/AppAuthServiceTest.java

Add test cases for AppAuthController of soul-admin(#510)

---

soul-admin/src/main/java/org/dromara/soul/admin/service/impl/UpstreamCheckService.java
soul-admin/src/test/resources/META-INF/schema.sql
soul-admin/src/test/resources/application-test.yml

Optimize the setup selectors of divide plugin

---

soul-common/src/test/java/org/dromara/soul/common/enums/SelectorTypeEnumTest.java

Add test case for soul-common constants&enum #655

---

soul-common/src/test/java/org/dromara/soul/common/enums/LoadBalanceEnumTest.java

687 issue, Test case for LoadBalanceEnum

---

soul-client/soul-client-http/soul-client-springcloud/pom.xml
soul-client/soul-client-http/soul-client-springcloud/src/test/java/org/dromara/soul/client/springcloud/ContextRegisterListenerTest.java
soul-client/soul-client-http/soul-client-springcloud/src/test/java/org/dromara/soul/client/springcloud/SpringMvcClientBeanPostProcessorTest.java
soul-client/soul-client-http/soul-client-springmvc/pom.xml
soul-client/soul-client-http/soul-client-springmvc/src/test/java/org/dromara/soul/client/springmvc/init/ContextRegisterListenerTest.java
soul-client/soul-client-http/soul-client-springmvc/src/test/java/org/dromara/soul/client/springmvc/init/SpringMvcClientBeanPostProcessorTest.java
soul-client/soul-client-sofa/pom.xml
soul-client/soul-client-sofa/src/test/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessorTest.java

remove mock server in client module.

---

soul-common/src/test/java/org/dromara/soul/common/enums/ResultEnumTest.java

add test for ResultEnum in soul-common
// Describe your PR here; eg. Fixes #687

Test ResultEnum in soul-common

---

soul-common/src/test/java/org/dromara/soul/common/enums/PluginRoleEnumTest.java

issues687 Add test for PluginRoleEnum

---

soul-admin/src/test/java/org/dromara/soul/admin/controller/PluginControllerTest.java

Add test cases for PluginController of soul-admin

---

soul-admin/src/test/java/org/dromara/soul/admin/service/SelectorServiceTest.java

Add SelectorServiceTest(#507)

---

soul-sync-data-center/soul-sync-data-zookeeper/src/test/java/org/dromara/soul/sync/data/zookeeper/ZookeeperSyncDataServiceTest.java

Optimize unit test ZookeeperSyncDataService

---

soul-admin/src/test/java/org/dromara/soul/admin/utils/AesUtilsTest.java

add two method for AesUtilsTest.

Improve code coverage for AesUtils.

---

soul-client/soul-client-common/src/main/java/org/dromara/soul/client/common/utils/OkHttpTools.java
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/validation/AlibabaDubboClientValidator.java
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/test/java/org/dromara/soul/client/alibaba/dubbo/validation/AlibabaDubboClientValidatorTest.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/validation/ApacheDubboClientValidator.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/ApacheDubboClientValidatorTest.java
soul-client/soul-client-dubbo/soul-client-dubbo-common/src/main/java/org/dromara/soul/client/dubbo/common/dto/DubboRpcExt.java
soul-client/soul-client-http/soul-client-springmvc/src/test/java/org/dromara/soul/client/springmvc/init/ContextRegisterListenerTest.java
soul-client/soul-client-sofa/src/main/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessor.java
soul-common/src/main/java/org/dromara/soul/common/constant/DubboParamConstants.java
soul-common/src/main/java/org/dromara/soul/common/dto/convert/rule/RuleHandleFactory.java
soul-common/src/main/java/org/dromara/soul/common/utils/JsonUtils.java
soul-common/src/main/java/org/dromara/soul/common/utils/UpstreamCheckUtils.java
soul-common/src/test/java/org/dromara/soul/common/utils/UUIDUtilsTest.java
soul-plugin/soul-plugin-alibaba-dubbo/src/test/java/org/dromara/soul/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java
soul-plugin/soul-plugin-divide/src/main/java/org/dromara/soul/plugin/divide/balance/spi/RoundRobinLoadBalance.java
soul-plugin/soul-plugin-global/src/main/java/org/dromara/soul/plugin/global/GlobalPlugin.java
soul-plugin/soul-plugin-httpclient/src/main/java/org/dromara/soul/plugin/httpclient/config/HttpClientProperties.java
soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/executor/RedisRateLimiter.java
soul-plugin/soul-plugin-resilience4j/src/test/java/org/dromara/soul/plugin/resilience4j/executor/CombinedExecutorTest.java
soul-plugin/soul-plugin-sign/src/test/java/org/dromara/soul/plugin/sign/service/DefaultSignServiceTest.java
soul-plugin/soul-plugin-sofa/src/test/java/org/dromara/soul/plugin/sofa/handler/SofaPluginDataHandlerTest.java
soul-plugin/soul-plugin-sofa/src/test/java/org/dromara/soul/plugin/sofa/response/SofaResponsePluginTest.java
soul-sync-data-center/soul-sync-data-http/src/test/java/org/dromara/soul/sync/data/http/HttpSyncDataServiceTest.java
soul-sync-data-center/soul-sync-data-websocket/src/main/java/org/dromara/soul/plugin/sync/data/weboscket/WebsocketSyncDataService.java
soul-web/src/main/java/org/dromara/soul/web/configuration/SoulExtConfiguration.java
soul-web/src/main/java/org/dromara/soul/web/handler/SoulWebHandler.java
soul-web/src/main/java/org/dromara/soul/web/logo/SoulLogo.java

When use IDEA open project, some .java files had a little of warning, I try to eliminate the warnings in these files.

Eliminate the number of code warnings in the IDE.

---

soul-admin/src/main/resources/application-local.yml
soul-admin/src/test/java/org/dromara/soul/admin/service/PluginServiceTest.java

Fixes 802,  improve code coverage for PluginServiceImpl from 80% to 100% in soul-admin.

 Improve code coverage for PluginServiceImpl in soul-admin

---

soul-admin/src/test/java/org/dromara/soul/admin/service/MetaDataServiceTest.java

Improve code coverage in soul-admin for MetaDataServiceImpl (#802)

Improve code coverage in soul-admin for MetaDataServiceImpl (#802)

---

soul-admin/src/test/java/org/dromara/soul/admin/service/AppAuthServiceTest.java

Improve code coverage in soul-admin for AppAuthServiceImpl (#802)

---

soul-admin/src/test/java/org/dromara/soul/admin/service/AppAuthServiceTest.java

Improve code coverage for AppAuthServiceImpl in soul-admin (#802).

---

soul-admin/src/test/java/org/dromara/soul/admin/config/WebConfigTest.java

Remove unused import

---

soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java

revert ApacheDubboProxyServiceTest.

---

soul-admin/src/test/java/org/dromara/soul/admin/service/SelectorServiceTest.java

Improve code coverage in soul-admin for SelectorServiceImpl (#802)

Improve code coverage in soul-admin for SelectorServiceImpl (#802)

---

soul-plugin/soul-plugin-waf/pom.xml
soul-plugin/soul-plugin-waf/src/test/java/org/dromara/soul/plugin/waf/WafPluginTest.java
soul-plugin/soul-plugin-waf/src/test/java/org/dromara/soul/plugin/waf/handler/WafPluginDataHandlerTest.java

Add test case for WafPlugin.
Fixes #839 

issue-839: Add test case for WafPlugin.

---

soul-client/soul-client-http/soul-client-springcloud/src/test/java/org/dromara/soul/client/springcloud/SpringCloudClientBeanPostProcessorTest.java

Rename test class name for SpringCloudClientBeanPostProcessor

---

soul-common/src/main/java/org/dromara/soul/common/enums/PluginEnum.java
soul-plugin/soul-plugin-httpclient/pom.xml
soul-plugin/soul-plugin-httpclient/src/test/java/org/dromara/soul/plugin/httpclient/WebClientPluginTest.java
soul-plugin/soul-plugin-httpclient/src/test/java/org/dromara/soul/plugin/httpclient/response/WebClientResponsePluginTest.java

add: test case for WebClientPluginTest and WebClientResponsePluginTest(fixes #837)

---

soul-admin/src/test/java/org/dromara/soul/admin/listener/zookeeper/ZookeeperDataChangedListenerTest.java

issue805, Improve code coverage listener in soul-admin for ZookeeperDataChangedListener

---

soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessorTest.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/ApacheDubboClientValidationTest.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/ApacheDubboClientValidatorTest.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/mock/MockConstraint.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/mock/MockConstraintValidator.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/mock/MockEnumType.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/mock/MockValidationParameter.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/mock/MockValidatorTarget.java

Add test case for soul-client-apache-dubbo.
Fixes #798 

issue-798: Add test case for soul-client-apache-dubbo.

---

soul-common/src/test/java/org/dromara/soul/common/utils/GsonUtilsTest.java

refactor: optimize GsonUtilsTest.java(fixes #858)

---

soul-admin/src/test/java/org/dromara/soul/admin/listener/DataChangedEventDispatcherTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/zookeeper/ZookeeperDataChangedListenerTest.java
soul-plugin/soul-plugin-hystrix/pom.xml

Improve code coverage DataChangedEventDispatcher and mock ZookeeperDataChangedListenerTest zkClient 

---

soul-admin/src/test/java/org/dromara/soul/admin/service/SoulDictServiceTest.java

Improve code coverage for SoulDictServiceImpl in soul-admin  (#802)

Improve code coverage for SoulDictServiceImpl in soul-admin

---

soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-apache-dubbo/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-apache-dubbo/src/test/java/org/dromara/soul/springboot/starter/client/apache/dubbo/SoulApacheDubboClientConfigurationTest.java

test: Add test case for SoulApacheDubboClientConfiguration.

---

soul-web/pom.xml
soul-web/src/test/java/org/dromara/soul/web/WebSocketParamFilterTest.java

Test cases for WebSocketParamFilter

---

script/soul_checkstyle.xml
soul-admin/src/test/java/org/dromara/soul/admin/listener/http/HttpLongPollingDataChangedListenerTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/collector/JmxScraperTest.java
soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java
soul-plugin/soul-plugin-divide/src/test/java/org/dromara/soul/plugin/divide/DividePluginTest.java
soul-plugin/soul-plugin-ratelimiter/src/test/java/org/dromara/soul/plugin/ratelimiter/RateLimiterPluginTest.java

Prohibit using `System.out.println()` in source code including test code.

`System.out.println` is prohibited

---

soul-admin/src/test/java/org/dromara/soul/admin/config/NacosConfigurationTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/AppAuthControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/MetaDataControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/controller/SoulClientControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/dto/AuthPathApplyDTOTest.java
soul-admin/src/test/java/org/dromara/soul/admin/result/SoulAdminResultTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/RuleServiceTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/SelectorServiceTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/SoulClientRegisterServiceTest.java

test: Add test case for soul-admin module.

---

soul-web/src/test/java/org/dromara/soul/web/forward/ForwardedRemoteAddressResolverTest.java

Fixes #868
- [x ] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [x ] You submit test cases (unit or integration tests) that back your changes.
- [x ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

add Test cases for ForwardedRemoteAddressResolver #868

---

soul-plugin/soul-plugin-httpclient/src/test/java/org/dromara/soul/plugin/httpclient/NettyHttpClientPluginTest.java
soul-plugin/soul-plugin-httpclient/src/test/java/org/dromara/soul/plugin/httpclient/WebClientPluginTest.java
soul-plugin/soul-plugin-httpclient/src/test/java/org/dromara/soul/plugin/httpclient/response/NettyClientResponsePluginTest.java

add: test case for NettyHttpClientPlugin and NettyClientResponsePlugin(fixes #837)

---

soul-admin/src/test/java/org/dromara/soul/admin/service/SoulClientRegisterServiceTest.java

#issueNo802 SoulClientRegisterServiceImpl

test: add test coverage about SoulClientRegisterServiceTest

---

soul-client/soul-client-common/pom.xml
soul-client/soul-client-common/src/main/java/org/dromara/soul/client/common/utils/OkHttpTools.java
soul-client/soul-client-common/src/test/java/org/dromara/soul/client/common/utils/OkHttpToolsTest.java

Fix testcase

---

soul-admin/src/test/java/org/dromara/soul/admin/listener/ApplicationStartListenerTest.java

Add test cases for ApplicationStartListener

---

soul-web/src/test/java/org/dromara/soul/web/filter/CrossFilterTest.java

add: test case for CrossFilter.(fix#867)

---

soul-client/soul-client-tars/src/main/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessor.java
soul-client/soul-client-tars/src/main/java/org/dromara/soul/client/tars/common/dto/MetaDataDTO.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/TarsPlugin.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/proxy/TarsInvokePrxList.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/util/PrxInfoUtil.java

[#771]tars plugin metadata and cache code refactoring

---

soul-client/soul-client-tars/src/test/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessorTest.java
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-tars/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-tars/src/test/java/org/dromara/soul/springboot/starter/client/tars/SoulTarsClientConfigurationTest.java

[#771]add tars client test

---

soul-admin/src/main/java/org/dromara/soul/admin/listener/nacos/NacosDataChangedListener.java

If nacos don't have config, sync-data maybe throw NPE, add default value "{}" handle NPE.

nacos-sync-data add default value;

---

soul-metrics/soul-metrics-prometheus/src/main/java/org/dromara/soul/metrics/prometheus/PrometheusMetricsTrackerManager.java

Fixes [https://github.com/dromara/soul/issues/934](https://github.com/dromara/soul/issues/934)

Fixed NPE that could be thrown

---

pom.xml
soul-admin/pom.xml
soul-admin/src/main/java/org/dromara/soul/admin/config/JwtProperties.java
soul-admin/src/main/java/org/dromara/soul/admin/shiro/bean/StatelessAuthFilter.java
soul-admin/src/main/java/org/dromara/soul/admin/shiro/bean/StatelessToken.java
soul-admin/src/main/java/org/dromara/soul/admin/shiro/config/ShiroConfiguration.java
soul-admin/src/main/java/org/dromara/soul/admin/shiro/config/ShiroRealm.java
soul-admin/src/main/java/org/dromara/soul/admin/utils/JwtUtils.java
soul-admin/src/main/resources/application-local.yml

feat: add shiro and jwt.

---

soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-alibaba-dubbo/src/test/java/org/dromara/soul/springboot/starter/client/alibaba/dubbo/SoulAlibabaDubboClientConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-apache-dubbo/src/test/java/org/dromara/soul/springboot/starter/client/apache/dubbo/SoulApacheDubboClientConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-sofa/src/test/java/org/dromara/soul/springboot/starter/client/sofa/SoulSofaClientConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-springcloud/src/test/java/org/dromara/soul/springboot/starter/client/springcloud/SoulSpringCloudClientConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-springmvc/src/test/java/org/dromara/soul/springboot/starter/client/springmvc/SoulSpringMvcClientConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-tars/src/test/java/org/dromara/soul/springboot/starter/client/tars/SoulTarsClientConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-alibaba-dubbo/src/test/java/org/dromara/soul/spring/boot/starter/plugin/alibaba/dubbo/AlibabaDubboPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-apache-dubbo/src/test/org/dromara/soul/spring/boot/starter/plugin/apache/dubbo/ApacheDubboPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-httpclient/src/test/java/org/dromara/soul/springboot/starter/plugin/httpclient/HttpClientPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-http/src/test/java/org/dromara/soul/spring/boot/starter/sync/data/http/HttpClientPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-nacos/src/test/java/org/dromara/soul/springboot/starter/sync/data/nacos/NacosSyncDataConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-websocket/src/test/java/org/dromara/soul/spring/boot/starter/sync/data/websocket/WebsocketSyncDataConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-zookeeper/src/test/java/org/dromara/soul/spring/boot/sync/data/zookeeper/ZookeeperSyncDataConfigurationTest.java

refactor soul-spring-boot-starter test classes

refactor soul-spring-boot-starter test classes

---

.github/ISSUE_TEMPLATE/task.md
.github/workflows/ci.yml
soul-dist/soul-admin-dist/Dockerfile

Fix build and add task issue template.

---

soul-client/soul-client-common/src/test/java/org/dromara/soul/client/common/utils/OkHttpToolsTest.java
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/test/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessorTest.java
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/test/java/org/dromara/soul/client/alibaba/dubbo/validation/AlibabaDubboClientValidatorTest.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessorTest.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/test/java/org/dromara/soul/client/apache/dubbo/validation/ApacheDubboClientValidatorTest.java
soul-client/soul-client-http/soul-client-springcloud/src/test/java/org/dromara/soul/client/springcloud/init/ContextRegisterListenerTest.java
soul-client/soul-client-http/soul-client-springcloud/src/test/java/org/dromara/soul/client/springcloud/init/SpringCloudClientBeanPostProcessorTest.java
soul-client/soul-client-http/soul-client-springcloud/src/test/java/org/dromara/soul/client/springcloud/utils/ValidateUtilsTest.java
soul-client/soul-client-http/soul-client-springmvc/src/test/java/org/dromara/soul/client/springmvc/init/ContextRegisterListenerTest.java
soul-client/soul-client-http/soul-client-springmvc/src/test/java/org/dromara/soul/client/springmvc/init/SpringMvcClientBeanPostProcessorTest.java
soul-client/soul-client-sofa/src/test/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessorTest.java

To optimize the soul-client test class.
Fixes #945 

test: To optimize the soul-client test class.

---

soul-bootstrap/src/test/java/org/dromara/soul/boostrap/DubboMultiParameterTest.java
soul-bootstrap/src/test/java/org/dromara/soul/boostrap/dubbo/ComplexBeanTest.java
soul-bootstrap/src/test/java/org/dromara/soul/boostrap/dubbo/DubboTest.java

for #945 modify all string variables to constants and Keep indents (including blank lines) consistent with the previous one in soul-bootstrap test

 optimize soul-bootstrap test case

---

soul-client/soul-client-tars/src/main/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessor.java
soul-client/soul-client-tars/src/main/java/org/dromara/soul/client/tars/common/dto/MetaDataDTO.java
soul-examples/soul-examples-tars/src/main/java/org/dromara/soul/examples/tars/servant/testapp/HelloServant.java
soul-plugin/soul-plugin-tars/pom.xml
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/TarsPlugin.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/util/ReturnValueResolver.java

[#963]tars return value polish.

---

soul-admin/src/main/resources/mappers/plugin-sqlmap.xml

Modify the query plug-in list sort field

---

soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/collector/BuildInfoCollectorTest.java
soul-metrics/soul-metrics-prometheus/src/test/java/org/dromara/soul/metrics/prometheus/impl/collector/JmxCollectorTest.java

[#972] fix #972 and Optimize BuildInfoCollectorTest

---

pom.xml

Fixes #981  
- this issue need not new test case. If not , please let me know. Thx.

fix pom property mismatch(#981)

---

soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/AbstractSoulPlugin.java

fix the log content of rule match success (#984)

---

soul-admin/src/main/java/org/dromara/soul/admin/listener/websocket/WebsocketCollector.java
soul-admin/src/main/java/org/dromara/soul/admin/utils/ThreadLocalUtil.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/websocket/WebsocketCollectorTest.java
soul-admin/src/test/java/org/dromara/soul/admin/utils/ThreadLocalUtilTest.java

Fixes #983 
Use ThreadLocal temporary storage websocket Session

modify temporary session

---

soul-admin/src/main/resources/META-INF/schema.h2.sql

Sync h2 sql

---

soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SelectorServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/UpstreamCheckService.java
soul-admin/src/test/java/org/dromara/soul/admin/service/SelectorServiceTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/UpstreamCheckServiceTest.java

* delete UpstreamCheckService dependence on SelectorService
* reduce one select operation in UpstreamCheckService#updateSelectorHandler
* modify SelectorServiceTest, UpstreamCheckServiceTest

fix the divide selector added through soul-admin is not checked (#990)

---

soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/subscriber/AlibabaDubboMetaDataSubscriber.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriber.java

fixed #994: soul-admin metadata sync to soul-bootstrap NPE

---

soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/cache/ApplicationConfigCache.java

Get rid of this bug for a while

change sofa config repeated num to -1

---

soul-common/src/test/java/org/dromara/soul/common/utils/UpstreamCheckUtilsTest.java

fix: UpstreamCheckUtilsTest will generate a port conflict(fix:#1003)

---

soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCacheTest.java

fix #1019 
- [ √] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [√ ] You submit test cases (unit or integration tests) that back your changes.
- [√ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

alibaba and apache dubbo config cache execption catch

---

soul-admin/src/main/java/org/dromara/soul/admin/config/DataSyncConfiguration.java

fix #1024: correct the comment of (default strategy)

fix #1024: correct the comment of (default strategy)

---

soul-admin/src/main/java/org/dromara/soul/admin/page/PageResultUtils.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/AppAuthServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/DashboardUserServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/MetaDataServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/PluginHandleServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/PluginServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/ResourceServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/RoleServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/RuleServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SelectorServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulDictServiceImpl.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/UpstreamCheckService.java
soul-admin/src/main/java/org/dromara/soul/admin/transfer/ConditionTransfer.java
soul-admin/src/test/java/org/dromara/soul/admin/page/PageResultUtilsTest.java

Fix #1031 
- [ √] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [√ ] You submit test cases (unit or integration tests) that back your changes.
- [ √] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

Refactor code#1031

---

soul-sync-data-center/soul-sync-data-zookeeper/src/main/java/org/dromara/soul/sync/data/zookeeper/ZookeeperSyncDataService.java

fix #1037:ZookeeperSyncDataService's watchMetaData subscribe wrong group

fix #1037:ZookeeperSyncDataService's watchMetaData subscribe wrong group

---

soul-admin/src/main/java/org/dromara/soul/admin/listener/zookeeper/ZookeeperDataChangedListener.java

fix IndexOutOfBoundsException thrown when synchronizing divide plugin data by zookeeper.  issue #1033

---

soul-bootstrap/src/main/resources/application-local.yml

Use enabled instead of enable.

Fix: Use enabled instead of enable.

---

soul-admin/src/main/resources/mappers/selector-sqlmap.xml

Fix selector resultMap

---

soul-admin/src/main/java/org/dromara/soul/admin/listener/websocket/WebsocketCollector.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java
soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/subscriber/AlibabaDubboMetaDataSubscriber.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriber.java

refactor DubboMetaDataSubscriber variables
refactor WebsocketCollector and fix comment typo in SoulClientRegisterServiceImpl

do some refactor

---

soul-sync-data-center/soul-sync-data-nacos/src/main/java/org/dromara/soul/sync/data/nacos/handler/NacosCacheHandler.java

fix #1045 throw NullPointerException when synchronizing data with nacos

---

soul-admin/src/main/java/org/dromara/soul/admin/config/DataSyncConfiguration.java
soul-admin/src/main/java/org/dromara/soul/admin/listener/nacos/NacosDataChangedListener.java
soul-admin/src/main/java/org/dromara/soul/admin/listener/nacos/NacosDataInit.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/nacos/NacosDataChangedListenerTest.java
soul-common/src/main/java/org/dromara/soul/common/constant/NacosPathConstants.java

// Describe your PR here; eg. Fixes Nacos synchronize Data can't init load to nacos and rules add is empty #1052 

fix soul-admin nacos don't synchronize data to nacos when nacos center is empty

---

soul-web/src/test/java/org/dromara/soul/web/filter/ExcludeFilterTest.java

add test case for ExcludeFilter.

test: add test case for ExcludeFilter.

---

soul-admin/src/main/resources/application.yml

add soul internal request path to shiro white list

---

pom.xml
soul-admin/pom.xml

Fix #1065:NoClassDefFoundError caused by dependency of commons-dbcp:1.2.1

---

soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-springcloud/src/main/java/org/dromara/soul/springboot/starter/client/springcloud/SoulSpringCloudClientConfiguration.java

Optimize code comments of SoulSpringCloudClientConfiguration.java

---

soul-admin/src/main/resources/application.yml
soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/handler/RateLimiterPluginDataHandler.java
soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/handler/SoulReactiveRedisTemplate.java
soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/handler/SoulReactiveScriptExecutor.java

ratelimiter-plugin stress testing, report an java.lang.IllegalStateException Error #1060
This PR does two things:
1.Create in SoulReactiveRedisTemplate.java and SoulReactiveScriptExecutor package org.dromara.soul.plugin.ratelimiter.handler 
1.Update org.dromara.soul.plugin.ratelimiter.handler.RateLimiterPluginDataHandler handlerPlugin method, Replace  ReactiveRedisTemplate<String, String> reactiveRedisTemplate = new ReactiveRedisTemplate<>(lettuceConnectionFactory, serializationContext)  with  ReactiveRedisTemplate<String, String> reactiveRedisTemplate = new SoulReactiveRedisTemplate<>(lettuceConnectionFactory, serializationContext);

repair issueNo 1060

---

soul-plugin/soul-plugin-waf/src/main/java/org/dromara/soul/plugin/waf/WafPlugin.java

replace magic value 403 -> HttpStatus#FORBIDDEN#value

replace magic value

---

soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-springcloud/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-client/soul-spring-boot-starter-client-springcloud/src/test/java/org/dromara/soul/springboot/starter/client/springcloud/SoulSpringCloudClientConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-context-path/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-context-path/src/test/java/org/dromara/soul/springboot/starter/plugin/contextpath/ContextPathMappingPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-divide/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-divide/src/test/java/org/dromara/soul/spring/boot/plugin/divide/DividePluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-global/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-global/src/test/java/org/dromara/soul/spring/boot/starter/plugin/global/GlobalPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-hystrix/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-hystrix/src/test/java/org/dromara/soul/springboot/starter/plugin/hystrix/HystrixPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-monitor/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-monitor/src/test/java/org/dromara/soul/springboot/starter/plugin/monitor/MonitorPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-ratelimiter/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-ratelimiter/src/test/java/org/dromara/soul/springboot/starter/plugin/ratelimiter/RateLimiterPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-resilience4j/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-resilience4j/src/test/java/org/dromara/soul/springboot/starter/plugin/resilience4j/Resilience4JPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-rewrite/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-rewrite/src/test/java/org/dromara/soul/springboot/starter/plugin/rewrite/RewritePluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-sentinel/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-sentinel/src/test/java/org/dromara/soul/springboot/starter/plugin/sentinel/SentinelPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-sign/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-sign/src/test/java/org/dromara/soul/springboot/starter/plugin/sign/SignPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-sofa/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-sofa/src/test/java/org/dromara/soul/spring/boot/starter/plugin/sofa/SofaPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-tars/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-tars/src/test/java/org/dromara/soul/spring/boot/starter/plugin/tars/TarsPluginConfigurationTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-waf/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-waf/src/test/java/org/dromara/soul/springboot/starter/plugin/waf/WafPluginConfigurationTest.java

Add test case for soul-spring-boot-starter-plugin.

test: Add test case for soul-spring-boot-starter-plugin.

---

soul-sync-data-center/soul-sync-data-http/src/main/java/org/dromara/soul/sync/data/http/refresh/AbstractDataRefresh.java

fix #1084 modify the prompt so that it accurately expresses the problem

---

soul-plugin/soul-plugin-sentinel/src/main/java/org/dromara/soul/plugin/sentinel/SentinelPlugin.java

SentinelPlugin：The http success status is changed from 200 to 2XX

---

pom.xml
soul-admin/src/main/java/org/dromara/soul/admin/entity/RuleDO.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/RuleServiceImpl.java
soul-admin/src/main/resources/META-INF/schema.h2.sql
soul-admin/src/main/resources/META-INF/schema.sql
soul-admin/src/test/java/org/dromara/soul/admin/service/RuleServiceTest.java
soul-common/src/main/java/org/dromara/soul/common/dto/convert/Resilience4JHandle.java
soul-common/src/main/java/org/dromara/soul/common/dto/convert/SentinelHandle.java
soul-plugin/soul-plugin-resilience4j/src/main/java/org/dromara/soul/plugin/resilience4j/Resilience4JPlugin.java
soul-plugin/soul-plugin-resilience4j/src/main/java/org/dromara/soul/plugin/resilience4j/build/Resilience4JBuilder.java
soul-plugin/soul-plugin-sentinel/src/main/java/org/dromara/soul/plugin/sentinel/SentinelPlugin.java
soul-plugin/soul-plugin-sentinel/src/main/java/org/dromara/soul/plugin/sentinel/handler/SentinelRuleHandle.java

[#1092] fix #1092- Modify the content of the plugin label and optimize the necessary properties of the plugin must have default values

---

soul-admin/src/main/java/org/dromara/soul/admin/controller/SoulClientController.java
soul-admin/src/main/java/org/dromara/soul/admin/dto/SpringCloudRegisterDTO.java
soul-admin/src/main/java/org/dromara/soul/admin/dto/SpringMvcRegisterDTO.java
soul-admin/src/main/java/org/dromara/soul/admin/register/zookeeper/ZookeeperRegisterService.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java
soul-admin/src/main/resources/application.yml
soul-admin/src/test/java/org/dromara/soul/admin/controller/SoulClientControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/SoulClientRegisterServiceTest.java
soul-client/soul-client-http/soul-client-springmvc/src/main/java/org/dromara/soul/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
soul-client/soul-client-tars/src/test/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessorTest.java
soul-examples/soul-examples-http/src/main/resources/application.yml
soul-examples/soul-examples-sofa/src/main/resources/application.yml
soul-examples/soul-examples-springcloud/README.md
soul-examples/soul-examples-tars/README.md
soul-register-center/soul-register-client/soul-register-client-http/src/main/java/org/dromara/soul/register/client/http/HttpClientRegisterRepository.java
soul-register-center/soul-register-common/src/main/java/org/dromara/soul/register/common/dto/MetaDataDTO.java

repair http register

---

soul-admin/src/test/java/org/dromara/soul/admin/controller/RoleControllerTest.java
soul-admin/src/test/java/org/dromara/soul/admin/mapper/RoleMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/RoleServiceTest.java

Test cases for RoleService, RoleMapper, RoleController 

[#1071]Add test case for soul-admin

---

soul-admin/src/main/java/org/dromara/soul/admin/service/impl/DashboardUserServiceImpl.java
soul-admin/src/main/resources/mappers/dashboard-user-sqlmap.xml

modify dashboard-user-sqlmap.xml

---

soul-admin/src/main/resources/META-INF/schema.h2.sql
soul-admin/src/main/resources/META-INF/schema.sql
soul-admin/src/test/java/org/dromara/soul/admin/mapper/DashboardUserMapperTest.java

add unique constraint 'unique_user_name' on table dashboard_user

---

soul-client/soul-client-tars/src/main/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessor.java

```
2021-02-08 23:47:15.217 ERROR 33080 --- [ctReadThread-22] o.d.s.p.t.cache.ApplicationConfigCache   : init tars ref ex:null
java.lang.NullPointerException
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.dromara.soul.plugin.tars.util.PrxInfoUtil.getParamClass(PrxInfoUtil.java:61)
at org.dromara.soul.plugin.tars.cache.ApplicationConfigCache.initPrx(ApplicationConfigCache.java:139)
at org.dromara.soul.plugin.tars.subscriber.TarsMetaDataSubscriber.onSubscribe(TarsMetaDataSubscriber.java:50)
at org.dromara.soul.plugin.sync.data.websocket.handler.MetaDataHandler.lambda$null$0(MetaDataHandler.java:42)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.dromara.soul.plugin.sync.data.websocket.handler.MetaDataHandler.lambda$doRefresh$1(MetaData …
```

Fix tars client register

---

soul-admin/src/main/java/org/dromara/soul/admin/controller/DashboardUserController.java

Delete unnecessary log in DashboardUserController

Delete unnecessary log in DashboardUserController

---

pom.xml
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessor.java
soul-client/soul-client-sofa/src/main/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessor.java
soul-client/soul-client-tars/src/main/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessor.java
soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/handler/SoulReactiveScriptExecutor.java

Optimize log, dependencies, and deprecated method 
* Log when Redis execute script hit exception
* Bump guava version to fix dependencies conflict #1000
* replace deprecated ClassUtils.isCglibProxyClass to AopUtils.isCglibProxy

Bump guava version to fix dependencies conflict #1000

---

soul-admin/src/main/resources/mappers/app-auth-sqlmap.xml
soul-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
soul-admin/src/main/resources/mappers/soul-dict-sqlmap.xml

optimized mybatis statement, "where 1=1" replace to label <where>

---

soul-admin/src/main/resources/mappers/app-auth-sqlmap.xml
soul-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml

optimize some statements,avoid some query questions.

---

soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-sofa/src/main/java/org/dromara/soul/plugin/sofa/proxy/SofaProxyService.java

sofa code polish

---

soul-admin/src/main/java/org/dromara/soul/admin/config/RegisterCenterConfiguration.java
soul-admin/src/main/java/org/dromara/soul/admin/disruptor/SoulServerMetaDataRegisterEventPublisher.java
soul-admin/src/main/resources/application.yml
soul-bootstrap/pom.xml
soul-client/soul-client-http/soul-client-springcloud/src/main/java/org/dromara/soul/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
soul-client/soul-client-http/soul-client-springmvc/src/main/java/org/dromara/soul/client/springmvc/init/ContextRegisterListener.java
soul-client/soul-client-http/soul-client-springmvc/src/main/java/org/dromara/soul/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
soul-examples/soul-examples-dubbo/soul-examples-alibaba-dubbo-service/src/main/resources/application.yml
soul-examples/soul-examples-dubbo/soul-examples-apache-dubbo-service/src/main/resources/application.yml
soul-examples/soul-examples-http/src/main/resources/application.yml
soul-examples/soul-examples-sofa/src/main/resources/application.yml
soul-examples/soul-examples-springcloud/src/main/resources/application.yml
soul-examples/soul-examples-tars/pom.xml
soul-examples/soul-examples-tars/src/main/resources/application.yml
soul-register-center/soul-register-client/soul-register-client-http/src/main/java/org/dromara/soul/register/client/http/HttpClientRegisterRepository.java
soul-register-center/soul-register-client/soul-register-client-http/src/main/java/org/dromara/soul/register/client/http/utils/OkHttpTools.java
soul-register-center/soul-register-client/soul-register-client-http/src/main/java/org/dromara/soul/register/client/http/utils/RegisterUtils.java
soul-register-center/soul-register-client/soul-register-client-http/src/test/java/org/dromara/soul/register/client/http/OkHttpToolsTest.java
soul-register-center/soul-register-client/soul-register-client-http/src/test/java/org/dromara/soul/register/client/http/RegisterUtilsTest.java
soul-register-center/soul-register-client/soul-register-client-zookeeper/src/main/java/org/dromara/soul/register/client/zookeeper/ZookeeperClientRegisterRepository.java
soul-register-center/soul-register-server/soul-register-server-api/src/main/java/org/dromara/soul/register/server/api/SoulSeverRegisterCenterEventPublisher.java
soul-register-center/soul-register-server/soul-register-server-zookeeper/src/main/java/org/dromara/soul/register/server/zookeeper/ZookeeperServerRegisterRepository.java
soul-spring-boot-starter/pom.xml

refactor http register

---

soul-examples/pom.xml

fix soul-example maven pom

---

soul-admin/src/main/java/org/dromara/soul/admin/disruptor/SoulServerMetaDataRegisterEventHandler.java
soul-client/soul-client-grpc/src/main/java/org/dromara/soul/client/grpc/GrpcClientBeanPostProcessor.java
soul-examples/pom.xml

Fix grpc register

---

soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessor.java
soul-client/soul-client-grpc/src/main/java/org/dromara/soul/client/grpc/GrpcClientBeanPostProcessor.java
soul-client/soul-client-sofa/src/main/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessor.java
soul-client/soul-client-tars/src/main/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessor.java

Fix client register

---

soul-web/src/main/java/org/dromara/soul/web/filter/FileSizeFilter.java
soul-web/src/test/java/org/dromara/soul/web/filter/FileSizeFilterTest.java

Fixes #issue167
master branch code.  to resolve DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144

fix #167 modify file size limit

---

soul-plugin/soul-plugin-divide/src/main/java/org/dromara/soul/plugin/divide/DividePlugin.java

// Describe your PR here; eg. Fixes #issueNo 1133
1.update DividePlugin.buildRealUrl(), getRawQuery() replace getQuery()

update DividePlugin.buildRealUrl(), getRawQuery() replace getQuery()

---

README.md
README_CN.md

Fix gitee link

---

soul-plugin/soul-plugin-api/src/main/java/org/dromara/soul/plugin/api/result/SoulResultEnum.java
soul-web/src/main/java/org/dromara/soul/web/fallback/DefaultFallbackController.java
soul-web/src/test/java/org/dromara/soul/web/fallback/DefaultFallbackControllerTest.java

Add default failback Impl for Resilience4j  Plugin In Soul Bootstrap #1123

Add default fallback Impl for resilience4j plugin.

---

soul-admin/src/main/java/org/dromara/soul/admin/config/RegisterCenterConfiguration.java
soul-admin/src/main/java/org/dromara/soul/admin/controller/SoulClientController.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java
soul-register-center/soul-register-client/soul-register-client-zookeeper/src/main/java/org/dromara/soul/register/client/zookeeper/ZookeeperClientRegisterRepository.java
soul-register-center/soul-register-server/soul-register-server-zookeeper/src/main/java/org/dromara/soul/register/server/zookeeper/ZookeeperServerRegisterRepository.java

fix http and zk register

---

soul-admin/src/main/resources/META-INF/schema.h2.sql
soul-admin/src/main/resources/META-INF/schema.sql
soul-common/src/main/java/org/dromara/soul/common/dto/convert/RedirectHandle.java
soul-plugin/pom.xml
soul-plugin/soul-plugin-redirect/pom.xml
soul-plugin/soul-plugin-redirect/src/main/java/org/dromara/soul/plugin/redirect/RedirectPlugin.java
soul-plugin/soul-plugin-redirect/src/test/java/org/dromara/soul/plugin/redirect/RedirectPluginTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-redirect/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-redirect/src/main/java/org/dromara/soul/springboot/starter/plugin/redirect/RedirectPluginConfiguration.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-redirect/src/main/resources/META-INF/spring.factories
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-redirect/src/main/resources/META-INF/spring.provides
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-redirect/src/test/java/org/dromara/soul/springboot/starter/plugin/redirect/RedirectPluginConfigurationTest.java

add redirect plugin.
Fixes #1137 

issue-1137: Add redirect plugin

---

soul-admin/src/main/java/org/dromara/soul/admin/disruptor/subscriber/URIRegisterExecutorSubscriber.java
soul-admin/src/main/java/org/dromara/soul/admin/service/SoulClientRegisterService.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java
soul-register-center/soul-register-server/soul-register-server-zookeeper/src/main/java/org/dromara/soul/register/server/zookeeper/ZookeeperServerRegisterRepository.java

refactor zk register center mvc upstream update

---

soul-admin/src/main/java/org/dromara/soul/admin/config/NacosConfiguration.java
soul-admin/src/main/java/org/dromara/soul/admin/config/properties/NacosProperties.java
soul-admin/src/main/resources/application.yml
soul-admin/src/test/java/org/dromara/soul/admin/config/NacosConfigurationTest.java
soul-bootstrap/src/main/resources/application-local.yml
soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-nacos/src/main/java/org/dromara/soul/springboot/starter/sync/data/nacos/NacosSyncDataConfiguration.java
soul-sync-data-center/soul-sync-data-nacos/src/main/java/org/dromara/soul/sync/data/nacos/config/NacosConfig.java

support Nacos config authentication for sync data

---

.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/task.md
.github/PULL_REQUEST_TEMPLATE.md

fix issue template

---

soul-admin/src/main/resources/META-INF/schema.h2.sql
soul-admin/src/main/resources/META-INF/schema.sql

[#1138] add rate_limiter four algorithm

---

soul-admin/src/main/resources/META-INF/schema.h2.sql
soul-admin/src/main/resources/META-INF/schema.sql

[#1138] Adjust rate_limiter handle order

---

soul-plugin/soul-plugin-ratelimiter/src/main/java/org/dromara/soul/plugin/ratelimiter/algorithm/SlidingWindowRateLimiterAlgorithm.java
soul-plugin/soul-plugin-ratelimiter/src/main/resources/META-INF/scripts/sliding_window_request_rate_limiter.lua
soul-plugin/soul-plugin-ratelimiter/src/main/resources/META-INF/soul/org.dromara.soul.plugin.ratelimiter.algorithm.RateLimiterAlgorithm

[#1138] Add sliding window rate limiter algorithm

---

soul-register-center/soul-register-client/soul-register-client-etcd/src/main/java/org/dromara/soul/register/client/etcd/EtcdClient.java
soul-register-center/soul-register-client/soul-register-client-etcd/src/main/java/org/dromara/soul/register/client/etcd/EtcdClientRegisterRepository.java
soul-register-center/soul-register-client/soul-register-client-etcd/src/test/java/org/dromara/soul/register/client/etcd/EtcdClientRegisterRepositoryTest.java
soul-register-center/soul-register-client/soul-register-client-zookeeper/src/main/java/org/dromara/soul/register/client/zookeeper/ZookeeperClientRegisterRepository.java
soul-register-center/soul-register-common/src/main/java/org/dromara/soul/register/common/path/RegisterPathConstants.java
soul-register-center/soul-register-server/soul-register-server-etcd/src/main/java/org/dromara/soul/register/server/etcd/EtcdServerRegisterRepository.java
soul-register-center/soul-register-server/soul-register-server-etcd/src/main/java/org/dromara/soul/register/server/etcd/client/EtcdClient.java
soul-register-center/soul-register-server/soul-register-server-etcd/src/test/java/org/dromara/soul/register/server/etcd/EtcdServerRegisterRepositoryTest.java
soul-register-center/soul-register-server/soul-register-server-zookeeper/src/main/java/org/dromara/soul/register/server/zookeeper/ZookeeperServerRegisterRepository.java

refactor etcd register client
add test for EtcdClientRegisterRepository
refactor etcd register server
add test for EtcdServerRegisterRepository

refactor etcd register center

---

soul-client/soul-client-tars/src/main/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessor.java
soul-client/soul-client-tars/src/test/java/org/dromara/soul/client/tars/TarsServiceBeanPostProcessorTest.java
soul-examples/soul-examples-tars/src/main/resources/application.yml

change the way tars register

---

README.md
README_CN.md

[#1179] update readme

---

soul-admin/pom.xml
soul-admin/src/main/resources/application.yml
soul-client/soul-client-core/pom.xml
soul-client/soul-client-dubbo/soul-client-alibaba-dubbo/src/main/java/org/dromara/soul/client/alibaba/dubbo/AlibabaDubboServiceBeanPostProcessor.java
soul-client/soul-client-dubbo/soul-client-apache-dubbo/src/main/java/org/dromara/soul/client/apache/dubbo/ApacheDubboServiceBeanPostProcessor.java
soul-client/soul-client-http/soul-client-springcloud/src/main/java/org/dromara/soul/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
soul-client/soul-client-sofa/src/main/java/org/dromara/soul/client/sofa/SofaServiceBeanPostProcessor.java
soul-examples/soul-examples-dubbo/soul-examples-alibaba-dubbo-service/src/main/resources/application.yml
soul-examples/soul-examples-dubbo/soul-examples-apache-dubbo-service/src/main/resources/application.yml
soul-examples/soul-examples-grpc/src/main/resources/application.yml
soul-examples/soul-examples-http/src/main/resources/application.yml
soul-examples/soul-examples-sofa/soul-examples-sofa-service/src/main/resources/application.yml
soul-examples/soul-examples-springcloud/src/main/resources/application.yml
soul-examples/soul-examples-tars/src/main/resources/application.yml
soul-register-center/soul-register-client/pom.xml
soul-register-center/soul-register-client/soul-register-client-nacos/pom.xml
soul-register-center/soul-register-client/soul-register-client-nacos/src/main/java/org/dromara/soul/register/client/nacos/NacosClientRegisterRepository.java
soul-register-center/soul-register-client/soul-register-client-nacos/src/main/resources/META-INF/soul/org.dromara.soul.register.client.api.SoulClientRegisterRepository
soul-register-center/soul-register-common/src/main/java/org/dromara/soul/register/common/path/RegisterPathConstants.java
soul-register-center/soul-register-server/soul-register-server-nacos/pom.xml
soul-register-center/soul-register-server/soul-register-server-nacos/src/main/java/org/dromara/soul/register/server/nacos/NacosServerRegisterRepository.java
soul-register-center/soul-register-server/soul-register-server-nacos/src/main/resources/META-INF/soul/org.dromara.soul.register.server.api.SoulServerRegisterRepository

add nacos register center
fix some bug
fix ci
fix some detail
// Describe your PR here; eg. Fixes #1162 

nacos register center

---

soul-admin/src/main/resources/logback.xml
soul-bootstrap/src/main/resources/logback.xml

add logback configuration file to soul-admin and soul-bootstrap

---

soul-admin/pom.xml
soul-admin/src/main/java/org/dromara/soul/admin/config/NacosConfiguration.java
soul-admin/src/test/java/org/dromara/soul/admin/config/WebConfigurationTest.java
soul-admin/src/test/java/org/dromara/soul/admin/listener/nacos/NacosMockConfigService.java
soul-register-center/soul-register-client/soul-register-client-nacos/pom.xml
soul-register-center/soul-register-server/soul-register-server-nacos/pom.xml
soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-nacos/src/main/java/org/dromara/soul/springboot/starter/sync/data/nacos/NacosSyncDataConfiguration.java
soul-spring-boot-starter/soul-spring-boot-starter-sync-data-center/soul-spring-boot-starter-sync-data-nacos/src/test/java/org/dromara/soul/springboot/starter/sync/data/nacos/NacosMockConfigService.java
soul-sync-data-center/soul-sync-data-nacos/pom.xml
soul-sync-data-center/soul-sync-data-nacos/src/test/java/org/dromara/soul/sync/data/nacos/handler/NacosMockConfigService.java

nacos2.0.0 adapt

---

soul-sync-data-center/soul-sync-data-http/src/main/java/org/dromara/soul/sync/data/http/refresh/PluginDataRefresh.java

optimize code structure(#1200)

optimize code structure(#1200)

---

soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/util/PrxInfoUtil.java
soul-plugin/soul-plugin-tars/src/test/java/org/dromara/soul/plugin/tars/util/PrxInfoUtilTest.java

polish the tars primitive type map

---

README.md
README_CN.md

[#1207] add who use soul

---

soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-httpclient/src/main/java/org/dromara/soul/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java

fix Duplicate handler name: write_timeout

---

soul-admin/src/main/java/org/dromara/soul/admin/service/impl/SoulClientRegisterServiceImpl.java
soul-common/src/main/java/org/dromara/soul/common/dto/MetaData.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/handler/TarsPluginDataHandler.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/subscriber/TarsMetaDataSubscriber.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/util/PrxInfoUtil.java
soul-plugin/soul-plugin-tars/src/test/java/org/dromara/soul/plugin/tars/util/PrxInfoUtilTest.java

Fix tars register issue

---

soul-dist/soul-admin-dist/Dockerfile
soul-dist/soul-admin-dist/entrypoint.sh
soul-dist/soul-bootstrap-dist/entrypoint.sh

improve dockerfile

---

soul-examples/pom.xml

change soul.version in soul-examples

---

soul-plugin/soul-plugin-httpclient/src/main/java/org/dromara/soul/plugin/httpclient/WebClientPlugin.java
soul-plugin/soul-plugin-tars/src/main/java/org/dromara/soul/plugin/tars/TarsPlugin.java

chore: print full stack trace error log

---

soul-common/src/main/java/org/dromara/soul/common/utils/IpUtils.java
soul-common/src/test/java/org/dromara/soul/common/utils/IpUtilsTest.java

refactor IpUtils

---

.github/release-drafter-config.yml
.github/workflows/codeql-analysis.yml

Add codeql-analysis and update release drafter config

---

soul-common/src/main/java/org/dromara/soul/common/utils/JsonUtils.java
soul-common/src/test/java/org/dromara/soul/common/utils/JsonUtilsTest.java
soul-examples/soul-examples-dubbo/soul-examples-alibaba-dubbo-service/src/main/java/org/dromara/soul/examples/alibaba/dubbo/service/impl/DubboTestServiceImpl.java
soul-examples/soul-examples-dubbo/soul-examples-apache-dubbo-service/src/main/java/org/dromara/soul/examples/apache/dubbo/service/impl/DubboTestServiceImpl.java
soul-examples/soul-examples-dubbo/soul-examples-dubbo-api/src/main/java/org/dromara/soul/examples/dubbo/api/entity/ListResp.java

Fixes [https://github.com/dromara/soul/issues/1232](https://github.com/dromara/soul/issues/1232)

Fix excluding 'class' field not working

---

soul-admin/src/main/resources/application.yml

fix admin boot exception for mysql jdbc option useSSL=false

fix admin boot exception

---

soul-common/src/main/java/org/dromara/soul/common/utils/UpstreamCheckUtils.java
soul-common/src/test/java/org/dromara/soul/common/utils/UpstreamCheckUtilsTest.java

// Describe your PR here; eg. Fixes #1235 

UpStreamCheckUtils detection failing when upstream using hostname without port

---

soul-dist/README.md

Update dist README

---

soul-plugin/soul-plugin-divide/src/test/java/org/dromara/soul/plugin/divide/DividePluginTest.java
soul-plugin/soul-plugin-httpclient/src/test/java/org/dromara/soul/plugin/httpclient/WebClientPluginTest.java

add the test case that post request with query in the url

---

soul-register-center/soul-register-client/soul-register-client-zookeeper/src/test/java/org/dromara/soul/register/client/zookeeper/ZookeeperClientRegisterRepositoryTest.java

add test： ZookeeperClientRegisterRepositoryTest.java

---

soul-bootstrap/src/main/java/org/dromara/soul/bootstrap/SoulBootstrapApplication.java
soul-bootstrap/src/main/java/org/dromara/soul/bootstrap/configuration/SoulNettyWebServerFactory.java
soul-bootstrap/src/main/java/org/dromara/soul/bootstrap/filter/HealthFilter.java
soul-common/src/main/java/org/dromara/soul/common/utils/SignUtils.java
soul-plugin/soul-plugin-api/src/main/java/org/dromara/soul/plugin/api/utils/WebFluxResultUtils.java

minor refactoring for soul bootstrap.

minor refactoring

---

soul-dist/soul-admin-dist/src/main/resources/bin/start.bat
soul-dist/soul-bootstrap-dist/src/main/resources/bin/start.bat

Fixes [https://github.com/dromara/soul/issues/1263](https://github.com/dromara/soul/issues/1263)

Fix windows start script config

---

soul-admin/src/main/java/org/dromara/soul/admin/mapper/PluginMapper.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/UpstreamCheckService.java
soul-admin/src/main/resources/mappers/plugin-sqlmap.xml
soul-admin/src/test/java/org/dromara/soul/admin/mapper/PluginMapperTest.java
soul-admin/src/test/java/org/dromara/soul/admin/service/UpstreamCheckServiceTest.java
soul-common/src/main/java/org/dromara/soul/common/constant/Constants.java
soul-common/src/main/java/org/dromara/soul/common/enums/PluginEnum.java
soul-plugin/soul-plugin-context-path/src/main/java/org/dromara/soul/plugin/contextpath/ContextPathMappingPlugin.java
soul-plugin/soul-plugin-context-path/src/test/java/org/dromara/soul/plugin/contextpath/ContextPathMappingPluginTest.java

1.remove String.split() in ContextPathMappingPlugin
2.fix UpstreamCheckService setUp method can not load grpc and tars selector
3.fix some Constants

remove String.split() in ContextPathMappingPlugin

---

soul-register-center/soul-register-server/soul-register-server-etcd/src/main/java/org/dromara/soul/register/server/etcd/EtcdServerRegisterRepository.java

fix etcd-register-server subscribeMetaData, make etcd-register-server work normal

fix(etcd): fix etcd register-server

---

README.md
README_CN.md

fix README.md

---

soul-common/src/main/java/org/dromara/soul/common/enums/OperatorEnum.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactory.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/SpELJudge.java
soul-plugin/soul-plugin-base/src/test/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactoryTest.java

#1295, add SpEL for judge conditions

---

soul-common/src/main/java/org/dromara/soul/common/utils/GsonUtils.java
soul-plugin/soul-plugin-dubbo-common/src/test/java/org/dromara/soul/plugin/dubbo/common/param/DubboBodyParamResolveServiceTest.java

fix #1311， add mutil parameter test case
- [√] You have read the [contribution guidelines](https://dromara.org/projects/soul/contributor/).
- [√] You submit test cases (unit or integration tests) that back your changes.
- [√] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

fix: json convert to map throws exception (#1311)

---

soul-examples/pom.xml
soul-examples/soul-examples-motan/pom.xml
soul-examples/soul-examples-motan/soul-examples-motan-api/pom.xml
soul-examples/soul-examples-motan/soul-examples-motan-api/src/main/java/org/dromara/soul/examples/motan/service/MotanDemoService.java
soul-examples/soul-examples-motan/soul-examples-motan-service/pom.xml
soul-examples/soul-examples-motan/soul-examples-motan-service/src/main/java/org/dromara/soul/examples/motan/service/TestMotanApplication.java
soul-examples/soul-examples-motan/soul-examples-motan-service/src/main/java/org/dromara/soul/examples/motan/service/impl/MotanDemoServiceImpl.java

Add motan demo

---

soul-register-center/soul-register-server/soul-register-server-nacos/src/main/java/org/dromara/soul/register/server/nacos/NacosServerRegisterRepository.java

// Describe your PR here; eg. Fixes #1297

fix nacos register center update uri error

---

soul-register-center/soul-register-client/soul-register-client-nacos/src/main/java/org/dromara/soul/register/client/nacos/NacosClientRegisterRepository.java
soul-register-center/soul-register-server/soul-register-server-nacos/src/main/java/org/dromara/soul/register/server/nacos/NacosServerRegisterRepository.java

code polish

---

soul-plugin/soul-plugin-api/src/main/java/org/dromara/soul/plugin/api/utils/BodyParamUtils.java

#1306 
- [ √] You have read the [contribution guidelines](https://dromara.org/projects/soul/contributor/).
- [ √] You submit test cases (unit or integration tests) that back your changes.
- [ √] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

optimize: dubbo plugin support parameter name->type mapping (#1306)

---

soul-plugin/soul-plugin-alibaba-dubbo/src/main/java/org/dromara/soul/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCache.java
soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/cache/ApplicationConfigCacheTest.java

fix #1308 and add test case
- [√] You have read the [contribution guidelines](https://dromara.org/projects/soul/contributor/).
- [√] You submit test cases (unit or integration tests) that back your changes.
- [√] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

fix: can't update dubbo plugin registry config (#1308)

---

soul-admin/pom.xml
soul-admin/src/main/java/org/dromara/soul/admin/config/LdapConfiguration.java
soul-admin/src/main/java/org/dromara/soul/admin/config/properties/LdapProperties.java
soul-admin/src/main/java/org/dromara/soul/admin/service/DashboardUserService.java
soul-admin/src/main/java/org/dromara/soul/admin/service/impl/DashboardUserServiceImpl.java
soul-admin/src/main/resources/META-INF/schema.h2.sql
soul-admin/src/main/resources/META-INF/schema.sql
soul-admin/src/main/resources/application.yml
soul-admin/src/test/java/org/dromara/soul/admin/service/DashboardUserServiceTest.java

soul-admin login support ldap
#1302 

soul-admin login support ldap

---

pom.xml
soul-common/src/main/java/org/dromara/soul/common/enums/OperatorEnum.java
soul-plugin/soul-plugin-base/pom.xml
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/GroovyJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactory.java
soul-plugin/soul-plugin-base/src/test/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactoryTest.java

#1295, add Groovy for judge conditions

---

soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/GroovyJudge.java
soul-plugin/soul-plugin-base/src/test/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactoryTest.java

#1295, change to standard Groovy expression and support GString

---

soul-common/src/main/java/org/dromara/soul/common/enums/OperatorEnum.java
soul-common/src/test/java/org/dromara/soul/common/enums/OperatorEnumTest.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/ContainsOperatorJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactory.java
soul-plugin/soul-plugin-base/src/test/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactoryTest.java

#1309, rename like operator to contains

---

soul-plugin/soul-plugin-base/src/test/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactoryTest.java

Add test TimerAfterOperatorJudge in OperatorJudgeFactoryTest

Add test TimerAfterOperatorJudge in OperatorJudgeFactoryTest

---

soul-common/src/main/java/org/dromara/soul/common/enums/OperatorEnum.java
soul-common/src/test/java/org/dromara/soul/common/enums/OperatorEnumTest.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/OperatorJudgeFactory.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/RegexOperatorJudge.java

#1309, rename regEx to regex

---

soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/ContainsPredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/EqualsPredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/GroovyPredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/MatchPredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/PredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/PredicateJudgeFactory.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/RegexPredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/SpELPredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/TimerAfterPredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/judge/TimerBeforePredicateJudge.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/strategy/AndMatchStrategy.java
soul-plugin/soul-plugin-base/src/main/java/org/dromara/soul/plugin/base/condition/strategy/OrMatchStrategy.java
soul-plugin/soul-plugin-base/src/test/java/org/dromara/soul/plugin/base/condition/judge/PredicateJudgeFactoryTest.java

#1343, replace the term Operator by Predicate in soul-plugin-base module

---

soul-register-center/soul-register-server/soul-register-server-nacos/src/main/java/org/dromara/soul/register/server/nacos/NacosServerRegisterRepository.java

fix: NacosServerRegisterRepository class miss authentication parameters #1341

add nacos authentication parameters

---

soul-common/src/main/java/org/dromara/soul/common/constant/Constants.java
soul-plugin/soul-plugin-apache-dubbo/src/main/java/org/dromara/soul/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
soul-plugin/soul-plugin-apache-dubbo/src/test/java/org/dromara/soul/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java

fix: dubbo only support $invokeAsyinc after version 2.7.3

---

soul-admin/src/main/java/org/dromara/soul/admin/exception/ExceptionHandlers.java
soul-admin/src/main/java/org/dromara/soul/admin/utils/SoulResultMessage.java
soul-common/src/main/java/org/dromara/soul/common/exception/CommonErrorCode.java

about issue  #1301
- [] You submit test cases (unit or integration tests) that back your changes.

feat: add handler for NullPointException(#1301)

---

soul-admin/src/main/resources/META-INF/schema.h2.sql
soul-admin/src/main/resources/META-INF/schema.sql
soul-common/src/main/java/org/dromara/soul/common/dto/convert/rule/impl/ContextMappingHandle.java
soul-plugin/soul-plugin-context-path/src/main/java/org/dromara/soul/plugin/contextpath/ContextPathMappingPlugin.java
soul-plugin/soul-plugin-context-path/src/main/java/org/dromara/soul/plugin/contextpath/handler/ContextPathMappingPluginDataHandler.java

refactor Context path plugin

---

soul-admin/src/main/resources/META-INF/schema.h2.sql
soul-admin/src/main/resources/META-INF/schema.sql
soul-common/src/main/java/org/dromara/soul/common/constant/Constants.java
soul-common/src/main/java/org/dromara/soul/common/dto/convert/rule/impl/DivideRuleHandle.java
soul-plugin/soul-plugin-api/src/main/java/org/dromara/soul/plugin/api/result/SoulResultEnum.java
soul-plugin/soul-plugin-divide/src/main/java/org/dromara/soul/plugin/divide/DividePlugin.java

#1290 Add Header-Max-Size and Request_Max_Size to divide plugin.

Add Header-Max-Size and Request_Max_Size to divide plugin.

---

soul-common/src/main/java/org/dromara/soul/common/enums/PluginEnum.java
soul-plugin/soul-plugin-logging/src/main/java/org/dromara/soul/plugin/logging/LoggingPlugin.java
soul-plugin/soul-plugin-logging/src/test/java/org/dromara/soul/plugin/logging/LoggingPluginTest.java
soul-spring-boot-starter/soul-spring-boot-starter-plugin/soul-spring-boot-starter-plugin-logging/src/test/java/org/dromara/soul/springboot/starter/plugin/logging/LoggingPluginConfigurationTest.java

// Describe your PR here; eg. Fixes #1365
fix: #1365
logging plugin code optimization.

code optimization(#1365)

---

soul-bootstrap/pom.xml

fix log4j warn (#1385)

---

soul-admin/src/main/resources/META-INF/schema.h2.sql

Fix init h2 sql

---

shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ErrorHandlerConfiguration.java
shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ExcludePathProperties.java
shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ShenyuConfiguration.java
shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ShenyuExtConfiguration.java
shenyu-web/src/main/java/org/apache/shenyu/web/fallback/DefaultFallbackController.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/AbstractWebFilter.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/ExcludeFilter.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/FileSizeFilter.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/TimeWebFilter.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/WebSocketParamFilter.java
shenyu-web/src/main/java/org/apache/shenyu/web/forward/ForwardedRemoteAddressResolver.java
shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java
shenyu-web/src/test/java/org/apache/shenyu/web/fallback/DefaultFallbackControllerTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/filter/CrossFilterTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/filter/FileSizeFilterTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/filter/WebSocketParamFilterTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/forward/ForwardedRemoteAddressResolverTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/handler/GlobalErrorHandlerTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/handler/ShenyuWebHandlerTest.java

rename soul to shenyu in web (#1394)

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/AppAuthController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ConfigController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DataPermissionController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/IndexController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/MetaDataController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PermissionController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PlatformController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginHandleController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ResourceController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RoleController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RuleController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/SelectorController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuDictController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuHttpRegistryController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/zookeeper/HttpServiceDiscovery.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/AppAuthService.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/init/LocalDataSourceLoader.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ShenyuDictControllerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ShenyuHttpRegistryControllerTest.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java

renamed soul in spring mvc controller path

---

shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-common/src/main/java/org/apache/shenyu/springboot/starter/client/common/config/ShenyuClientCommonBeanConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-divide/src/main/java/org/apache/shenyu/spring/boot/plugin/divide/DividePluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-dubbo-common/src/main/java/org/apache/shenyu/spring/boot/plugin/dubbo/common/DubboCommonConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-grpc/src/main/java/org/apache/shenyu/spring/boot/starter/plugin/grpc/GrpcPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/test/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfigurationTest.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-motan/src/main/java/org/apache/shenyu/spring/boot/starter/plugin/motan/MotanPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sofa/src/main/java/org/apache/shenyu/spring/boot/starter/plugin/sofa/SofaPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-springcloud/src/main/java/org/apache/shenyu/springboot/starter/plugin/springcloud/SpringCloudPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-tars/src/main/java/org/apache/shenyu/spring/boot/starter/plugin/tars/TarsPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-http/src/main/java/org/apache/shenyu/spring/boot/starter/sync/data/http/HttpSyncDataConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-http/src/test/java/org/apache/shenyu/spring/boot/starter/sync/data/http/HttpClientPluginConfigurationTest.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-nacos/src/main/java/org/apache/shenyu/springboot/starter/sync/data/nacos/NacosSyncDataConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-nacos/src/test/java/org/apache/shenyu/springboot/starter/sync/data/nacos/NacosSyncDataConfigurationTest.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-websocket/src/main/java/org/apache/shenyu/spring/boot/starter/sync/data/websocket/WebsocketSyncDataConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-websocket/src/test/java/org/apache/shenyu/spring/boot/starter/sync/data/websocket/WebsocketSyncDataConfigurationTest.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-zookeeper/src/main/java/org/apache/shenyu/spring/boot/sync/data/zookeeper/ZookeeperConfig.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-zookeeper/src/main/java/org/apache/shenyu/spring/boot/sync/data/zookeeper/ZookeeperSyncDataConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-zookeeper/src/test/java/org/apache/shenyu/spring/boot/sync/data/zookeeper/ZookeeperSyncDataConfigurationTest.java

Modify the prefix of the soul-spring-boot configuration property to shenyu.

---

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java

Reason: don't modify the header's content type, keep it as it is

fix issue #1397

---

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java

remove unused method

---

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboTestServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/resources/application.yml
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/impl/DubboMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/impl/DubboTestServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/resources/application.yml
shenyu-examples/shenyu-examples-grpc/src/main/resources/application.yml
shenyu-examples/shenyu-examples-http/src/main/resources/application.yml
shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/resources/application.yml
shenyu-examples/shenyu-examples-sofa/README.md
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaSingleParamServiceImpl.java
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/resources/application.yml
shenyu-examples/shenyu-examples-springcloud/README.md
shenyu-examples/shenyu-examples-springcloud/src/main/resources/application.yml
shenyu-examples/shenyu-examples-tars/src/main/java/org/apache/shenyu/examples/tars/servant/testapp/impl/HelloServantImpl.java
shenyu-examples/shenyu-examples-tars/src/main/resources/application.yml

rename soul to shenyu in example

---

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/resources/spring-dubbo.xml
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/resources/spring-dubbo.xml

fix dubbo example classNotFound

---

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/executor/RegisterClientConsumerExecutor.java
shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/validation/AlibabaDubboClientValidator.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/test/java/org/apache/shenyu/client/apache/dubbo/validation/ApacheDubboClientValidatorTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/ShenyuThreadFactoryTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/utils/GsonUtilsTest.java
shenyu-metrics/shenyu-metrics-prometheus/src/test/java/org/apache/shenyu/metrics/prometheus/register/PrometheusMetricsRegisterTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/strategy/AndMatchStrategyTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/strategy/OrMatchStrategyTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/handler/PluginDataHandlerTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/FallbackUtilsTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/MatchStrategyUtilsTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/UriUtilsTest.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/client/GrpcClientBuilder.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/context/GrpcShenyuContextDecorator.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/reflection/ShenyuGrpcReflectionClient.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java

Signed-off-by: sunl888 <2013855675@qq.com>

Change some names from soul to shenyu (#1394)

---

shenyu-admin/README.md
shenyu-dist/README.md

Rename soul to shenyu

---

shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/DubboProviderVersionCache.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/handler/ApacheDubboPluginDataHandler.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriber.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/DubboProviderVersionCacheTest.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java

fix #1381 the no.2 question
cache dubbo version and update dubbo plugin test case

cache dubbo provider version

---

shenyu-plugin/shenyu-plugin-sentinel/src/main/java/org/apache/shenyu/plugin/sentinel/SentinelPlugin.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sentinel/src/main/java/org/apache/shenyu/springboot/starter/plugin/sentinel/SentinelPluginConfiguration.java

support custom fallback handler

---

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-logging/src/test/java/org/apache/shenyu/springboot/starter/plugin/logging/LoggingPluginConfigurationTest.java

…ke its coverage rate is more than 80%
// Describe your PR here; eg. Fixes #1459

Enhance shenyu-spring-boot-starter-plugin-logging module unit test

---

shenyu-plugin/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/context/DubboShenyuContextDecorator.java
shenyu-plugin/shenyu-plugin-dubbo-common/src/test/java/org/apache/shenyu/plugin/dubbo/common/context/DubboShenyuContextDecoratorTest.java

fix #1455 enhance shenyu-plugin-dubbo-common module unit test. and remove redundant code.

Enhance shenyu-plugin-dubbo-common module unit test. and remove redundant code.

---

shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/BaseHandleCacheTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/EmptyMockBaseHandleCache.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/CacheKeyUtilsTest.java

fix #1449 enhance soul-plugin-base unti test coverage.

enhance soul-plugin-base unti test coverage.

---

shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCacheTest.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/cache/ApplicationConfigCache.java

fix guava cache usage (#1477)

---

shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/AlibabaDubboPluginTest.java
shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCacheTest.java
shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java
shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyServiceTest.java
shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java

Enhance shenyu-plugin-alibaba-dubbo module unit test

---

shenyu-web/src/main/java/org/apache/shenyu/web/filter/WebSocketParamFilter.java

completed the task of issue#1485

---

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceBeanPostProcessor.java
shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/resources/invoke-server-example.xml

Optimize getTargetClass method and fix sofa examples

---

pom.xml
shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/pom.xml
shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/test/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepositoryTest.java
shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/path/RegisterPathConstants.java

add Enhance shenyu-register-center module unit test #1457 
update ZookeeperClientRegisterRepository buildMetadataNodeName add startsWith
enhance curator-test.version 3.3.0 to 4.0.1

Enhance shenyu-register-center module unit test #1457

---

shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/DefaultShenyuContextBuilder.java

add rpcType param in header

---

shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java

Add scheduler config

---

shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/loadbalance/picker/RoundRobinPicker.java

fix org.apache.shenyu.plugin.grpc.loadbalance.picker.RoundRobinPicker  new instance error

fix grpc RoundRobinPicker

---

shenyu-common/src/test/java/org/apache/shenyu/common/utils/CollectionUtilsTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/utils/DateUtilsTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/utils/SpiImpl.java
shenyu-common/src/test/java/org/apache/shenyu/common/utils/SpiInterface.java
shenyu-common/src/test/java/org/apache/shenyu/common/utils/SpiLoadFactoryTest.java
shenyu-common/src/test/resources/META-INF/services/org.apache.shenyu.common.utils.SpiInterface

Enhance shenyu-common module unit test.

---

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/CookieParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/HeaderParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/HostParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/IpParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/ParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/ParameterDataFactory.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/PostParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/QueryParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/RequestMethodParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/URIParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/PredicateJudgeFactory.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/strategy/MatchStrategyFactory.java
shenyu-plugin/shenyu-plugin-base/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.base.condition.data.ParameterData
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/MatchStrategyFactoryTest.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/loadbalance/picker/RoundRobinPicker.java

refactor param data to SPI

---

shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/CookieParameterDataTest.java

Add test cases for CookieParameterData (#1508)

---

shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/strategy/MatchStrategyFactoryTest.java

Add MatchStrategyFactory Test (#1507)

---

shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/HostParameterDataTest.java

#1508 // Describe your PR here; eg. Fixes #issueNo

add HostParameterDataTest for #1508

---

shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/IpParameterDataTest.java

Ipparameter data test

---

shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/filter/HealthFilter.java

Use charset for heath info in HealthFilter

---

shenyu-admin/src/main/resources/META-INF/schema.sql

修复admin项目初始化sql脚本错误

---

shenyu-admin/src/main/resources/META-INF/schema.h2.sql

add h2 sql for rewrite uri plugin

add h2 sql for rewrite uri plugin

---

shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/NettyTcpConfig.java
shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/ShenyuNettyWebServerFactory.java

Customized netty tcp config #1529

---

shenyu-admin/src/main/resources/META-INF/schema.sql
shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java
shenyu-plugin/pom.xml
shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultEnum.java
shenyu-plugin/shenyu-plugin-jwt/pom.xml
shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java
shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/config/JwtConfig.java
shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandler.java
shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/lambda/ThrowingFunction.java
shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/JwtPluginTest.java
shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandlerTest.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/main/java/org/apache/shenyu/springboot/starter/plugin/jwt/JwtPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/main/resources/META-INF/spring.factories
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/main/resources/META-INF/spring.provides
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/test/java/org/apache/shenyu/springboot/starter/plugin/jwt/JwtPluginConfigurationTest.java

add jwt plugin

---

pom.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/AbstractReflectGetterSetterTest.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/ServerJsonListener.java
shenyu-common/pom.xml
shenyu-common/src/main/java/org/apache/shenyu/common/utils/ReflectUtils.java
shenyu-metrics/shenyu-metrics-spi/pom.xml
shenyu-plugin/shenyu-plugin-resilience4j/pom.xml

fix build under java11

---

shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/ParameterDataFactoryTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/PostParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/QueryParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/RequestMethodParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/URIParameterDataTest.java

add test for ParameterData:
ParameterDataFactory
PostParameterData
QueryParameterData
RequestMethodParameterData
URIParameterData
WIP #1508

add test for  ParameterData

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RoleController.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/GsonUtils.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/support/CachedBodyOutputMessage.java

// Describe your PR here; eg. Fixes #1582
- [] You submit test cases (unit or integration tests) that back your changes.

Fix magic value and forgotten override.

---

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboTestServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboTestServiceImpl.java

remove @author

---

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-request/src/test/java/org/apache/shenyu/springboot/starter/plugin/request/RequestPluginConfigurationTest.java

add test for RequestPluginConfiguration
fixes #1566

add test for RequestPluginConfiguration

---

shenyu-plugin/shenyu-plugin-request/pom.xml
shenyu-plugin/shenyu-plugin-request/src/test/java/org/apache/shenyu/plugin/request/RequestPluginTest.java
shenyu-plugin/shenyu-plugin-request/src/test/java/org/apache/shenyu/plugin/request/handler/RequestPluginHandlerTest.java

add test for request plugin
fixes #1565

add test for request plugin

---

shenyu-admin/pom.xml
shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/EtcdProperties.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdClient.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListener.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdDataInit.java
shenyu-admin/src/main/resources/application.yml
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/zookeeper/ZookeeperDataChangedListenerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/zookeeper/ZookeeperDataInitTest.java
shenyu-bootstrap/pom.xml
shenyu-bootstrap/src/main/resources/application-local.yml
shenyu-common/src/main/java/org/apache/shenyu/common/constant/DefaultPathConstants.java
shenyu-common/src/test/java/org/apache/shenyu/common/constant/DefaultPathConstantsTest.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-etcd/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-etcd/src/main/java/org/apache/shenyu/springboot/sync/data/etcd/EtcdConfig.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-etcd/src/main/java/org/apache/shenyu/springboot/sync/data/etcd/EtcdSyncDataConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-etcd/src/main/resources/META-INF/spring.factories
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-etcd/src/main/resources/META-INF/spring.provides
shenyu-sync-data-center/shenyu-sync-data-etcd/pom.xml
shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdClient.java
shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/test/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataServiceTest.java

// Describe your PR here; eg. Fixes #1545 

Data Sync Center Support Etcd

---

shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/SpringCloudPlugin.java
shenyu-plugin/shenyu-plugin-springcloud/src/test/java/org/apache/shenyu/plugin/springcloud/SpringCloudPluginTest.java

fixes #1580
1. delete query param when use spring cloud plugin send post request
2. rewrite plugin didn't work  when use spring cloud plugin

fix bug about #1580

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/ShiroProperties.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/config/ShiroConfiguration.java
shenyu-admin/src/main/resources/application.yml

[ISSUE #1615] modify shiro's white list to support swagger

---

shenyu-admin/src/main/resources/META-INF/schema.h2.sql
shenyu-admin/src/main/resources/META-INF/schema.sql
shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/RateLimiterHandle.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/RateLimiterPlugin.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/resolver/RateLimiterKeyResolver.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/resolver/RateLimiterKeyResolverFactory.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/resolver/RemoteAddrKeyResolver.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/resolver/WholeKeyResolver.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.ratelimiter.resolver.RateLimiterKeyResolver
shenyu-plugin/shenyu-plugin-ratelimiter/src/test/java/org/apache/shenyu/plugin/ratelimiter/RateLimiterPluginTest.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/test/java/org/apache/shenyu/plugin/ratelimiter/resolver/RateLimiterKeyResolverTest.java

[ISSUE #1603] add ratelimiter key for ratelimiter plugin.
You have read the contribution guidelines.
You submit test cases (unit or integration tests) that back your changes.
Your local test passed mvn clean install -Dmaven.javadoc.skip=true.

[ISSUE #1603]add ratelimiter key for ratelimiter plugin.

---

shenyu-bootstrap/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/pom.xml

[ISSUE #1625] Move context-path plugin to shenyu starter gateway

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/http/HttpLongPollingDataChangedListener.java
shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/shutdown/ShenyuClientShutdownHook.java

[ISSUE #1622] Add try catch block in case of queue is full

---

.asf.yaml

[BUILD] add asf.yaml

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/HttpSyncProperties.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/http/HttpLongPollingDataChangedListener.java

[ISSUE #1630] Add batch size to notify client concurrently

---

README.md
README_CN.md

[BUILD] update readme

---

pom.xml
shenyu-admin/pom.xml
shenyu-bootstrap/pom.xml
shenyu-plugin/shenyu-plugin-ratelimiter/pom.xml

[BUILD] add apache parent pom

---

shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/GrpcPlugin.java

use Constants.RPC_RESULT replace Constants.GRPC_RPC_RESULT in grpcPlugin.

[ISSUE #1639] use Constants.RPC_RESULT replace Constants.GRPC_RPC_RESULT in grpcPlugin.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ShenyuClientRegisterServiceImpl.java
shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcClientBeanPostProcessor.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceBeanPostProcessor.java
shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceBeanPostProcessor.java
shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java

There is no thread name in the thread pool, which is inconvenient for debugging.
Add the thread pool name to the thread pool of shenyu client, and increase the exception rollback of the transaction.

[ISSUE #1633]fix (admin,client): Add the thread pool name to the thread pool of shenyu-client

---

shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java

Fix #1647 
- [√ ] You have read the [contribution guidelines](https://dromara.org/projects/soul/contributor/).
- [√ ] You submit test cases (unit or integration tests) that back your changes.
- [√ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

[ISSUE #1647] Fix context-path-plugin: addPrefix is not working properly.

---

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-response/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-response/src/test/java/org/apache/shenyu/springboot/starter/plugin/response/ResponsePluginConfigurationTest.java

// Describe your PR here; eg. Fixes #1649 

[ISSUE #1649] Add test case for shenyu-spring-boot-starter-plugin-response module

---

.asf.yaml

closes #1658 change Gitbox notification.

[ISSUE #1658] change Gitbox notification.

---

README.md
README_CN.md

[BUILD] refactor apache shenyu logo

---

shenyu-common/src/main/java/org/apache/shenyu/common/utils/UpstreamCheckUtils.java
shenyu-common/src/test/java/org/apache/shenyu/common/utils/UpstreamCheckUtilsTest.java

[ISSUE #1662] Fix check url return false

---

shenyu-admin/src/main/resources/META-INF/schema.h2.sql

fix param plugin sql for h2

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDubboServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringMVCServiceImpl.java

Fix bug, create rule when meta data is null. #1676 

[ISSUE #1676] Fix bug, create rule when meta data is null.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringMVCServiceImpl.java

Fix bug, register context-plugin selector and rule. Fixes #1676 

[ISSUE #1676]Fix bug, register context-plugin selector and rule.

---

shenyu-register-center/shenyu-register-server/shenyu-register-server-zookeeper/src/main/java/org/apache/shenyu/register/server/zookeeper/ZookeeperServerRegisterRepository.java

[ISSUE #1681]Increase the default value of zookeeperSessionTimeout 

---

shenyu-plugin/shenyu-plugin-response/src/test/java/org/apache/shenyu/plugin/response/ResponsePluginTest.java
shenyu-plugin/shenyu-plugin-response/src/test/java/org/apache/shenyu/plugin/response/strategy/NettyClientMessageWriterTest.java
shenyu-plugin/shenyu-plugin-response/src/test/java/org/apache/shenyu/plugin/response/strategy/RPCMessageWriterTest.java
shenyu-plugin/shenyu-plugin-response/src/test/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriterTest.java

// Describe your PR here; eg. Fixes #1674 

[ISSUE #1674] Add test case for shenyu-plugin-response module

---

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcClientBeanPostProcessor.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceBeanPostProcessor.java
shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceBeanPostProcessor.java
shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/IpUtils.java
shenyu-common/src/test/java/org/apache/shenyu/common/utils/IpUtilsTest.java

Add a parameter to get the desired IP based on the prefix.
// Describe your PR here; eg. Fixes #1655 

feature shenyu-common: IpUtils Add parameters to select the network ip .

---

README.md
README_CN.md

change data sync pic urls in Readme

---

shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
shenyu-plugin/shenyu-plugin-oauth2/src/main/java/org/apache/shenyu/plugin/oauth2/filter/OAuth2PreFilter.java

// Describe your PR here; eg. Fixes #1687
Fixes #1687

[ISSUS #1687] Complete selector type in OAuth2PreFilter

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/DataBaseProperties.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/LocalDataSourceLoader.java
shenyu-admin/src/main/resources/application.yml

[Feature  #1689]  add execute multi-path sql script

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginDTO.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/PluginDO.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/PluginVO.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
shenyu-admin/src/main/resources/META-INF/schema.h2.sql
shenyu-admin/src/main/resources/META-INF/schema.sql
shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/PluginControllerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/websocket/WebsocketDataChangedListenerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ShenyuClientRegisterServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SyncDataServiceTest.java
shenyu-common/src/main/java/org/apache/shenyu/common/dto/PluginData.java
shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java
shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/JwtPluginTest.java
shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandlerTest.java
shenyu-plugin/shenyu-plugin-monitor/src/test/java/org/apache/shenyu/plugin/monitor/handler/MonitorPluginDataHandlerTest.java
shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java
shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/handler/SofaPluginDataHandlerTest.java
shenyu-plugin/shenyu-plugin-tars/src/test/java/org/apache/shenyu/plugin/tars/handler/TarsPluginDataHandlerTest.java
shenyu-plugin/shenyu-plugin-waf/src/test/java/org/apache/shenyu/plugin/waf/WafPluginTest.java
shenyu-plugin/shenyu-plugin-waf/src/test/java/org/apache/shenyu/plugin/waf/handler/WafPluginDataHandlerTest.java
shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/HttpSyncDataServiceTest.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/test/java/org/apache/shenyu/plugin/sync/data/websocket/handler/PluginDataHandlerTest.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/test/java/org/apache/shenyu/plugin/sync/data/websocket/handler/WebsocketDataHandlerTest.java

- add field `sort` in plugin.
- modify `role` to store the category of plugin.

[ISSUE #1679] Add category and sort for plugin list. 

---

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java

Removed unnecessary constants from Constants.java which were not used anywhere in the codebase.

Removed unnecessary constants

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/task.md
.github/PULL_REQUEST_TEMPLATE.md

Fixes #1696
Hi @dengliming, how does this look?
Let me know if this needs any changes.
Thanks

[ISSUE #1696] Update the issue template

---

shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/balance/spi/AbstractLoadBalance.java

[refactor #1703] refactor code

---

shenyu-bootstrap/pom.xml

Remove duplicate dependency

---

shenyu-common/src/test/java/org/apache/shenyu/common/utils/UpstreamCheckUtilsTest.java

closes #1707 
- [ x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor/).
- [] You submit test cases (unit or integration tests) that back your changes.

[ISSUE#1707] delete unit test to solve isHostConnector always return true.

---

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-rewrite/src/main/java/org/apache/shenyu/springboot/starter/plugin/rewrite/RewritePluginConfiguration.java

[BUG #1715] fix redirectPluginDataHandler not initialized to spring bean

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdClientTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListenerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataInitTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedListenerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataInitTest.java

// Describe your PR here; eg. Fixes #1709 

[ISSUE #1709] Add test case for shenyu-admin module

---

pom.xml

[ISSUE #1700] Remove distributionManagement and sonatype plugin

---

shenyu-admin/src/main/resources/META-INF/schema.h2.sql
shenyu-admin/src/main/resources/META-INF/schema.sql

[ISSUE #1727] Fix sentinel plugin's fallbackUri in rule.

---

shenyu-admin/src/main/resources/META-INF/schema.h2.sql
shenyu-admin/src/main/resources/META-INF/schema.sql
shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/RewriteHandle.java
shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/RewritePlugin.java
shenyu-plugin/shenyu-plugin-rewrite/src/test/java/org/apache/shenyu/plugin/rewrite/RewritePluginTest.java

[ISSUE #1723] rewrite request uri with regex.

---

shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/ContextMappingHandle.java
shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java
shenyu-plugin/shenyu-plugin-context-path/src/test/java/org/apache/shenyu/plugin/context/path/ContextPathPluginTest.java
shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/RewritePlugin.java
shenyu-plugin/shenyu-plugin-rewrite/src/test/java/org/apache/shenyu/plugin/rewrite/RewritePluginTest.java

[ISSUE #1744] Fix rewrite plugin cannot rewrite uri after context-path plugin

---

.github/workflows/integrated-test-http.yml
shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-http/script/healthcheck.sh
shenyu-integrated-test/shenyu-integrated-test-http/script/services.list

polish health check for integrated-test

---

.github/workflows/integrated-test-http.yml
shenyu-dist/README.md
shenyu-dist/shenyu-admin-dist/pom.xml
shenyu-dist/shenyu-bootstrap-dist/pom.xml
shenyu-integrated-test/README.md

[ISSUE #1700] Change the profile name from dist to release

---

DISCLAIMER
shenyu-dist/pom.xml
shenyu-dist/shenyu-src-dist/pom.xml
shenyu-dist/shenyu-src-dist/src/main/assembly/source.xml

[ISSUE #1700] Add shenyu-src-dist

---

.gitmodules
pom.xml

[ISSUE #1700] Add shenyu-dashboard as submodule

---

pom.xml
shenyu-admin/pom.xml
shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/ConsulProperties.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/consul/ConsulDataChangedListener.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/consul/ConsulDataInit.java
shenyu-admin/src/main/resources/application.yml
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/consul/ConsulDataChangedListenerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/consul/ConsulDataInitTest.java
shenyu-bootstrap/pom.xml
shenyu-bootstrap/src/main/resources/application-local.yml
shenyu-common/src/main/java/org/apache/shenyu/common/constant/ConsulConstants.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-consul/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-consul/src/main/java/org/apache/shenyu/springboot/sync/data/consul/ConsulSyncDataConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-consul/src/main/resources/META-INF/spring.factories
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-consul/src/main/resources/META-INF/spring.provides
shenyu-sync-data-center/pom.xml
shenyu-sync-data-center/shenyu-sync-data-consul/pom.xml
shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/config/ConsulConfig.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/handler/ConsulCacheHandler.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataServiceTest.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/handler/ConsulCacheHandlerTest.java

[ISSUE #1538] data sync support consul

---

RELEASE-NOTES.md

[ISSUE #1780]Add Changes By Version

---

RELEASE-NOTES.md

[ISSUE# 1700] Update release notes

---

shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE
shenyu-dist/shenyu-admin-dist/src/main/release-docs/licenses/LICENSE-consul.txt
shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/licenses/LICENSE-consul.txt

[ISSUE #1700] Add consul license

---

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java

[Bug-Fix  #1778] fix uri encode

---

pom.xml

[ISSUE #1700] Change the scm address to https

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/SwaggerConfiguration.java

Fixes #1789.
update SwaggerConfiguration apiInfo contact url.

[ISSUE #1789] update contact url.

---

pom.xml
shenyu-dist/shenyu-admin-dist/pom.xml
shenyu-dist/shenyu-bootstrap-dist/pom.xml
shenyu-dist/shenyu-src-dist/pom.xml

[ISSUE #1700] Refine release config

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/JwtProperties.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/LoginDashboardUserVO.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/config/ShiroRealm.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/JwtUtils.java
shenyu-admin/src/main/resources/application.yml
shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/PlatformControllerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DashboardUserServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/utils/JwtUtilsTest.java

- Add verifyToken
- expiredSeconds configurable
- Using different secretKey for token generator

Improve token security

---

shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/handler/ContextPathPluginDataHandler.java
shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/handler/HystrixPluginDataHandler.java
shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/handler/ModifyResponsePluginDataHandler.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/handler/RateLimiterPluginDataHandler.java
shenyu-plugin/shenyu-plugin-redirect/src/main/java/org/apache/shenyu/plugin/redirect/handler/RedirectPluginDataHandler.java
shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/handler/RequestPluginHandler.java
shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/handler/Resilience4JHandler.java
shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/handler/RewritePluginDataHandler.java
shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/handler/WafPluginDataHandler.java

I found some code to simplify when using IDEA to inspect the code, so I submit a PR here.

Simplify some code

---

.asf.yaml
.github/workflows/integrated-test-http.yml
shenyu-admin/src/main/resources/application.yml
shenyu-bootstrap/src/main/resources/application-local.yml
shenyu-bootstrap/src/main/resources/application.yml
shenyu-dist/shenyu-admin-dist/src/main/resources/application.yml
shenyu-examples/shenyu-examples-grpc/src/main/resources/application.yml
shenyu-examples/shenyu-examples-springcloud/src/main/resources/application.yml
shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/application-local.yml

Format all non-standard yaml file

Format all non-standard yaml file

---

shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java

fix: NPE when refreshURIService

---

shenyu-integrated-test/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/src/main/java/org/apache/shenyu/integratedtest/App.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/AbstractTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/AppTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/HelloWorldTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/HttpRateLimitTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/SignTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/dto/AdminResponse.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/helper/HttpHelper.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/package-info.java

Ref #1817 .
refactor integrated-test : Change the parent project of the shenyu-integrated-test to shenyu.

[ISSUE #1817] Change the parent project of the shenyu-integrated-test to shenyu

---

shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java

fix check style

---

shenyu-common/src/main/java/org/apache/shenyu/common/healthcheck/HealthCheckTask.java

Using lambda and CompleteFuture to decrease logic codes (#)

---

shenyu-admin/src/main/resources/META-INF/schema.h2.sql
shenyu-admin/src/main/resources/META-INF/schema.sql
shenyu-common/src/main/java/org/apache/shenyu/common/enums/ParamTypeEnum.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/DomainParameterData.java
shenyu-plugin/shenyu-plugin-base/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.base.condition.data.ParameterData

// Describe your PR here; eg. Fixes #1805
add domain type filter

Add domain type filter

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java

Fix createDashboardUser bug

---

shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/validation/ApacheDubboClientValidator.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/resources/META-INF/dubbo/org.apache.dubbo.validation.Validation
shenyu-metrics/shenyu-metrics-prometheus/src/test/java/org/apache/shenyu/metrics/prometheus/register/PrometheusMetricsRegisterTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/strategy/AbstractMatchStrategyTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/fallback/FallbackHandlerTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/ShenyuResultWrapTest.java
shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/balance/spi/HashLoadBalance.java
shenyu-plugin/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/balance/spi/HashLoadBalanceTest.java
shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/DefaultShenyuContextBuilder.java
shenyu-plugin/shenyu-plugin-global/src/test/java/org/apache/shenyu/plugin/global/DefaultShenyuContextBuilderTest.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/GrpcClientCache.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/loadbalance/GrpcAttributeUtils.java
shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java
shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/strategy/FormDataOperatorTest.java
shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/strategy/JsonOperatorTest.java
shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutorTest.java
shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-consul/src/main/java/org/apache/shenyu/register/server/consul/ShenyuConsulConfigWatch.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-jwt/src/main/java/org/apache/shenyu/springboot/starter/plugin/jwt/JwtPluginConfiguration.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandlerTest.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/TimeWebFilter.java

Fixes #1831
Rename some soul code to shenyu

[ISSUE #1831] Fix ShenyuConsulConfigWatch and Rename soul to shenyu

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DataPermissionServiceTest.java

Add unit test for DataPermissionService in shenyu-admin

---

shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCacheTest.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCacheTest.java

New feature, delete judgment. #1838 
* No need to check the type of loadbalance.

[ISSUE #1838]New feature, delete judgment.

---

shenyu-common/src/test/java/org/apache/shenyu/common/dto/ConfigDataTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/dto/MetaDataTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/dto/convert/rule/impl/ContextMappingHandleTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/dto/convert/rule/impl/ModifyResponseRuleHandleTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/dto/convert/rule/impl/ParamMappingHandleTest.java

Add unit test for common dto in shenyu-common
- org.apache.shenyu.common.dto.MetaData
- org.apache.shenyu.common.dto.ConfigData
- org.apache.shenyu.common.dto.convert.rule.impl.ModifyResponseRuleHandle
- org.apache.shenyu.common.dto.convert.rule.impl.ContextMappingHandle
- org.apache.shenyu.common.dto.convert.rule.impl.ParamMappingHandle

Add unit test for common dto in shenyu-common

---

shenyu-common/src/test/java/org/apache/shenyu/common/exception/CommonErrorCodeTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/exception/SerializerExceptionTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/exception/ShenyuExceptionTest.java

#1824 Improve test coverage of org.apache.shenyu.common.exception.*

#1824 Add test for org.apache.shenyu.common.exception.*

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DashboardUserServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/MetaDataServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PermissionServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/RuleServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SelectorServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java

[ISSUE #1824] Improve test coverage of org.apache.shenyu.admin.service.*

---

shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/ApacheDubboPlugin.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java

* Optimze code about dubbo async call;
* Delete redundant code;
* Update error log.

[ISSUE #1844]Optimze code about dubbo async call

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AuthPathMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PermissionMapper.java
shenyu-admin/src/main/resources/mappers/auth-path-sqlmap.xml

Remove redundant code that does not implement the interface code and MybatisMapper is not called.

refactor remove redundant code

---

pom.xml
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/zookeeper/HttpServiceDiscovery.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/ConsulServerConfigurationTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/DataBaseConfigurationTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/LdapConfigurationTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/exception/ExceptionHandlersTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/AbstractDataChangedListenerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/ConfigDataCacheTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/websocket/WebsocketConfiguratorTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/websocket/WebsocketListenerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/zookeeper/HttpServiceDiscoveryTest.java

[ISSUE #1849] shenyu-admin a part of classes test code

---

shenyu-spi/src/test/java/org/apache/shenyu/spi/ExtensionLoaderTest.java

[ISSUE#1850] refactor ExtensionLoaderTest, different jdk version has different exception message. (#1850)

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/exception/ExceptionHandlers.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketListener.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/exception/ExceptionHandlersTest.java

##Motivation
1. Uniform the method name in ExceptionHandlers.java.
2. Regular the log format.

Uniform the method name and regular the log format

---

.github/workflows/ci.yml
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/AppAuthMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/AuthParamMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/AuthPathMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/DashboardUserMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/MetaDataMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginHandleMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/RoleMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/RuleConditionMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/RuleMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/SelectorConditionMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/SelectorMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ShenyuDictMapperTest.java

compatible with java11+

---

shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/NettyTcpConfig.java

[ISSUE #1866] Delete @Getter from <shenyu-bootstrap>.

---

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java
shenyu-integrated-test/shenyu-integrated-test-http/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/WafTest.java

Add integrated test for waf plugin

---

shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ShenyuConfiguration.java
shenyu-web/src/main/java/org/apache/shenyu/web/configuration/properties/ExcludePathProperties.java
shenyu-web/src/main/java/org/apache/shenyu/web/configuration/properties/ShenyuConfig.java
shenyu-web/src/main/java/org/apache/shenyu/web/fallback/DefaultFallbackController.java
shenyu-web/src/main/java/org/apache/shenyu/web/forward/ForwardedRemoteAddressResolver.java
shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java
shenyu-web/src/main/java/org/apache/shenyu/web/logo/ShenyuLogo.java

[ISSUE #1866] remove lombok dependency from <shenyu-web>.

---

shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java

spi module remove lombok dependency issue  #1866

[ISSUE #1866] Remove lombok dependency from <shenyu-spi> 

---

shenyu-common/src/test/java/org/apache/shenyu/common/enums/AdminPluginOperateEnumTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/AdminResourceEnumTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/HttpMethodEnumTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/ParamTypeEnumTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/PluginTypeEnumTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/RateLimitEnumTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/RpcTypeEnumTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/WafEnumTest.java

add some unit test for enum

---

shenyu-metrics/shenyu-metrics-facade/src/main/java/org/apache/shenyu/metrics/facade/MetricsTrackerFacade.java
shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/register/PrometheusMetricsRegister.java
shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/service/PrometheusBootService.java
shenyu-metrics/shenyu-metrics-prometheus/src/test/java/org/apache/shenyu/metrics/prometheus/service/PrometheusBootServiceTest.java
shenyu-metrics/shenyu-metrics-spi/src/main/java/org/apache/shenyu/metrics/config/JmxConfig.java
shenyu-metrics/shenyu-metrics-spi/src/main/java/org/apache/shenyu/metrics/config/MetricsConfig.java
shenyu-metrics/shenyu-metrics-spi/src/main/java/org/apache/shenyu/metrics/entity/Metric.java
shenyu-metrics/shenyu-metrics-spi/src/main/java/org/apache/shenyu/metrics/enums/MetricType.java
shenyu-metrics/shenyu-metrics-spi/src/test/java/org/apache/shenyu/metrics/config/JmxConfigTest.java

refactor:[ISSUE #1866]<shenyu-metrics> remvoe lombok dependency

[ISSUE #1866]<shenyu-metrics> remvoe lombok dependency

---

shenyu-common/src/main/java/org/apache/shenyu/common/healthcheck/HealthCheckTask.java

##Motivation
#1832 has involved a concurrent issue with below trace. The easy way to fix is reverting.
```
07:14:45.276 [shenyu-upstream-health-check-request-4] INFO org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Selector [null] upstream  health check failed, server is offline.
07:14:45.320 [shenyu-upstream-health-check-3] ERROR org.apache.shenyu.common.healthcheck.HealthCheckTask - [Health Check] Meet problem: 
java.util.ConcurrentModificationException: null
at java.util.ArrayList.forEach(ArrayList.java:1262)
at org.apache.shenyu.common.healthcheck.HealthCheckTask.lambda$check$3(HealthCheckTask.java:144)
at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
at org.apache.shenyu.common.healthcheck.HealthCheckTask.check(HealthCheckTask.java:14 …
```

Fix the ConcurrentModificationException by revert #1832

---

shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/config/ConsulConfig.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/handler/ConsulCacheHandler.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataServiceTest.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/handler/ConsulCacheHandlerTest.java
shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdClient.java
shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/config/HttpConfig.java
shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/AbstractDataRefresh.java
shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/AppAuthDataRefresh.java
shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/MetaDataRefresh.java
shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/PluginDataRefresh.java
shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/RuleDataRefresh.java
shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/refresh/SelectorDataRefresh.java
shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/HttpSyncDataServiceTest.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/config/NacosACMConfig.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/config/NacosConfig.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandler.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandlerTest.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/WebsocketSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/client/ShenyuWebsocketClient.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/config/WebsocketConfig.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/handler/AuthDataHandler.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/handler/MetaDataHandler.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/handler/PluginDataHandler.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/handler/RuleDataHandler.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/handler/SelectorDataHandler.java
shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java

remove lombok dependency from module: shenyu-sync-data-center

refactor:[ISSUE #1866] remove lombok dependency

---

shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/consumer/QueueConsumerExecutor.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/event/DataEvent.java

// Describe your PR here; eg. Fixes #1866 

remove lombok of distrupt model

---

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/shutdown/ShenyuClientShutdownHook.java
shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/validation/AlibabaDubboClientValidator.java
shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/test/java/org/apache/shenyu/client/alibaba/dubbo/validation/mock/MockValidationParameter.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/validation/ApacheDubboClientValidator.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/test/java/org/apache/shenyu/client/apache/dubbo/validation/ApacheDubboClientValidatorTest.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/test/java/org/apache/shenyu/client/apache/dubbo/validation/service/TestService.java
shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/dto/DubboRpcExt.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcClientBeanPostProcessor.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/common/dto/GrpcExt.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonForwardingServerCall.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonServerCallListener.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonServerServiceInterceptor.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/server/GrpcServerRunner.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceBeanPostProcessor.java
shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/common/dto/MotanRpcExt.java
shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceBeanPostProcessor.java
shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/common/dto/SofaRpcExt.java
shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java
shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/common/dto/TarsRpcExt.java

[ISSUE #1866] remove lombok in client module

---

shenyu-protocol/shenyu-protocol-grpc/src/main/java/org/apache/shenyu/protocol/grpc/message/JsonMessage.java

Remove lombok dependency from <shenyu-protocol>

Remove lombok dependency from <shenyu-protocol>

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java

fix:remove lombok

---

pom.xml
shenyu-agent/pom.xml
shenyu-agent/shenyu-agent-api/pom.xml
shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/config/AgentPluginConfig.java
shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/exception/AgentException.java
shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/spi/AgentPluginBootService.java
shenyu-agent/shenyu-agent-bootstrap/pom.xml
shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/ShenyuAgentBootstrap.java
shenyu-agent/shenyu-agent-core/pom.xml
shenyu-agent/shenyu-agent-plugins/pom.xml
shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/pom.xml
shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/pom.xml
shenyu-dist/shenyu-agent-dist/pom.xml
shenyu-dist/shenyu-agent-dist/src/main/assembly/binary.xml
shenyu-dist/shenyu-agent-dist/src/main/resources/logback.xml

[Feature: Agent] init shenyu agent

---

shenyu-integrated-test/shenyu-integrated-test-http/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integratedtest/http/JwtTest.java

[ISSUE #1905] Add integrated test for jwt

---

.github/workflows/integrated-test-spring-cloud.yml
shenyu-examples/shenyu-examples-eureka/Dockerfile
shenyu-examples/shenyu-examples-eureka/pom.xml
shenyu-examples/shenyu-examples-springcloud/Dockerfile
shenyu-examples/shenyu-examples-springcloud/pom.xml
shenyu-integrated-test/pom.xml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/Dockerfile
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/pom.xml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/script/healthcheck.sh
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/script/services.list
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/main/java/org/apache/shenyu/integratedtest/springcloud/ShenyuBootstrapApplication.java
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/main/resources/application.yml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/test/java/org/apache/shenyu/integratedtest/springcloud/AbstractTest.java
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/test/java/org/apache/shenyu/integratedtest/springcloud/HelloWorldTest.java
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/test/java/org/apache/shenyu/integratedtest/springcloud/dto/OrderDTO.java
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/test/java/org/apache/shenyu/integratedtest/springcloud/dto/UserDTO.java
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/test/java/org/apache/shenyu/integratedtest/springcloud/helper/HttpHelper.java

Fixes #1882
integrated test for spring cloud plugin
just test shennyu can route request to spring cloud service
Plugin testing will be added in the future

feature : add integrated test for spring cloud plugin

---

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientMetadataExecutorSubscriber.java

fix client : retry the connection add log and increase sleep time #1918

[ISSUE #1918] fix client : retry the connection add log and increase sleep time

---

shenyu-integrated-test/pom.xml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/pom.xml

[Bug: fix] springcloud integration test

---

README.md

i think u means 'will update dynamic'  rather than 'wiil update dynamic'?

docs(readme.md): Misspelling

---

shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepository.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java

// Describe your PR here; eg. Fixes #1910 

[ISSUE #1910] fix the default_group of nacos.

---

pom.xml
shenyu-examples/shenyu-examples-springcloud/pom.xml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/pom.xml
shenyu-plugin/shenyu-plugin-springcloud/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-springcloud/pom.xml

remove lombok depend in spring-cloud.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java

Fix bug, LDAP query built from user-controlled sources.

---

README.md
README_CN.md

modify readme

---

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/result/PaymentTypeService.java

There is a line of Chinese comment here, it seems unnecessary. So, I just deleted it.

Remove Chinese note in PaymentTypeService.java in shenyu-examples-http

---

shenyu-examples/pom.xml
shenyu-examples/shenyu-examples-plugin/pom.xml
shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/CustomShenyuPlugin.java
shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/MyCustomShenyuPlugin.java
shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java
shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java
shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginPathBuilder.java

[new feature] add shenyu ext plugin dynamic loading

---

.gitignore
shenyu-dist/shenyu-bootstrap-dist/entrypoint.sh

[Fix: build] fix maven ignore and docker entrypoint

---

shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ContextPathPluginTest.java

Ref #1950 .
1. remove context path, without prefix.
2. remove context path, and appending prefix.

[ISSUE #1950] Add integrated test for context-path plugin

---

shenyu-bootstrap/src/main/resources/application-local.yml
shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ShenyuConfiguration.java
shenyu-web/src/main/java/org/apache/shenyu/web/controller/PluginController.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/LocalDispatcherFilter.java

[new feature] add shenyu can update local data

---

shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepository.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-zookeeper/src/main/java/org/apache/shenyu/register/server/zookeeper/ZookeeperServerRegisterRepository.java

[type: refactor] shenyu-register-center: rename zookeeper properties name.

---

shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java
shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/AbstractPluginDataInit.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/WafPluginTest.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/BaseDataCache.java
shenyu-web/src/main/java/org/apache/shenyu/web/controller/PluginController.java

[type: refactor] refactor integration test for waf plugin

---

shenyu-integrated-test/README.md

Update README in `shenyu-integrated-test`

Change README in `shenyu-integrated-test`

---

shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ParamMappingPluginTest.java

[ISSUE #1966] Add integrated test for param mapping plugin

---

shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ContextPathPluginTest.java

[ISSUE #1979] Refactor integration test for context-path plugin

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/MapperConfig.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/DataBaseProperties.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/PostgreSqlQueryInterceptor.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/LocalDataSourceLoader.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/PostgreSqlLoader.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/ScriptLoader.java
shenyu-admin/src/main/resources/application-pg.yml

[type: refactor] refactor  admin support PostgreSql

---

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java
shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SentinelPluginTest.java

[ISSUE #1966] Add integrated test for sentinel plugin

---

shenyu-bootstrap/src/main/resources/application-local.yml
shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java
shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/pom.xml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/main/resources/application-local.yml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfiguration.java
shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java
shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuLoaderService.java
shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java
shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginPathBuilder.java
shenyu-web/src/test/java/org/apache/shenyu/web/filter/CrossFilterTest.java

[type: refactor] refactor shenyu config

---

shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE
shenyu-dist/shenyu-admin-dist/src/main/release-docs/licenses/LICENSE-jaxb-api.txt
shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/licenses/LICENSE-jaxb-api.txt

[ISSUE #2006] add jaxb-api license

---

shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/test/java/org/apache/shenyu/register/client/http/RegisterUtilsTest.java

fix client :  gson toJson is null question `org.apache.shenyu.register.client.http.RegisterUtilsTest` #2030

[ISSUE #2030] Fix gson toJson is null question

---

.github/ISSUE_TEMPLATE/task.yml
.github/ISSUE_TEMPLATE/volunteer.yml

[type: build] add Volunteer issue

---

shenyu-integrated-test/shenyu-integrated-test-http/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java

Ref #1979 .
Refactor integration test for rate-limiter plugin

[ISSUE #1979] Refactor integration test for rate-limiter plugin

---

.github/workflows/integrated-test-alibaba-dubbo.yml
.github/workflows/integrated-test-apache-dubbo.yml
shenyu-examples/shenyu-examples-dubbo/pom.xml
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/Dockerfile
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/pom.xml
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/Dockerfile
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/resources/spring-dubbo.xml
shenyu-integrated-test/pom.xml
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/DubboTest.java
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/Dockerfile
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/docker-compose.yml
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/pom.xml
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/script/healthcheck.sh
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/script/services.list
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/src/main/java/org/apache/shenyu/intergratedtest/alibaba/dubbo/AlibabaDubboIntergratedBootstrap.java
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/src/main/resources/application.yml
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/src/test/java/org/apache/shenyu/intergratedtest/alibaba/dubbo/AlibabaDubboPluginTest.java
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/Dockerfile
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/docker-compose.yml
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/pom.xml
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/script/healthcheck.sh
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/script/services.list
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/src/main/java/org/apache/shenyu/intergratedtest/apache/dubbo/ApacheDubboIntergratedBootstrap.java
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/src/main/resources/application.yml
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/src/test/java/org/apache/shenyu/intergratedtest/alibaba/dubbo/ApacheDubboPluginTest.java

Init dubbo integration test, issue#1981

[Integration-Test] Init dubbo integration test

---

shenyu-examples/pom.xml
shenyu-examples/shenyu-examples-websocket/Dockerfile
shenyu-examples/shenyu-examples-websocket/pom.xml
shenyu-examples/shenyu-examples-websocket/src/main/java/org/apache/shenyu/examples/websocket/ShenyuWebsocketApplication.java
shenyu-examples/shenyu-examples-websocket/src/main/java/org/apache/shenyu/examples/websocket/config/WebSocketConfiguration.java
shenyu-examples/shenyu-examples-websocket/src/main/java/org/apache/shenyu/examples/websocket/handler/EchoHandler.java
shenyu-examples/shenyu-examples-websocket/src/main/resources/application.yml

[Examples : websocket] add websocket examples

---

shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPlugin.java
shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePlugin.java
shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/HttpUtil.java
shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/JsonUtil.java
shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginPathBuilder.java
shenyu-web/src/main/java/org/apache/shenyu/web/logo/ShenyuLogo.java

[type: refactor] code refactor

---

shenyu-web/src/test/java/org/apache/shenyu/web/controller/AppAuthControllerTest.java

add unit test for org.apache.shenyu.web.controller.AppAuthController
#2081

[type: feature] add unit  test for AppAuthController, pr [#2081]

---

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java
shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ModifyResponsePluginTest.java
shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java

// Describe your PR here; eg. Fixes #1980

add integraton test for modifyResponse plugin

---

.github/workflows/integrated-test-motan.yml
shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/Dockerfile
shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/pom.xml
shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/TestMotanApplication.java
shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/config/RegistryProperties.java
shenyu-integrated-test/pom.xml
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/MotanDTO.java
shenyu-integrated-test/shenyu-integrated-test-motan/Dockerfile
shenyu-integrated-test/shenyu-integrated-test-motan/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-motan/pom.xml
shenyu-integrated-test/shenyu-integrated-test-motan/script/healthcheck.sh
shenyu-integrated-test/shenyu-integrated-test-motan/script/services.list
shenyu-integrated-test/shenyu-integrated-test-motan/src/main/java/org/apache/shenyu/integrated/test/motan/MotanIntegratedBootstrap.java
shenyu-integrated-test/shenyu-integrated-test-motan/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-motan/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integrated-test-motan/src/main/resources/application.yml
shenyu-integrated-test/shenyu-integrated-test-motan/src/test/java/org/apache/shenyu/integrated/test/motan/MotanPluginTest.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/proxy/MotanProxyService.java

[ISSUE #2060] feature integrated-test-motan:  init motan integration test

feature integrated-test-motan: init motan integration test #2060

---

shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/proxy/MotanProxyService.java

[type: bug] modify motan plugin init  refererConfig

---

shenyu-plugin/shenyu-plugin-alibaba-dubbo/pom.xml
shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyService.java
shenyu-plugin/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyServiceTest.java
shenyu-plugin/shenyu-plugin-apache-dubbo/pom.xml
shenyu-plugin/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java
shenyu-plugin/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java
shenyu-plugin/shenyu-plugin-dubbo-common/pom.xml
shenyu-plugin/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/param/DubboParamResolveService.java
shenyu-plugin/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/param/DubboParamResolveServiceImpl.java
shenyu-plugin/shenyu-plugin-dubbo-common/src/test/java/org/apache/shenyu/plugin/dubbo/common/param/DubboParamResolveServiceTest.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/param/SofaParamResolveService.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/param/SofaParamResolveServiceImpl.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/proxy/SofaProxyService.java
shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/param/SofaBodyParamResolveServiceTest.java
shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/proxy/SofaProxyServiceTest.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/springboot/starter/plugin/alibaba/dubbo/AlibabaDubboPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-apache-dubbo/src/main/java/org/apache/shenyu/springboot/starter/plugin/apache/dubbo/ApacheDubboPluginConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-dubbo-common/src/main/java/org/apache/shenyu/springboot/plugin/dubbo/common/DubboCommonConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sofa/src/main/java/org/apache/shenyu/springboot/starter/plugin/sofa/SofaPluginConfiguration.java

[type: refactor]modify dubbo and sofa param resolve service

---

shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/register/PrometheusMetricsRegister.java
shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/service/PrometheusBootService.java
shenyu-metrics/shenyu-metrics-spi/src/main/java/org/apache/shenyu/metrics/reporter/MetricsReporter.java
shenyu-metrics/shenyu-metrics-spi/src/main/java/org/apache/shenyu/metrics/spi/MetricsRegister.java
shenyu-plugin/shenyu-plugin-monitor/src/main/java/org/apache/shenyu/plugin/monitor/MonitorPlugin.java

[type: bug] monitor plugin enabled after register labels

---

shenyu-integrated-test/shenyu-integrated-test-spring-cloud/script/healthcheck.sh

Fixes #2119
I did the following:
1.Increase sleep time to wait for registration to complete
2.add log for debug

[ISSUE #2119] sometime spring cloud integration test error

---

shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginPathBuilder.java
shenyu-web/src/test/java/org/apache/shenyu/web/loader/ShenyuPluginPathBuilderTest.java

[ISSUE #2079] Add unit test for ShenyuPluginPathBuilder 

---

shenyu-integrated-test/shenyu-integrated-test-motan/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-motan/script/healthcheck.sh

Fixes #2124
1. Modify container dependencies
2. Increase sleep time to wait for registration to complete

[ISSUE #2124] sometime motan integration test error 

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDubboServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterGrpcServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterMotanServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSofaServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringMVCServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterTarsServiceImpl.java

Ref #2116 .
Bug: The rules will be empty by the first start of example(sofa, motan, grpc), but it will be filled after the re-start.

[ISSUE #2116] Fix the bug of register

---

shenyu-admin/src/main/resources/sql-script/h2/schema.sql
shenyu-admin/src/main/resources/sql-script/mysql/schema.sql
shenyu-admin/src/main/resources/sql-script/pg/schema.sql

Add missing plugin_handle sql for plugin motan

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringMVCServiceImpl.java

[type: refactor] Optimize register rules

---

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/AbstractPluginDataInit.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ContextPathPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/JwtPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ModifyResponsePluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ParamMappingPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RedirectPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RequestPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SentinelPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SignPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/WafPluginTest.java
shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/subsciber/MetaDataCacheSubscriber.java
shenyu-plugin/shenyu-plugin-global/src/test/java/org/apache/shenyu/plugin/global/subsciber/MetaDataCacheSubscriberTest.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-global/src/main/java/org/apache/shenyu/springboot/starter/plugin/global/GlobalPluginConfiguration.java
shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalAppAuthController.java
shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalMetadataController.java
shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java
shenyu-web/src/test/java/org/apache/shenyu/web/controller/LocalAppAuthControllerTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/controller/LocalPluginControllerTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/controller/TestObjectProvider.java

[type: refactor] refactor code and add metadata controller

---

RELEASE-NOTES.md

[type: build] Add RELEASE-NOTES for 2.4.1

---

shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java

[ISSUE #2128] Fix unit tests occasionally fail to execute.

---

shenyu-common/src/main/java/org/apache/shenyu/common/dto/AppAuthData.java
shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalAppAuthController.java
shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalMetadataController.java

[type: refactor] Modify local model controller

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/executor/RegisterServerConsumerExecutor.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/subscriber/URIRegisterExecutorSubscriber.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDefaultServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterServiceFactory.java

fix and optimize #2150 : optimize meta data and URI data register.

[type:refactor] optimize metadata & uri data register.

---

.github/workflows/integrated-test.yml
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/Dockerfile
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/pom.xml
shenyu-integrated-test/pom.xml
shenyu-integrated-test/shenyu-integrated-test-sofa/Dockerfile
shenyu-integrated-test/shenyu-integrated-test-sofa/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-sofa/pom.xml
shenyu-integrated-test/shenyu-integrated-test-sofa/script/healthcheck.sh
shenyu-integrated-test/shenyu-integrated-test-sofa/script/services.list
shenyu-integrated-test/shenyu-integrated-test-sofa/src/main/java/org/apache/shenyu/integrated/test/sofa/SofaIntegratedBootstrap.java
shenyu-integrated-test/shenyu-integrated-test-sofa/src/main/java/org/apache/shenyu/integrated/test/sofa/dto/SofaTestData.java
shenyu-integrated-test/shenyu-integrated-test-sofa/src/main/resources/admin-config/schema.sql
shenyu-integrated-test/shenyu-integrated-test-sofa/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integrated-test-sofa/src/main/resources/application.yml
shenyu-integrated-test/shenyu-integrated-test-sofa/src/test/java/org/apache/shenyu/integrated/test/sofa/SofaPluginTest.java

[ISSUE #1982] Add integrated test for sofa plugin

---

shenyu-admin/src/main/resources/sql-script/h2/schema.sql
shenyu-admin/src/main/resources/sql-script/mysql/schema.sql
shenyu-admin/src/main/resources/sql-script/pg/schema.sql

[type: refactor] Remove selector and rule name as unique name in sql

---

shenyu-plugin/shenyu-plugin-websocket/src/main/java/org/apache/shenyu/plugin/websocket/handler/WebSocketPluginDataHandler.java

// Describe your PR here; eg. Fixes #2168 

[ISSUE #2168] Fix the bug of starting bootstarp with websocket plugin failed

---

RELEASE-NOTES.md

fix release notes typo

---

shenyu-dist/release_check.py

add release check script

---

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcClientBeanPostProcessor.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceBeanPostProcessor.java
shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceBeanPostProcessor.java
shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java

at client, valid contextPath if need, and change build path user Paths. Done #2164

[#2164]optimization client build path #2170

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketCollector.java

websocket send message add lock Fixes #2173

[ISSUE #2173] fix websocket send message unsafe

---

shenyu-admin/src/main/resources/sql-script/pg/schema.sql

[ISSUE #2176] Fix the bug of websocket plugin in pg/schema.sql.

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImplTest.java

test for ShenyuClientRegisterSpringCloudServiceImplTest do #2142

for ShenyuClientRegisterSpringCloudServiceImplTest test

---

shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java

[ISSUE #2116] Fix the bug of building sofa-rpc reference error in sofa plugin

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ShenyuClientRegisterMotanServiceImplTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ShenyuClientRegisterServiceTest.java

add test case for ShenyuClientRegisterMotanServiceImpl

---

shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorRequestPluginTest.java

[ISSUE #2239] Add integrated test for cryptor request plugin

---

README.md
README_CN.md

[refactor: readme] add quick start to readme

---

shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/ShenyuAgentBootstrap.java
shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/classloader/AgentClassLoader.java
shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/exception/AgentBootstrapFailException.java

[ISSUE #1978] add agent class loader

---

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/ClientResponseUtils.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/ClientResponseUtils.java
shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/decorator/ResponseDecorator.java
shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/response/CryptorResponsePlugin.java
shenyu-plugin/shenyu-plugin-modify-response/src/main/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePlugin.java

[type: bug] fix 2225, optimize client response builder.

---

shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/path/RegisterPathConstants.java

// Describe your PR here; eg. Fixes #2275

[ISSUE #2275]Fix register error by nacos

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketCollector.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketListener.java

refactor admin :  websocket data sync code polish

---

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java

// Describe your PR here; eg. Fixes #2276

[ISSUE #2276]Fix bug, throw NullPointException when use spring cloud client.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketCollector.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketListener.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/zookeeper/ZookeeperDataChangedListener.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/zookeeper/ZookeeperDataInit.java
shenyu-common/src/main/java/org/apache/shenyu/common/enums/DataEventTypeEnum.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/WebsocketSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/handler/AbstractDataHandler.java
shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java

refactor shenyu-data-sync-zookeeper: code polish .

---

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/annotation/ShenyuSpringCloudClient.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/annotation/ShenyuSpringMvcClient.java

remove Deprecated field

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SelectorServiceTest.java

remove unused code

---

shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/loadbalance/AbstractLoadBalancer.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/loadbalance/GrpcAttributeUtils.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/loadbalance/picker/AbstractReadyPicker.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/resolver/ShenyuNameResolver.java
shenyu-plugin/shenyu-plugin-grpc/src/test/java/org/apache/shenyu/plugin/grpc/loadbalance/AbstractLoadBalancerTest.java

grpc code refactor

---

shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java

[Volunteer] <Support real async in dubbo request> #2272

---

shenyu-admin/src/main/resources/application-mysql.yml
shenyu-admin/src/main/resources/application.yml

[type: refactor]refactor admin mysql yaml config

---

shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/classloader/AgentClassLoader.java
shenyu-agent/shenyu-agent-plugins/pom.xml
shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/pom.xml

agent bug fix

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/config/NacosConfigurationTest.java

Eliminate the yellow code prompt

---

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/dto/DubboRpcExt.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java

[type:feature] Support sent in dubbo. 

---

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/cache/ApplicationConfigCache.java

[type:feature]replace maxCount with Constants.CACHE_MAX_COUNT

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginHandleMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ResourceMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleConditionMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorConditionMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/ResourceService.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ResourceServiceImpl.java
shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
shenyu-admin/src/main/resources/mappers/resouce-sqlmap.xml
shenyu-admin/src/main/resources/mappers/rule-condition-sqlmap.xml
shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml
shenyu-admin/src/main/resources/mappers/selector-condition-sqlmap.xml
shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginServiceTest.java
shenyu-common/src/main/java/org/apache/shenyu/common/constant/AdminConstants.java

[type: refactor] optimize admin plugin delete.

---

shenyu-common/src/main/java/org/apache/shenyu/common/utils/DateUtils.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/GsonUtils.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/IpUtils.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/PathMatchUtils.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/ReflectUtils.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/SignUtils.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/UpstreamCheckUtils.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/VersionUtils.java

refactor shenyu-common: code polish.

---

shenyu-agent/shenyu-agent-api/pom.xml
shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/spi/PluginAdviceDef.java
shenyu-agent/shenyu-agent-bootstrap/src/main/java/org/apache/shenyu/agent/bootstrap/classloader/AgentClassLoader.java
shenyu-agent/shenyu-agent-core/pom.xml
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/AgentInstaller.java
shenyu-agent/shenyu-agent-plugins/pom.xml
shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/pom.xml
shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/tracing/jaeger/JaegerPluginAdviceDef.java
shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/resources/META-INF/shenyu/org.apache.shenyu.agent.spi.PluginAdviceDef

support spi in javaagent

---

shenyu-dist/shenyu-admin-dist/Dockerfile

#2308, update dockerfile for admin

---

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-springcloud/src/main/java/org/apache/shenyu/springboot/starter/plugin/springcloud/SpringCloudPluginConfiguration.java

[ISSUE #2339]  springCloud router choose error 

---

shenyu-dist/shenyu-admin-dist/src/main/release-docs/README.txt
shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/README.txt

change getting started link in readme.txt

---

shenyu-admin/src/main/resources/logback.xml
shenyu-bootstrap/src/main/resources/logback.xml
shenyu-dist/shenyu-admin-dist/entrypoint.sh
shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.sh
shenyu-dist/shenyu-admin-dist/src/main/resources/logback.xml
shenyu-dist/shenyu-bootstrap-dist/entrypoint.sh
shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh
shenyu-dist/shenyu-bootstrap-dist/src/main/resources/logback.xml

[[// Describe your PR here; eg. Fixes #issueNo](https://github.com/apache/incubator-shenyu/issues/2342)](https://github.com/apache/incubator-shenyu/issues/2341)

modify log directory for shenyu-admin and shenyu-bootstrap

---

.gitmodules

#2336, remove the front end submodule

---

shenyu-common/src/main/java/org/apache/shenyu/common/utils/UpstreamCheckUtils.java

Fixes issue #2346 
enhancement  shenyu-common :  trim spaces in ip and port

issues#2346 trim spaces in ip and port 

---

shenyu-dist/shenyu-admin-dist/Dockerfile
shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.sh
shenyu-dist/shenyu-admin-dist/src/main/resources/bin/stop.sh
shenyu-dist/shenyu-bootstrap-dist/Dockerfile
shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh
shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/stop.sh

[ISSUE #2338] fix the start/stop script can't work in container

---

shenyu-integrated-test/shenyu-integrated-test-http/pom.xml
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RequestPluginTest.java

The original integration test has no effect...

[Integrated-Test] Fix the integrated test of request plugin

---

RELEASE-NOTES.md

fix some spelling mistakes in  Release Notes

---

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java

Remove the yellow alert

---

shenyu-protocol/shenyu-protocol-mqtt/pom.xml
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/AbstractMessageType.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/BootstrapServer.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Connect.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MessageType.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttBootstrapServer.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttEnv.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttFactory.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/PubAck.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Publish.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Subscribe.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Unsubscribe.java

[ISSUE #2071] add mqtt protocol

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/exception/ExceptionHandlers.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdDataInit.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/converter/SelectorHandleConverterFactor.java

fix some yellow alert in shenyu-admin module

---

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java

[ISSUE #2296] Enhanced integration test of RateLimiter plugin

---

shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorRuleHandler.java

Let `CryptorRuleHandler` implements `RuleHandle`

[type: refactor] `CryptorRuleHandler` implements `RuleHandle`

---

.github/workflows/integrated-test.yml
shenyu-bootstrap/pom.xml
shenyu-integrated-test/pom.xml
shenyu-integrated-test/shenyu-integrated-test-combination/Dockerfile
shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml
shenyu-integrated-test/shenyu-integrated-test-combination/script/healthcheck.sh
shenyu-integrated-test/shenyu-integrated-test-combination/script/services.list
shenyu-integrated-test/shenyu-integrated-test-combination/src/main/java/org/apache/shenyu/integrated/test/combination/CombinationIntegratedBootstrap.java
shenyu-integrated-test/shenyu-integrated-test-combination/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integrated-test-combination/src/main/resources/application.yml
shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/MultiRequestPluginTest.java

We can add more in `shenyu-integrated-test-combination` later, such as combination of response plugins, rpc plugins, request and response plugins...

[Integrated-Test] Init combination integrated test

---

pom.xml
shenyu-dist/shenyu-admin-dist/pom.xml
shenyu-dist/shenyu-bootstrap-dist/pom.xml
shenyu-examples/pom.xml
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/pom.xml
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml
shenyu-examples/shenyu-examples-eureka/pom.xml
shenyu-examples/shenyu-examples-grpc/pom.xml
shenyu-examples/shenyu-examples-http/pom.xml
shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/pom.xml
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/pom.xml
shenyu-examples/shenyu-examples-websocket/pom.xml
shenyu-integrated-test/pom.xml
shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-grpc/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-motan/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-sofa/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-websocket/docker-compose.yml
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/docker-compose.yml
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/docker-compose.yml

Fixes #2331
change shenyu-admin image version from 2.4.2-SNAPSHOT to latest

[ISSUE #2331] change shenyu-admin image version to latest

---

shenyu-disruptor/pom.xml
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/DisruptorProviderManage.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/consumer/QueueConsumer.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/provider/DisruptorProvider.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/thread/DisruptorThreadFactory.java

[ISSUE #2366] remove warning codes in shenyu-disruptor module

---

shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataServiceTest.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/handler/ConsulCacheHandlerTest.java
shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/HttpSyncDataServiceTest.java
shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/refresh/AppAuthDataRefreshTest.java
shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/refresh/RuleDataRefreshTest.java
shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/refresh/SelectorDataRefreshTest.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/NacosSyncDataServiceTest.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/config/NacosACMConfigTest.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/config/NacosConfigTest.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandlerTest.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/handler/NacosMockConfigService.java

[ISSUE #2373] Remove warning code in shenyu-sync-data-center

---

shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCacheManager.java
shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTask.java
shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamWithSelectorId.java
shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/entity/Upstream.java
shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/AbstractLoadBalancer.java
shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/HashLoadBalancer.java
shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RandomLoadBalancer.java
shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalancer.java

Fixes #2377 
clean up waring code for moudle shenyu-loadbalancer

[ISSUE #2377] clean up optimize [shenyu-loadbalancer]

---

shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionFactory.java
shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java
shenyu-spi/src/test/java/org/apache/shenyu/spi/ExtensionLoaderTest.java
shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/JdbcSPI.java

cleanup warning code for module `shenyu-spi`
Closes https://github.com/apache/incubator-shenyu/issues/2368

[ISSUE #2368] Remove warning code in shenyu-SPI

---

shenyu-dist/shenyu-bootstrap-dist/pom.xml

Make shenyu-bootstrap build 2 images when user docker profile.
It's same to shenyu-admin

feature(dist): make shenyu-bootstrap build 2 images

---

shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java

[ISSUE #2373] Remove warning code of HttpSyncDataService.java

---

shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java
shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/factory/LoadBalancerFactoryTest.java
shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalanceTest.java

About #2366 
clean up optimize [shenyu-loadbalancer] test code. 

[ISSUE #2366] clean up optimize [shenyu-loadbalancer] test code.

---

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultWrap.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/RpcParamTransformPlugin.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/support/BodyInserterContext.java
shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/BeanHolder.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/BaseDataCacheTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/CommonHandleCacheTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/CookieParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/HeaderParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/HostParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/IpParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/ParameterDataFactoryTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/PostParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/QueryParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/RequestMethodParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/data/URIParameterDataTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/handler/PluginDataHandlerTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/CacheKeyUtilsTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/HostAddressUtilsTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/UriUtilsTest.java

[ISSUE #2370]  remove warning code in shenyu-plugin-api and shenyu-plugin-base

---

shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/TarsPlugin.java
shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/context/TarsShenyuContextDecorator.java
shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/handler/TarsPluginDataHandler.java
shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/proxy/TarsInvokePrx.java
shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/subscriber/TarsMetaDataSubscriber.java
shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/util/PrxInfoUtil.java
shenyu-plugin/shenyu-plugin-tars/src/test/java/org/apache/shenyu/plugin/tars/subscriber/TarsMetaDataSubscriberTest.java
shenyu-plugin/shenyu-plugin-uri/src/main/java/org/apache/shenyu/plugin/uri/URIPlugin.java

About #2370
clean up optimize shenyu-plugin-tars and shenyu-plugin-uri for the module [shenyu-plugin] .

[ISSUE #2370] clean up optimize [shenyu-plugin-tars] and  [shenyu-plugin-url].

---

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java
shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/OrderController.java
shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/RequestController.java
shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/result/PaymentTypeService.java
shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/router/ShenyuTestHttpRouter.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SignPluginTest.java

[issue #2366]Remove warning code in [shenyu-examples-http] module 

---

shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/RequestPlugin.java
shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/handler/RequestPluginHandler.java
shenyu-plugin/shenyu-plugin-request/src/test/java/org/apache/shenyu/plugin/request/RequestPluginTest.java

[issue #2370]Remove warning code in [shenyu-plugin-request] module

---

shenyu-metrics/shenyu-metrics-facade/src/main/java/org/apache/shenyu/metrics/facade/MetricsTrackerFacade.java
shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/collector/BuildInfoCollector.java
shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/service/PrometheusBootService.java
shenyu-metrics/shenyu-metrics-spi/src/main/java/org/apache/shenyu/metrics/config/MetricsConfig.java

about issue #2366
work list:
clean warning code in shenyu-metrics

[ISSUE #2366] <Remove warning code in shenyu-metrics>

---

shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/handler/CryptorRuleHandler.java
shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java
shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/cache/MetaDataCache.java
shenyu-spi/src/main/java/org/apache/shenyu/spi/SpiExtensionFactory.java

// Fixes #2370
link: #2368  
* optimize warning code
* replace `if` with `optional`

[ISSUE #2370] <Remove warning code in shenyu-plugin-global、shenyu-spi>

---

shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/handler/RewritePluginDataHandler.java
shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java

[issue #2370] remove warning code in shenyu-plugin-sign and shenyu-plugin-rewrite

---

shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/Resilience4JPlugin.java
shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutor.java
shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/RateLimiterExecutor.java
shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/ResponsePlugin.java
shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/MessageWriter.java
shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/NettyClientMessageWriter.java
shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java

About #2370 
clean up optimize [shenyu-plugin-resilience4j] and [shenyu-plugin-response] for the module [shenyu-plugin] . 

[ISSUE #2370] clean up optimize [shenyu-plugin-resilience4j] and [shenyu-plugin-response]. 

---

shenyu-protocol/shenyu-protocol-mqtt/pom.xml
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/AbstractMessageType.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Connect.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttEnv.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttFactory.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttServerConfiguration.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/repositories/ChannelRepository.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/repositories/SimpleChannelRepository.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/utils/EncryptUtil.java

[ISSUE 2071] feat connect

---

shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.bat
shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.sh
shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.bat
shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh

https://github.com/apache/incubator-shenyu/issues/2390

[ISSUE #2390]fix bug  start.sh  do not work 

---

shenyu-plugin/shenyu-plugin-logging/src/main/java/org/apache/shenyu/plugin/logging/LoggingPlugin.java

[ISSUE 2370] Remove warning code in [shenyu-plugin-logging] module

---

shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/Resilience4JPlugin.java
shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/build/Resilience4JBuilder.java
shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/conf/Resilience4JConf.java
shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/RateLimiterExecutor.java
shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/handler/Resilience4JHandler.java
shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutorTest.java
shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/executor/RateLimiterExecutorTest.java

cleanup warning codes.
* shenyu-plugin-resilience4j

[issue #2370]Remove warning code in [shenyu-plugin-resilience4j] #2399

---

shenyu-common/src/test/java/org/apache/shenyu/common/utils/UpstreamCheckUtilsTest.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/test/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepositoryTest.java

[type: refactor] fix unit test fail

---

shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java

for #2370 
shenyu-plugin-context-path @AhahaGe
I think this code is simple and no warn part, and I just extract some variable which used multiple times in one method to simplify code.
I have run all test case and passed.

[issue #2370]Remove warning code in [shenyu-plugin-context-path]

---

.github/workflows/ci.yml
shenyu-admin/pom.xml
shenyu-bootstrap/pom.xml
shenyu-dist/shenyu-admin-dist/pom.xml
shenyu-dist/shenyu-bootstrap-dist/pom.xml
shenyu-dist/shenyu-src-dist/pom.xml

[type:bug] ShiroProperties.getWhiteList() is null

---

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
shenyu-common/src/main/java/org/apache/shenyu/common/constant/DefaultPathConstants.java
shenyu-common/src/main/java/org/apache/shenyu/common/utils/Md5Utils.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-consul/src/main/java/org/apache/shenyu/register/client/consul/ConsulClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-etcd/src/main/java/org/apache/shenyu/register/client/etcd/EtcdClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-http/pom.xml
shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/utils/RegisterUtils.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepository.java
shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/path/RegisterPathConstants.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-consul/src/main/java/org/apache/shenyu/register/server/consul/ConsulServerRegisterRepository.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-consul/src/main/java/org/apache/shenyu/register/server/consul/ShenyuConsulConfigWatch.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-etcd/src/main/java/org/apache/shenyu/register/server/etcd/EtcdServerRegisterRepository.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/main/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepository.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-zookeeper/src/main/java/org/apache/shenyu/register/server/zookeeper/ZookeeperServerRegisterRepository.java

[refactor]<register-client> clean code for  register client 

---

shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml
shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/RpcAndRequestPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java

[ISSUE #2365] Add integrated test for combination of dubbo and request plugins

---

shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml
shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml
shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml
shenyu-admin/src/main/resources/mappers/shenyu-dict-sqlmap.xml

support selector, rule, plugin,plugin-data,metadata,dict like query.

[type: refactor] support like field query.

---

shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/controller/GrpcTestController.java
shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/echo/EchoServiceImpl.java
shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/stream/StreamServiceImpl.java
shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtPluginDataHandler.java
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaSingleParamServiceImpl.java
shenyu-examples/shenyu-examples-springcloud/src/main/java/org/apache/shenyu/examples/springcloud/controller/OrderController.java
shenyu-examples/shenyu-examples-websocket/src/main/java/org/apache/shenyu/examples/websocket/handler/EchoHandler.java

about issue #2366 
work list :
shenyu-examples-dubbo give it to @dizent , if not found, I will fix it

[issue #2366]Remove warning code in [shenyu-examples]

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java

Remove the duplicate comments of the websocketcollector method

[type: refactor] Remove the duplicate comments of the websocketcollector method

---

shenyu-bootstrap/pom.xml
shenyu-bootstrap/src/main/resources/application-local.yml
shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java
shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/dto/InstanceRegisterDTO.java
shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/path/RegisterPathConstants.java
shenyu-register-center/shenyu-register-instance/pom.xml
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-api/pom.xml
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-api/src/main/java/org/apache/shenyu/register/instance/api/ShenyuInstanceRegisterRepository.java
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-core/pom.xml
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-core/src/main/java/org/apache/shenyu/register/instance/core/ShenyuInstanceRegisterRepositoryFactory.java
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/pom.xml
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/main/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperInstanceRegisterRepository.java
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.instance.api.ShenyuInstanceRegisterRepository
shenyu-spring-boot-starter/shenyu-spring-boot-starter-instance/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-instance/src/main/java/org/apache/shenyu/springboot/starter/instance/InstanceRegisterListener.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-instance/src/main/java/org/apache/shenyu/springboot/starter/instance/ShenyuInstanceConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-instance/src/main/resources/META-INF/spring.factories
shenyu-spring-boot-starter/shenyu-spring-boot-starter-instance/src/main/resources/META-INF/spring.provides

[new: feature] register shenyu instance by zookeeper

---

shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java

Remove warning in ide

---

shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/AbstractRateLimiterAlgorithm.java
shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/handler/RateLimiterPluginDataHandler.java
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/main/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperInstanceRegisterRepository.java

[type: refactor] refactor some warning code

---

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java

[ISSUE #2443] Improve the stability of Ratelimiter plugin integration test

---

shenyu-bootstrap/pom.xml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-oauth2/pom.xml

[type: refactor] refactor boostrap pom

---

shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/MotanPlugin.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/handler/MotanPluginDataHandler.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/proxy/MotanProxyService.java
shenyu-plugin/shenyu-plugin-redirect/src/main/java/org/apache/shenyu/plugin/redirect/handler/RedirectPluginDataHandler.java

[ISSUE apache#2370]Remove warning code in [shenyu-plugin-motan and shenyu-plugin-redirect] module

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java
shenyu-register-center/shenyu-register-server/shenyu-register-server-etcd/src/main/java/org/apache/shenyu/register/server/etcd/client/EtcdClient.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-etcd/src/main/java/org/apache/shenyu/springboot/sync/data/etcd/EtcdSyncDataConfiguration.java

[ISSUE #2456] Fix using etcd cluster to sync data init failed

---

shenyu-plugin/shenyu-plugin-uri/src/test/java/org/apache/shenyu/plugin/uri/URIPluginTest.java

[ISSUE #2236] Add unit test for URIPlugin.

---

shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/NettyTcpConfig.java
shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/ShenyuNettyWebServerFactory.java
shenyu-bootstrap/src/main/resources/application-local.yml
shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/NettyTcpConfig.java
shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/ShenyuNettyWebServerFactory.java
shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/resources/application-local.yml

refactor bootstrap: Use the annotation @ConfigurationProperties instead of the @Value in NettyTcpConfig

---

shenyu-admin/src/main/resources/application.yml

[type: security]fix shenyu-admin: remove plugin info from shiro white list.

---

shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/NettyTcpConfig.java
shenyu-bootstrap/src/main/java/org/apache/shenyu/bootstrap/configuration/ShenyuNettyWebServerFactory.java

[type: refactor] fix boostrap config bug

---

shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/NettyTcpConfig.java
shenyu-integrated-test/shenyu-integrated-test-grpc/src/main/java/org/apache/shenyu/integrated/test/grpc/configuration/ShenyuNettyWebServerFactory.java

[type: refactor] fix shenyu-integrated-test: fix NettyTcpConfig bug

---

shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtPluginDataHandler.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/handler/SofaPluginDataHandler.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/param/SofaParamResolveService.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/param/SofaParamResolveServiceImpl.java
shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/proxy/SofaProxyService.java
shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/handler/SofaPluginDataHandlerTest.java
shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/param/SofaBodyParamResolveServiceTest.java
shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/proxy/SofaProxyServiceTest.java

about issue no: #2370 
work list:
Part of the submission was lost due to the network

[ISSUE #2370]【Code Clean】Remove warning codes in [shenyu-plugin-sofa] module

---

shenyu-plugin/shenyu-plugin-oauth2/src/main/java/org/apache/shenyu/plugin/oauth2/OAuth2Plugin.java
shenyu-plugin/shenyu-plugin-oauth2/src/main/java/org/apache/shenyu/plugin/oauth2/filter/OAuth2PreFilter.java

[#2465] remove warning codes in module shenyu-plugin-oauth2

[ISSUE #2465]clean waring code in module shenyu-plugin-oauth2

---

shenyu-plugin/shenyu-plugin-ratelimiter/src/test/java/org/apache/shenyu/plugin/ratelimiter/handler/RateLimiterPluginDataHandlerTest.java

[ISSUE #2468] clean warning codes in module shenyu-plugin-ratelimiter

[ISSUE #2468] clean warning codes in module shenyu-plugin-ratelimiter

---

pom.xml
shenyu-register-center/shenyu-register-instance/pom.xml
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-core/pom.xml
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/pom.xml
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/main/java/org/apache/shenyu/register/instance/etcd/EtcdClient.java
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/main/java/org/apache/shenyu/register/instance/etcd/EtcdInstanceRegisterRepository.java
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.instance.api.ShenyuInstanceRegisterRepository

[ISSUE #2450] register shenyu instance by etcd

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterTarsServiceImplTest.java

[ISSUE #2144] Add unit test for ShenyuClientRegisterTarsServiceImpl

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterGrpcServiceImplTest.java

[ISSUE #2139] Add unit test for ShenyuClientRegisterGrpcServiceImpl

---

shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepository.java

[ISSUE #2476] When the project is started, the ZK node cannot be found exception

---

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CryptorResponsePluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ModifyResponsePluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ParamMappingPluginTest.java

[ISSUE #2239] Add integration test for CryptorResponsePlugin

---

shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/test/java/org/apache/shenyu/register/instance/etcd/EtcdInstanceRegisterRepositoryTest.java

[ISSUE #2450] Add unit test for register instance by etcd

---

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboTestServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboTestServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboTestServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/impl/DubboMultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/impl/DubboTestServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/impl/MultiParamServiceImpl.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/impl/TestServiceImpl.java

about issue #2366
work list :
about pr : https://github.com/apache/incubator-shenyu/pull/2399

[issue #2366]Remove warning code in [shenyu-examples-dubbo] 

---

shenyu-plugin/shenyu-plugin-oauth2/src/main/java/org/apache/shenyu/plugin/oauth2/OAuth2Plugin.java

[ISSUE #2494] Fix skip oauth2 plugin failed

---

shenyu-dist/shenyu-docker-compose-dist/src/main/assembly/source.xml
shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-h2/docker-compose.yaml

[ISSUE #2361] add docker-compose h2

---

shenyu-dist/shenyu-docker-compose-dist/src/main/assembly/source.xml
shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-pg/docker-compose.yaml

[ISSUE #2361] add docker-compose pg

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AppAuthMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AuthParamMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AuthPathMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ResourceMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PermissionServiceImpl.java
shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml
shenyu-admin/src/main/resources/mappers/auth-param-sqlmap.xml
shenyu-admin/src/main/resources/mappers/auth-path-sqlmap.xml
shenyu-admin/src/main/resources/mappers/resouce-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/AppAuthServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PermissionServiceTest.java

I refactored some database operations in the loop in AppAuthServiceImpl and PermissionServiceImpl

[ISSUE #2321] Optimize database access in the loop.

---

shenyu-common/src/main/java/org/apache/shenyu/common/utils/ReflectUtils.java
shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/BodyParamUtils.java

[BUG] <not support dubbo primitive type >
// Describe your PR here; eg. Fixes #2487

[fix #2487] Support Dubbo Plugin Single Parameter  Primitive Type 

---

shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/AbstractPluginDataInit.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/MotanDTO.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/OrderDTO.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SentinelPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/WafPluginTest.java
shenyu-integrated-test/shenyu-integrated-test-motan/src/test/java/org/apache/shenyu/integrated/test/motan/MotanPluginTest.java

link #2366 
remove code smell in  integrated-test

refactor(integrated-test): remove code smell in  integrated-test

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java

[type: refactor] ignore upstream check unit test

---

shenyu-plugin/shenyu-plugin-sentinel/src/test/java/org/apache/shenyu/plugin/sentinel/SentinelPluginTest.java

[ISSUE #2370] remove warning code in shenyu-plugin-sentinel

---

script/2.4.1-upgrade-2.4.2-mysql.sql
script/2.4.1-upgrade-2.4.2-pg.sql
script/upgrade-guide.md

[ISSUE #2525] Add upgrade script for postgreSql.

---

shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java

[ISSUE #2447] Add clean plugin log for LocalPluginController

---

shenyu-examples/pom.xml

[ISSUE #2532]: add <relativePath> in shenyu-examples' module pom.xml

---

shenyu-agent/shenyu-agent-bootstrap/pom.xml
shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/pom.xml
shenyu-dist/shenyu-bootstrap-dist/pom.xml
shenyu-dist/shenyu-bootstrap-dist/src/main/assembly/binary.xml

[type:refactor]: modify the packaging path about agent

---

shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/RequestAndResponsePluginTest.java

about #2365 
I just only add encrypt request and decrypt response.

[ISSUE #2365] Add integrated test for combination of encrypt request and decrypt response

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/aspect/DataPermissionAspectTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/aspect/PageableAspectTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/DataSyncConfigurationTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/LdapConfigurationTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/MapperConfigTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/RegisterCenterConfigurationTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/ShenyuAdminConfigurationTest.java

About #1824
About #2420
improve following classes test code coverage:
org.apache.shenyu.admin.aspect.DataPermissionAspect
org.apache.shenyu.admin.aspect.PageableAspect
org.apache.shenyu.admin.config.DataSyncConfiguration
org.apache.shenyu.admin.config.LdapConfiguration
org.apache.shenyu.admin.config.MapperConfig
org.apache.shenyu.admin.config.RegisterCenterConfiguration
org.apache.shenyu.admin.config.ShenyuAdminConfiguration

[ISSUE #1824] shenyu-admin module test coverage improvement

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DataPermissionMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/MetaDataMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java
shenyu-admin/src/main/resources/mappers/data-permission-sqlmap.xml
shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/DataPermissionMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/MetaDataMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/MetaDataServiceTest.java

In the implementation of metadataservice, the database access in the loop is optimized

[ISSUE #2321] In the implementation of metadataservice, the database access in the loop is optimized

---

shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCache.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/AlibabaDubboPluginTest.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCacheTest.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyServiceTest.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/subscriber/AlibabaDubboMetaDataSubscriberTest.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCacheTest.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/subscriber/ApacheDubboMetaDataSubscriberTest.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/AbstractDubboPlugin.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboConfigCache.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/test/java/org/apache/shenyu/plugin/dubbo/common/param/DubboParamResolveServiceTest.java

about issue#2370 remoe shenyu-plugin dubbo warning code

[Issue #2370]remoe shenyu-plugin-dubbo warning code

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginHandleMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ShenyuDictMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginHandleServiceImpl.java
shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
shenyu-admin/src/main/resources/mappers/shenyu-dict-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginHandleMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ShenyuDictMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginHandleServiceTest.java

In the implementation of the pluginhandleservice interface, the database access in the loop is optimized.

[ISSUE #2321] In the implementation of the pluginhandleservice interface, the database access in the loop is optimized.

---

shenyu-plugin/shenyu-plugin-modify-response/src/test/java/org/apache/shenyu/plugin/modify/response/ModifyResponsePluginTest.java
shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/strategy/FormDataOperator.java
shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/strategy/JsonOperator.java
shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/strategy/Operator.java
shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/strategy/FormDataOperatorTest.java
shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/strategy/JsonOperatorTest.java

[ISSUE #2370]Remove shenyu-plugin-modify-response  shenyu-plugin-param-mapping warning code

---

shenyu-register-center/shenyu-register-client/shenyu-register-client-consul/src/main/java/org/apache/shenyu/register/client/consul/ConsulClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-etcd/src/main/java/org/apache/shenyu/register/client/etcd/EtcdClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepository.java
shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepository.java

issue #2512 
add constructor for ShenyuClientRegisterRepository to supoort springmvc project without springboot

[ISSUE #2512] add constructor for ShenyuClientRegisterRepository to supoort springmvc project without springboot

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/MapperConfig.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/pg/handler/PostgreSQLBooleanHandler.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/pg/interceptor/PostgreSQLQueryInterceptor.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/PostgreSQLLoader.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/MapperConfigTest.java

// Describe your PR here;
refactor class name, PostgreSql -> PostgreSQL.

[type: refactor] refactor class name, PostgreSql -> PostgreSQL.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginServiceTest.java

In the implementation of the pluginservice interface, the database access in the loop is optimized. (#2321)

[ISSUE  #2321]In the implementation of the pluginservice interface, the database access in the loop is optimized.

---

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/NettyHttpClientPlugin.java
shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java

[type:feature]Replace with constants.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/ResourceAndPermissionDataSourceLoader.java

[type:feactor]Fix resource bug

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java

In upstreamcheckservice, the database access in the loop is optimized.

[ISSUE #2321] In upstreamcheckservice, the database access in the loop is optimized.

---

shenyu-bootstrap/src/main/resources/application-local.yml
shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/NettyChannelProperties.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/NettyTcpProperties.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/ShenyuNettyWebServerConfiguration.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/test/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfigurationTest.java

@lahmXu I refactor again based on you. you can ref it.

[type: refactor] refactor netty connfig.

---

shenyu-web/src/test/java/org/apache/shenyu/web/controller/LocalPluginControllerTest.java

https://github.com/apache/incubator-shenyu/issues/2080

[ISSUE #2080] Add unit test for LocalPluginController (#2080)

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SyncDataServiceImpl.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/RuleServiceTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SyncDataServiceTest.java

In syncdataserviceimpl, the database access in the loop is optimized.

[ISSUE #2321] In syncdataserviceimpl, the database access in the loop is optimized.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleConditionMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java
shenyu-admin/src/main/resources/mappers/rule-condition-sqlmap.xml
shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/RuleConditionMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/SelectorMapperTest.java

In ruleserviceimpl, the database access in the loop is optimized.

[ISSUE #2321] In ruleserviceimpl, the database access in the loop is optimized.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/RuleConditionVO.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/SelectorConditionVO.java
shenyu-common/src/main/java/org/apache/shenyu/common/enums/OperatorEnum.java
shenyu-common/src/main/java/org/apache/shenyu/common/enums/ParamTypeEnum.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/OperatorEnumTest.java
shenyu-common/src/test/java/org/apache/shenyu/common/enums/ParamTypeEnumTest.java

[fix: bug] Custom spi config

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ShenyuDictMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ShenyuDictServiceImpl.java
shenyu-admin/src/main/resources/mappers/shenyu-dict-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ShenyuDictControllerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ShenyuDictMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ShenyuDictServiceTest.java

In shenyudictserviceimpl, the database access in the loop is optimized.

[ISSUE #2321] In shenyudictserviceimpl, the database access in the loop is optimized.

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginHandleServiceImpl.java

[ISSUE #2587]  Fix the bug  of #2587

---

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/ExcludePredicateJudge.java
shenyu-plugin/shenyu-plugin-base/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.base.condition.judge.PredicateJudge

[type: refactor] change class name

---

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/WebFluxResultUtils.java
shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java

[type: refactor] optimize result media type and reset response header.

---

shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/AgentInstaller.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/HasParentTypeMatcher.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/SafeErasureMatcher.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/TransformListener.java

[type: refactor]add agent listener and polish code

---

shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/RoleControllerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ShenyuHttpRegistryControllerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/http/HttpLongPollingDataChangedListenerTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/model/query/DataPermissionQueryTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/model/vo/UserRoleVOTest.java
shenyu-sync-data-center/shenyu-sync-data-etcd/src/test/java/org/apache/shenyu/sync/data/etcd/EtcdClientTest.java
shenyu-sync-data-center/shenyu-sync-data-etcd/src/test/java/org/apache/shenyu/sync/data/etcd/EtcdSyncDataServiceTest.java

About #1824
About #1458
About #2420

[ISSUE #2420]   Enhance apache shenyu unit test 

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DataPermissionMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorConditionMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java
shenyu-admin/src/main/resources/mappers/data-permission-sqlmap.xml
shenyu-admin/src/main/resources/mappers/selector-condition-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/DataPermissionMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/SelectorConditionMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SelectorServiceTest.java

In selectorserviceimpl, the database access in the loop is optimized.

[ISSUE #2321] In selectorserviceimpl, the database access in the loop is optimized.

---

shenyu-common/src/main/java/org/apache/shenyu/common/utils/UpstreamCheckUtils.java

[type: refactor] optimize upstream check utils.

---

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java

[type: bug] fix 2611, support image.

---

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java

[type: refactor] list all common binary media types.

---

shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-grpc/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-https/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-motan/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-sofa/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-spring-cloud/docker-compose.yml
shenyu-integrated-test/shenyu-integrated-test-websocket/docker-compose.yml
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/docker-compose.yml
shenyu-integrated-test/shenyu-integration-test-apache-dubbo/docker-compose.yml

Fixes #2619
According to the https://docs.docker.com/compose/compose-file/compose-file-v3/
Unified docker-compose.yml Format in shenyu-integrated-test

refactor(integrated-test): format docker-compose.yml

---

pom.xml

[type: refactor] cleanup useless dependencies

---

shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/AlibabaDubboPlugin.java
shenyu-plugin/shenyu-plugin-general-context/src/main/java/org/apache/shenyu/plugin/general/context/GeneralContextPlugin.java
shenyu-plugin/shenyu-plugin-general-context/src/test/java/org/apache/shenyu/plugin/general/context/GeneralContextPluginTest.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/GrpcPlugin.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/client/GrpcClientBuilder.java
shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/intercept/ContextClientInterceptor.java
shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/proxy/MotanProxyService.java

[ISSUE #2459]context plugin support grpc

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/ResourceService.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PermissionServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ResourceServiceImpl.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ResourceServiceTest.java

In resourceservice,  the recursion is optimized.

[ISSUE #2321] In resourceservice,  the recursion is optimized. 

---

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/dto/DubboRpcExt.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCache.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java
shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboParam.java

[type:feature]Support cluster in dubbo

---

shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh

[type: feature] add install script

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PlatformController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/ShenyuResultMessage.java

[type: refactor] support user disable status.

---

shenyu-register-center/shenyu-register-instance/shenyu-register-instance-core/src/test/java/org/apache/shenyu/register/instance/core/ShenyuInstanceRegisterRepositoryFactoryTest.java
shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/test/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperInstanceRegisterRepositoryTest.java

[ISSUE #2449] Add doc and unit test for register-instance (#2449)

[ISSUE #2449] Add doc and unit test for register-instance (#2449)

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginHandleServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RoleServiceImpl.java

In roleservice,  the recursion is optimized.

[ISSUE #2321] In roleservice,  the recursion is optimized. 

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/RegisterServerDisruptorPublisher.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/FallbackShenyuClientRegisterService.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/config/ZookeeperConfigurationTest.java
shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/ShenyuClientRegisterEventPublisher.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/DisruptorProviderManage.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/consumer/QueueConsumer.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/event/OrderlyDataEvent.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/event/OrderlyDisruptorEventFactory.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/provider/DisruptorProvider.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/thread/OrderlyExecutor.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/thread/SingletonExecutor.java
shenyu-integrated-test/shenyu-integrated-test-https/script/services.list
shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/script/services.list

[type: refactor] Modify register metadata and uri order

[type: refactor] Modify register metadata and uri order

---

shenyu-common/src/main/java/org/apache/shenyu/common/utils/VersionUtils.java
shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java
shenyu-web/src/test/java/org/apache/shenyu/web/loader/ShenyuPluginLoaderTest.java
shenyu-web/src/test/java/org/apache/shenyu/web/logo/ShenyuLogoTest.java

enhance test of shenyu-web , for issue #1456 

[issue:1456]enhance test of shenyu-web

---

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/annotation/ShenyuSpringMvcClient.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
shenyu-examples/shenyu-examples-http/src/main/http/http-test-api-local.http
shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/ShenyuClientPathController.java
shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/SpringMvcMappingPathController.java

【new: feature】Support the use of request Mapping to follow the solution

---

shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh

In the shell, if string comparison is [], if you use (), system variables will be used.

[type: fix] fix install.sh

---

shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java

[type:refactor] optimize cors for Access-Control-Allow-Origin header.

---

shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/yaml/ShenyuYamlEngine.java

[type:fix]Add DumperOptions for yaml parsing

---

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/pom.xml
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/TestApacheDubboAnnotationApplication.java
shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml
shenyu-integrated-test/shenyu-integrated-test-motan/script/services.list

dubbo example revise zookeeper version 3.4.6

[type:bug] dubbo example revise zookeeper version 3.4.6

---

shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java
shenyu-spi/src/test/java/org/apache/shenyu/spi/ExtensionLoaderTest.java
shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/ArrayListSPI.java
shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/EmptySPI.java
shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/LinkedListSPI.java
shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/ListSPI.java
shenyu-spi/src/test/resources/META-INF/shenyu/org.apache.shenyu.spi.fixture.EmptySPI
shenyu-spi/src/test/resources/META-INF/shenyu/org.apache.shenyu.spi.fixture.ListSPI

Add ExtensionLoader#getJoins method.

[type: feature]Add ExtensionLoader#getJoins method.

---

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/ContainsPredicateJudge.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/judge/ContainsPredicateJudgeTest.java
shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/judge/PredicateJudgeFactoryTest.java

[ISSUE #2603]  ContainsPredicateJudge not work for multiple config

---

shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/api/point/ConstructorPointCut.java
shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/api/point/InstanceMethodPointCut.java
shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/api/point/ShenyuAgentJoinPoint.java
shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/api/point/StaticMethodPointCut.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/interceptor/ConstructorInterceptor.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/interceptor/InstanceMethodInterceptor.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/interceptor/StaticMethodInterceptor.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/matcher/ShenyuAgentTypeMatcher.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/transformer/ShenyuAgentTransformer.java
shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/loader/ShenyuAgentPluginLoader.java
shenyu-dist/shenyu-bootstrap-dist/src/main/resources/conf/shenyu-agent.yaml

[new: feature] shenyu agent architecture

---

shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-api/pom.xml

[fix: bug] fix motan examples

---

shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/DisruptorProviderManage.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/provider/DisruptorProvider.java
shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/thread/OrderlyExecutor.java

[type:fix]update the strategy of disruptor to #BlockingWaitStrategy.

[type:fix]update the strategy of disruptor to #BlockingWaitStrategy.

---

shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java

MINOR:polish code of ShenyuPluginLoader.java

---

shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/AbstractMessageType.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Connect.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MessageType.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttBootstrapServer.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttEnv.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttServerConfiguration.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttTransportHandler.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttTransportServerInitializer.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Publish.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/annotation/Connect.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/annotation/Disconnect.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/annotation/Primary.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/annotation/Publish.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/annotation/Subscribe.java
shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/utils/EncryptUtil.java

Runnable, smallest mqtt service.
You can use connect and publish.

[ISSUE #2071] feat mqtt server

---

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java
shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java
shenyu-examples/shenyu-examples-springcloud/src/main/http/spring-cloud-test-api-local.http
shenyu-examples/shenyu-examples-springcloud/src/main/http/spring-cloud-test-api.http
shenyu-examples/shenyu-examples-springcloud/src/main/java/org/apache/shenyu/examples/springcloud/controller/AllController.java
shenyu-examples/shenyu-examples-springcloud/src/main/java/org/apache/shenyu/examples/springcloud/controller/NewFeatureController.java
shenyu-examples/shenyu-examples-springcloud/src/main/java/org/apache/shenyu/examples/springcloud/dto/EntityResult.java

about issue #2662 
Use @XXXMapping#path   to register metadata

[issue ##2662] SpringCloud client support used @XXXMapping#path 

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PermissionMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ResourceMapper.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/ResourceService.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ResourceServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/spring/ResourcePermissionDataSourceLoader.java
shenyu-admin/src/main/resources/application-mysql.yml
shenyu-admin/src/main/resources/mappers/permission-sqlmap.xml
shenyu-admin/src/main/resources/mappers/resouce-sqlmap.xml
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PermissionMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ResourceMapperTest.java
shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ResourceServiceTest.java

In resourcepermissiondatasourceloader, the database access in the loop is optimized.

[ISSUE #2321] In resourcepermissiondatasourceloader, the database access in the loop is optimized.

---

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/config/HttpClientProperties.java
shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java

[type: bug] fix Connection has been closed BEFORE response and java.io.IOException: Connection reset by peer..

---

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/ResponseUtils.java
shenyu-plugin/shenyu-plugin-response/src/test/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriterTest.java

[type: bug] Exceeded limit on max bytes to buffer : 262144.

---

shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh
shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-mysql/docker-compose.yaml
shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-pg/docker-compose.yaml

[type: refactor] update docker-compose & install.sh

---

shenyu-web/pom.xml

[type: refactor] remove extra dependency

---

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/AppAuthController.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java
shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PermissionServiceImpl.java

add permission for admin

---

shenyu-common/src/main/java/org/apache/shenyu/common/utils/ReflectUtils.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataService.java
shenyu-sync-data-center/shenyu-sync-data-consul/src/test/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataServiceTest.java
shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandler.java
shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/test/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataServiceTest.java

[type:refactor] modify judge null and consulSyncDataServiceTest

---

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/config/HttpClientProperties.java

[type: refactor] add http client strategy property.

---

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/UserDTO.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java
shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/result/ResultBean.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/HttpTest.java
shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/HttpTestControllerTest.java

[ISSUE #2679]Add integration test for httpTestController
