apache/shenyu

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/config/HttpClientProperties.java
=> [type: bug] fix responseTimeout can not config in yaml.

shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/OAuth2DTO.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/OrderControllerTest.java
=> [ISSUE #2679] Add integration test for orderController

shenyu-common/src/main/java/org/apache/shenyu/common/utils/ReflectUtils.java
#2684 
As dubbo generic invoke support List<DubboTest> call, so we need not to change it to a single map first.
=> [type: bug] Fix dubbo batchSave problem.

shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/pom.xml, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-common/src/main/java/org/apache/shenyu/agent/plugin/tracing/common/constant/TracingConstants.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-common/src/main/java/org/apache/shenyu/agent/plugin/tracing/common/definition/TracingAgentPluginDefinition.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/pom.xml, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/boot/OpenTelemetryAgentPluginBootService.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/handler/OpenTelemetryGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/handler/OpenTelemetryPluginCommonHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/span/OpenTelemetrySpanManager.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/resources/META-INF/shenyu/org.apache.shenyu.agent.api.spi.AgentPluginBootService, shenyu-dist/shenyu-agent-dist/pom.xml, shenyu-dist/shenyu-agent-dist/src/main/resources/conf/shenyu-agent.yaml, shenyu-dist/shenyu-agent-dist/src/main/resources/conf/tracing-point.yaml
=> [type: feature] Add tracing-opentelemetry plugin in shenyu-agent

shenyu-integrated-test/shenyu-integrated-test-http/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/SpringMvcMappingPathControllerTest.java
=> [ISSUE #2679] Add integration test for SpringMvcMappingPathController

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/ShenyuClientPathController.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/RequestControllerTest.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/ShenyuClientPathControllerTest.java
Add integration test for RequestControllerTest
Add integration test for ShenyuClientPathControllerTest
Add @ShenyuSpringMvcClient to ShenyuClientPathController
=> [ISSUE #2679] Add integration test for RequestControllerTest

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractContextPathRegisterService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/PathUtils.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/AdminConstants.java
=> [type: bug] fix shenyu client config isFull is true

shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/span/OpenTelemetrySpanManager.java
=> [type: refactor]change span kind to internal

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResult.java
=> [type: refactor] optimize content-type.

shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Publish.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Subscribe.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Unsubscribe.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/repositories/SubscribeRepository.java
=> [ISSUE #2071] feat subscribe & unsubscribe

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/page/PageParameter.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/page/PageResultUtils.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DataPermissionServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/AesUtils.java
=> [type:refactor] modify null judgment

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java, shenyu-admin/src/main/resources/application.yml
wait for @daiwenyu front side support
=> [type: refactor] optimize user edit logic.

shenyu-examples/shenyu-examples-eureka/pom.xml, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCacheManager.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTask.java, shenyu-web/pom.xml
=> [type: refactor] reconstruct some code

shenyu-common/src/main/java/org/apache/shenyu/common/constant/HttpConstants.java, shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java, shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/config/HttpConfig.java, shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/config/HttpConfigTest.java
=> [type:feature]Http sync, add property.

shenyu-plugin/shenyu-plugin-websocket/src/main/java/org/apache/shenyu/plugin/websocket/WebSocketPlugin.java
=> [type: refactor] support websocket query parameters.

shenyu-examples/shenyu-examples-http/src/main/http/http-test-api-local.http, shenyu-examples/shenyu-examples-http/src/main/http/http-test-api.http, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/HttpTestControllerTest.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/RequestQueryCodecUtil.java, shenyu-plugin/shenyu-plugin-uri/src/main/java/org/apache/shenyu/plugin/uri/URIPlugin.java, shenyu-plugin/shenyu-plugin-uri/src/test/java/org/apache/shenyu/plugin/uri/URIPluginTest.java
fix `status=[abc%2Cedf]`query  `Invalid character '[' for QUERY_PARAM in status=[abc%2Cedf]` bug
=> [type: refactor] optimize & fix uri with invalid char.

shenyu-integrated-test/README.md
#2727 
Change the README.md file under shenyu-integrated-text folder according to https://shenyu.apache.org/zh/community/integration-test.
=> [Task #2727] edit README.md file under shenyu-integrated-text folder

shenyu-plugin/shenyu-plugin-websocket/src/main/java/org/apache/shenyu/plugin/websocket/WebSocketPlugin.java
=> [type: refactor] support websocket query codec.

shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/IdArrayAndNameRequest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/IdsAndNameRequest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/ListResp.java, shenyu-integrated-test/shenyu-integration-test-alibaba-dubbo/src/test/java/org/apache/shenyu/integratedtest/alibaba/dubbo/AlibabaDubboPluginTest.java, shenyu-integrated-test/shenyu-integration-test-apache-dubbo/src/test/java/org/apache/shenyu/integratedtest/alibaba/dubbo/ApacheDubboPluginTest.java
#2680
1. add integrated test for DubboTestService in shenyu-examples-apache-dubbo-service
2. add integrated test for DubboTestService in shenyu-examples-alibaba-dubbo-service
=> [Task #2680] Add integration test for more dubbo api DubboTestService

shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtPluginDataHandler.java, shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtendsShenyuBerBean.java, shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtendsShenyuPlugin.java, shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtendsShenyuZerBean.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/SpringBeanUtils.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfiguration.java, shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuLoaderService.java, shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java
ext plugins register spring bean.
=> [type:feature] ext plugins register spring bean.

shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/pom.xml, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/pom.xml, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/pom.xml
=> [type: refactor] shade some dependencies in agent to solve conflict

shenyu-admin/src/test/java/org/apache/shenyu/admin/utils/PathUtilsTest.java
=> [type:test] add pathUtils test

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResult.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/WebFluxResultUtils.java
=> [type: refactor] optimize upstream result data processing.

shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java, shenyu-spi/src/test/java/org/apache/shenyu/spi/ExtensionLoaderTest.java
=> Optimization prompt of ExtensionLoader

shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtPluginDataHandler.java, shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java
Exclude  ShenyuPlugin subclass and PluginDataHandler subclass without adding @Component or @Service annotation
=> [type:fix]  Exclude major classes adding @Component or @Service annotation

shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-admin/src/main/resources/sql-script/mysql/schema.sql, shenyu-admin/src/main/resources/sql-script/pg/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java, shenyu-plugin/pom.xml, shenyu-plugin/shenyu-plugin-mqtt/pom.xml, shenyu-plugin/shenyu-plugin-mqtt/src/main/java/org/apache/shenyu/plugin/mqtt/handler/MqttPluginDataHandler.java, shenyu-plugin/shenyu-plugin-mqtt/src/test/java/org/apache/shenyu/plugin/mqtt/handler/MqttPluginDataHandlerTest.java, shenyu-protocol/shenyu-protocol-mqtt/pom.xml, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Connect.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttBootstrapServer.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttContext.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttServerConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/pom.xml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-mqtt/pom.xml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-mqtt/src/main/java/org/apache/shenyu/springboot/starter/plugin/mqtt/MqttPluginConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-mqtt/src/main/resources/META-INF/spring.factories, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-mqtt/src/test/java/org/apache/shenyu/springboot/starter/plugin/mqtt/MqttPluginConfigurationTest.java
=> [ISSUE #2071] add mqtt plugin

shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java
=> [type: refactor] optimize global error handler for flexible processing.

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketCollector.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/WebsocketSyncDataService.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/client/ShenyuWebsocketClient.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/test/java/org/apache/shenyu/plugin/sync/data/websocket/client/ShenyuWebsocketClientTest.java
Re-subscribe data after adjusting webSocket to reconnect.
=> [type:fix] Re-subscribe data after adjusting webSocket to reconnect.

RELEASE-NOTES.md
UPDATE RELEASE-NOTES.md for 2.4.2
=> [RELEASE 2.4.2]UPDATE RELEASE-NOTES.md for 2.4.2

.github/workflows/integrated-test-agent-tracing.yml, .github/workflows/integrated-test.yml, pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml, shenyu-examples/shenyu-examples-eureka/pom.xml, shenyu-examples/shenyu-examples-grpc/pom.xml, shenyu-examples/shenyu-examples-http/pom.xml, shenyu-examples/shenyu-examples-https/pom.xml, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/pom.xml, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/pom.xml, shenyu-examples/shenyu-examples-springcloud/pom.xml, shenyu-examples/shenyu-examples-springmvc/pom.xml, shenyu-examples/shenyu-examples-websocket/pom.xml
=> [type: refactor] Remove example moudle from shenyu

.licenserc.yaml, LICENSE, pom.xml, script/shenyu_checkstyle.xml, shenyu-common/src/main/java/org/apache/shenyu/common/timer/HashedWheelTimer.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/Timeout.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/Timer.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/TimerTask.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/WheelTimerFactory.java
=> [type:feature]add wheel timer.

shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/shutdown/ShenyuClientShutdownHook.java, shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcClientBeanPostProcessor.java, shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcContextRefreshedEventListener.java, shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonServerServiceInterceptor.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessorTest.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java, shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceBeanPostProcessor.java, shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsContextRefreshedEventListener.java, shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/ReflectUtilsTest.java, shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtPluginDataHandler.java, shenyu-examples/shenyu-examples-plugin/src/main/java/org/apache/shenyu/examples/plugin/ext/ExtendsShenyuZerBean.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/entity/Upstream.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java, shenyu-metrics/shenyu-metrics-prometheus/src/main/java/org/apache/shenyu/metrics/prometheus/service/PrometheusBootService.java, shenyu-metrics/shenyu-metrics-prometheus/src/test/java/org/apache/shenyu/metrics/prometheus/service/PrometheusBootServiceTest.java, shenyu-protocol/shenyu-protocol-grpc/src/main/java/org/apache/shenyu/protocol/grpc/message/JsonMessage.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/test/java/org/apache/shenyu/register/client/http/RegisterUtilsTest.java, shenyu-web/src/test/java/org/apache/shenyu/web/controller/TestObjectProvider.java, shenyu-web/src/test/java/org/apache/shenyu/web/handler/ShenyuWebHandlerTest.java
=> [optimize] Make field final

shenyu-common/src/main/java/org/apache/shenyu/common/timer/HierarchicalWheelTimer.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/TaskEntity.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/TimerTask.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/TimerTaskList.java, shenyu-common/src/test/java/org/apache/shenyu/common/timer/HierarchicalWheelTimerTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-api/src/main/java/org/apache/shenyu/register/client/api/FailbackRegistryRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-api/src/main/java/org/apache/shenyu/register/client/api/retry/AbstractRetryTask.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-api/src/main/java/org/apache/shenyu/register/client/api/retry/FailureRegistryTask.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java, shenyu-register-center/shenyu-register-common/pom.xml
1.Add http register client retry.
=> [type:feature]Add http register client retry.

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/FallbackShenyuClientRegisterService.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/AbstractRetryTask.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/AbstractRoundTask.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/WebsocketSyncDataService.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/client/ShenyuWebsocketClient.java
…ass.
Use Wheel-Timer to replace part of the ScheduledExecutorService class.
=> [type:fix] Used Wheel-Timer instead of ScheduledExecutorService class.

shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/CommonUpstreamUtils.java
…st  NullPointer]
// refactor fix init CommonUpstreamUtils . Fixes #2795 
=> [ISSUE #2795 refactor  fix init CommonUpstreamUtils NullPointer]

shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh, shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-h2/docker-compose.yaml, shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-mysql/docker-compose.yaml, shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-pg/docker-compose.yaml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
=> add docker-compose agent

shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/provider/DisruptorProvider.java
Fixes #2803 
delete method of DisruptorProvider#onData(final Consumer<DataEvent> function).
this method not called in anywhere.
=> remove DisruptorProvider#onData(final Consumer<DataEvent> function)

shenyu-admin/src/main/java/org/apache/shenyu/admin/transfer/DashboardUserTransfer.java, shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/transfer/ShenyuServiceTransfer.java
fix https://github.com/apache/incubator-shenyu/issues/2810
=> [ISSUE #2810] fix NPE

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java, shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml, shenyu-integrated-test/shenyu-integrated-test-combination/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/MultiRequestPluginTest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/ModifyResponseDTO.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java
link #2365
test combination of Param mapping and Rewrite plugin. 
test combination of Param mapping and Redirect plugin.
test combination of RateLimiter and Rewrite plugin.
test combination of RateLimiter and Redirect plugin.
test combination of Request and Redirect plugin.
test combination of Request and Rewrite plugin.
test combination of JWT and RateLimiter plugin.
test combination of JWT and Redirect plugin.
test combination of JWT and Rewrite plugin.
=> feature(Integrated-Test): combination integrated test for Request Plugins

.github/workflows/integrated-test-agent-tracing.yml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/pom.xml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/script/healthcheck.sh, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/script/services.list, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/main/assembly/binary.xml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/main/java/org/apache/shenyu/integrated/test/agent/zipkin/ZipkinIntegratedBootstrap.java, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/main/resources/bin/start.sh, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/main/resources/bin/stop.sh, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/main/resources/conf/logback.xml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/main/resources/conf/shenyu-agent.yaml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/main/resources/conf/tracing-point.yaml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/test/java/org/apache/shenyu/integrated/test/agent/zipkin/ZipkinPluginTest.java, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-zipkin/src/test/java/org/apache/shenyu/integrated/test/agent/zipkin/result/ZipkinSpan.java
=> feature(integrated-test): add integrated test for tracing-zipkin moudle in agent

.github/workflows/integrated-test-agent-tracing.yml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/pom.xml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/pom.xml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/script/healthcheck.sh, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/script/services.list, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/main/assembly/binary.xml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/main/java/org/apache/shenyu/integrated/test/agent/jaeger/JaegerIntegratedBootstrap.java, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/main/resources/bin/start.sh, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/main/resources/bin/stop.sh, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/main/resources/conf/logback.xml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/main/resources/conf/shenyu-agent.yaml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/main/resources/conf/tracing-point.yaml, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/test/java/org/apache/shenyu/integrated/test/agent/jaeger/JaegerPluginTest.java, shenyu-integrated-test/shenyu-integrated-test-agent/shenyu-integrated-test-agent-tracing/shenyu-integrated-test-agent-tracing-jaeger/src/test/java/org/apache/shenyu/integrated/test/agent/jaeger/result/JaegerSpan.java
link #2699
add integrated test for agent plugin witch is tracing-jaeger module
=> feature(integrated-test): add integrated test for tracing-jaeger plugin

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/helper/HttpHelper.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/HttpTestControllerTest.java
link #2679
1. add upload and download file api in examples-http
2. add simple integrated-test for upload/download file in integrated-test-http
=> feature(integrated-test): add upload and download file in examples-http

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java, shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java
=> [type: refactor] correct param name

shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java, shenyu-examples/shenyu-examples-tars/pom.xml, shenyu-examples/shenyu-examples-tars/src/main/java/org/apache/shenyu/examples/tars/aop/Log.java, shenyu-examples/shenyu-examples-tars/src/main/java/org/apache/shenyu/examples/tars/aop/LogInterceptor.java, shenyu-examples/shenyu-examples-tars/src/main/java/org/apache/shenyu/examples/tars/servant/testapp/impl/HelloServantImpl.java
see https://github.com/apache/incubator-shenyu/issues/2833
Tests code here : `org.apache.shenyu.examples.tars.servant.testapp.impl.HelloServantImpl#helloInt`.
=> [ISSUE #2833] fix TarsServiceBeanPostProcessor when client use AOP

shenyu-bootstrap/src/main/resources/application.yml
=> [#2846]Update application.yml to fix

shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
=> [type: refactor] support octet-stream context-type.

pom.xml, shenyu-agent/shenyu-agent-core/src/test/java/org/apache/shenyu/agent/core/ShenyuYamlEngineTest.java, shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/test/java/org/apache/shenyu/client/alibaba/dubbo/validation/AlibabaDubboClientValidatorTest.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/test/java/org/apache/shenyu/client/apache/dubbo/validation/ApacheDubboClientValidationTest.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/test/java/org/apache/shenyu/client/apache/dubbo/validation/ApacheDubboClientValidatorTest.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessorTest.java, shenyu-client/shenyu-client-tars/src/test/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessorTest.java, shenyu-common/pom.xml, shenyu-common/src/test/java/org/apache/shenyu/common/utils/UpstreamCheckUtilsTest.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/factory/LoadBalancerFactoryTest.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/HashLoadBalanceTest.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/RandomLoadBalanceTest.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalanceTest.java
About #2830 , migrate from junit 4 to 5 for client, agent and loadbalancer modules.
=> [ISSUE 2830] migrate from junit 4 to 5 for client, agent and loadbalancer modules

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/RegisterCenterConfiguration.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuHttpRegistryController.java, shenyu-dist/shenyu-admin-dist/src/main/resources/bin/start.sh, shenyu-dist/shenyu-admin-dist/src/main/resources/bin/stop.sh, shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh, shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/stop.sh
=> fix: shell error

shenyu-metrics/shenyu-metrics-prometheus/src/test/java/org/apache/shenyu/metrics/prometheus/collector/BuildInfoCollectorTest.java, shenyu-metrics/shenyu-metrics-prometheus/src/test/java/org/apache/shenyu/metrics/prometheus/register/PrometheusMetricsRegisterTest.java, shenyu-metrics/shenyu-metrics-prometheus/src/test/java/org/apache/shenyu/metrics/prometheus/service/PrometheusBootServiceTest.java, shenyu-metrics/shenyu-metrics-spi/src/test/java/org/apache/shenyu/metrics/config/JmxConfigTest.java, shenyu-metrics/shenyu-metrics-spi/src/test/java/org/apache/shenyu/metrics/config/MetricsConfigTest.java, shenyu-metrics/shenyu-metrics-spi/src/test/java/org/apache/shenyu/metrics/enums/MetricsTypeEnumTest.java, shenyu-metrics/shenyu-metrics-spi/src/test/java/org/apache/shenyu/metrics/reporter/MetricsReporterTest.java
=> upgrade unit test framework of shenyu-metrics from JUnit4 toJUnit5

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java, shenyu-examples/shenyu-examples-springcloud/src/main/resources/application.yml
you can run `org.apache.shenyu.examples.springcloud.ShenyuTestSpringCloudApplication` to see result directly.
=> [ISSUE #2860] spring cloud client auto set port

shenyu-examples/shenyu-examples-http/src/main/http/http-test-api.http, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/ShenyuClientPathController.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
1.  run `org.apache.shenyu.admin.ShenyuAdminBootstrap`;
2.  run `org.apache.shenyu.bootstrap.ShenyuBootstrapApplication`;
3.  run `org.apache.shenyu.examples.http.ShenyuTestHttpApplication`;
4.  then send request:
```text
POST http://localhost:9195/http/shenyu/client/timeout
Accept: application/json
Content-Type: application/json
```
watch `org.apache.shenyu.examples.http.controller.ShenyuClientPathController#timeout`, you can see the result is correct.
=> [ISSUE #2847] fix retryCount not work bug

shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/interceptor/StaticMethodInterceptor.java, shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/matcher/ShenyuAgentTypeMatcher.java, shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/locator/ShenyuAgentLocator.java, shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/utils/ShenyuAgentConfigUtils.java
=> [type: refactor] fix agent NPE and log error

shenyu-admin/src/main/resources/logback.xml, shenyu-bootstrap/src/main/resources/logback.xml, shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh, shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh
=> [ISSUE #2831] fix double log

shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java
=> [type:fix] fix token pasrse error

shenyu-examples/pom.xml, shenyu-examples/shenyu-examples-springmvc-tomcat/pom.xml, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/http/http-test-api-local.http, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/http/http-test-api.http, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/java/org/apache/shenyu/examples/springmvc/controller/HttpTestController.java, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/java/org/apache/shenyu/examples/springmvc/controller/OrderController.java, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/java/org/apache/shenyu/examples/springmvc/dto/OAuth2DTO.java, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/java/org/apache/shenyu/examples/springmvc/dto/OrderDTO.java, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/java/org/apache/shenyu/examples/springmvc/dto/UserDTO.java, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/java/org/apache/shenyu/examples/springmvc/result/ResultBean.java, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/resources/application.properties, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/resources/context/shenyu.xml, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/resources/spring-mvc.xml, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/webapp/WEB-INF/web.xml
see https://github.com/apache/incubator-shenyu/issues/2884 and https://github.com/apache/incubator-shenyu/pull/2875
=> [ISSUE #2884] add shenyu-examples-springmvc-tomcat

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SelectorServiceTest.java
=> [ISSUE #2878] fix UpstreamCheckService failed to remove the invalid upstream added in web

shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/api/handler/InstanceMethodHandler.java, shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/interceptor/InstanceMethodInterceptor.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-logging/shenyu-agent-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/agent/plugin/logging/rocketmq/handler/RocketMQGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/plugin/tracing/jaeger/handler/JaegerGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/plugin/tracing/jaeger/handler/JaegerPluginCommonHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/handler/OpenTelemetryGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/handler/OpenTelemetryPluginCommonHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/src/main/java/org/apache/shenyu/agent/plugin/tracing/zipkin/handler/ZipkinGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/src/main/java/org/apache/shenyu/agent/plugin/tracing/zipkin/handler/ZipkinPluginCommonHandler.java
=> Refactor InstanceMethodHandler in agent

shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-metrics/shenyu-agent-plugin-metrics-common/src/main/java/org/apache/shenyu/agent/plugin/metrics/common/definition/MetricsAgentPluginDefinition.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-metrics/shenyu-agent-plugin-metrics-common/src/main/java/org/apache/shenyu/agent/plugin/metrics/common/factory/MetricsRecorderPool.java
=> [refactor: metrics] fix agent metrics init bug

shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-common/src/main/java/org/apache/shenyu/agent/plugin/tracing/common/constant/TracingConstants.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/plugin/tracing/jaeger/handler/JaegerGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/handler/OpenTelemetryGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/src/main/java/org/apache/shenyu/agent/plugin/tracing/zipkin/handler/ZipkinGlobalPluginHandler.java
just rename HTTP_STATUS TO HTTP_METHOD
=>  [BUG] <shenyu agent zipkin method tag error> #2911 

shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/build/Resilience4JBuilder.java
For #2924 , change to `Duration.ofMiles` to avoid calculate manually.
=> change to Duration.ofMiles to avoid calculate manually

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-springcloud/src/main/java/org/apache/shenyu/springboot/starter/plugin/springcloud/SpringCloudPluginConfiguration.java
see https://github.com/apache/incubator-shenyu/issues/2916.
You can follow these steps to verify whether the results are correct :
1. run `ShenyuAdminBootstrap`;
2. turn on `SpringCloudPlugin` in `shenyu-admin`;
3. run `EurekaServerApplication`;
4. run `ShenyuTestSpringCloudApplication`;
5. enable `Ribbon` then run `ShenyuBootstrapApplication`;
6. run `spring-cloud-test-api.http`.
=> [type:refactor][ISSUE #2916]change ribbon default ServerListRefreshInterval from 30s to 10s

script/2.4.2-upgrade-2.4.3-mysql.sql, script/2.4.2-upgrade-2.4.3-pg.sql
// Describe your PR here; eg. Fixes #2928 
add update mysql.sql and pg.sql
=> [ISSUE #1888] Add database upgrade script

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuHttpRegistryController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/RegisterServerDisruptorPublisher.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/executor/RegisterServerConsumerExecutor.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/transfer/DashboardUserTransfer.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/ShenyuClientRegisterEventPublisher.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/executor/RegisterClientConsumerExecutor.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientURIExecutorSubscriber.java, shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/AbstractRetryTask.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/AbstractRoundTask.java, shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/DisruptorProviderManage.java, shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/event/OrderlyDisruptorEventFactory.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/utils/RegisterUtils.java, shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/subsriber/AbstractQueueConsumerFactory.java, shenyu-register-center/shenyu-register-server/shenyu-register-server-api/src/main/java/org/apache/shenyu/register/server/api/ShenyuServerRegisterPublisher.java, shenyu-register-center/shenyu-register-server/shenyu-register-server-consul/src/test/java/org/apache/shenyu/register/server/consul/ConsulServerRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-server/shenyu-register-server-etcd/src/test/java/org/apache/shenyu/register/server/etcd/EtcdServerRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-server/shenyu-register-server-nacos/src/test/java/org/apache/shenyu/register/server/nacos/NacosServerRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-server/shenyu-register-server-zookeeper/src/test/java/org/apache/shenyu/register/server/zookeeper/ZookeeperServerRegisterRepositoryTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-alibaba-dubbo/src/test/java/org/apache/shenyu/springboot/starter/client/alibaba/dubbo/ShenyuAlibabaDubboClientConfigurationTest.java, shenyu-sync-data-center/shenyu-sync-data-consul/src/main/java/org/apache/shenyu/sync/data/consul/ConsulSyncDataService.java
=> [type: refactor] fix generics

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java, shenyu-integrated-test/shenyu-integrated-test-http/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/Resilience4JPluginTest.java
For #2910 , added below tests
- testRateLimiterPass, testRateLimiter
- testCircuitBreaker, testCircuitBreakerFallbackUri
Besides that, also added some APIs in `http-example` module for testing.
=> [ISSUE #2910] Add integrated test for Resilience4j plugin

shenyu-admin/src/main/resources/sql-script/pg/schema.sql
=> [ISSUE #2947] Fix pg schema.sql .

shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginMapperTest.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/factory/LoadBalancerFactory.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/AbstractLoadBalancer.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/HashLoadBalancer.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/LoadBalancer.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RandomLoadBalancer.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalancer.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/factory/LoadBalancerFactoryTest.java
=> [Task #2945] Optimize some code style for shenyu-loadbalance plugin

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/AbstractDataChangedListener.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DataPermissionMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SyncDataServiceImpl.java, shenyu-admin/src/main/resources/mappers/data-permission-sqlmap.xml
=> [Type:Refactor] optimize some code in admin

shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java
=> [Type:Refactor] Refactor code

shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh
=> [type:fix] fix install.sh

shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-common/src/main/java/org/apache/shenyu/agent/plugin/tracing/common/constant/TracingConstants.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/plugin/tracing/jaeger/handler/JaegerGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/plugin/tracing/jaeger/handler/JaegerPluginCommonHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/plugin/tracing/jaeger/span/JaegerSpanManager.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/handler/OpenTelemetryGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/handler/OpenTelemetryPluginCommonHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-opentelemetry/src/main/java/org/apache/shenyu/agent/plugin/tracing/opentelemetry/span/OpenTelemetrySpanManager.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/src/main/java/org/apache/shenyu/agent/plugin/tracing/zipkin/handler/ZipkinGlobalPluginHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/src/main/java/org/apache/shenyu/agent/plugin/tracing/zipkin/handler/ZipkinPluginCommonHandler.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/src/main/java/org/apache/shenyu/agent/plugin/tracing/zipkin/span/ZipkinSpanManager.java
update SHENYU_AGENT in exchange to distinguish between different plugins.
=> [type:refactor] feature shenyu-agent : update SHENYU_AGENT in exchange.

shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCache.java
see https://github.com/apache/incubator-shenyu/issues/2940, this is `alibaba dubbo` part.
=> [ISSUE #2940] alibaba dubbo part

script/2.4.2-upgrade-2.4.3-mysql.sql, script/2.4.2-upgrade-2.4.3-pg.sql, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/ShaUtils.java, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-admin/src/main/resources/sql-script/mysql/schema.sql, shenyu-admin/src/main/resources/sql-script/pg/schema.sql, shenyu-admin/src/test/java/org/apache/shenyu/admin/utils/ShaUtilsTest.java
=> [ISSUE #1888]Fix the encryption tool class

shenyu-bootstrap/src/main/resources/application.yml, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/config/HttpClientProperties.java
=> [type: refactor] add http client in yaml

shenyu-bootstrap/src/main/resources/application.yml, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/NettyHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
see https://github.com/apache/incubator-shenyu/issues/2627 and https://github.com/apache/incubator-shenyu/pull/2939, how to test ?
1. run `ShenyuAdminBootstrap`;
2. run `ShenyuTestHttpApplication`;
3. set `shenyu.httpclient.strategy` to `netty` or don't set, then run `ShenyuBootstrapApplication`;
4. send request
```http
POST http://localhost:9195/http/shenyu/client/hello
Accept: application/json
Content-Type: application/json
```
finally, you can see the correct result.
=> [ISSUE #2627] [type:refactor] refactor httpclient plugin

shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-metrics/shenyu-agent-plugin-metrics-prometheus/src/main/java/org/apache/shenyu/agent/plugin/metrics/prometheus/handler/PrometheusGlobalPluginHandler.java
=> [type: modify]: modify shenyu_request_undone metrics' access.

shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-metrics/shenyu-agent-plugin-metrics-prometheus/src/main/java/org/apache/shenyu/agent/plugin/metrics/prometheus/boot/PrometheusPluginBootService.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-metrics/shenyu-agent-plugin-metrics-prometheus/src/main/java/org/apache/shenyu/agent/plugin/metrics/prometheus/collector/BuildInfoCollector.java
=> [type: bug] fix metrics build info bug

shenyu-plugin/shenyu-plugin-cryptor/pom.xml
=> [type: refactor] fix metrics pom

shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/entity/Upstream.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/RequestUrlUtils.java, shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java, shenyu-plugin/shenyu-plugin-uri/src/main/java/org/apache/shenyu/plugin/uri/URIPlugin.java
1.move `buildDomain` from `DividePlugin` to `Upstream`;
2.refactor  some code in `URIPlugin`.
=> [ISSUE #2627] [type:refactor] part 2

shenyu-admin/src/http/http-debug-dashboard-user-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/exception/ExceptionHandlers.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/exception/ValidFailException.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DashboardUserMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/Assert.java, shenyu-admin/src/main/resources/mappers/dashboard-user-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/DashboardUserControllerTest.java
=> [ISSUE:#2956]valid user dashboard api param

shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttFactory.java
=> [refector]code polish 4 mqtt

shenyu-admin/src/http/http-debug-data-permission-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ConfigController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DataPermissionController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/DataPermissionDTO.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/DataPermissionControllerTest.java
about issue #2956
work list:
proposal: delete about DataPermissionController.java API, may be is never used
=> [ISSUE #2956]valid data permission api paramater

script/2.4.2-upgrade-2.4.3-mysql.sql, script/2.4.2-upgrade-2.4.3-pg.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-admin/src/main/resources/sql-script/mysql/schema.sql, shenyu-admin/src/main/resources/sql-script/pg/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/DivideRuleHandle.java, shenyu-common/src/main/java/org/apache/shenyu/common/enums/RetryEnum.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultEnum.java, shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java, shenyu-plugin/shenyu-plugin-httpclient/pom.xml, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/NettyHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
see https://github.com/apache/incubator-shenyu/issues/2627, you can test by these steps:
1. run `ShenyuAdminBootstrap`;
2. run `ShenyuTestHttpApplication`;
3. visit `http://localhost:9095` and change retry strategy to `failover`;
4. run `ShenyuBootstrapApplication`;
5. send post request
```http
POST http://localhost:9195/http/shenyu/client/timeout
Accept: application/json
Content-Type: application/json
```
then you can see the correct result.
=> [ISSUE #2627] [type:new feature] DividePlugin support failover retry

shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/command/Command.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/command/HystrixCommand.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/command/HystrixCommandOnThread.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/handler/HystrixPluginDataHandler.java
Resolve hystrix plugin configuration rules do not take effect
=> [ISSUE #2931]Resolve hystrix plugin configuration rules do not take effect

shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-websocket/src/main/java/org/apache/shenyu/springboot/plugin/websocket/WebSocketPluginConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-websocket/src/test/java/org/apache/shenyu/springboot/plugin/websocket/WebSocketPluginConfigurationTest.java
support WebSocket client max frame payload length configuration.
=> [type: refactor] support websocket client configuration

shenyu-admin/src/http/http-debug-meta-data-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/MetaDataController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/exception/ExceptionHandlers.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/MetaDataMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/BatchCommonDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/MetaDataDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/provider/MetaDataPathProvider.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/validation/annotation/Existed.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/validation/validator/ExistedValidator.java, shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/MetaDataControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/MetaDataServiceTest.java
=> [ISSUE #2956]valid meta data api paramater

shenyu-admin/src/http/http-debug-platform-controller-api.http, shenyu-admin/src/http/http-debug-plugin-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/provider/PluginNameProvider.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/validation/annotation/Existed.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/validation/validator/ExistedValidator.java, shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/MetaDataControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/PluginControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginServiceTest.java
=> [ISSUE #2956] valid plugin api paramater

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/RuleConditionDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/SelectorConditionDO.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/RegexPredicateJudge.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/TimerAfterPredicateJudge.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/TimerBeforePredicateJudge.java
=> [type: refactor] trim condition param value.

shenyu-admin/src/http/http-debug-plugin-handle-controller-api.http, shenyu-admin/src/http/http-debug-resource-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginHandleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ResourceController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginHandleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ResourceMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginHandleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/ResourceDTO.java, shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml, shenyu-admin/src/main/resources/mappers/resouce-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/PluginHandleControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ResourceControllerTest.java
=> [ISSUE #2956]plugin-handle and resource api paramater

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/MetaDataController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/MetaDataMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/MetaDataDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/MetaDataService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/PluginService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/Assert.java, shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml, shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/MetaDataControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/PluginControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/MetaDataServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginServiceTest.java
about issue:  #3042
work list:
=> [ISSUE #3042] fix bug plugin metadata valid error

shenyu-admin/src/http/http-debug-role-controller-api.http, shenyu-admin/src/http/http-debug-rule-controller-api.http, shenyu-admin/src/http/http-debug-selector-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RoleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RuleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/SelectorController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RoleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/RoleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/RuleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/SelectorDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/main/resources/mappers/role-sqlmap.xml, shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml, shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/RoleControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/RuleControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/SelectorControllerTest.java
=> [ISSUE ##2956]valid role rule selector api

shenyu-agent/shenyu-agent-api/src/main/java/org/apache/shenyu/agent/api/exception/ShenyuAgentException.java, shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/bytebuddy/transformer/ShenyuAgentTransformer.java, shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/loader/ShenyuAgentPluginLoader.java, shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/locator/ShenyuAgentLocator.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-metrics/shenyu-agent-plugin-metrics-api/src/main/java/org/apache/shenyu/agent/plugin/metrics/api/MetricsRecorder.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-metrics/shenyu-agent-plugin-metrics-prometheus/src/main/java/org/apache/shenyu/agent/plugin/metrics/prometheus/collector/BuildInfoCollector.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/plugin/tracing/jaeger/boot/JaegerAgentPluginBootService.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-jaeger/src/main/java/org/apache/shenyu/agent/plugin/tracing/jaeger/span/JaegerErrorSpan.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/src/main/java/org/apache/shenyu/agent/plugin/tracing/zipkin/boot/ZipkinAgentPluginBootService.java, shenyu-agent/shenyu-agent-plugins/shenyu-agent-plugin-tracing/shenyu-agent-plugin-tracing-zipkin/src/main/java/org/apache/shenyu/agent/plugin/tracing/zipkin/enums/SamplerTypeEnum.java, shenyu-dist/shenyu-agent-dist/src/main/resources/conf/shenyu-agent.yaml
=> [type: refactor] refactor agent code

shenyu-agent/shenyu-agent-core/src/main/java/org/apache/shenyu/agent/core/loader/ShenyuAgentPluginLoader.java, shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java
=> [type: refactor]: remove ByteArrayOutputStream.

shenyu-admin/src/http/http-debug-dict-controller-api.http, shenyu-admin/src/http/http-debug-registry-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RuleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuDictController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ShenyuDictMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/MetaDataDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/ShenyuDictDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ShenyuDictServiceImpl.java, shenyu-admin/src/main/resources/mappers/shenyu-dict-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ShenyuDictControllerTest.java
=> [ISSUE #2956]valid shenyu dict api

shenyu-bootstrap/src/main/resources/application.yml, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/config/HttpClientProperties.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
=> [ISSUE #3063] fix bug

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedListener.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/nacos/NacosDataInit.java
=> [ISSUE #2879]Fix bug, data syn with nacos.

shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh, shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-h2/docker-compose.yaml, shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-mysql/docker-compose.yaml, shenyu-dist/shenyu-docker-compose-dist/src/main/resources/stand-alone-pg/docker-compose.yaml
=> [type: refactor]remove agent

shenyu-bootstrap/src/main/resources/application-nacos.yml, shenyu-examples/shenyu-examples-springcloud/src/main/resources/application-nacos.yml
=> [ISSUE #3082] Fix Nacos namespace config

shenyu-bootstrap/pom.xml, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/config/HttpClientProperties.java, shenyu-plugin/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/AbstractLogCollector.java, shenyu-plugin/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/LogConsumeClient.java, shenyu-plugin/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/body/BodyWriter.java, shenyu-plugin/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/body/LoggingServerHttpRequest.java, shenyu-plugin/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/constant/LoggingConstant.java, shenyu-plugin/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/rocketmq/RocketMQLogCollectClient.java, shenyu-plugin/shenyu-plugin-metrics/src/main/java/org/apache/shenyu/plugin/metrics/constant/LabelNames.java, shenyu-plugin/shenyu-plugin-metrics/src/main/java/org/apache/shenyu/plugin/metrics/prometheus/PrometheusMetricsService.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-metrics/src/main/java/org/apache/shenyu/springboot/starter/plugin/metrics/boot/MetricsRunner.java
=> [type: refactor] Minor code optimizations

shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml
Hi Community:
This PR is to format the current SQL, following the principle of left-aligning keywords (Uppercase) and right-aligning fields. I would like to make this task a `good first issue` so that new comers can get involved in handling the rest of the SQL file. Do you think it's a good idea?
=> [type:refactor] format SQL

shenyu-admin/src/main/resources/logback.xml, shenyu-bootstrap/src/main/resources/logback.xml
=> [Type:refactor]change logback theme

shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
optimize webclient message writer to cancel business response override. like `NettyClientMessageWriter`
=> [type:refactor] optimize webclient message writer to cancel business response override.

shenyu-admin/src/main/resources/mappers/auth-param-sqlmap.xml
format auth-param-sqlmap.xml #3088
=> [type:refactor #3088]format auth-param-sqlmap.xml 

shenyu-admin/src/main/resources/mappers/selector-condition-sqlmap.xml
[type:refactor #3088]format selector-condition-sqlmap.xml
=> format selector-condition-sqlmap.xml #3088

shenyu-admin/src/main/resources/mappers/permission-sqlmap.xml
fix  format permission-sqlmap.xml [#3088 ]
=> refactor admin : format SQL. (#3088)

shenyu-admin/src/main/resources/mappers/resouce-sqlmap.xml
format resouce-sqlmap.xml SQL (#3088)
=> resouce-sqlmap.xml: format SQL  (#3088)

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/custom/UserInfo.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/FallbackShenyuClientRegisterService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/SQLInitUtils.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/ShenyuResultMessage.java, shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml
=> [type:refactor] code polish for shenyu-admin

shenyu-admin/src/main/resources/mappers/rule-condition-sqlmap.xml
=> [refactor #3088] format rule-condition-sqlmap.xml

shenyu-admin/src/main/resources/mappers/role-sqlmap.xml
=> [type:refactor #3088]format role-sqlmap.xml

shenyu-admin/src/main/resources/mappers/shenyu-dict-sqlmap.xml
format shenyu-dict-sqlmap.xml https://github.com/apache/incubator-shenyu/issues/3088
=> [type:refactor #3088]format shenyu-dict-sqlmap.xml

pom.xml, shenyu-plugin/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/AbstractLogCollector.java
=> Modify the method for determining whether a parameter is null

shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
=> [ISSUE #3088] format SQL

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/AbstractDataChangedInit.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/DataChangedInit.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/consul/ConsulDataChangedInit.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdDataChangedInit.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedInit.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/zookeeper/ZookeeperDataChangedInit.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/config/DataSyncConfigurationTest.java
Optimize code about data init when sync data.
If data synchronization requires data initialization, implement `DataChangedInit`.
=> [type:refactor]optimize code about data init when sync data.

shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-base/src/main/java/org/apache/shenyu/plugin/cache/base/config/CacheConfig.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-base/src/main/java/org/apache/shenyu/plugin/cache/base/handler/CacheHandler.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-base/src/main/java/org/apache/shenyu/plugin/cache/base/utils/CacheUtils.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-read/src/main/java/org/apache/shenyu/plugin/cache/read/CacheReadPlugin.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-redis/src/main/java/org/apache/shenyu/plugin/cache/redis/RedisCache.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-redis/src/main/java/org/apache/shenyu/plugin/cache/redis/RedisConfigProperties.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-write/src/main/java/org/apache/shenyu/plugin/cache/write/CacheWritePlugin.java
=> [type: refactor] refactor cache plugin

shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-admin/src/main/resources/sql-script/mysql/schema.sql, shenyu-admin/src/main/resources/sql-script/pg/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/CacheRuleHandle.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-handler/src/main/java/org/apache/shenyu/plugin/cache/CachePlugin.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-handler/src/main/java/org/apache/shenyu/plugin/cache/handler/CachePluginDataHandler.java
=> Optimize cache plugin

shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/Assert.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/validation/annotation/Existed.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/validation/validator/ExistedValidator.java, shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/json/JsonServerCallListener.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/ReflectUtils.java
about  #3122
- Rename ReflectUtils#invokeMethod to ReflectUtils#invokeMethod;
- Define the constant defaultProviderName in the annotation Existed and replace usages;
=> [ISSUE  #3122]Refactor ReflectUtils and fixed #3122

shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
=> [type: add]: add mockito LICENSE.

shenyu-bootstrap/pom.xml, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/licenses/LICENSE-motan
see #2070, this PR add motan plugin dependency to shenyu-bootstrap.
=> [ISSUE #2070] add motan plugin dependency to shenyu-bootstrap

shenyu-admin/src/main/resources/mappers/dashboard-user-sqlmap.xml
=> format SQL, fix #3088

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/utils/RuntimeUtils.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/utils/SystemUtils.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/test/java/org/apache/shenyu/register/client/http/utils/OkHttpToolsTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/test/java/org/apache/shenyu/register/client/http/utils/RegisterUtilsTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/test/java/org/apache/shenyu/register/client/http/utils/RuntimeUtilsTest.java
=> HTTP registers the client plug-in port occupancy detection

shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/licenses/LICENSE-motan.txt
=> [type: refactor] refactor motan license

shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
=> [type: add]: add rocketmq-client LICENSE.

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/RpcParamTransformPlugin.java
// Describe your PR here; eg. Fixes #3158
=> fix bug of issues-3158

shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-handler/src/main/java/org/apache/shenyu/plugin/cache/config/CacheConfig.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-handler/src/main/java/org/apache/shenyu/plugin/cache/handler/CachePluginDataHandler.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-handler/src/main/java/org/apache/shenyu/plugin/cache/utils/CacheUtils.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-redis/src/main/java/org/apache/shenyu/plugin/cache/redis/RedisCache.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-spi/src/main/java/org/apache/shenyu/plugin/cache/ICache.java
=> [type: refactor] optimize cache-plugin config logic.

shenyu-bootstrap/pom.xml
=> [ISSUE #3169] exclude log4j dependency in motan-registry-zookeeper

script/2.4.1-upgrade-2.4.2-mysql.sql, script/2.4.1-upgrade-2.4.2-pg.sql, script/2.4.2-upgrade-2.4.3-mysql.sql, script/2.4.2-upgrade-2.4.3-pg.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-admin/src/main/resources/sql-script/mysql/schema.sql
=> [ISSUE #3168] SQL Upgrade add id

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/MetaDataController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginHandleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ResourceController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RoleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuDictController.java
=> [ISSUE #3175] admin interface permission

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ResourceController.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ResourceControllerTest.java
=> [ISSUE #3179] resource add button gives an error

shenyu-bootstrap/src/main/resources/application.yml
=> [type: refactor] Add jvm_enabled prop in config yaml of metrics plugin

.github/PULL_REQUEST_TEMPLATE.md
=> docs: fix dead link in pull request template

shenyu-plugin/shenyu-plugin-logging-rocketmq/src/test/java/org/apache/shenyu/plugin/logging/utils/LogCollectConfigUtilsTest.java, shenyu-plugin/shenyu-plugin-logging-rocketmq/src/test/java/org/apache/shenyu/plugin/logging/utils/LogCollectUtilsTest.java
Add unit test for package ：plugin-logging-rocketmq-utils
=> [type: test]: Add unit test for package ：plugin-logging-rocketmq-utils

shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml
[type:refactor #3088] Format meta-data-sqlmap.xml
Format SQL to improve code readability in shenyu-admin. 
Format meta-data-sqlmap.xml
=> [type:refactor #3088] Format meta-data-sqlmap.xml

shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/DefaultShenyuContextBuilder.java
=> [type: refactor] Optimize how to build rpcType

shenyu-admin/src/main/resources/mappers/data-permission-sqlmap.xml
Format SQL to improve code readability in shenyu-admin.
Format data-permission-sqlmap.xml
=> [type: refactor #3088] Format data-permission-sqlmap.xml

shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
=> format SQL

shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/context/GrpcShenyuContextDecorator.java, shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/context/MotanShenyuContextDecorator.java, shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/context/SofaShenyuContextDecorator.java, shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/context/TarsShenyuContextDecorator.java
delete ShenyuContextDecorator duplicate code
=> [type: refactor]delete ShenyuContextDecorator duplicate code

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/utils/RequestQueryCodecUtil.java
**support** 
- ?id=&name=%2f
- ?id&name=%2f
- ?id=123&name=%2f
=> [type: refactor] optimize request query codec.

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/RpcParamTransformPlugin.java
// Describe your PR here; eg. Fixes #issue 3158
=> [ISSUE #3158] support big request body and formdata

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuDictController.java
=> [type: refactor] optimize admin permission.

shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/RequestPlugin.java
=> [BUG #3235]request plugin uri encode

shenyu-admin/src/main/resources/mappers/auth-param-sqlmap.xml, shenyu-admin/src/main/resources/mappers/auth-path-sqlmap.xml, shenyu-admin/src/main/resources/mappers/dashboard-user-sqlmap.xml, shenyu-admin/src/main/resources/mappers/data-permission-sqlmap.xml, shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml, shenyu-admin/src/main/resources/mappers/permission-sqlmap.xml, shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml
=> [type: refactor] refactor shenyu-admin: format SQL to improve code readability.

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/UpstreamCheckServiceTest.java
=> [type: refactor] Optimize admin upstream check

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/MetaDataService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java
Code polish.
* delete redundant `@Transactional`;
* method refactor.
=> [type: refactor]code polish.

shenyu-plugin/shenyu-plugin-websocket/pom.xml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-websocket/src/main/java/org/apache/shenyu/springboot/plugin/websocket/WebSocketPluginConfiguration.java
see https://github.com/apache/incubator-shenyu/issues/3224
=> [ISSUE #3224] reuse HttpClient if available

shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepository.java
=> With nacos, a service can register multiple types of RPC clients

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/SwaggerConfiguration.java
Fix issue #3209 
Swagger add header parameter X-Access-Token.  
=> [ISSUE #3209]Swagger add header parameter X-Access-Token.

shenyu-admin/src/http/http-debug-plugin-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/PluginSnapshotVO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/PluginService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/SyncDataService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
=> [ISSUE #3221]plugin snapshot api

shenyu-common/src/main/java/org/apache/shenyu/common/cache/MemorySafeLRUMap.java, shenyu-common/src/test/java/org/apache/shenyu/common/cache/MemorySafeLRUMapTest.java, shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/cache/MetaDataCache.java
see #3177 , match `metaData` once and only once.
=> [ISSUE #3177] match once and only once

README.md
=> [Doc] Fix the syntax of ShenYu name

shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh
Docker-compose install script supports default version as latest.
=> [type: refactor] Docker-compose install script supports default version as latest

shenyu-admin/src/http/http-debug-plugin-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/page/condition/BaseExcludedSearchCondition.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/page/condition/SearchCondition.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/page/condition/SwitchCondition.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/query/PluginQueryCondition.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/PluginService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
about issue #3258
new plugin page list api
work list:
=> [ISSUE #3258]add plugin page list api

pom.xml, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java, shenyu-proxy/pom.xml, shenyu-proxy/proxy-remote/pom.xml, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/AbstractServer.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/Channel.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/ChannelFuture.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/ChannelHandler.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/Server.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/ServerConfig.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/netty/NettyChannel.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/netty/NettyChannelFuture.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/netty/NettyServer.java, shenyu-proxy/proxy-remote/src/main/java/org/apache/shenyu/proxy/remote/netty/NettyServerHandler.java, shenyu-proxy/proxy-remote/src/test/java/org/apache/shenyu/proxy/remote/NettyServerTest.java
=> Features: new shenyu-proxy, partial implementation of the network layer.

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/NettyHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java
=> [type: refactor] refactor httpclient plugin.

pom.xml, shenyu-bootstrap/pom.xml, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/pom.xml, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml, shenyu-integrated-test/pom.xml
=> upgrade apache dubbo due to security issues

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml
=> upgrade zookeeper jar in examples to match secure version in main pom

pom.xml, shenyu-plugin/shenyu-plugin-cryptor/pom.xml
=> upgrade commons-io due to cve

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AuthPathWarpDTO.java, shenyu-admin/src/main/resources/mybatis/mybatis-config.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/AppAuthControllerTest.java, shenyu-examples/shenyu-examples-springmvc/src/main/resources/context/shenyu.xml
springmvc example register is fail ,it not authed
=> [type:Fixbug]springmvc example register error

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/PluginService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginMapperTest.java
=> [tpye:refactor]code polish in PluginService

shenyu-admin/src/http/http-debug-rule-controller-api.http, shenyu-admin/src/http/http-debug-selector-controller-api.http, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RuleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/SelectorController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/query/RuleQueryCondition.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/query/SelectorQueryCondition.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/SelectorService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml, shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml
=> [ISSUE #3258]rule and selector page list api

shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
=> [type:refactor] optimize response cors headers.

shenyu-common/src/test/java/org/apache/shenyu/common/dto/AppAuthDataTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/AuthParamDataTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/AuthPathDataTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/ConditionDataTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/PluginDataTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/RuleDataTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/SelectorDataTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/WebsocketDataTest.java
Add unit tests for org.apache.shenyu.common.dto
=> [ISSUE #3293] Add unit tests for shenyu-common.

shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
=> [type:refactor] optimize response cros header filter logic.

shenyu-common/src/main/java/org/apache/shenyu/common/timer/TimingWheel.java
=> First take the modulo and then convert to int

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/test/java/org/apache/shenyu/springboot/starter/gateway/ShenyuConfigurationTest.java, shenyu-web/pom.xml, shenyu-web/src/main/java/org/apache/shenyu/web/filter/ExcludeFilter.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/FallbackFilter.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/HealthFilter.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/LocalDispatcherFilter.java, shenyu-web/src/test/java/org/apache/shenyu/web/filter/FallbackFilterTest.java
=> [type: refactor] refactor  shenyu web filter

shenyu-plugin/shenyu-plugin-rewrite/src/test/java/org/apache/shenyu/plugin/rewrite/RewritePluginTest.java, shenyu-plugin/shenyu-plugin-rewrite/src/test/java/org/apache/shenyu/plugin/rewrite/handler/RewritePluginDataHandlerTest.java
=> [type: test]: fixes #3292 Increase the test coverage of package: plugin-rewrite to more than 80%

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/AppAuthController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/MetaDataController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/PluginHandleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ResourceController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RoleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RuleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/SelectorController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuDictController.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/DashboardUserControllerTest.java
Swagger request param currentPage locates in body for get request.
#3251 
=> [ISSUE #3251]Swagger request param currentPage locates in body for get request.

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
=> [type: refactor] refactor shenyu http client

shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/EagerExecutorService.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimitedTaskQueue.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/ShenyuThreadPoolExecutor.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/TaskQueue.java, shenyu-web/src/main/java/org/apache/shenyu/web/configuration/ShenyuThreadPoolConfiguration.java
this PR only refactor shared thread pool.
=> [ISSUE #3303] [type: refactor] refactor shared thread pool

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
=> [ISSUE #3284] correct fix #3063

shenyu-web/src/main/java/org/apache/shenyu/web/filter/AbstractWebFilter.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/ExcludeFilter.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/FallbackFilter.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/HealthFilter.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/LocalDispatcherFilter.java
=> [type: refactor] refactor shenyu filter logic and method name

shenyu-common/src/test/java/org/apache/shenyu/common/config/ShenyuConfigTest.java
test shenyu-common: improve unit test coverage of org.apache.shenyu.common.config
=> [ISSUE #3275] Add unit tests for org.apache.shenyu.common.config

shenyu-web/src/test/java/org/apache/shenyu/web/filter/LocalDispatcherFilterTest.java
// Describe your PR here; eg. Fixes #issueNo 3299
commit LocalDispatcherFilter test case.
=> [ISSUE #3299] Commit LocalDispatcherFilter test case

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DashboardUserMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DataPermissionMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/UserRoleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java, shenyu-admin/src/main/resources/mappers/dashboard-user-sqlmap.xml, shenyu-admin/src/main/resources/mappers/data-permission-sqlmap.xml, shenyu-admin/src/main/resources/mappers/user-role-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DashboardUserServiceTest.java
=> [type:refactor]Code polish in DashboardUserService

shenyu-web/src/test/java/org/apache/shenyu/web/filter/ExcludeFilterTest.java, shenyu-web/src/test/java/org/apache/shenyu/web/filter/FallbackFilterTest.java
[fix #3325 ]optimize the shenyu webfilter unit test.
=> [ISSUE #3325] To optimize the shenyu webfilter unit test.

shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/impl/DivideRuleHandle.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultWrap.java, shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java
=> [type: refactor] refactor shenyu divide plugin

shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/config/ShiroRealm.java
=> [ISSUE #3331] User permissions Exclude admin

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DataPermissionServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/MetaDataServiceTest.java
=> [type:refactor]Code polish in MetaDataService

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/result/ShenyuResultWrap.java, shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/utils/CryptorUtil.java, shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/AlibabaDubboPluginTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/AbstractDubboPlugin.java, shenyu-plugin/shenyu-plugin-grpc/src/main/java/org/apache/shenyu/plugin/grpc/GrpcPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/command/Command.java, shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java, shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/MotanPlugin.java, shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/RateLimiterPlugin.java, shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/Executor.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/RPCMessageWriter.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java, shenyu-plugin/shenyu-plugin-sentinel/src/main/java/org/apache/shenyu/plugin/sentinel/fallback/SentinelFallbackHandler.java, shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/SofaPlugin.java, shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/SpringCloudPlugin.java, shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/TarsPlugin.java, shenyu-plugin/shenyu-plugin-websocket/src/main/java/org/apache/shenyu/plugin/websocket/WebSocketPlugin.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/FileSizeFilter.java
=> [type: refactor] optimize&refactor shenyu result wrap.

shenyu-bootstrap/src/main/resources/application.yml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
=> [type:refactor] fix wrong alignment

shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/handler/TarsPluginDataHandler.java
// Describe your PR here; eg. Fixes TarsPluginDataHandler
=> [type: fix] fix bug of TarsPluginDataHandler, this logic isn't used.

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/PluginHandleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ShenyuDictMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PermissionServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginHandleServiceImpl.java, shenyu-admin/src/main/resources/mappers/plugin-handle-sqlmap.xml, shenyu-admin/src/main/resources/mappers/shenyu-dict-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/PluginHandleMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ShenyuDictMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginHandleServiceTest.java
=> [type: refactor]Code polish in admin.

shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceBeanPostProcessor.java, shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/common/dto/MotanRpcExt.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-api/src/main/java/org/apache/shenyu/examples/motan/service/MotanDemoService.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/TestMotanApplication.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/config/RegistryProperties.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/impl/MotanDemoServiceImpl.java, shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/cache/ApplicationConfigCache.java
// Describe your PR here; eg. Fixes #3173 
You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
You submit test cases (unit or integration tests) that back your changes.
Your local test passed mvn clean install -Dmaven.javadoc.skip=true.
=> [ISSUE #3173] support configurable timeout for MotanPlugin

shenyu-register-center/shenyu-register-instance/pom.xml, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-consul/pom.xml, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-consul/src/main/java/org/apache/shenyu/register/instance/consul/ConsulInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-consul/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.instance.api.ShenyuInstanceRegisterRepository
// Describe your PR here; eg. Fixes #2451
=> [ISSUE #2451] Support regsiter instance to consul

shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/build/Resilience4JBuilderTest.java, shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/conf/Resilience4JConfTest.java, shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/handler/Resilience4JHandlerTest.java
=> Increase the test coverage of package: plugin-resilienct4j to more than 80%

shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/AbstractDubboPlugin.java
=> [type: refactor]Code polish in DubboPlugin

shenyu-register-center/shenyu-register-instance/shenyu-register-instance-consul/src/test/java/org/apache/shenyu/register/instance/consul/ConsulInstanceRegisterRepositoryTest.java
// Describe your PR here; eg. Fixes #3375
=> [ISSUE #3375] Add shenyu-register-instance-consul Test

shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/MemoryLimitCalculatorTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/MemoryLimitedLinkedBlockingQueueTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/MemoryLimitedTaskQueueTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/ShenyuThreadPoolExecutorTest.java
Add unit test cases (#3275) for org.apache.shenyu.common.concurrent 
=> [ISSUE #3275]test common: add unit test cases 

shenyu-common/src/main/java/org/apache/shenyu/common/utils/IpUtils.java
=> [type:refactor] refactor IpUtils#getHost

script/shenyu_checkstyle.xml, shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/EtcdProperties.java
// Describe your PR here; eg. Fixes #3370 
=> [ISSUE #3370] update check style

shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Connect.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MessageType.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/MqttTransportHandler.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/PingReq.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/PingResp.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/Subscribe.java, shenyu-protocol/shenyu-protocol-mqtt/src/main/java/org/apache/shenyu/protocol/mqtt/repositories/SubscribeRepository.java
=> [ISSUE #3118]  feature protocol-mqtt: enhanced mqtt plugin

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/RuleServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/SelectorServiceTest.java
=> [type:refactor] code polish in admin

README.md
=> Update logo in readme, support Github dark mode

shenyu-admin/src/main/java/org/apache/shenyu/admin/aspect/PageableAspect.java, shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/AppAuthMapperTest.java
=> [type: fix]  ci error

shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceBeanPostProcessor.java, shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/common/dto/MotanRpcExt.java, shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java, shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/common/dto/TarsRpcExt.java
// Describe your PR here; eg. Fixes #3414 
=> [ISSUE #3414] optimize rpcExt in motan client and tars client

shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/pg/handler/PostgreSQLBooleanHandler.java, shenyu-admin/src/main/resources/mappers/operation-record-log-sqlmap.xml, shenyu-admin/src/main/resources/sql-script/pg/schema.sql
// Describe your PR here; eg. Fixes #3396
Change:
- Adjusted `PostgreSQLBooleanHandler.java` to fix the type conversion exception bug.
- Table `operation_record_log` requires primary key increment.  Add the `operation_record_log_id_seq` sequence to pg.schema.sql.
=> [ISSUE #3396] Fix type convert exception in `PostgreSQLBooleanHandler.java`.

shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/test/java/org/apache/shenyu/springboot/starter/netty/ShenyuNettyWebServerConfigurationTest.java
=> [type: test] add NettyWebServerConfiguration test

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MetaDataCache.java, shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/handler/DividePluginDataHandler.java, shenyu-plugin/shenyu-plugin-global/pom.xml, shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/DefaultShenyuContextBuilder.java, shenyu-plugin/shenyu-plugin-global/src/main/java/org/apache/shenyu/plugin/global/subsciber/MetaDataCacheSubscriber.java, shenyu-plugin/shenyu-plugin-global/src/test/java/org/apache/shenyu/plugin/global/cache/MetaDataCacheTest.java, shenyu-plugin/shenyu-plugin-global/src/test/java/org/apache/shenyu/plugin/global/subsciber/MetaDataCacheSubscriberTest.java
=> [type:refactor] fix lost logic bug

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListener.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListener.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
=> [ISSUE #3350] why contextpath "/springcloud" != "springcloud" ?

README.md, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboClassTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-dubbo-api/src/main/java/org/apache/shenyu/examples/dubbo/api/service/DubboClassMultiParamService.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-dubbo-api/src/main/java/org/apache/shenyu/examples/dubbo/api/service/DubboClassTestService.java
// Describe your PR here; eg. Fixes #3407
=> [ISSUE 3407] sub task1 add the logic of annotation on the splicing class for apache dubbo client

shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/annotation/ShenyuSpringMvcClient.java
// Describe your PR here; eg. Fixes #3436
=> SpringMvcClient register metadata by default

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/http/apache-dubbo-class-test-api.http, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/http/apache-dubbo-class-test-api.http, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/xml/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/xml/impl/DubboClassTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/resources/spring-dubbo.xml
// Describe your PR here; eg. Fixes #3443
=> Improve example of shenyu-examples-apache-dubbo

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterSpringCloudServiceImplTest.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/annotation/ShenyuSpringCloudClient.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientBeanPostProcessor.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java
// Describe your PR here; eg. Fixes #3436 
=> [ISSUE #3436] task2 SpringCloudClient register more detaild metadata

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/config/NacosConfiguration.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/config/ZookeeperConfiguration.java
=> [type: feature]Data sync configuration.

shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java
=> [type: refactor] reset cache plugin sort.

shenyu-bootstrap/src/main/resources/application.yml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/NettyChannelProperties.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/NettyHttpProperties.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/ShenyuNettyWebServerConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/test/java/org/apache/shenyu/springboot/starter/netty/ShenyuNettyWebServerConfigurationTest.java
optimize netty http server parameters.
=> [type:optimize] optimize netty http server parameters.

shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceBeanPostProcessor.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/impl/MotanDemoServiceImpl.java, shenyu-integrated-test/shenyu-integrated-test-motan/src/test/java/org/apache/shenyu/integrated/test/motan/MotanPluginTest.java
=> [ISSUE 3407] sub task4 add the logic of annotation on the splicing class for motan client #3411 

shenyu-admin/pom.xml, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/bean/DocInfo.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/DocParser.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/DocManagerImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/SwaggerDocParser.java
// Describe your PR here; eg. Fixes #3480
=> Remove fastjson

db/init/oracle/schema.sql, shenyu-admin/pom.xml, shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataBaseConfiguration.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/oracle/OracleSQLPrepareInterceptor.java, shenyu-admin/src/main/resources/mappers/operation-record-log-sqlmap.xml, shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
// Describe your PR here; eg. Fixes #3489
=> Admin module Oracle add operation_ record_ Log table processing

.github/workflows/codeql-analysis.yml
Never start github flow on forked repo.
=> [type:fix] does not run github flow on forked repo

.github/workflows/docker-publish.yml
=> [type:fix] fix docker-public flow issue

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/annotation/ShenyuDubboClient.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboClassTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboClassTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboClassTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/xml/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/xml/impl/DubboClassTestServiceImpl.java
https://github.com/apache/incubator-shenyu/issues/3485
=> [ISSUE 3485] sub task1&2 @AliasFor for @ShenyuDubboClient

pom.xml, shenyu-bootstrap/pom.xml, shenyu-examples/shenyu-examples-grpc/pom.xml, shenyu-examples/shenyu-examples-springcloud/pom.xml, shenyu-integrated-test/shenyu-integrated-test-spring-cloud/pom.xml, shenyu-plugin/shenyu-plugin-sentinel/pom.xml, shenyu-plugin/shenyu-plugin-springcloud/pom.xml, shenyu-register-center/shenyu-register-client/shenyu-register-client-etcd/pom.xml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-springcloud/pom.xml
I have fix question as follow:
task1. set grpc version: 1.33.1
task2. set sentinel 1.8.4
task3. set spring cloud alibaba nacos 2021.0.1.0
task4. fix spring cloud conflict
task5. remove spring cloud conflict package
=> [type:optimize] fix springboot upgrade question

pom.xml, shenyu-register-center/shenyu-register-instance/pom.xml, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-nacos/pom.xml, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-nacos/src/main/java/org/apache/shenyu/register/instance/nacos/NacosInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-nacos/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.instance.api.ShenyuInstanceRegisterRepository, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-nacos/src/test/java/org/apache/shenyu/register/instance/nacos/NacosInstanceRegisterRepositoryTest.java
=> [type:feature] add nacos register for shenyu instance

shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-zookeeper/src/main/java/org/apache/shenyu/register/client/server/zookeeper/ZookeeperClient.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/main/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClient.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/main/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperClient.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperClient.java
=> [type:refactor] make sure zk client delete success

shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/subscriber/MetadataExecutorSubscriber.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/subscriber/URIRegisterExecutorSubscriber.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/disruptor/subscriber/URIRegisterExecutorSubscriberTest.java
=> [type: refactor] refactor uri register

shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/annotation/ShenyuSpringWebSocketClient.java, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/init/SpringWebSocketClientBeanPostProcessor.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-annotation-websocket/src/main/java/org/apache/shenyu/examples/websocket/ws/WsServerEndpoint.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/config/WebSocketConfig.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-reactive-websocket/src/main/java/org/apache/shenyu/examples/websocket/config/WebSocketConfiguration.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-reactive-websocket/src/main/java/org/apache/shenyu/examples/websocket/handler/EchoHandler.java
https://github.com/apache/incubator-shenyu/issues/3485
=> simplify ShenyuSpringWebSocketClient

shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessor.java, shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/common/annotation/ShenyuTarsClient.java, shenyu-client/shenyu-client-tars/src/test/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessorTest.java, shenyu-examples/shenyu-examples-tars/src/main/java/org/apache/shenyu/examples/tars/servant/testapp/impl/HelloServantImpl.java
https://github.com/apache/incubator-shenyu/issues/3485
=> simplify ShenyuTarsClient

shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/annotation/ShenyuSpringMvcClient.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientBeanPostProcessor.java, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/OrderController.java, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/RequestController.java, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/ShenyuClientPathController.java, shenyu-examples/shenyu-examples-https/src/main/java/org/apache/shenyu/examples/https/controller/OrderController.java, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/java/org/apache/shenyu/examples/springmvc/controller/HttpTestController.java, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/java/org/apache/shenyu/examples/springmvc/controller/OrderController.java, shenyu-examples/shenyu-examples-springmvc/src/main/java/org/apache/shenyu/examples/springmvc/controller/HttpTestController.java, shenyu-examples/shenyu-examples-springmvc/src/main/java/org/apache/shenyu/examples/springmvc/controller/OrderController.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/controller/TestHttpController.java
#3485 Simplify the ShenyuSpringMvcClient with `@AliasFor` annotation.
=> [ISSUE #3485]refactor client: simplify the ShenyuSpringMvcClient

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/annotation/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/xml/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/xml/impl/DubboMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/xml/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/impl/DubboMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/java/org/apache/shenyu/examples/apache/dubbo/service/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/impl/MultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/impl/TestServiceImpl.java
https://github.com/apache/incubator-shenyu/issues/3485
=> simplify ShenyuDubboClient

shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcClientEventListener.java, shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/server/GrpcServerRunner.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/main/java/org/apache/dromara/springboot/starter/client/grpc/ShenyuGrpcClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/test/java/org/apache/dromara/springboot/starter/client/grpc/ShenyuGrpcClientConfigurationTest.java
=> [ISSUE #3484] fix grpc client lossless registration

shenyu-examples/shenyu-examples-grpc/pom.xml, shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/aop/Log.java, shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/aop/LogInterceptor.java, shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/echo/EchoServiceImpl.java
see #3523
grpc-client works fine when users use AOP.
=> [ISSUE #3523] add aop for grpc-example

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/http/apache-dubbo-class-test-api.http, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/http/apache-dubbo-test-api.http, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/http/apache-dubbo-class-test-api.http, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/http/apache-dubbo-test-api.http
Add shenyu-example-alibaba-dubbo http
=> Add shenyu-example-alibaba-dubbo http

shenyu-plugin/shenyu-plugin-hystrix/pom.xml, shenyu-plugin/shenyu-plugin-ratelimiter/pom.xml, shenyu-plugin/shenyu-plugin-resilience4j/pom.xml, shenyu-plugin/shenyu-plugin-sentinel/pom.xml
I have finished faultTolerance module upgrade.
=> [type:optimize] dependency upgrade

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/aop/Log.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/aop/LogInterceptor.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/aop/Log.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/aop/LogInterceptor.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/impl/DubboTestServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/aop/Log.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/aop/LogInterceptor.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-spring-cloud-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/spring/cloud/dubbo/service/annotation/impl/TestServiceImpl.java
https://github.com/apache/incubator-shenyu/issues/3523
=> add AOP test for shenyu-client-alibaba-dubbo

shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceBeanPostProcessor.java, shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/common/annotation/ShenyuSofaClient.java, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaClientMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaClientSingleParamServiceImpl.java, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaSingleParamServiceImpl.java
=> Simplify ShenyuSofaClient

shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/pom.xml, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/aop/Log.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/aop/LogInterceptor.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/impl/MotanDemoServiceImpl.java
https://github.com/apache/incubator-shenyu/issues/3523
=> [ISSUE 3523] task6 aop test case for motan

pom.xml, shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/MultiRequestPluginTest.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/JwtPluginTest.java, shenyu-plugin/shenyu-plugin-jwt/pom.xml, shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java, shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/JwtPluginTest.java
=> [type:optimize] upgrade jwt dependency

shenyu-bootstrap/pom.xml
task No. 1 of ISSUE #3556 . quick fix to unblock others who want to use sofa.
=> [ISSUE #3556] add curator 4.0.1 dependency in bootstrap for sofa issue

shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/pom.xml, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/aop/Log.java, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/aop/LogInterceptor.java, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/src/main/java/org/apache/shenyu/examples/sofa/service/impl/SofaSingleParamServiceImpl.java
=> Fix issue #3523，add AOP test for shenyu-client-sofa

shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-redis/src/main/java/org/apache/shenyu/plugin/cache/redis/RedisCache.java
=> [type:refactor] refactor redis blocking get method

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
=> [type:refactor] refactor fixed and elastic connection provider pool

.asf.yaml, README.md
=> rename shenyu to apache shenyu

pom.xml, shenyu-admin/src/main/resources/application-mysql.yml
=> [ISSUE #3511] upgrade mybatis , druid, pagehelper version and test.

shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceEventListener.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-motan/src/main/java/org/apache/shenyu/springboot/starter/client/motan/ShenyuMotanClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-motan/src/test/java/org/apache/shenyu/springboot/starter/client/motan/ShenyuMotanClientConfigurationTest.java
=> fix issue #3484,motan client lossless registration

shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/pom.xml, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/aop/Log.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/aop/LogInterceptor.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/controller/TestHttpController.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-reactive-websocket/pom.xml, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-reactive-websocket/src/main/java/org/apache/shenyu/examples/websocket/aop/Log.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-reactive-websocket/src/main/java/org/apache/shenyu/examples/websocket/aop/LogInterceptor.java
#3523 Add AOP for shenyu-examples-websocket
=> [ISSUE #3523]Add AOP for shenyu-examples-websocket.

shenyu-common/src/main/java/org/apache/shenyu/common/enums/MatchModeEnum.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
Add selector preference.
1. If multiple AND conditions are present, select the condition with the highest match.
2. If the conditions match equally, sort according to the sort field
=> [type:fix]  Sort selection by and condition for selector

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/CachePluginTest.java
The cache plugin has two modes, and this pr tests the two modes together by refactoring the code.
=> [type:Integration Test] Add  redis modle test for cache-plugin 

shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-api/src/main/java/org/apache/shenyu/examples/motan/service/MotanClassDemoService.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/http/motan-class-test-api.http, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/impl/MotanClassDemoServiceImpl.java
Supplementary shenyu-example-motan
=> [type:example] Supplementary shenyu-example-motan

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/DefaultLogCollectorTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/LoggingElasticSearchPluginTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/body/BodyWriterTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/body/LoggingElasticSearchServerHttpResponseTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/config/LogCollectConfigTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/entity/LZ4CompressDataTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/entity/ShenyuRequestLogTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/handler/LoggingElasticSearchPluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/sampler/CountSamplerTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/utils/LogCollectConfigUtilsTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/utils/LogCollectUtilsTest.java
=> [type: test]:Add the unit test of package: plugin-logging-elasticsearch

db/init/mysql/schema.sql, db/init/oracle/schema.sql
Refactor timestamp(0) to timestamp(3) to support millisecond storage
=> [type:refactor] Refactor timestamp(0) to timestamp(3) to support millisecond storage

pom.xml, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
Upgrade shenyu motan plugin dependency and test. About #3511.
=> [ISSUE #3511] Upgrade shenyu motan plugin dependency and test

shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
add license for logging-elasticsearch-plugin
=> add dependency license  for logging-elasticsearch-plugin

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/pom.xml, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/main/java/org/apache/shenyu/plugin/logging/elasticsearch/AbstractLogCollector.java
=> [type:refactor] change logging-elasticsearch-plugin thread pool

shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/MessageWriter.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/NettyClientMessageWriter.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/RPCMessageWriter.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-response/src/main/java/org/apache/shenyu/springboot/starter/plugin/response/ResponsePluginConfiguration.java
=> [new: feature] can custom message writer in response plugin

shenyu-integrated-test/shenyu-integrated-test-combination/script/services.list, shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/RpcAndRequestPluginTest.java, shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/SharedThreadPoolTest.java
=> [ISSUE #3605] Fix the error of combination plugin IT

shenyu-common/src/main/java/org/apache/shenyu/common/enums/PluginEnum.java
=> [type: refactor] add a plugin enum cache, get plugin quickly by name in this cache.

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListener.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListenerTest.java, shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceEventListener.java, shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceEventListener.java, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/init/SpringWebSocketClientEventListener.java
=> [type:refactor] code polish in client

shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/main/java/org/apache/shenyu/springboot/starter/netty/ShenyuNettyWebServerConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-gateway/src/test/java/org/apache/shenyu/springboot/starter/netty/ShenyuNettyWebServerConfigurationTest.java
https://github.com/apache/incubator-shenyu/issues/3570
=> [ISSUE 3570] @ConditionalOnProperty trans camelcase to lower case

pom.xml
=> [type: refactor] update prometheus-java-client.version

shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-http/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/script/services.list, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/LoggingElasticSearchPluginTest.java
=> [type:Integration Test] add integrated-test of logging-elasticsearch-plugin

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/main/java/org/apache/shenyu/plugin/logging/elasticsearch/elasticsearch/ElasticSearchLogCollectClient.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/springboot/starter/plugin/logging/elasticsearch/LoggingElasticSearchPluginConfigurationTest.java
Add logging-elasticsearch spring-boot-starter test
=> [type: test]:Add logging-elasticsearch spring-boot-starter test

shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java
=> [ISSUE #3629 ] fix register-client-http: modify loop error.

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java
=> [ISSUE #3614] admin delay update handle in selector

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java
=> [type: refactor] optimize cors logic.

pom.xml, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/pom.xml
=> pom polish

db/init/oracle/schema.sql
Fix loggingElasticSearch oracle sql
=> Fix loggingElasticSearch oracle sql

pom.xml, shenyu-integrated-test/shenyu-integrated-test-alibaba-dubbo/pom.xml, shenyu-integrated-test/shenyu-integrated-test-apache-dubbo/pom.xml, shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml, shenyu-integrated-test/shenyu-integrated-test-grpc/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/pom.xml, shenyu-integrated-test/shenyu-integrated-test-https/pom.xml, shenyu-integrated-test/shenyu-integrated-test-motan/pom.xml, shenyu-integrated-test/shenyu-integrated-test-sofa/pom.xml, shenyu-integrated-test/shenyu-integrated-test-spring-cloud/pom.xml, shenyu-integrated-test/shenyu-integrated-test-websocket/pom.xml
About #3513 
Former packaging plugin is [dockerfile-maven-plugin](https://github.com/spotify/dockerfile-maven), which is archived now. The new packaging plugin is [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin).
[dockerfile-maven-plugin](https://github.com/spotify/dockerfile-maven) used as:
```xml
<plugin>
<groupId>com.spotify</groupId>
<artifactId>dockerfile-maven-plugin</artifactId>
<version>${dockerfile-maven-plugin.version}</version>
<executions>
<execution>
<id>shenyu-integrated-test-apache-dubbo</id>
<goals>
<goal>build</goal>
</goals>
</execution>
</executions>
<configuration>
<repository>shenyu-integrated-test-apache-dubbo</repository>
<tag>latest</tag>
<buildArgs>
<APP_NAME>shenyu-integrated-test-apache-dubbo</APP_NAME>
</buildArgs> …
```
=> [ISSUE 3513] [Part 1] (only integrated-test now) Change dockerfile-maven-plugin to docker-maven-plugin

shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/oracle/OracleSQLPrepareInterceptor.java
Refactor oracle replace insert into
=> [type:refactor] Refactor oracle replace insert into

shenyu-bootstrap/src/main/resources/application.yml, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/config/HttpClientProperties.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
=> [type: feat] body maxInMemorySize

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java
=> [type: refactor] optimize corss filter logic for safety.

db/init/mysql/schema.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/utils/JsonUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/JsonUtilsTest.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SignPluginTest.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/SignPlugin.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/api/SignService.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/decorator/SignRequestDecorator.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/handler/SignPluginDataHandler.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/handler/SignRuleHandler.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/service/DefaultSignService.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/subscriber/SignAuthDataSubscriber.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/SignPluginTest.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/subscriber/SignAuthDataSubscriberTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sign/src/main/java/org/apache/shenyu/springboot/starter/plugin/sign/SignPluginConfiguration.java
=> [ISSUE #3628] Signature plugin extension

shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/UserRoleMapperTest.java
#3655 Add unit test for user-role-sqlmap
=> [ISSUE #3655]Add unit test for user-role-sqlmap.

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java, shenyu-web/src/test/java/org/apache/shenyu/web/filter/CrossFilterTest.java
=> [type: refactor] support custom origins for cors 'Acess-Control-Allow-Origin'.

shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java, shenyu-web/src/test/java/org/apache/shenyu/web/filter/CrossFilterTest.java
=> [type: refactor] cross origins config from string to set.

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/DocManagerImpl.java
=> [ISSUE #3641] Fix add doc info NullPointerException.

shenyu-plugin/shenyu-plugin-metrics/pom.xml, shenyu-plugin/shenyu-plugin-metrics/src/test/java/org/apache/shenyu/plugin/metrics/MetricsPluginTest.java, shenyu-plugin/shenyu-plugin-metrics/src/test/java/org/apache/shenyu/plugin/metrics/config/MetricTest.java, shenyu-plugin/shenyu-plugin-metrics/src/test/java/org/apache/shenyu/plugin/metrics/prometheus/PrometheusMetricsRegisterTest.java, shenyu-plugin/shenyu-plugin-metrics/src/test/java/org/apache/shenyu/plugin/metrics/reporter/MetricsReporterTest.java
=> [type: test]:Improve the unit test coverage of shenyu-plugin-metrics

shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java
Fixes #3620 
Copy a new list of plugins without affecting the current request being processed.
=> Plugin modification concurrency issues #3620

shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/OperationRecordLogMapperTest.java
=> [ISSUE #3655] add operation-record-log-sqlmap unit test

shenyu-plugin/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutor.java
Reactor netty pollutes stderr by default when timeout exceptions are thrown, showing errors like `io.netty.handler.timeout.ReadTimeoutException: null`
There are two ways to handle this:
- First, pass a custom fallback for each flux timeout to override the default one:
```
.timeout(timeout) // Before
.timeout(timeout, Mono.error(new TimeoutException("Response took longer than timeout: " + timeout)) // After
```
- Second, disabling all netty logs with this configuration line (and manually logging web flux errors with methods like onErrorContinue, ...):
```
logging.level.reactor.netty.http.client.HttpClient=off
```
I choose the first one, it is done like that in other parts of the code. I checked all usages of _WebClient_ and all the timeouts.
The only place where timeouts are not explicitly …
=> #2303 Prevent redundant timeout error by overriding the fallback

pom.xml, shenyu-dist/shenyu-admin-dist/pom.xml, shenyu-dist/shenyu-bootstrap-dist/pom.xml, shenyu-examples/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml, shenyu-examples/shenyu-examples-eureka/pom.xml, shenyu-examples/shenyu-examples-grpc/pom.xml, shenyu-examples/shenyu-examples-http/pom.xml, shenyu-examples/shenyu-examples-https/pom.xml, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/pom.xml, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/pom.xml, shenyu-examples/shenyu-examples-springcloud/pom.xml, shenyu-examples/shenyu-examples-springmvc/pom.xml, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/pom.xml
About #3513 
In this PR, I remove `dockerfile-maven-plugin` totally.
use dockerfile-maven-plugin:
use docker-maven-plugin:
=> [ISSUE 3513] [Part 1] Change dockerfile-maven-plugin to docker-maven-plugin

shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java
=> [type: bug]: fix divide NPE

shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimitCalculator.java, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-etcd/src/main/java/org/apache/shenyu/register/client/server/etcd/client/EtcdClient.java
refactor some code.
MemoryLimitCalculator.java see [dubbo #10178](https://github.com/apache/dubbo/pull/10178)
=> [type: refactor] refactor some code.

shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/AlibabaDubboPluginTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/handler/AlibabaDubboPluginDataTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboGrayLoadBalanceTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/subscriber/AlibabaDubboMetaDataSubscriberTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/test/java/org/apache/shenyu/plugin/alibaba/dubbo/threadpool/SharedThreadPoolTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/ApacheDubboPluginTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCacheTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboGrayLoadBalanceTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/threadpool/SharedThreadPoolTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/test/java/org/apache/shenyu/plugin/dubbo/common/AbstractDubboPluginTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/test/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboConfigCacheTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/test/java/org/apache/shenyu/plugin/dubbo/common/handler/AbstractDubboPluginDataHandlerTest.java
Improve the unit test coverage of shenyu-plugin-dubbo
=> [ISSUE #3674] Improve the unit test coverage of shenyu-plugin-dubbo

README.md
=> [type: refactor]refactor readme

shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springcloud/src/main/java/org/apache/shenyu/springboot/starter/client/springcloud/ShenyuSpringCloudClientConfiguration.java
=> add shenyu.register.enabled

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/main/java/org/apache/shenyu/plugin/aliyun/sls/client/AliyunSlsLogCollectClient.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/main/java/org/apache/shenyu/plugin/aliyun/sls/handler/LoggingAliYunSlsPluginDataHandler.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/test/java/org/apache/shenyu/plugin/aliyun/sls/aliyunsls/AliyunSlsLogCollectClientTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/test/java/org/apache/shenyu/plugin/aliyun/sls/collector/AliyunSlsLogCollectorTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/test/java/org/apache/shenyu/plugin/aliyun/sls/handler/LoggingAliYunSlsPluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/AbstractLoggingPlugin.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/main/java/org/apache/shenyu/plugin/logging/kafka/client/KafkaLogCollectClient.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/main/java/org/apache/shenyu/plugin/logging/kafka/config/KafkaLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/main/java/org/apache/shenyu/plugin/logging/kafka/handler/LoggingKafkaPluginDataHandler.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/test/java/org/apache/shenyu/plugin/logging/kafka/collector/KafkaLogCollectorTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/test/java/org/apache/shenyu/plugin/logging/kafka/handler/LoggingKafkaPluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/test/java/org/apache/shenyu/plugin/logging/kafka/kafka/KafkaLogCollectClientTest.java
=> [type: refactor]refactor logging plugin code

shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-alibaba-dubbo/src/main/java/org/apache/shenyu/springboot/starter/client/alibaba/dubbo/ShenyuAlibabaDubboClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-apache-dubbo/src/main/java/org/apache/shenyu/springboot/starter/client/apache/dubbo/ShenyuApacheDubboClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-common/src/main/java/org/apache/shenyu/springboot/starter/client/common/config/ShenyuClientCommonBeanConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/main/java/org/apache/dromara/springboot/starter/client/grpc/ShenyuGrpcClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-motan/src/main/java/org/apache/shenyu/springboot/starter/client/motan/ShenyuMotanClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-sofa/src/main/java/org/apache/shenyu/springboot/starter/client/sofa/ShenyuSofaClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-spring-websocket/src/main/java/org/apache/shenyu/springboot/starter/client/spring/websocket/ShenyuSpringWebSocketClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springcloud/src/main/java/org/apache/shenyu/springboot/starter/client/springcloud/ShenyuSpringCloudClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springmvc/src/main/java/org/apache/shenyu/springboot/starter/client/springmvc/ShenyuSpringMvcClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-tars/src/main/java/org/apache/shenyu/springboot/starter/client/tars/ShenyuTarsClientConfiguration.java
complete https://github.com/apache/incubator-shenyu/issues/3710
=> [type:feat] add shenyu.register.enabled

shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/loadbalance/ShenyuSpringCloudServiceChooser.java
=> [type:fix] fix timestamp error

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AlertTemplateDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AppAuthDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/DashboardUserDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/DataPermissionDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/MetaDataDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginHandleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/ResourceDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/RoleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/RuleConditionDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/RuleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/SelectorConditionDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/SelectorDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/ShenyuDictDTO.java
Fix the problem of space checking of admin controller string, and change notnull to notblank.
=> [type:bug] Fix the problem of space checking of admin controller string, and change notnull to notblank

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AppAuthDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AuthParamDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AuthPathDTO.java
=> [type:add] Add appauth valid

shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java, shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginLoader.java, shenyu-web/src/main/java/org/apache/shenyu/web/logo/ShenyuLogo.java
=> [type: refactor] Minor changes to the code

db/init/mysql/schema.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, db/upgrade/2.4.3-upgrade-2.5.0-mysql.sql, db/upgrade/2.4.3-upgrade-2.5.0-pg.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/enums/OperatorEnum.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/PathMatchUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/enums/OperatorEnumTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/PathMatchUtilsTest.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/judge/PathPatternPredicateJudge.java, shenyu-plugin/shenyu-plugin-base/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.base.condition.judge.PredicateJudge, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/condition/judge/PredicateJudgeFactoryTest.java
=> [type:  new feature] add support pathPatter

shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimitCalculator.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimiter.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/ShenyuThreadPoolExecutor.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/TaskQueue.java, shenyu-common/src/main/java/org/apache/shenyu/common/timer/HierarchicalWheelTimer.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/BeanHolder.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-handler/src/main/java/org/apache/shenyu/plugin/cache/CachePlugin.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-handler/src/test/java/org/apache/shenyu/plugin/cache/CachePluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-memory/src/main/java/org/apache/shenyu/plugin/cache/memory/MemoryCache.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-memory/src/test/java/org/apache/shenyu/plugin/cache/memory/MemoryCacheTest.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-redis/src/main/java/org/apache/shenyu/plugin/cache/redis/RedisCache.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-redis/src/test/java/org/apache/shenyu/plugin/cache/redis/RedisCacheTest.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-spi/src/main/java/org/apache/shenyu/plugin/cache/ICache.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/main/java/org/apache/shenyu/plugin/aliyun/sls/LoggingAliyunSlsPlugin.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/main/java/org/apache/shenyu/plugin/aliyun/sls/collector/AliyunSlsLogCollector.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/main/java/org/apache/shenyu/plugin/aliyun/sls/handler/LoggingAliyunSlsPluginDataHandler.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/test/java/org/apache/shenyu/plugin/aliyun/sls/LoggingAliyunSlsPluginTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/test/java/org/apache/shenyu/plugin/aliyun/sls/handler/LoggingAliyunSlsPluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/proxy/MotanProxyService.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-logging-aliyun-sls/src/main/java/org/apache/shenyu/springboot/starter/plugin/logging/aliyun/sls/LoggingAliyunSlsPluginConfiguration.java
=> [type:refactor] refactor thread pool and cache pluign

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/RpcParamTransformPlugin.java
if `serverHttpRequest.getBody()` is empty, flatmap will not be entered
=> [type:bug] If the data is empty, RpcParamTransformPlugin may return  an empty response

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java
=> [type:bug] fix metaData event lost id bug

db/init/mysql/schema.sql, db/upgrade/2.4.3-upgrade-2.5.0-mysql.sql
=> [type:fix]fix sql error

shenyu-integrated-test/shenyu-integrated-test-http/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/MockPluginTest.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/ArrayGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/CurrentTimeGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/EmailGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/EnStringGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/Generator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/GeneratorFactory.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/RandomDoubleGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/RandomIntGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/RangeDataGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/ZhStringGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/resources/META-INF/shenyu/org.apache.shenyu.plugin.mock.generator.Generator, shenyu-plugin/shenyu-plugin-mock/src/test/java/org/apache/shenyu/plugin/mock/generator/ArrayGeneratorTest.java
Add integration tests for mock plugin;
Add array generator, support using ${array} to generate array type data;
=> [type:Integration Test] Add integration tests and new feature for mock plugin

.github/workflows/docker-publish-dockerhub.yml, .github/workflows/docker-publish.yml, shenyu-dist/shenyu-admin-dist/pom.xml, shenyu-dist/shenyu-bootstrap-dist/pom.xml, shenyu-dist/shenyu-docker-compose-dist/pom.xml, shenyu-dist/shenyu-docker-compose-dist/src/main/resources/install.sh, shenyu-dist/shenyu-src-dist/pom.xml
=> [type: build] Remove incubating in shenyu-dist

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/bean/UpstreamInstance.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/LoadServiceDocEntryImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/ServiceDocManagerImpl.java
=> [type:refactor]Refactor redundant code

DISCLAIMER, MATURITY.md, NOTICE, shenyu-dist/release_check.py, shenyu-dist/shenyu-admin-dist/src/main/release-docs/DISCLAIMER, shenyu-dist/shenyu-admin-dist/src/main/release-docs/NOTICE, shenyu-dist/shenyu-admin-dist/src/main/release-docs/README.txt, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/DISCLAIMER, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/NOTICE, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/README.txt
=> [type:fix] fix-incubating

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MetaDataCache.java, shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/subscriber/DivideMetaDataSubscriber.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-divide/src/main/java/org/apache/shenyu/springboot/plugin/divide/DividePluginConfiguration.java
=> [type:refactor] code polish in MetaDataCache

shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/consul/ConsulDataChangedInitTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/etcd/EtcdDataChangedInitTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedInitTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/zookeeper/ZookeeperDataChangedInitTest.java
=> [type:test]Add test case for DataChangedInit.

README.md, pom.xml, shenyu-admin/src/main/java/org/apache/shenyu/admin/config/SwaggerConfiguration.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-dist/shenyu-admin-dist/src/main/release-docs/README.txt, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/README.txt, shenyu-dist/shenyu-docker-compose-dist/README.md, shenyu-sync-data-center/shenyu-sync-data-nacos/src/main/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandler.java
=> [type: refactor] remove incubator prefix

shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/MotanPlugin.java, shenyu-plugin/shenyu-plugin-mqtt/src/main/java/org/apache/shenyu/plugin/mqtt/handler/MqttPluginDataHandler.java, shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/SofaPlugin.java, shenyu-plugin/shenyu-plugin-websocket/src/main/java/org/apache/shenyu/plugin/websocket/WebSocketPlugin.java
=> [type: feature] add sofa ,motan ,wesocket plugin not match handler

shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/AbortPolicy.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/DiscardOldestPolicy.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/DiscardPolicy.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemorySafeLinkedBlockingQueue.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/RejectException.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/Rejector.java, shenyu-common/src/test/java/org/apache/shenyu/common/concurrent/MemorySafeLinkedBlockingQueueTest.java
=> [ISSUE #3763] support custom reject in MemorySafeLinkedBlockingQueue

shenyu-bootstrap/src/main/resources/application.yml, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
=> [type: fix] fix selector cache bug

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/ShenyuClientPathController.java, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/router/ShenyuTestHttpRouter.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-annotation-websocket/src/main/java/org/apache/shenyu/examples/websocket/ws/WsServerEndpoint.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/handler/HttpAuthHandler.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/interceptor/WebSocketInterceptor.java
Dear community
refactor system.out.println change to log info
please review code
=> [type:refactor] refactor system.out.println change to  log info

pom.xml, shenyu-bootstrap/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml
=> upgrade to nacos-client 2.0.4 due to cve

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-web/src/main/java/org/apache/shenyu/web/filter/CrossFilter.java, shenyu-web/src/test/java/org/apache/shenyu/web/filter/CrossFilterTest.java
=> [type:feat] cross add originRegex type

script/shenyu_checkstyle.xml, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientURIExecutorSubscriber.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/GsonUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/UpstreamCheckUtilsTest.java, shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/demo/EventServiceImpl.java, shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/demo/HelloServiceImpl.java, shenyu-examples/shenyu-examples-grpc/src/main/java/org/apache/shenyu/examples/grpc/stream/StreamServiceImpl.java, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/config/WsSessionManager.java, shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/cache/ApplicationConfigCache.java
=> [ISSUE #3777] banning #printStackTrace in source code

shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
=> [type:feat] commonBinaryTypes add force-download.

shenyu-examples/shenyu-examples-https/src/main/http/https-test-api-local.http, shenyu-examples/shenyu-examples-https/src/main/http/https-test-api.http, shenyu-examples/shenyu-examples-https/src/main/java/org/apache/shenyu/examples/https/controller/UploadController.java, shenyu-examples/shenyu-examples-springcloud/src/main/http/spring-cloud-test-api-local.http, shenyu-examples/shenyu-examples-springcloud/src/main/http/spring-cloud-test-api.http, shenyu-examples/shenyu-examples-springcloud/src/main/java/org/apache/shenyu/examples/springcloud/controller/UploadController.java, shenyu-integrated-test/shenyu-integrated-test-https/src/test/java/org/apache/shenyu/integrated/test/https/HttpsUploadFileTest.java, shenyu-integrated-test/shenyu-integrated-test-spring-cloud/src/test/java/org/apache/shenyu/integratedtest/springcloud/SpringCloudPluginUploadTest.java
=> [Task #3740] add upload file example and integrated test.

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/init/ContextRegisterListenerTest.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListenerTest.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/test/java/org/apache/shenyu/client/springmvc/init/ContextRegisterListenerTest.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/test/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientEventListenerTest.java, shenyu-client/shenyu-client-tars/src/test/java/org/apache/shenyu/client/tars/TarsContextRefreshedEventListenerTest.java, shenyu-client/shenyu-client-tars/src/test/java/org/apache/shenyu/client/tars/TarsRpcExtTest.java, shenyu-client/shenyu-client-tars/src/test/java/org/apache/shenyu/client/tars/TarsServiceBeanPostProcessorTest.java
Improve the unit test coverage of shenyu-client
=> [type:test] Improve the unit test coverage of shenyu-client

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/main/java/org/apache/springboot/starter/client/grpc/ShenyuGrpcClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/main/resources/META-INF/spring.factories, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/test/java/org/apache/springboot/starter/client/grpc/ShenyuGrpcClientConfigurationTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-grpc/src/test/java/org/apache/springboot/starter/client/grpc/server/ShenyuGrpcServerBuilderTest.java
=> [type: refactor] fix group and package

README.md
=> [type:refactor] Update ShenYu Architecture Image With 3D.

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/AppAuthController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AppAuthDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AuthApplyDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AuthPathApplyDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AuthPathDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/AuthPathWarpDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/DashboardUserDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/MetaDataDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/PluginHandleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/RoleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/SelectorDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/ShenyuDictDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/UserRoleDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/AppAuthControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/DashboardUserControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/PluginHandleControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ShenyuDictControllerTest.java
=> [ISSUE #3157] Optimize admin  dto validate.

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/event/selector/BatchSelectorDeletedEvent.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/publish/RuleEventPublisher.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/publish/SelectorEventPublisher.java, shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml, shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java
When onDeleted, ruleId has been deleted, so change to getPluginNameBySelectorId to get pluginName. 
Fixes #3821.
Fixes #3822.
=> [ISSUE 3822] When onDeleted, ruleId has been deleted, so change to getPluginNameBySelectorId to get pluginName.

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/SelectorDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/SelectorService.java
Fixes #3826
remove `@Valid` , SelectorService#createOrUpdate has necessary validation
=> [type:BUG] admin new selector type is full error.

shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/builder/HystrixBuilder.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/command/Command.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/command/HystrixCommand.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/command/HystrixCommandOnThread.java, shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/handler/HystrixPluginDataHandler.java
=> [type:BUG] hystrix plugin can't circuitBreaker.

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/annotation/ShenyuService.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboClassMultiParamServiceImpl.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/src/main/java/org/apache/shenyu/examples/alibaba/dubbo/service/annotation/impl/DubboClassTestServiceImpl.java
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
#3805
=> [ISSUE #3805] sub task3 add @ShenyuService for `shenyu-client-alibaba-dubbo`

shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/dto/ConditionData.java
=> [type: bug] fix  h2 sql

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListener.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientEventListener.java
=> [ISSUE #3839] fill metadata as much as possible

pom.xml, shenyu-admin/pom.xml
=> [type: refactor] fix: patch license

RELEASE-NOTES.md
=> [type: add]: 2.5.0 RELEASE-NOTES.md

db/init/mysql/schema.sql
=> [type:fix] fix sql error

shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java, shenyu-spi/src/main/java/org/apache/shenyu/spi/Join.java, shenyu-spi/src/test/java/org/apache/shenyu/spi/ExtensionLoaderTest.java, shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/ArrayListSPI.java, shenyu-spi/src/test/java/org/apache/shenyu/spi/fixture/TreeListSPI.java, shenyu-spi/src/test/resources/META-INF/shenyu/org.apache.shenyu.spi.fixture.ListSPI
…tensionLoader.getJoins() method is obtained, it is returned in ascending order.
- [ v] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ v] You submit test cases (unit or integration tests) that back your changes.
- [ v] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.
=>  [type: feature]An order attribute is added to the @Join annotation

.github/workflows/docker-publish-dockerhub.yml
=> [type: build] Fix docker image publish failed in github action

.licenserc.yaml, DISCLAIMER
=> [type: refactor] remove disclaimer

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DashboardUserController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/DashboardUserModifyPasswordDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/DashboardUserDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/DashboardUserService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java
=> [ISSUE #3381]Fix change password error.

pom.xml
Hi, com.squareup.okhttp3:okhttp:3.7.0 has CVE: CVE-2018-20200. Would you please consider upgrading it to 3.12.1 to fix it.  The unit tests have passed:
```[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ shenyu-alert ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.7:report (report) @ shenyu-alert ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for shenyu 2.5.1-SNAPSHOT:
[INFO]
[INFO] shenyu ............................................. SUCCESS [  3.715 s]
[INFO] shenyu-common ...................................... SUCCESS [ 32.140 s]
[INFO] shenyu-disruptor ................................... SUCCESS [  0.457 s]
[INFO] shenyu-spi …
```
=> Upgrade okhttp to a secure version

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ResourceController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/CreateResourceDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/ResourceDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/ResourceService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ResourceServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ResourceControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ResourceServiceTest.java
=> [ISSUE #3896]Fix bug, add menu error.

shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RandomLoadBalancer.java
=> [type: refactor]Refactor random loadbalancer.

shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/AbortPolicy.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/DiscardOldestPolicy.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/DiscardPolicy.java, shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/Rejector.java
see https://github.com/apache/dubbo/pull/10414
=> [type: refactor] use broader interface

shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/RateLimiterPlugin.java, shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/executor/RedisRateLimiter.java, shenyu-plugin/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/response/RateLimiterResponse.java, shenyu-plugin/shenyu-plugin-ratelimiter/src/test/java/org/apache/shenyu/plugin/ratelimiter/RateLimiterPluginTest.java
=> [type:BUG] RateLimiterPlugin concurrent hanlder error.

shenyu-bootstrap/src/main/resources/application.yml, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/collector/AbstractLogCollector.java
Use the data in the configuration file first. If not, create a new one
=> [type: refactor] Fix thread pool

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/WebClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/test/java/org/apache/shenyu/plugin/httpclient/WebClientPluginTest.java
=> [ISSUE #3773] use #exchangeToMono replace #exchange

shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RandomLoadBalancer.java
=> Optimize random algorithm.

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java
=> [type: refactor] refactor ApacheDubboServiceBeanListener

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/MapperConfig.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/oracle/OracleSQLUpdateInterceptor.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/config/MapperConfigTest.java
=> [type:refactor] Refactor admin mapper config

pom.xml, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/spi/HashLoadBalanceTest.java, shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/subsriber/WatcherListener.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-api/src/main/java/org/apache/shenyu/register/instance/api/ShenyuInstanceRegisterRepository.java, shenyu-sdk/pom.xml, shenyu-sdk/src/main/java/org/apache/shenyu/sdk/core/RequestTemplate.java, shenyu-sdk/src/main/java/org/apache/shenyu/sdk/core/ShenyuRequest.java, shenyu-sdk/src/main/java/org/apache/shenyu/sdk/core/ShenyuResponse.java, shenyu-sdk/src/main/java/org/apache/shenyu/sdk/http/api/ShenyuHttpClient.java
=> [type:feat] java sdk module init.

db/upgrade/2.5.0-upgrade-2.5.1-oracle.sql
Add pulsar oracle sql update script.
=> [type:feat] add puslar oracle sql

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/model/bean/RegisterInfo.java, shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
Dear community
I have finished task refactor client sdks alibaba dubbo
please review code.
=> [ISSUE #3932]refactor client sdks alibaba dubbo

shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/websocket/WebsocketDataChangedListenerTest.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/utils/CacheKeyUtils.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/utils/CacheKeyUtilsTest.java, shenyu-plugin/shenyu-plugin-general-context/src/test/java/org/apache/shenyu/plugin/general/context/handler/GeneralContextPluginHandlerTest.java, shenyu-plugin/shenyu-plugin-request/src/test/java/org/apache/shenyu/plugin/request/handler/RequestPluginHandlerTest.java, shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/Resilience4JPluginTest.java, shenyu-plugin/shenyu-plugin-resilience4j/src/test/java/org/apache/shenyu/plugin/resilience4j/handler/Resilience4JHandlerTest.java, shenyu-plugin/shenyu-plugin-rewrite/src/test/java/org/apache/shenyu/plugin/rewrite/handler/RewritePluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-sentinel/src/test/java/org/apache/shenyu/plugin/sentinel/handler/SentinelRuleHandleTest.java, shenyu-plugin/shenyu-plugin-springcloud/src/test/java/org/apache/shenyu/plugin/springcloud/handler/SpringCloudPluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-websocket/src/test/java/org/apache/shenyu/plugin/websocket/handler/WebSocketPluginDataHandlerTest.java
Fixes #3939
modify the cache key value.
=> [type:bug] fix bug issue #3939, modify the cache key value.

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/AbstractListDataChangedListener.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/AbstractNodeDataChangedListener.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/consul/ConsulDataChangedListener.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdDataDataChangedListener.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedListener.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/zookeeper/ZookeeperDataChangedListener.java
refactor shenyu-admin sync data listener.
abstract Template
=> [type:refactor] refactor shenyu-admin sync data listener.

db/init/mysql/schema.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, db/upgrade/2.5.0-upgrade-2.5.1-mysql.sql, db/upgrade/2.5.0-upgrade-2.5.1-oracle.sql, db/upgrade/2.5.0-upgrade-2.5.1-pg.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql
Fixes  #3945 add spring-cloud plugin_handle 
and Fix sql id duplication and sql exception.
=> [type:bug] fix issue #3945 and Fix sql id duplication and sql exception.

shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceEventListener.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-sofa/src/test/java/org/apache/shenyu/springboot/starter/client/sofa/ShenyuSofaClientConfigurationTest.java
Dear community
I have finished task refactor client sdks alibaba sofa
please review code.
=> [ISSUE #3932] Refactor shenyu-client-sofa

shenyu-admin/src/main/resources/sql-script/h2/schema.sql
fix h2 sql by mistakenly deleted
=> [type:bug] fix h2 sql by mistakenly deleted

pom.xml, shenyu-common/pom.xml, shenyu-common/src/main/java/org/apache/shenyu/common/cache/MemorySafeLRUMap.java, shenyu-common/src/main/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMap.java, shenyu-common/src/test/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMapTest.java, shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MetaDataCache.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/MatchDataCacheTest.java
=> [ISSUE 3929] make MetaDataCache#CACHE thread-safe

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-tencent-cls/src/main/java/org/apache/shenyu/plugin/tencent/cls/client/TencentClsLogCollectClient.java
[type:bug] fix TencentClsLogCollectClient#createThreadPoolExecutor input parameter error.
=> [type:bug] fix TencentClsLogCollectClient bug.

shenyu-e2e/pom.xml, shenyu-e2e/shenyu-e2e-case/pom.xml, shenyu-e2e/shenyu-e2e-client/pom.xml, shenyu-e2e/shenyu-e2e-common/pom.xml, shenyu-e2e/shenyu-e2e-engine/pom.xml, shenyu-plugin/shenyu-plugin-metrics/src/main/java/org/apache/shenyu/plugin/metrics/prometheus/PrometheusMetricsService.java, shenyu-sdk/pom.xml, shenyu-sdk/shenyu-sdk-core/pom.xml, shenyu-sdk/shenyu-sdk-spring/pom.xml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-sdk/pom.xml
=> [type: refactor] refactor module

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/fallback/FallbackHandler.java
=> [type:fix] fix sentinel can't fuse

shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceEventListener.java
=> [ISSUE 3932] refactor MotanServiceEventListener

shenyu-dist/shenyu-src-dist/src/main/assembly/source.xml
=> [type:test] exclude module shenyu-e2e from source package

shenyu-admin/src/main/resources/mappers/plugin-sqlmap.xml
=> fix issue 3975: reslove the postgresql error during ShenYu-Admin startup.

db/init/pg/create-table.sql
=> fix issue 3973: modify the non-standard quote(`) which is not supported by PG.

.github/filters.yml, Makefile
Introduced Makefile, we only need to type `make build-all-image` to build compile and build related images.
=> [type:build] provide the Makefile to easier to build image

db/init/mysql/schema.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, db/upgrade/2.5.0-upgrade-2.5.1-mysql.sql, db/upgrade/2.5.0-upgrade-2.5.1-oracle.sql, db/upgrade/2.5.0-upgrade-2.5.1-pg.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/dto/convert/rule/SentinelHandle.java, shenyu-common/src/test/java/org/apache/shenyu/common/dto/convert/rule/SentinelHandleTest.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SentinelPluginTest.java, shenyu-plugin/shenyu-plugin-sentinel/src/main/java/org/apache/shenyu/plugin/sentinel/handler/SentinelRuleHandle.java
add sentinel rule handle parameter.
=> [type:feat] add sentinel rule handle parameter.

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedListener.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/listener/nacos/NacosDataChangedListenerTest.java, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/init/ShenyuServerEndpointerExporter.java, shenyu-common/src/test/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMapTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/main/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-nacos/src/test/java/org/apache/shenyu/register/client/nacos/NacosClientRegisterRepositoryTest.java, shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/handler/NacosCacheHandlerTest.java, shenyu-sync-data-center/shenyu-sync-data-nacos/src/test/java/org/apache/shenyu/sync/data/nacos/handler/NacosMockConfigService.java
Config nacos configType to JSON.
=> [Bug] Config nacos configType to JSON.

shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-zookeeper/src/test/java/org/apache/shenyu/register/client/server/zookeeper/ZookeeperClientTest.java, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-zookeeper/src/test/java/org/apache/shenyu/register/client/server/zookeeper/ZookeeperServerRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/test/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-zookeeper/src/test/java/org/apache/shenyu/register/client/zookeeper/ZookeeperClientTest.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/test/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperClientTest.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/test/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperInstanceRegisterRepositoryTest.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/test/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperClientTest.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/test/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataServiceTest.java
=> [type:test] zookeeper client test.

db/init/mysql/schema.sql, db/upgrade/2.5.0-upgrade-2.5.1-mysql.sql
=> [type:bug] fix sentinel sql bug.

shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/test/java/org/apache/shenyu/register/client/http/utils/SystemUtilsTest.java
=> [type:bug] fix test bug.

shenyu-admin/src/main/resources/mappers/operation-record-log-sqlmap.xml
=> [ISSUE #3993] fix sql fail in operation-record-log-sqlmap.xml support postgresql.

shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/common/dto/MotanRpcExt.java
[ISSUE #4012] fix javadoc warning
=> [ISSUE #4012] fix javadoc warning

shenyu-plugin/shenyu-plugin-cryptor/src/main/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPlugin.java, shenyu-plugin/shenyu-plugin-cryptor/src/test/java/org/apache/shenyu/plugin/cryptor/request/CryptorRequestPluginTest.java, shenyu-plugin/shenyu-plugin-param-mapping/src/main/java/org/apache/shenyu/plugin/param/mapping/strategy/JsonOperator.java, shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/ParamMappingPluginTest.java, shenyu-plugin/shenyu-plugin-param-mapping/src/test/java/org/apache/shenyu/plugin/param/mapping/strategy/JsonOperatorTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-cryptor/src/main/java/org/apache/shenyu/springboot/starter/plugin/cryptor/CryptorPluginConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-cryptor/src/test/java/org/apache/shenyu/springboot/starter/plugin/cryptor/CryptorPluginConfigurationTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-param-mapping/src/main/java/org/apache/shenyu/springboot/starter/plugin/param/mapping/ParamMappingPluginConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-param-mapping/src/test/java/org/apache/shenyu/springboot/starter/plugin/param/mapping/ParamMappingPluginConfigurationTest.java
about #4010
refactor `JsonOperator` `CryptorRequestPlugin` message_readers
=> [type:refactor] refactor_message_readers.

shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java
=> fix issue: correctly parse dubbo.protocol.port=-1

shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/SignPlugin.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/SignPluginTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sign/src/main/java/org/apache/shenyu/springboot/starter/plugin/sign/SignPluginConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-sign/src/test/java/org/apache/shenyu/springboot/starter/plugin/sign/SignPluginConfigurationTest.java
[BUG] <using the Sign Plugin, a DataBufferLimitException occurred when the JSON request was too large> #4010
=> [ISSUE #4010]fix sign plugin DataBufferLimitException error

shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-http/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/LoggingPulsarPluginTest.java
Add Logging-Pulsar integrated test
=> [type:feat] Add Logging-Pulsar integrated test

shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/RequestPlugin.java
=> fix issue: only one cookie in request should can be removed if you want

.github/workflows/e2e.yaml, shenyu-e2e/pom.xml, shenyu-e2e/script/storage_init.sh, shenyu-e2e/script/storage_init_mysql.sh, shenyu-e2e/script/storage_init_postgres.sh, shenyu-e2e/shenyu-e2e-case/src/test/resources/docker-compose.postgres.yml, shenyu-e2e/shenyu-e2e-client/src/test/java/org/apache/shenyu/e2e/client/admin/AdminClientTest.java, shenyu-e2e/shenyu-e2e-engine/src/test/resources/docker-compose.yml
=> [type:test] enable log to console and test with pg

Makefile
[type:bugfix] fix the variables issue and add an image label commit.id
=> [type:bugfix] fix the variables issue and add an image label commit.id

shenyu-e2e/shenyu-e2e-case/src/main/java/org/apache/shenyu/e2e/testcase/common/function/HttpCheckers.java, shenyu-e2e/shenyu-e2e-case/src/main/java/org/apache/shenyu/e2e/testcase/common/function/WaitForHelper.java, shenyu-e2e/shenyu-e2e-case/src/test/resources/log4j2.xml, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/ShenYuLogExtension.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/annotation/ShenYuTest.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/config/ShenYuEngineConfigure.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/scenario/ShenYuScenarioInvocationContextProvider.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/scenario/specification/ScenarioSpecLogProxy.java
=> [type:test] beautify e2e log

db/init/oracle/schema.sql, db/upgrade/2.5.0-upgrade-2.5.1-oracle.sql
=> [ISSUE #4034]fix sql error: missing ';', duplicate id, special table name missing quotation.

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-handler/src/main/java/org/apache/shenyu/plugin/cache/CachePlugin.java, shenyu-plugin/shenyu-plugin-casdoor/src/main/java/org/apache/shenyu/plugin/casdoor/CasdoorPlugin.java, shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java, shenyu-plugin/shenyu-plugin-context-path/src/test/java/org/apache/shenyu/plugin/context/path/ContextPathPluginTest.java, shenyu-plugin/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/DividePlugin.java, shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/SpringCloudPlugin.java, shenyu-plugin/shenyu-plugin-waf/src/main/java/org/apache/shenyu/plugin/waf/WafPlugin.java, shenyu-plugin/shenyu-plugin-websocket/src/main/java/org/apache/shenyu/plugin/websocket/WebSocketPlugin.java
=> [new: feature] not config rule

.asf.yaml
PR is mergeable that required CI and E2E to check past.
=> [type:build] strict to merge pull-request

.asf.yaml, .github/workflows/ci.yml, .github/workflows/e2e.yaml
=> [type:build] fix mergeable conditions

shenyu-common/src/main/java/org/apache/shenyu/common/utils/ParamCheckUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/ParamCheckUtilsTest.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/proxy/AlibabaDubboProxyService.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java, shenyu-plugin/shenyu-plugin-motan/src/main/java/org/apache/shenyu/plugin/motan/proxy/MotanProxyService.java, shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/param/SofaParamResolveServiceImpl.java, shenyu-plugin/shenyu-plugin-sofa/src/main/java/org/apache/shenyu/plugin/sofa/proxy/SofaProxyService.java, shenyu-plugin/shenyu-plugin-sofa/src/test/java/org/apache/shenyu/plugin/sofa/param/SofaBodyParamResolveServiceTest.java, shenyu-plugin/shenyu-plugin-tars/src/main/java/org/apache/shenyu/plugin/tars/util/PrxInfoUtil.java, shenyu-protocol/shenyu-protocol-grpc/src/main/java/org/apache/shenyu/protocol/grpc/constant/GrpcConstants.java, shenyu-protocol/shenyu-protocol-grpc/src/main/java/org/apache/shenyu/protocol/grpc/message/JsonMessage.java
About #3808 
Plugins involved：
- dubbo
- sofa
- motan
- tars
- grpc
example: motan plugin
=> [ISSUE #3808] Checking for empty parameter for plugins.

.github/filters.yml, .github/workflows/e2e.yaml
=> [type:build] skip ci and it when only shenyu-e2e changed

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/exception/ShenyuTimeoutException.java, shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java
=> [ISSUE #4059] optimize request timeout response

shenyu-e2e/pom.xml, shenyu-e2e/shenyu-e2e-case/pom.xml, shenyu-e2e/shenyu-e2e-case/src/test/java/org/apache/shenyu/e2e/testcase/plugin/DividePluginCases.java, shenyu-e2e/shenyu-e2e-client/src/main/java/org/apache/shenyu/e2e/client/admin/AdminClient.java, shenyu-e2e/shenyu-e2e-client/src/main/java/org/apache/shenyu/e2e/client/admin/model/Plugin.java, shenyu-e2e/shenyu-e2e-common/src/main/java/org/apache/shenyu/e2e/common/TableView.java, shenyu-e2e/shenyu-e2e-common/src/test/java/org/apache/shenyu/e2e/common/TableViewTest.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/scenario/ShenYuScenarioInvocationContextProvider.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/service/NamingResolver.java
=> [type:e2e] downgrade shenyu-e2e jdk11 version to jdk8

shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/spi/RoundRobinLoadBalancer.java
=> [type: refactor]Replace with computeIfAbsent.

db/init/mysql/schema.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-common/src/main/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMap.java
=> [ISSUE 4029] add  api doc ddl

shenyu-e2e/script/storage_init_mysql.sh, shenyu-e2e/script/storage_init_postgres.sh
=> [type:bugfix] using the sql script by current branch

.github/workflows/ci.yml, .github/workflows/e2e.yaml
=> fix required jobs success on merge

shenyu-register-center/shenyu-register-instance/shenyu-register-instance-nacos/src/main/java/org/apache/shenyu/register/instance/nacos/NacosInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-nacos/src/test/java/org/apache/shenyu/register/instance/nacos/NacosInstanceRegisterRepositoryTest.java
=> shenyu-register-instance-nacos#selectInstancesAndWatcher

shenyu-sdk/pom.xml, shenyu-sdk/shenyu-sdk-okhttp/pom.xml, shenyu-sdk/shenyu-sdk-okhttp/src/main/java/org/apache/shenyu/sdk/okhttp/OkHttpShenyuHttpClient.java, shenyu-sdk/shenyu-sdk-okhttp/src/test/java/org/apache/shenyu/sdk/okhttp/OkHttpShenyuHttpClientTest.java
=> [type:feat] Sdk okhttpclient. (#3930)

db/init/pg/create-table.sql, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/FieldMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ModelMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/FieldDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/ModelDO.java, shenyu-admin/src/main/resources/mappers/field-sqlmap.xml, shenyu-admin/src/main/resources/mappers/model-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/FieldMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ModelMapperTest.java
=> Implementation FieldMapper and ModelMapper #4029

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java
=> [type:optimize] optimized judgment nonNull

pom.xml, shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/common/annotation/ShenyuMotanService.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-api/pom.xml, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/impl/MotanClassDemoServiceImpl.java, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/java/org/apache/shenyu/examples/motan/service/impl/MotanDemoServiceImpl.java
https://github.com/apache/shenyu/issues/3805
=> [ISSUE #3805] Add simpler client annotations for motan 

shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/path/RegisterPathConstants.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-consul/src/main/java/org/apache/shenyu/register/instance/consul/ConsulInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-consul/src/main/java/org/apache/shenyu/register/instance/consul/TtlScheduler.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-consul/src/test/java/org/apache/shenyu/register/instance/consul/ConsulInstanceRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/main/java/org/apache/shenyu/register/instance/etcd/EtcdClient.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/main/java/org/apache/shenyu/register/instance/etcd/EtcdInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/test/java/org/apache/shenyu/register/instance/etcd/EtcdInstanceRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-nacos/src/main/java/org/apache/shenyu/register/instance/nacos/NacosInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-nacos/src/test/java/org/apache/shenyu/register/instance/nacos/NacosInstanceRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/main/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperInstanceRegisterRepository.java
=> [type:refactor] Refactor persist instance

shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/ApiDocControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/OperationRecordLogControllerTest.java
=> add unit test ApiDocControllerTest & OperationRecordLogControllerTest

shenyu-register-center/shenyu-register-instance/shenyu-register-instance-api/src/main/java/org/apache/shenyu/register/instance/api/ShenyuInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-api/src/main/java/org/apache/shenyu/register/instance/api/path/InstancePathConstants.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/main/java/org/apache/shenyu/register/instance/etcd/EtcdInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-etcd/src/test/java/org/apache/shenyu/register/instance/etcd/EtcdInstanceRegisterRepositoryTest.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-zookeeper/src/main/java/org/apache/shenyu/register/instance/zookeeper/ZookeeperInstanceRegisterRepository.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-sdk/src/main/java/org/apache/shenyu/springboot/starter/sdk/ShenyuSdkAutoConfiguration.java
=> [type:refactor] Refactor sdk code

shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java, shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/JwtPluginTest.java
**test jwt plugin when  convert of handle is null**
[integration testing](javascript:;)
[unit testing](javascript:;)
before the fix
after the fix
=> [type:bugfix] fixed Null Exception when Converter is null

pom.xml, shenyu-bootstrap/pom.xml, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-apache-dubbo/pom.xml
=> [ISSUE #4122] fix dubbo generic call performance bug

shenyu-sdk/pom.xml, shenyu-sdk/shenyu-sdk-httpclient/pom.xml, shenyu-sdk/shenyu-sdk-httpclient/src/main/java/org/apache/shenyu/sdk/httpclient/HttpShenyuSdkClient.java, shenyu-sdk/shenyu-sdk-httpclient/src/test/java/org/apache/shenyu/sdk/httpclient/HttpShenyuSdkClientTest.java
=> [type:feat] shenyu-sdk httpclient use async (#3930)

shenyu-admin/src/test/java/org/apache/shenyu/admin/utils/CommonUpstreamUtilsTest.java
=> test shenyu-admin :add CommonUpstream Util Test.

shenyu-common/src/main/java/org/apache/shenyu/common/constant/DefaultPathConstants.java, shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdClient.java, shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdSyncDataService.java, shenyu-sync-data-center/shenyu-sync-data-etcd/src/test/java/org/apache/shenyu/sync/data/etcd/EtcdSyncDataServiceTest.java
=> [ISSUE #4088] fix sync data by etcd io.vertx.core.VertxException

db/init/oracle/schema.sql
=> [fix issue]ORA-00904: invalid identifier.

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/BaseDataCache.java
Fixes 4071
```java
// total 300 rules
// use synchronized with RULE_MAP, 
// find: total 10 tests, average cost 0.4ms
// remove: total 10 tests, average cost 0.8ms
// use CopyOnWriteArrayList, the larger the amount of rules, the longer the time
// find: total 10 tests, average cost 0.3ms
// remove: total 10 test cases, average cost 1.2ms
```
test cases is: https://paste.ubuntu.com/p/HG7Jv99jPR/
=> [ISSUE #4071] fix ConcurrentModificationException

shenyu-plugin/shenyu-plugin-cryptor/src/test/java/org/apache/shenyu/plugin/cryptor/strategy/RSAStrategyTest.java
=> [test] added RSAStrategy Test

pom.xml, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-eureka/pom.xml, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-eureka/src/main/java/org/apache/shenyu/register/instance/eureka/EurekaInstanceRegisterRepository.java, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-eureka/src/main/resources/META-INF/shenyu/org.apache.shenyu.register.instance.api.ShenyuInstanceRegisterRepository, shenyu-register-center/shenyu-register-instance/shenyu-register-instance-eureka/src/test/java/org/apache/shenyu/register/instance/eureka/EurekaInstanceRegisterRepositoryTest.java
=> [type:feature] shenyu-register-instance-eureka development.

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java
=> [ISSUE #4157]Prevent the first time from failing to load

db/init/oracle/schema.sql, shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/config/ShenyuConfig.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/CommonPluginDataSubscriber.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MatchDataCache.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/cache/MatchDataCacheTest.java, shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java
about #4120
I will refactor it by trie when uri condition
=> [type:feature] add rule cache

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ParameterMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/ParameterDO.java, shenyu-admin/src/main/resources/mappers/parameter-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ParameterMapperTest.java
=> [ISSUE #4029]Add ParameterMapper

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/TagController.java
=> fix ambiguous controller path

shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ApiMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/TagMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ApiServiceTest.java
=> [ISSUE #4029] api improve test case

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-http/src/main/java/org/apache/shenyu/examples/sdk/http/config/SdkConfig.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-http/src/main/java/org/apache/shenyu/examples/sdk/http/controller/HttpServiceController.java, shenyu-sdk/shenyu-sdk-core/src/main/java/org/apache/shenyu/sdk/core/client/AbstractShenyuSdkClient.java, shenyu-sdk/shenyu-sdk-core/src/main/java/org/apache/shenyu/sdk/core/client/ShenyuSdkClient.java, shenyu-sdk/shenyu-sdk-core/src/main/java/org/apache/shenyu/sdk/core/interceptor/ShenyuSdkRequestInterceptor.java, shenyu-sdk/shenyu-sdk-okhttp/src/test/java/org/apache/shenyu/sdk/okhttp/OkHttpShenyuSdkClientTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-sdk/src/main/java/org/apache/shenyu/springboot/starter/sdk/ShenyuSdkAutoConfiguration.java
=> [Task]add SDK ShenyuSdkRequestInterceptor (#3925)

shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/JwtPlugin.java, shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/handle/JwtPluginDataHandler.java, shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/rule/JwtRuleHandle.java, shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/strategy/DefaultJwtConvertStrategy.java, shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/strategy/JwtConvertStrategy.java, shenyu-plugin/shenyu-plugin-jwt/src/main/java/org/apache/shenyu/plugin/jwt/strategy/JwtConvertStrategyFactory.java, shenyu-plugin/shenyu-plugin-jwt/src/test/java/org/apache/shenyu/plugin/jwt/strategy/CustomJwtConvertStrategy.java
about task :#3011
about pr :https://github.com/apache/shenyu/pull/4133
=> eliminate generic warnings

shenyu-common/src/main/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMap.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/cache/MetaDataCache.java
=> [type:fix] fix cache too large

shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-alibaba-dubbo-consumer/src/main/http/sdk-alibaba-dubbo-test-api.http, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-alibaba-dubbo-consumer/src/main/java/org/apache/shenyu/examples/sdk/alibaba/dubbo/consumer/api/ShenyuAlibabaDubboClientApi.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-alibaba-dubbo-consumer/src/main/java/org/apache/shenyu/examples/sdk/alibaba/dubbo/consumer/controller/ShenyuAlibabaDubboSdkExampleController.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-alibaba-dubbo-consumer/src/main/java/org/apache/shenyu/examples/sdk/alibaba/dubbo/consumer/dto/DubboRequestBody.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-alibaba-dubbo-consumer/src/main/java/org/apache/shenyu/examples/sdk/alibaba/dubbo/consumer/dto/DubboTestSaveRequest.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-apache-dubbo-consumer/src/main/http/sdk-apache-dubbo-test-api.http, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-apache-dubbo-consumer/src/main/java/org/apache/shenyu/examples/sdk/apache/dubbo/consumer/api/ShenyuApacheDubboClientApi.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-apache-dubbo-consumer/src/main/java/org/apache/shenyu/examples/sdk/apache/dubbo/consumer/controller/ShenyuApacheDubboSdkExampleController.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-apache-dubbo-consumer/src/main/java/org/apache/shenyu/examples/sdk/apache/dubbo/consumer/dto/DubboRequestBody.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-apache-dubbo-consumer/src/main/java/org/apache/shenyu/examples/sdk/apache/dubbo/consumer/dto/DubboTestSaveRequest.java
=> [Task]add apache and alibaba dubbo sdk examples #3925

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java
=> [type:bugfix] fixed shenyu-admin rule

shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/AppAuthControllerTest.java
=> feat:add unittest

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java, shenyu-examples/shenyu-examples-sdk/pom.xml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/pom.xml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-consumer/Dockerfile, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-consumer/pom.xml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-consumer/src/main/http/sdk-spring-cloud-test-api.http, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-consumer/src/main/java/org/apache/shenyu/examples/sdk/springcloud/consumer/ShenyuSdkSpringCloudConsumerExampleApplication.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-consumer/src/main/java/org/apache/shenyu/examples/sdk/springcloud/consumer/api/ShenyuSpringCloudClientApi.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-consumer/src/main/java/org/apache/shenyu/examples/sdk/springcloud/consumer/controller/ShenyuSdkSpringCloudConsumerController.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-consumer/src/main/java/org/apache/shenyu/examples/sdk/springcloud/consumer/dto/OrderDTO.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-consumer/src/main/resources/application.yaml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-provider/Dockerfile, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-provider/pom.xml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-provider/src/main/java/org/apache/shenyu/examples/sdk/springcloud/provider/ShenyuSdkSpringCloudProviderApplication.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-springcloud/shenyu-examples-sdk-springcloud-provider/src/main/resources/application.yml
=> Task(shenyu-examples-sdk-springcloud) (#3925)

shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/SignPlugin.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/api/SignService.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/api/VerifyResult.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/api/VerifySupplier.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/service/DefaultSignService.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/SignPluginTest.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java
+ Increased readability
+ decoupling
=> [type: refactor] refactor DefaultSignService#signVerify，No functional changes

shenyu-common/src/main/java/org/apache/shenyu/common/utils/HmacUtils.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/MapUtils.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/SignUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/MapUtilsTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/SignUtilsTest.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SignPluginTest.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/api/DefaultSignProvider.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/service/DefaultSignService.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/sign/DefaultSignProviderTest.java, shenyu-web/src/main/java/org/apache/shenyu/web/controller/LocalPluginController.java
Decoupled and enhanced SignUtil. no funtion change .
Added HmacUtils . 
=> [type:refactor]Decoupled and enhanced SignUtil

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SignPluginTest.java, shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/service/DefaultSignService.java, shenyu-plugin/shenyu-plugin-sign/src/test/java/org/apache/shenyu/plugin/sign/service/DefaultSignServiceTest.java
=> [bugfix]fix sign

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/SwaggerDocParser.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java, shenyu-common/src/test/java/org/apache/shenyu/common/enums/PluginEnumTest.java, shenyu-loadbalancer/src/test/java/org/apache/shenyu/loadbalancer/cache/UpstreamCheckTaskTest.java, shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java
Some Collection's `size` is an `O(n)` operation.
we should always prefer `isEmpty` when we what to determine if collection is empty.
=> perf: replace `Collection.size()` with `isEmpty`

shenyu-plugin/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/SignPlugin.java
Fixed this ISSUE #4253  in sign plugin 
=> [ISSUE #4253] fix  #4253 issue  in sign plugin 

shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/generator/ExpressionGenerator.java, shenyu-plugin/shenyu-plugin-mock/src/main/java/org/apache/shenyu/plugin/mock/util/MockUtil.java, shenyu-plugin/shenyu-plugin-mock/src/test/java/org/apache/shenyu/plugin/mock/generator/ExpressionGeneratorTest.java
added array method of expression in mock plugin
Now ,The features of expression genetators include all  other generators' 
=> [type:feature]  added array method of expression in mock plugin

db/init/oracle/schema.sql, db/upgrade/2.5.0-upgrade-2.5.1-mysql.sql, db/upgrade/2.5.0-upgrade-2.5.1-oracle.sql, db/upgrade/2.5.0-upgrade-2.5.1-pg.sql
=> [ISSUE #4029] add api doc upgrade sql

shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCacheManager.java
=> keep the style consistent

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/SignPluginTest.java
added test of requestBody and more other test in SignPluginTest
=> [type:refactor] added test of requestBody and more other test in SignPluginTest

shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuLoaderService.java
=> [type:fix] fix logger clazz

shenyu-bootstrap/pom.xml, shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml
=> Polish maven dependencies of dubbo

shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/TagMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/TagRelationMapper.java, shenyu-admin/src/main/resources/mappers/tag-relation-sqlmap.xml, shenyu-admin/src/main/resources/mappers/tag-sqlmap.xml
=> fix sql problem

shenyu-admin/src/main/java/org/apache/shenyu/admin/validation/validator/ExistedValidator.java
=> [type: refactor]Replace with computeIfAbsent in ExistedValidator.

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuClientHttpRegistryController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/RegisterClientServerDisruptorPublisher.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/executor/RegisterServerConsumerExecutor.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/subscriber/ApiDocExecutorSubscriber.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ApiMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/ApiService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ApiServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterService.java, shenyu-admin/src/main/resources/mappers/api-sqlmap.xml
=> [ISSUE #4029] add shenyu-client-api-doc part2 admin module 

pom.xml, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/test/java/org/apache/shenyu/plugin/logging/kafka/handler/LoggingKafkaPluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/test/java/org/apache/shenyu/plugin/logging/kafka/kafka/KafkaLogCollectClientTest.java
LoggingKafkaPluginDataHandlerTest 60.505
KafkaLogCollectClientTest 60.03
=> [type:test] fix Kafka test takes too long.

.github/workflows/e2e.yaml, RELEASE-NOTES.md, shenyu-plugin/shenyu-plugin-casdoor/pom.xml
=> [type:add] 2.5.1 RELEASE-NOTES.md

db/init/mysql/schema.sql, db/upgrade/2.5.0-upgrade-2.5.1-mysql.sql
=> [type: sql] fix sql

shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE, shenyu-dist/shenyu-admin-dist/src/main/release-docs/NOTICE, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/NOTICE
=> [type:license] update license of admin and bootstrap

NOTICE
=> [type:notice] update notice year

shenyu-dist/shenyu-admin-dist/src/main/release-docs/DISCLAIMER, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/DISCLAIMER
=> [type:dist] remove DISCLAIMER

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/TagDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java, shenyu-client/shenyu-client-api-docs-annotations/src/main/java/org/apache/shenyu/client/apidocs/annotations/ApiDoc.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java, shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/dto/ApiDocRegisterDTO.java
=> [type:refactor] refactor api-doc-client add tag

shenyu-admin/src/main/java/org/apache/shenyu/admin/aspect/DataPermissionAspect.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/subscriber/ApiDocExecutorSubscriber.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/AbstractListDataChangedListener.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdClient.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/bean/DocInfo.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/CreateResourceDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/DashboardUserDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/RoleEditVO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mybatis/oracle/OracleSQLPrepareInterceptor.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/LoadServiceDocEntryImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/CommonUpstreamUtils.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java
Optimize code for shenyu-admin
=> Fix 4354 Optimize code for shenyu-admin

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/UpstreamCheckService.java
=> [type: performance] optimize UpstreamCheckService

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/OperationRecordLog.java, shenyu-admin/src/main/resources/application.yml
=> [type:fix] fix to 24-hour format

shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyService.java, shenyu-plugin/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/test/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboProxyServiceTest.java
=> Dubbo cache bugs

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrieRuleListener.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java
[ISSUE #{4461}] Fix zookeeper sync error
=> fix shenyu-sync-data-zookeeper : modify zookeeper sync delete error

pom.xml, shenyu-dist/shenyu-admin-dist/pom.xml, shenyu-dist/shenyu-bootstrap-dist/pom.xml, shenyu-dist/shenyu-docker-compose-dist/pom.xml, shenyu-dist/shenyu-src-dist/pom.xml
After the upgrade, the lib content is consistent with the maven export dependent lib
=> [type:update] maven-assembly-plugin update version 2.2-beta-5 -> 3.5.0

shenyu-common/src/test/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMapTest.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java
=> [type:fix] fix trie match error

shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperClient.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/main/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperSyncDataService.java, shenyu-sync-data-center/shenyu-sync-data-zookeeper/src/test/java/org/apache/shenyu/sync/data/zookeeper/ZookeeperClientTest.java
fixes #4520, just remove the current child node
=> [type:fix] fix zookeeper sync error

shenyu-common/src/test/java/org/apache/shenyu/common/enums/ApiHttpMethodEnumTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/enums/ApiSourceEnumTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/enums/ApiStateEnumTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/enums/RuleTrieEventEnumTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/enums/TrieMatchModeEnumTest.java
=> [ISSUE #4539] Added enum test cases for common

shenyu-admin/src/test/java/org/apache/shenyu/admin/model/bean/DocParameterTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/model/bean/UpstreamInstanceTest.java
[type:test] add test cases for shenyu-admin.model (#4540)
=> [type:test] add test cases for shenyu-admin.model (#4540)

shenyu-admin/src/test/java/org/apache/shenyu/admin/utils/HttpUtilsTest.java
Add test cases for the HttpUtils class
=> [Task#4540]Add test cases for the HttpUtils class

shenyu-bootstrap/src/main/resources/application.yml, shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.bat, shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/start.sh, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/config/HttpClientProperties.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-httpclient/src/main/java/org/apache/shenyu/springboot/starter/plugin/httpclient/HttpClientPluginConfiguration.java
=> [type:optimize] optimize shenyu parameters

shenyu-client/pom.xml, shenyu-client/shenyu-client-autoconfig/pom.xml, shenyu-client/shenyu-client-autoconfig/src/main/java/org/apache/shenyu/client/auto/config/ClientRegisterConfiguration.java, shenyu-client/shenyu-client-autoconfig/src/main/java/org/apache/shenyu/client/auto/config/EnableClientRegister.java
Implements https://github.com/apache/shenyu/issues/4560  
=> [ISSUE #4560] Initializes spring-boot-client auto config

shenyu-client/shenyu-client-autoconfig/src/main/java/org/apache/shenyu/client/auto/config/ClientRegisterConfiguration.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/constant/ShenyuClientConstants.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/ClientApiRefreshedEventListener.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/matcher/AnnotatedApiBeanMatcher.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/matcher/ApiBeanMatcher.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/parser/ApiDocDefinitionParser.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/parser/ApiMetaBeanParser.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/parser/ApiMetaDefinitionParser.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/registrar/PreApiBeanRegistrar.java
Some class names have been modified to improve readability
=> [type:refactor]rename some class name

pom.xml
=> upgrade hutool 5.8.18

db/init/oracle/schema.sql
=> fix oracle sql

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/ApiBean.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/ClientInfoRefreshedEventListener.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/ClientRegisterConfig.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/ClientRegisterConfigImpl.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/matcher/ApiDocBeanMatcher.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/matcher/ApiDocDefinitionMatcher.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/parser/AbstractApiDocDefinitionParser.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/parser/HttpApiDocDefinitionParser.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/parser/NoHttpApiDocDefinitionParser.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/register/apimeta/SpringMvcApiMetaDefinitionParser.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/register/apimeta/SpringMvcPreApiMetaBeanParser.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/test/java/org/apache/shenyu/client/springmvc/register/apimeta/SpringMvcApiMetaDefinitionParserTest.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/test/java/org/apache/shenyu/client/springmvc/register/apimeta/SpringMvcPreApiMetaBeanParserTest.java, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/ShenyuTestHttpApplication.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springmvc/src/main/java/org/apache/shenyu/springboot/starter/client/springmvc/ShenyuSpringMvcClientInfoRegisterConfiguration.java
Implements https://github.com/apache/shenyu/issues/4560
exmaple:
`@EnableClientRegister `  will enable api collect 
```java
@SpringBootApplication
@EnableClientRegister
public class ShenyuTestHttpApplication {
/**
* main.
*
* @param args args
*/
public static void main(final String[] args) {
SpringApplication.run(ShenyuTestHttpApplication.class, args);
}
}
```
Collection rules
```java
@RestController
@RequestMapping("/oauth")
@ApiModule(value = "oauth")
public class OauthController {
/**
* Test oauth2 code request.
*
* @return String
*/
@GetMapping("/authorize")
@ApiDoc(desc = "authorize")
public String testCode() {
return "authorize";
}
}
```
`/oauth/authorize` will be collected ,`@ApiModule` and `@ApiDoc` must be present at the same time
=> [ISSUE #4560] spring-mvc(boot) client support collect api-doc

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/DiscoveryUpstreamController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ProxySelectorController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DiscoveryUpstreamMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/ProxySelectorMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/DiscoveryUpstreamDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/ProxySelectorDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/DiscoveryUpstreamDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/ProxySelectorDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/query/ProxySelectorQuery.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/ProxySelectorVO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/DiscoveryUpstreamService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/ProxySelectorService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DiscoveryUpstreamServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ProxySelectorServiceImpl.java, shenyu-admin/src/main/resources/mappers/discovery-upstream-sqlmap.xml, shenyu-admin/src/main/resources/mappers/proxy-selector-sqlmap.xml, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/DiscoveryUpstreamMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/ProxySelectorMapperTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/DiscoveryUpstreamServiceTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ProxySelectorServiceTest.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/AdminConstants.java
discovery upstream and proxy selector proxy crud
=> #4534 discovery upstream and proxy selector proxy crud

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/ContextPathPluginTest.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/ShenyuPlugin.java, shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java
=> refactor some code

shenyu-examples/shenyu-examples-https/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-https/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-https/src/main/resources/application.yml
see this : https://github.com/docker-library/openjdk/issues/135
=> fix  docker image build from openjdk11  env set  error

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/DataSyncConfiguration.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ConfigController.java
=> [ISSUE #4629] fix ConfigController loading order

shenyu-common/src/main/java/org/apache/shenyu/common/utils/ListUtil.java, shenyu-common/src/test/java/org/apache/shenyu/common/utils/ListUtilTest.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/trie/ShenyuTrie.java, shenyu-plugin/shenyu-plugin-base/src/test/java/org/apache/shenyu/plugin/base/trie/ShenyuRuleTrieTest.java
=> refactor method name.

shenyu-dist/shenyu-admin-dist/src/main/resources/bin/stop.bat, shenyu-dist/shenyu-bootstrap-dist/src/main/resources/bin/stop.bat
- support shenyu admin service stop script bat in windows `stop.bat`
- support shenyu bootstrap service stop script bat in windows `stop.bat`
=> support shenyu admin, bootstrap service stop script bat in windows

db/init/mysql/schema.sql
=> refactor discovery init sql

README.md
=> docs: precision fix for terminology in the quick start guide

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuClientHttpRegistryController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/subscriber/URIRegisterExecutorSubscriber.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/AbstractShenyuClientRegisterServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDivideServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterService.java, shenyu-client/shenyu-client-brpc/src/main/java/org/apache/shenyu/client/brpc/BrpcContextRefreshedEventListener.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientURIExecutorSubscriber.java, shenyu-client/shenyu-client-dubbo/shenyu-client-alibaba-dubbo/src/main/java/org/apache/shenyu/client/alibaba/dubbo/AlibabaDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-client/shenyu-client-grpc/src/main/java/org/apache/shenyu/client/grpc/GrpcClientEventListener.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListener.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientEventListener.java, shenyu-client/shenyu-client-motan/src/main/java/org/apache/shenyu/client/motan/MotanServiceEventListener.java, shenyu-client/shenyu-client-sofa/src/main/java/org/apache/shenyu/client/sofa/SofaServiceEventListener.java, shenyu-client/shenyu-client-sofa/src/test/java/org/apache/shenyu/client/sofa/SofaServiceEventListenerTest.java, shenyu-client/shenyu-client-tars/src/main/java/org/apache/shenyu/client/tars/TarsServiceBeanEventListener.java, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/init/SpringWebSocketClientEventListener.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-api/src/main/java/org/apache/shenyu/register/client/api/ShenyuClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java, shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/utils/RegisterUtils.java
=> [ISSUE #4686] divide support active offline

shenyu-register-center/shenyu-register-client/shenyu-register-client-http/src/main/java/org/apache/shenyu/register/client/http/HttpClientRegisterRepository.java, shenyu-web/src/main/java/org/apache/shenyu/web/handler/GlobalErrorHandler.java
=> fix token expire bug

shenyu-examples/shenyu-examples-http/src/main/http/http-test-api.http, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java, shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/dto/BigObject.java, shenyu-integrated-test/shenyu-integrated-test-brpc/src/test/java/org/apache/shenyu/integrated/test/brpc/BrpcPluginDemoTest.java, shenyu-integrated-test/shenyu-integrated-test-brpc/src/test/java/org/apache/shenyu/integrated/test/brpc/BrpcPluginTest.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/BigObject.java, shenyu-integrated-test/shenyu-integrated-test-common/src/main/java/org/apache/shenyu/integratedtest/common/dto/ComplexObjects.java, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/HttpTestControllerTest.java
=> [type:feat]  add brpc and http Integration testing cases

shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/register/SpringMvcApiMetaRegister.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/test/java/org/apache/shenyu/client/springmvc/register/SpringMvcApiMetaRegisterTest.java
Adds SpringMvcApiMetaRegisterTest
=> [type:unit test]Adds SpringMvcApiMetaRegisterTest

shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiBeansExtractor.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiMetaRegister.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiBeansExtractorTest.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/test/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiMetaRegisterTest.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springcloud/pom.xml, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springcloud/src/main/java/org/apache/shenyu/springboot/starter/client/springcloud/ShenyuSpringCloudClientConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springcloud/src/main/java/org/apache/shenyu/springboot/starter/client/springcloud/ShenyuSpringCloudClientInfoRegisterConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-client/shenyu-spring-boot-starter-client-springcloud/src/main/resources/META-INF/spring.factories
Implements https://github.com/apache/shenyu/issues/4560
=> [ISSUE #4560] spring-cloud(boot) client support collect metaData and apiDoc

shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
=> [type: license] add license note for kubernetes java client

shenyu-e2e/shenyu-e2e-engine/src/test/java/org/apache/shenyu/e2e/engine/function/WaitForHelperTest.java
switch to a highly available http test web site.
=> switch to a highly available http test web site.

shenyu-examples/shenyu-examples-http/src/main/java/org/apache/shenyu/examples/http/controller/HttpTestController.java, shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/LoggingElasticSearchPluginTest.java, shenyu-integrated-test/shenyu-integrated-test-upload-plugin/shenyu-custom-plugin/pom.xml
some integration testing optimize
1、optimize BigObject response size test case
2、LoggingElasticSearchPluginTest test case config number_of_replicas and auto sharded
=> [type:optimize] some integration testing optimize

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/main/java/org/apache/shenyu/plugin/logging/kafka/client/KafkaLogCollectClient.java
Get topic from config in KafkaLogCollectClient
=> Get topic from config in KafkaLogCollectClient

pom.xml, shenyu-examples/pom.xml, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-annotation-websocket/pom.xml, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/pom.xml, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-native-websocket/src/main/java/org/apache/shenyu/examples/websocket/interceptor/WebSocketInterceptor.java, shenyu-protocol/shenyu-protocol-tcp/pom.xml
=> [type:refactor] remove hutool

pom.xml, shenyu-client/shenyu-client-core/pom.xml, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/utils/OpenApiUtils.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/utils/UrlPathUtils.java
=> feat remove hutool dependent

shenyu-sdk/shenyu-sdk-core/src/test/java/org/apache/shenyu/sdk/core/util/UtilTest.java
=> add test cases for Util class.

shenyu-admin/src/main/resources/sql-script/h2/schema.sql
update h2 schema create table sql
=> update h2 schema create table sql

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/etcd/EtcdDataChangedInit.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-sync-data-center/shenyu-spring-boot-starter-sync-data-etcd/src/main/java/org/apache/shenyu/springboot/sync/data/etcd/EtcdSyncDataConfiguration.java, shenyu-sync-data-center/shenyu-sync-data-etcd/src/main/java/org/apache/shenyu/sync/data/etcd/EtcdSyncDataService.java, shenyu-sync-data-center/shenyu-sync-data-etcd/src/test/java/org/apache/shenyu/sync/data/etcd/EtcdSyncDataServiceTest.java
=> [Discovery] etcd sync discoveryData

shenyu-register-center/shenyu-register-client/shenyu-register-client-consul/src/main/java/org/apache/shenyu/register/client/consul/ConsulClientRegisterRepository.java
Optimize consul, when the metadata does not change, do not perform metadata updates
=>  Optimize consul, when the metadata does not change, do not perform metadata updates

shenyu-common/src/main/java/org/apache/shenyu/common/utils/GsonUtils.java
fix pick 6663e184b Optimize consul, when the metadata does not change, do not perform metadata updates
=> [ISSUE #4833] fix pick 6663e184b Optimize consul, when the metadata does not change, do not perform metadata updates

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/ConsulServerConfiguration.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/config/ConsulServerConfigurationTest.java, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-consul/src/main/java/org/apache/shenyu/register/client/server/consul/ConsulClientServerRegisterRepository.java, shenyu-register-center/shenyu-register-client-server/shenyu-register-client-server-consul/src/test/java/org/apache/shenyu/register/client/server/consul/ConsulServerRegisterRepositoryTest.java
fix shenyu admin cannot configure consule port when using consul as register
=> [ISSUE #4842] fix shenyu admin cannot configure consule port

shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/subscriber/URIRegisterExecutorSubscriber.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/register/ShenyuClientRegisterDivideServiceImpl.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/cache/UpstreamCacheManager.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/handler/DividePluginDataHandler.java
Admin actively synchronizes http service offline events to the gateway
=> [ISSUE #4686] Admin actively synchronizes http service offline events to the gateway

shenyu-admin/src/main/resources/sql-script/h2/schema.sql
=> [type:fix]fix  huaweicloud lts in  scheme.sql of h2

db/init/og/create-table.sql
=> [type:fix]update openGauss sql for tcp plugin

shenyu-registry/shenyu-registry-consul/src/main/java/org/apache/shenyu/registry/consul/ConsulInstanceRegisterRepository.java
=> fix ConsulInstanceRegisterRepository ConsulClient agentAddress port is repeated.

shenyu-admin/src/main/java/org/apache/shenyu/admin/discovery/DiscoveryLevel.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/discovery/DiscoveryMode.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/UpstreamCheckUtils.java, shenyu-common/src/main/java/org/apache/shenyu/common/utils/VersionUtils.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/pom.xml
=> refactor some no need code

RELEASE-NOTES.md, shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE
=> [type:release] add 2.6.0 release notes

shenyu-bootstrap/src/main/resources/application.yml
=> [fix: #4920] optimize minResponseSize

shenyu-dist/shenyu-bootstrap-dist/docker/Dockerfile
Closes #4961.
Comparing to `ghcr.io/apache/shenyu/bootstrap:e8381465caf02063f01abe578c795d90602f3990`
574MB -> 330MB
```
~> docker images ghcr.io/apache/shenyu/bootstrap:e8381465caf02063f01abe578c795d90602f3990
REPOSITORY                        TAG                                        IMAGE ID       CREATED          SIZE
ghcr.io/apache/shenyu/bootstrap   e8381465caf02063f01abe578c795d90602f3990   d9477d05cef5   41 minutes ago   574MB
~> docker history ghcr.io/apache/shenyu/bootstrap:e8381465caf02063f01abe578c795d90602f3990
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
d9477d05cef5   41 minutes ago   ENTRYPOINT ["/bin/sh" "entrypoint.sh"]          0B        buildkit.dockerfile.v0
<missing>      41 minutes ago   EXPOSE …
```
=> Optimize layers of shenyu-bootstrap Docker image

shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-resilience4j/src/main/java/org/apache/shenyu/plugin/resilience4j/executor/CombinedExecutor.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java
=> Avoid permanent overhead of creating TimeoutException

.gitignore, .idea/vcs.xml
Add vcs.xml for easier link to the pr
=> [type:build] Add vcs.xml for easier link to the pr

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/k8s/ingress.yml
Update package name in ingress yml file.
=> [type:fix] Update package name in ingress yml file.

shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/ShenYuExtensionContext.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/service/DockerServiceCompose.java, shenyu-registry/shenyu-registry-core/src/main/java/org/apache/shenyu/registry/core/ShenyuInstanceRegisterRepositoryFactory.java, shenyu-sdk/shenyu-sdk-core/src/main/java/org/apache/shenyu/sdk/core/client/ShenyuSdkClientFactory.java
=> [type: refactor] Simplify Map operations by computeIfAbsent

shenyu-common/src/test/java/org/apache/shenyu/common/cache/MemorySafeLRUMapTest.java, shenyu-common/src/test/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMapTest.java
=> fix unstable CI

shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/scenario/function/WaitForHelper.java
=> WaitForHelper.java  Add Exception Logging

shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
Eliminate compile overhead for each execution.
=> [type: refactor] Use compiled Pattern in WebClientMessageWriter

shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java
Requests other than 200 should not respond normally
=> Optimized code

db/init/mysql/schema.sql, db/init/og/create-table.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, db/upgrade/2.6.0-upgrade-2.6.1-mysql.sql, db/upgrade/2.6.0-upgrade-2.6.1-og.sql, db/upgrade/2.6.0-upgrade-2.6.1-oracle.sql, db/upgrade/2.6.0-upgrade-2.6.1-pg.sql, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/main/java/org/apache/shenyu/plugin/logging/clickhouse/client/ClickHouseLogCollectClient.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/main/java/org/apache/shenyu/plugin/logging/clickhouse/config/ClickHouseLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/main/java/org/apache/shenyu/plugin/logging/clickhouse/constant/ClickHouseLoggingConstant.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/test/java/org/apache/shenyu/plugin/logging/clickhouse/LoggingClickHousePluginTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/test/java/org/apache/shenyu/plugin/logging/clickhouse/client/ClickHouseLogCollectClientTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/test/java/org/apache/shenyu/plugin/logging/clickhouse/config/ClickHouseLogCollectConfigTest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/test/java/org/apache/shenyu/plugin/logging/clickhouse/handler/LoggingClickHousePluginDataHandlerTest.java
=> [feature] clickhouse support ttl

db/init/mysql/schema.sql, db/upgrade/2.5.1-upgrade-2.6.0-mysql.sql, db/upgrade/2.5.1-upgrade-2.6.0-pg.sql
=> Fix upgrade 2.6.0 sql

shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/ShenyuPlugin.java, shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java
=> [type: feature] Plugin of life cycle

shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml
=> [ISSUE #4981] userId can not update success when update auth

shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/alibabadubbo/AlibabaDubboPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/alibabadubbo/DataSynHttpTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/alibabadubbo/DataSynNacosTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/alibabadubbo/DataSynZookeeperTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/apachedubbo/ApacheDubboPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/apachedubbo/DataSynHttpTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/apachedubbo/DataSynNacosTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/apachedubbo/DataSynZookeeperTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-grpc/src/test/java/org/apache/shenyu/e2e/testcase/grpc/DataSynHttpTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-grpc/src/test/java/org/apache/shenyu/e2e/testcase/grpc/DataSynNacosTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-grpc/src/test/java/org/apache/shenyu/e2e/testcase/grpc/DataSynZookeeperTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-grpc/src/test/java/org/apache/shenyu/e2e/testcase/grpc/GrpcPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/java/org/apache/shenyu/e2e/testcase/motan/DataSynHttpTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/java/org/apache/shenyu/e2e/testcase/motan/DataSynNacosTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/java/org/apache/shenyu/e2e/testcase/motan/DataSynZookeeperTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/java/org/apache/shenyu/e2e/testcase/motan/MotanPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-sofa/src/test/java/org/apache/shenyu/e2e/testcase/sofa/DataSynHttpTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-sofa/src/test/java/org/apache/shenyu/e2e/testcase/sofa/DataSynNacosTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-sofa/src/test/java/org/apache/shenyu/e2e/testcase/sofa/DataSynZookeeperTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-sofa/src/test/java/org/apache/shenyu/e2e/testcase/sofa/SofaPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/DataSynHttpTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/DataSynNacosTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/DataSynZookeeperTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/SpringCloudPluginTest.java
Modify the rationale for testing synchronization correctness.
=> [type: refactor] change e2e syn

shenyu-dist/pom.xml, shenyu-dist/shenyu-admin-dist/pom.xml, shenyu-dist/shenyu-bootstrap-dist/pom.xml, shenyu-dist/shenyu-src-dist/pom.xml
Refer to https://github.com/apache/shardingsphere/issues/12902
```
wuweijies-MacBook-Air :: projects/shenyu » cd shenyu-dist/shenyu-admin-dist/target 
wuweijies-MacBook-Air :: shenyu-admin-dist/target » shasum -c *.sha512
apache-shenyu-2.6.1-SNAPSHOT-admin-bin.tar.gz: OK
wuweijies-MacBook-Air :: shenyu-admin-dist/target » ll *.tar.gz*
-rw-r--r--  1 wuweijie  staff   112M Aug 18 22:33 apache-shenyu-2.6.1-SNAPSHOT-admin-bin.tar.gz
-rw-r--r--  1 wuweijie  staff   175B Aug 18 22:33 apache-shenyu-2.6.1-SNAPSHOT-admin-bin.tar.gz.sha512
```
=> [type: release] Auto checksum when packing distribution

shenyu-integrated-test/README.md
=> [ISSUE #5064] Format "Quick start" part in shenyu-integrated-test/README.md

.github/workflows/e2e.yaml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/alibabadubbo/DataSynEtcdTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/resources/docker-compose.mysql.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/apachedubbo/DataSynEtcdTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/resources/docker-compose.mysql.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-grpc/src/test/java/org/apache/shenyu/e2e/testcase/grpc/DataSynEtcdTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-grpc/src/test/resources/docker-compose.mysql.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/java/org/apache/shenyu/e2e/testcase/motan/DataSynEtcdTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/resources/docker-compose.mysql.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/DataSynEtcdTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/resources/docker-compose.mysql.yml, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/handler/DataSyncHandler.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/service/DockerServiceCompose.java
=> [type:refactor] add e2e etcd syn

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker-publish-dockerhub.yml, .github/workflows/docker-publish.yml, .github/workflows/e2e.yaml, .github/workflows/integrated-test-k8s-ingress.yml, .github/workflows/integrated-test.yml, .github/workflows/k8s-examples-http.yml
=> [type:refactor] refactor ci.

pom.xml
Fix kafka dependency management.
=> [type:fix] Fix kafka dependency management

db/upgrade/2.5.1-upgrade-2.6.0-mysql.sql, db/upgrade/2.5.1-upgrade-2.6.0-pg.sql
about https://github.com/apache/shenyu/issues/5010
=> [type:bug]fix sql

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ApiDocController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/DocVO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/MenuDocItemVO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/MenuModuleVO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/MenuProjectVO.java
Update MenuProject, MenuModule, MenuDocItem to VO objects
=> [type:refactor] Update MenuProject, MenuModule, MenuDocItem to VO objects

shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/AbstractRateLimiterAlgorithm.java, shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/ConcurrentRateLimiterAlgorithm.java, shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/RateLimiterAlgorithm.java, shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/algorithm/SlidingWindowRateLimiterAlgorithm.java, shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/executor/RedisRateLimiter.java
No need to convert args to string pass to Lua script
=> [type:polish] No need to convert args to string pass to Lua script

shenyu-examples/shenyu-examples-sdk/pom.xml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/Dockerfile, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/pom.xml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/src/main/http/sdk-http-test-api.http, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/src/main/java/org/apache/shenyu/examples/sdk/feign/ShenyuSdkHttpExampleApplication.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/src/main/java/org/apache/shenyu/examples/sdk/feign/api/ShenyuHttpClientApi.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/src/main/java/org/apache/shenyu/examples/sdk/feign/config/SdkConfig.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/src/main/java/org/apache/shenyu/examples/sdk/feign/controller/HttpServiceController.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/src/main/java/org/apache/shenyu/examples/sdk/feign/controller/ShenyuHttpSdkExampleController.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/src/main/java/org/apache/shenyu/examples/sdk/feign/dto/SdkTestDto.java, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-feign/src/main/resources/application.yaml, shenyu-integrated-test/shenyu-integrated-test-sdk-http/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-sdk-http/src/test/java/org/apache/shenyu/integrated/test/sdk/http/SdkHttpIntegratedTest.java, shenyu-plugin/shenyu-plugin-cache/shenyu-plugin-cache-redis/src/main/java/org/apache/shenyu/plugin/cache/redis/serializer/ShenyuRedisSerializationContext.java, shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/executor/RedisRateLimiter.java, shenyu-plugin/shenyu-plugin-fault-tolerance/shenyu-plugin-ratelimiter/src/main/java/org/apache/shenyu/plugin/ratelimiter/handler/RateLimiterPluginDataHandler.java, shenyu-sdk/shenyu-sdk-feign/src/main/java/org/apache/shenyu/sdk/feign/ShenyuClientCapability.java, shenyu-sdk/shenyu-sdk-feign/src/main/java/org/apache/shenyu/sdk/feign/ShenyuClientsRegistrar.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-sdk-feign/src/main/java/org/apache/shenyu/springboot/starter/sdk/feign/ShenyuSdkAutoConfiguration.java
Add sdk-feign's example and integrated test.
=> [type:feature] Add sdk-feign's example and integrated test.

.github/workflows/ci.yml
It's no need 2 install, verify is enough.
=> [type: refactor] Update mvn install 2 verify.

shenyu-bootstrap/src/main/resources/application.yml, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-websocket/src/main/java/org/apache/shenyu/plugin/websocket/WebSocketPlugin.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/NettyClientMessageWriter.java, shenyu-plugin/shenyu-plugin-response/src/main/java/org/apache/shenyu/plugin/response/strategy/WebClientMessageWriter.java
=> [type:fix] Fix websocket plugin

.github/workflows/k8s-examples-http.yml, shenyu-examples/shenyu-examples-http-swagger2/k8s/script/services.list, shenyu-examples/shenyu-examples-http/k8s/script/healthcheck.sh, shenyu-examples/shenyu-examples-http/k8s/script/services.list, shenyu-examples/shenyu-examples-http/k8s/shenyu-deployment.yml, shenyu-examples/shenyu-examples-http/k8s/shenyu-zookeeper.yml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-http/script/services.list
=> [type:fix] fix k8s example error

.github/workflows/integrated-test-k8s-ingress-motan.yml, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/k8s/ingress.yml, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/k8s/shenyu-examples-motan.yml, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/k8s/shenyu-zookeeper.yml, shenyu-integrated-test/pom.xml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/deploy/deploy-shenyu.yaml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/deploy/kind-config.yaml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/pom.xml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/script/healthcheck.sh, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/script/services.list, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/src/main/java/org/apache/shenyu/integrated/test/k8s/ingress/motan/MotanIngressControllerIntegratedBootstrap.java, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-motan/src/test/java/org/apache/shenyu/integrated/test/k8s/ingress/motan/MotanPluginTest.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/parser/IngressParser.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/parser/MotanIngressParser.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/parser/SpringCloudParser.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/reconciler/IngressReconciler.java
=> add ingress-controller integration motan test

.github/workflows/integrated-test-k8s-ingress-apache-dubbo.yml, shenyu-common/src/main/java/org/apache/shenyu/common/utils/IpUtils.java, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/k8s/ingress.yml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/k8s/shenyu-zookeeper.yml, shenyu-integrated-test/pom.xml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/deploy/deploy-shenyu.yaml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/deploy/kind-config.yaml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/pom.xml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/script/healthcheck.sh, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/script/services.list, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/src/main/java/org/apache/shenyu/integrated/test/k8s/ingress/apache/dubbo/ApacheDubboIngressControllerIntegratedBootstrap.java, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/src/test/java/org/apache/shenyu/integrated/test/k8s/ingress/apache/dubbo/ApacheDubboPluginTest.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/common/IngressConstants.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/parser/DubboIngressParser.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/reconciler/EndpointsReconciler.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/reconciler/IngressReconciler.java
=> add ingress-controller integration apache dubbo test

.github/workflows/integrated-test-k8s-ingress-alibaba-dubbo.yml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/k8s/ingress.yml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/k8s/shenyu-examples-dubbo.yml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/k8s/shenyu-zookeeper.yml, shenyu-integrated-test/pom.xml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/deploy/deploy-shenyu.yaml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/deploy/kind-config.yaml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/pom.xml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/script/healthcheck.sh, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/script/services.list, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/src/main/java/org/apache/shenyu/integrated/test/k8s/ingress/alibaba/dubbo/AlibabaDubboIngressControllerIntegratedBootstrap.java, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-alibaba-dubbo/src/test/java/org/apache/shenyu/integrated/test/k8s/ingress/alibaba/dubbo/AlibabaDubboPluginTest.java
=> [type:Integration Test]: add ingress-controller integration alibaba dubbo test

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AlertDispatchServiceImpl.java
=> [type:bug] fix shenyu-admin cpu surge

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AlertDispatchServiceImpl.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/alert/AlarmSender.java, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/alert/AlarmThreadPoolExecutor.java
- remove alert data queue and fix cpu surge
- add AlarmSender.alarm use note 
=> remove alert data queue and bugfix cpu surge

shenyu-sdk/shenyu-sdk-core/src/main/java/org/apache/shenyu/sdk/core/client/AbstractShenyuSdkClient.java
=> [type:refactor] props get or default

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuClientHttpRegistryController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DiscoveryMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/DiscoveryService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DiscoveryServiceImpl.java, shenyu-admin/src/main/resources/mappers/discovery-sqlmap.xml, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/ClientDiscoveryConfigRefreshedEventListener.java, shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/config/ShenyuDiscoveryConfig.java, shenyu-register-center/shenyu-register-common/src/main/java/org/apache/shenyu/register/common/dto/DiscoveryConfigRegisterDTO.java
=> admin use discovery config init discovery-service

shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/alibabadubbo/AlibabaDubboPluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/alibabadubbo/AlibabaDubboPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/apachedubbo/ApacheDubboPluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/java/org/apache/shenyu/e2e/testcase/apachedubbo/ApacheDubboPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-brpc/src/test/java/org/apache/shenyu/e2e/testcase/brpc/BrpcPluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-brpc/src/test/java/org/apache/shenyu/e2e/testcase/brpc/BrpcPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-grpc/src/test/java/org/apache/shenyu/e2e/testcase/grpc/GrpcPluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/src/test/java/org/apache/shenyu/e2e/testcase/divide/DividePluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/src/test/java/org/apache/shenyu/e2e/testcase/divide/DividePluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/java/org/apache/shenyu/e2e/testcase/motan/MotanPluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/java/org/apache/shenyu/e2e/testcase/motan/MotanPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-sofa/src/test/java/org/apache/shenyu/e2e/testcase/sofa/SofaPluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-sofa/src/test/java/org/apache/shenyu/e2e/testcase/sofa/SofaPluginTest.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/SpringCloudPluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/SpringCloudPluginTest.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/scenario/specification/AfterEachSpec.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/scenario/specification/ScenarioSpecLogProxy.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/scenario/specification/ShenYuAfterEachSpec.java
e2e add waiting. waiting delete selector sync to bootstrap.
=> [type:e2e] e2e add waiting. waiting delete selector sync to bootstrap.

shenyu-common/src/main/java/org/apache/shenyu/common/dto/DiscoveryUpstreamData.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/handler/DivideUpstreamDataHandler.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/handler/DivideUpstreamDataHandlerTest.java, shenyu-protocol/shenyu-protocol-tcp/src/main/java/org/apache/shenyu/protocol/tcp/TcpBootstrapServer.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-divide/src/main/java/org/apache/shenyu/springboot/plugin/divide/DividePluginConfiguration.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-divide/src/test/java/org/apache/shenyu/springboot/plugin/divide/DividePluginConfigurationTest.java
=> [type:feat]  divide plugin adapt discovery 

shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/SpringCloudPluginTest.java, shenyu-web/src/main/java/org/apache/shenyu/web/configuration/SpringExtConfiguration.java, shenyu-web/src/test/java/org/apache/shenyu/web/configuration/SpringExtConfigurationTest.java
fix https://github.com/apache/shenyu/actions/runs/6325504533/job/17177453741
Key words: 
```
INFO [service_name:gateway] STDOUT: Caused by: java.lang.NullPointerException: null
INFO [service_name:gateway] STDOUT: 	at org.apache.shenyu.plugin.api.utils.SpringBeanUtils.getBean(SpringBeanUtils.java:68)
```
so 
=> [type:fix] applicationContextAware initialization too late .

shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/SpringCloudPluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/java/org/apache/shenyu/e2e/testcase/springcloud/SpringCloudPluginTest.java, shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/HttpSyncDataService.java
=> [type:fix] applicationContextAware initialization too late, e2e error.

shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-alibaba-dubbo/src/test/resources/bootstrap-application.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-apache-dubbo/src/test/resources/bootstrap-application.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-brpc/src/test/resources/bootstrap-application.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-grpc/src/test/resources/bootstrap-application.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-motan/src/test/resources/bootstrap-application.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-sofa/src/test/resources/bootstrap-application.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/src/test/resources/bootstrap-application.yml, shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/alert/AlarmServiceImpl.java
change e2e gateway yml config shenyu alert prop
=> change e2e case gateway yml config shenyu alert prop

shenyu-client/shenyu-client-autoconfig/src/main/java/org/apache/shenyu/client/auto/config/ClientRegisterConfiguration.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/registrar/ApiDocRegistrarImpl.java
add ApiDocRegistrar in new design
=> [type:refactor] add ApiDocRegistrar in new design

shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo/script/build_k8s_cluster.sh, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-spring-cloud/script/build_k8s_cluster.sh
fix this bug :
My guess is that eureka didn't finish starting and spring cloud was started, hence the attempt, but it's a random bug that requests multiple tests before the merge is done
=> [type:fix]: fix spring cloud ingress controller bug

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/main/java/org/apache/shenyu/plugin/logging/clickhouse/constant/ClickHouseLoggingConstant.java
=> [type:fix] fix type for status field

shenyu-examples/shenyu-examples-https/pom.xml, shenyu-integrated-test/shenyu-integrated-test-combination/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-grpc/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-https/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-sofa/docker-compose.yml
=> [type:fix] fix integrated test http

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-alibaba-dubbo-service/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/pom.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/pom.xml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-alibaba-dubbo-provider/pom.xml
=> bump zookeeper version 3.5.6 to 3.7.2

db/init/pg/create-table.sql
=> [type:fix] modify the format of field

shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java
=> [type:fix] fix testConcurrentTokenBucket concurrent ci error.

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/event/handle/PluginHandleChangedEvent.java
Fix the dataType error in the contrast method of PluginHandleChangedEvent.(#5231)
=> [type:fix]modify dataType contrast error.

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/resources/shenyu.xml, shenyu-examples/shenyu-examples-eureka/pom.xml, shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-apache-dubbo-provider/src/main/resources/shenyu.xml, shenyu-examples/shenyu-examples-springmvc-tomcat/src/main/resources/context/shenyu.xml, shenyu-examples/shenyu-examples-springmvc/src/main/resources/context/shenyu.xml
=> shenyu-examples: fix spelling

shenyu-sdk/shenyu-sdk-core/src/test/java/org/apache/shenyu/sdk/core/ShenyuRequestTest.java, shenyu-sdk/shenyu-sdk-core/src/test/java/org/apache/shenyu/sdk/core/ShenyuResponseTest.java
Related to https://github.com/apache/shenyu/issues/4537
=> [type:test][ISSUE #4775] Add test case for ShenYu sdk core

shenyu-registry/shenyu-registry-eureka/src/main/java/org/apache/shenyu/registry/eureka/EurekaInstanceRegisterRepository.java, shenyu-registry/shenyu-registry-eureka/src/test/java/org/apache/shenyu/registry/eureka/EurekaInstanceRegisterRepositoryTest.java
=> [BUG #5268] Fix bug when registering with Eureka through EurekaInstanceRegisterRepository#persistInstance.

shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-logging-clickhouse/src/main/java/org/apache/shenyu/springboot/starter/plugin/logging/clickhouse/LoggingClickHousePluginConfiguration.java
=> [type:fix] fix javadoc for logging ClickHouse plugin

shenyu-discovery/shenyu-discovery-etcd/src/test/java/org/apache/shenyu/discovery/etcd/EtcdDiscoveryServiceTest.java
#5278  
- org.apache.shenyu.discovery.etcd.EtcdDiscoveryService
=> [type:test][ISSUE #5278] add unit test for shenyu-discovery-etcd

shenyu-integrated-test/shenyu-integrated-test-http/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-http/pom.xml, shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/LoggingRabbitMqPluginTest.java
this pr is for the integrated-test of logging-rabbitmq-plugin.
=> [type:it] add integrated-test of logging-rabbitmq-plugin.

shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/pom.xml, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/test/java/org/apache/shenyu/client/spring/websocket/init/ShenyuServerEndpointerExporterTest.java, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/test/java/org/apache/shenyu/client/spring/websocket/init/SpringWebSocketClientEventListenerTest.java
related to https://github.com/apache/shenyu/issues/4547
=> [type:UT][ISSUE #4547] Add unit test for shenyu-client-spring-websocket

shenyu-admin/src/main/resources/banner.txt, shenyu-bootstrap/src/main/resources/banner.txt
=> [type:refactor] Refactor banner

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/handler/AbstractLogPluginDataHandler.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-rocketmq/src/main/java/org/apache/shenyu/plugin/logging/rocketmq/handler/LoggingRocketMQPluginDataHandler.java
=> [type:fix]fix logging plugin

README.md
Add quickstart parameters and improve the overall description
This makes it easier for users to get started
=> Update README.md - Fix the mistake in the quickstart.

RELEASE-NOTES.md
=> [type:release] add release doc 2.6.1

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/AbstractLoggingPlugin.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/handler/AbstractLogPluginDataHandler.java
=> [type:fix]fix logging handler bug

shenyu-web/src/main/java/org/apache/shenyu/web/handler/ShenyuWebHandler.java, shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuExtPathPluginJarLoader.java, shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuLoaderService.java, shenyu-web/src/main/java/org/apache/shenyu/web/loader/ShenyuPluginClassloaderHolder.java, shenyu-web/src/test/java/org/apache/shenyu/web/loader/ShenyuLoaderServiceTest.java
and pr https://github.com/apache/shenyu-dashboard/pull/380
=> [type:refactor] refactor plugin loader

db/init/pg/create-table.sql
Fixed PluginHandle list：
Fixed json formatting issues with the PluginHandle list query
=> （Fixed PluginHandle list，#5370）Update create-table.sql，postgres

shenyu-admin/src/main/resources/mappers/shenyu-dict-sqlmap.xml
=> [type:fix] fix admin: show the dictCode

shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-plugin/shenyu-plugin-security/shenyu-plugin-sign/src/main/java/org/apache/shenyu/plugin/sign/extractor/VersionTwoExtractor.java
=> [type:fix]fix authorization conflict in sign plugins

db/init/mysql/schema.sql, db/init/og/create-table.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, db/upgrade/2.6.0-upgrade-2.6.1-mysql.sql, db/upgrade/2.6.0-upgrade-2.6.1-og.sql, db/upgrade/2.6.0-upgrade-2.6.1-oracle.sql, db/upgrade/2.6.0-upgrade-2.6.1-pg.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql
=> [type:feat]logging plugins supports samplerate configuration at the plugin level and selector level.

shenyu-discovery/shenyu-discovery-eureka/src/test/java/org/apache/shenyu/discovery/eureka/EurekaDiscoveryServiceTest.java, shenyu-discovery/shenyu-discovery-nacos/src/test/java/org/apache/shenyu/discovery/nacos/NacosDiscoveryServiceTest.java
This pull request mainly adds unit tests for the `EurekaDiscoveryService`， related to https://github.com/apache/shenyu/issues/5278
=> [type: fesat] Add EurekaDiscoveryService unit test

shenyu-plugin/shenyu-plugin-context-path/src/main/java/org/apache/shenyu/plugin/context/path/ContextPathPlugin.java
=> [type:fix] fix context path error

NOTICE, RELEASE-NOTES.md, shenyu-dist/shenyu-admin-dist/src/main/release-docs/LICENSE, shenyu-dist/shenyu-admin-dist/src/main/release-docs/NOTICE, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/NOTICE
=> [type:release] Release 2.6.1

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/CreateResourceDTO.java
add First Leve Menu  failed parentId  not allow null
=> [type:fix]add First Leve Menu  failed parentId  not allow null

shenyu-client/shenyu-client-motan/test/MotanServiceEventListenerTest.java
=> shenyu-client-motan test case

shenyu-client/shenyu-client-core/src/test/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientURIExecutorSubscriberTest.java
=> Add test case for ShenyuClientURIExecutorSubscriber

shenyu-client/shenyu-client-core/src/test/java/org/apache/shenyu/client/core/exception/ShenyuClientIllegalArgumentExceptionTest.java
=> Add test case for `ShenyuClientIllegalArgumentException`

shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-alibaba-dubbo/src/main/java/org/apache/shenyu/plugin/alibaba/dubbo/cache/AlibabaDubboConfigCache.java
misspelling:refernce->reference
=> misspelling:refernce->reference

shenyu-e2e/shenyu-e2e-common/src/main/java/org/apache/shenyu/e2e/model/Plugin.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/utils/LogCollectConfigUtils.java
=> [type:fix]fix logging plugin sample bug

shenyu-bootstrap/src/main/resources/application.yml, shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/ShenyuPlugin.java
=> [type:refactor] print plugin execute time

.github/workflows/integrated-test.yml, shenyu-integrated-test/pom.xml, shenyu-integrated-test/shenyu-integrated-test-combination/src/test/java/org/apache/shenyu/integrated/test/combination/RequestAndResponsePluginTest.java, shenyu-integrated-test/shenyu-integrated-test-rewrite/Dockerfile, shenyu-integrated-test/shenyu-integrated-test-rewrite/docker-compose.yml, shenyu-integrated-test/shenyu-integrated-test-rewrite/pom.xml, shenyu-integrated-test/shenyu-integrated-test-rewrite/script/healthcheck.sh, shenyu-integrated-test/shenyu-integrated-test-rewrite/script/services.list, shenyu-integrated-test/shenyu-integrated-test-rewrite/src/main/java/org/apache/shenyu/integrated/test/rewrite/RewriteIntegratedBootstrap.java, shenyu-integrated-test/shenyu-integrated-test-rewrite/src/main/resources/application-local.yml, shenyu-integrated-test/shenyu-integrated-test-rewrite/src/main/resources/application.yml, shenyu-integrated-test/shenyu-integrated-test-rewrite/src/test/java/org/apache/shenyu/integrated/test/rewrite/ContextPathAndRewritePluginTest.java
=> fix rewrite integrated test

shenyu-sync-data-center/shenyu-sync-data-api/src/main/java/org/apache/shenyu/sync/data/core/AbstractNodeDataSyncService.java
=> fix comments

shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/AccessTokenManager.java
refactor shenyu-sync-data-http : replace log %s -> {}.
=> refactor shenyu-sync-data-http : replace log %s -> {}.

shenyu-sync-data-center/shenyu-sync-data-api/src/main/java/org/apache/shenyu/sync/data/core/AbstractNodeDataSyncService.java
AbstractNodeDataSyncService load discoverUpstream on startup Fixes #5472
=> AbstractNodeDataSyncService load discoverUpstream on startup (#5472)

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/RuleController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/SelectorController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/SelectorService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml, shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/RuleControllerTest.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/controller/SelectorControllerTest.java
Optimize dashboard experience: convenient for users to quickly switch Selector/Rule status
=> New API: supports batch modification of selector/rule status

shenyu-alert/src/main/resources/static/mailAlarm.html
=> add missing license

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/k8s/shenyu-examples-dubbo.yml, shenyu-examples/shenyu-examples-eureka/k8s/shenyu-examples-eureka.yml, shenyu-examples/shenyu-examples-grpc/k8s/shenyu-examples-grpc.yml, shenyu-examples/shenyu-examples-http/k8s/shenyu-examples-http.yml, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/k8s/shenyu-examples-motan.yml, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/k8s/shenyu-examples-sofa.yml, shenyu-examples/shenyu-examples-springcloud/k8s/shenyu-examples-springcloud.yml, shenyu-examples/shenyu-examples-websocket/shenyu-example-spring-annotation-websocket/k8s/shenyu-example-spring-annotation-websocket.yml
=> [ISSUE #5490] k8s liveness probe can not run wget command error

shenyu-examples/shenyu-examples-eureka/k8s/shenyu-examples-eureka.yml
=> fix k8s ci

.github/workflows/e2e-k8s.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-http/k8s/shenyu-examples-http.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-spring-cloud/k8s/shenyu-examples-springcloud.yml, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-websocket/k8s/shenyu-examples-websocket.yml
=> fix e2e test case can not run wget command

shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/bean/StatelessAuthFilter.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-storage/k8s/script/e2e-h2.sh
=> [type:feature] support get token from header\param\cookie

.github/workflows/ci.yml
=> [type: TASK] remove macos ci #5558

shenyu-registry/shenyu-registry-eureka/src/main/java/org/apache/shenyu/registry/eureka/EurekaInstanceRegisterRepository.java
Steps To Reproduce
On the master branch, run the test case code.
```
public static void main(final String[] args) {
EurekaInstanceRegisterRepository eurekaInstanceRegisterRepository = new EurekaInstanceRegisterRepository();
RegisterConfig config = new RegisterConfig();
config.setServerLists("http://localhost:8761/eureka/");
eurekaInstanceRegisterRepository.init(config);
InstanceEntity instanceEntity = new InstanceEntity("shenyu", "127.0.0.1", 12345);
eurekaInstanceRegisterRepository.selectInstances("other name");
eurekaInstanceRegisterRepository.persistInstance(instanceEntity);
while (true) {
try {
Thread.sleep(1000);
} catch (InterruptedException e) {
e.printStackTrace();
}
}
}
```
error log:
```
Exception in thread "main" java.lang.NullPointerException
at …
```
=> [type:fix] Fix the bug of being unable to query without registration

.github/workflows/e2e-k8s.yml, shenyu-admin/src/main/java/org/apache/shenyu/admin/config/ClusterConfiguration.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/config/properties/ClusterProperties.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/websocket/WebsocketCollector.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mode/cluster/filter/ClusterForwardFilter.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mode/cluster/impl/jdbc/ClusterSelectMasterServiceJdbcImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mode/cluster/service/ShenyuClusterService.java, shenyu-admin/src/main/resources/application.yml, shenyu-alert/src/main/java/org/apache/shenyu/alert/config/RestTemplateConfig.java, shenyu-alert/src/main/java/org/apache/shenyu/alert/strategy/AbstractAlertNotifyHandler.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-cluster/src/test/java/org/apache/shenyue/e2e/testcase/cluster/DividePluginCases.java, shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-cluster/src/test/java/org/apache/shenyue/e2e/testcase/cluster/DividePluginTest.java, shenyu-e2e/shenyu-e2e-client/src/main/java/org/apache/shenyu/e2e/client/admin/AdminClient.java, shenyu-e2e/shenyu-e2e-engine/src/main/java/org/apache/shenyu/e2e/engine/ShenYuExtension.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/cache/ServiceInstanceCache.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/listener/SpringCloudHeartBeatListener.java, shenyu-sync-data-center/shenyu-sync-data-websocket/src/main/java/org/apache/shenyu/plugin/sync/data/websocket/client/ShenyuWebsocketClient.java
for fixing e2e chunck header error
=> [type:fix] fixing e2e chunk header error

shenyu-bootstrap/src/main/resources/application.yml
=> [type:fix] close rule cache

shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/context/DivideShenyuContextDecorator.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/context/DivideShenyuContextDecoratorTest.java
about #5606 
fix divide logging request method
=> fix  divide logging request method

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/AbstractLoggingPlugin.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/entity/ShenyuRequestLog.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-divide/src/main/java/org/apache/shenyu/plugin/divide/context/DivideShenyuContextDecorator.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-divide/src/test/java/org/apache/shenyu/plugin/divide/context/DivideShenyuContextDecoratorTest.java
about #5606 
logging add field requestMethod
=> logging plugin  add requestMethod

pom.xml, shenyu-bootstrap/pom.xml, shenyu-client/shenyu-client-sofa/pom.xml, shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE, shenyu-examples/shenyu-examples-sofa/shenyu-examples-sofa-service/pom.xml, shenyu-integrated-test/shenyu-integrated-test-combination/pom.xml, shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-sofa/pom.xml, shenyu-integrated-test/shenyu-integrated-test-sofa/pom.xml
arrange sofa common tools dependencies
=> [type:feature] arrange sofa common tools dependencies

.devcontainer/devcontainer.json, .gitpod.yml, .licenserc.yaml, README.md, pom.xml
=> Support `Contribute with Gitpod`.

shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml
Fixes : https://github.com/apache/shenyu/issues/5631
=> [type:bugfix][ISSUE #5631]resolve the sql error in rule-sqlmap.xml

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DashboardUserServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/shiro/config/ShiroRealm.java
Fix HTTP registration failure when the client ID is changed.
=> [Fix] fix client id register problem

shenyu-examples/shenyu-examples-springmvc/src/main/resources/context/shenyu.xml
fix shenyu-examples-springmvc start failed bug. Fixes #5661 
=> fix shenyu-examples-springmvc start failed. (#5661)

shenyu-admin/src/main/resources/mappers/namespace-plugin-rel-sqlmap.xml
=> [type:fix] remove an extra comma

shenyu-admin/src/main/resources/mappers/namespace-plugin-rel-sqlmap.xml, shenyu-admin/src/test/java/org/apache/shenyu/admin/mapper/NamespacePluginRelMapperTest.java
=> [type:fix] fix BadSqlGrammarException

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/NamespacePluginController.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/AppAuthMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/DiscoveryMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/MetaDataMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/RuleMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/mapper/SelectorMapper.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/dto/NamespaceSyncDTO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/model/entity/NamespacePluginRelDO.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/AppAuthService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/DiscoveryService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/MetaDataService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/NamespacePluginService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/SelectorService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DiscoveryServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/NamespacePluginServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/NamespaceServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SelectorServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/SyncDataServiceImpl.java, shenyu-admin/src/main/resources/mappers/app-auth-sqlmap.xml, shenyu-admin/src/main/resources/mappers/discovery-sqlmap.xml, shenyu-admin/src/main/resources/mappers/meta-data-sqlmap.xml, shenyu-admin/src/main/resources/mappers/namespace-plugin-rel-sqlmap.xml, shenyu-admin/src/main/resources/mappers/rule-sqlmap.xml, shenyu-admin/src/main/resources/mappers/selector-sqlmap.xml
=> [type:feat]Synchronize data under namespace

shenyu-admin/src/main/resources/mappers/namespace-plugin-rel-sqlmap.xml, shenyu-spi/src/main/java/org/apache/shenyu/spi/ExtensionLoader.java
=> [type:fix]Fix namespace plugin enable switch

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/AbstractLoggingPlugin.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/entity/ShenyuRequestLog.java
=> [type:feat] logging adapt namespace

.github/workflows/integrated-test-k8s-ingress.yml
=> [type:fix] close k8s ingress sofa

shenyu-admin/src/main/java/org/apache/shenyu/admin/listener/AbstractDataChangedListener.java, shenyu-kubernetes-controller/src/main/java/org/apache/shenyu/k8s/parser/SpringCloudParser.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-pulsar/src/main/java/org/apache/shenyu/plugin/logging/pulsar/config/PulsarLogCollectConfig.java, shenyu-sdk/shenyu-sdk-core/src/main/java/org/apache/shenyu/sdk/core/retry/Retryer.java, shenyu-sync-data-center/shenyu-sync-data-polaris/src/main/java/org/apache/shenyu/sync/data/polaris/PolarisSyncDataService.java
=> [improve] code according to code specifications(#5725)

shenyu-admin-listener/shenyu-admin-listener-api/src/main/java/org/apache/shenyu/admin/listener/AbstractNodeDataChangedListener.java, shenyu-admin-listener/shenyu-admin-listener-api/src/main/java/org/apache/shenyu/admin/listener/AbstractPathDataChangedListener.java, shenyu-admin/src/main/resources/mappers/namespace-plugin-rel-sqlmap.xml
=> [type:fix] fix shenyu admin namespace sync

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-kafka/src/main/java/org/apache/shenyu/plugin/logging/kafka/client/KafkaLogCollectClient.java
=> [type:fix] Set up callback for send message on Kafka

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/resources/shenyu.xml
=> [type:fix] fix example TestApacheDubboXmlApplication start failed

shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-annotation/src/main/resources/application.yml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service-xml/src/main/resources/spring-dubbo.xml, shenyu-examples/shenyu-examples-dubbo/shenyu-examples-apache-dubbo-service/src/main/resources/spring-dubbo.xml
=> [type:fix] config dubbo serialize-check-status=DISABLE

shenyu-admin/src/main/resources/sql-script/h2/schema.sql
=> [type:bugfix] fix namespace user rel h2 sql

shenyu-admin/src/main/java/org/apache/shenyu/admin/config/HttpLongPollingSyncConfiguration.java
=> [type:bugfix] fix http sync ci error

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginHandleServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginHandleServiceTest.java
=> [type:fix] filter disable dict option

shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/ApacheDubboPlugin.java
=> [type:fix] set timeout which from rule handle to dubbo rpc context

shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboGrayLoadBalance.java
=> [type:fix] non null validation for upstream which obtained from select

shenyu-examples/shenyu-examples-sdk/shenyu-examples-sdk-dubbo/shenyu-examples-sdk-apache-dubbo-provider/src/main/resources/shenyu.xml
=> [type:fix] fix ShenyuApacheDubboXmlProviderApplication config

shenyu-admin/src/main/java/org/apache/shenyu/admin/model/vo/NamespacePluginVO.java, shenyu-admin/src/main/resources/mappers/namespace-plugin-rel-sqlmap.xml
=> [type:improve] add pluginRelId field for query

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DataPermissionServiceImpl.java
=> [type:bugfix] remove useless log

shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/handler/SpringCloudPluginDataHandler.java
=> [fix:bugfix] readYmlBuildRepository NPE (#5818)

shenyu-admin/src/main/resources/mappers/namespace-plugin-rel-sqlmap.xml
=> [fix:bugfix] fix shenyu-admin plugin can't operate (#5821)

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/main/java/org/apache/shenyu/plugin/logging/elasticsearch/config/ElasticSearchLogCollectConfig.java
close https://github.com/apache/shenyu/issues/5829
=> [ISSUE #5829] Class ElasticSearchLogConfig set function of indexName field missing

shenyu-registry/shenyu-registry-eureka/pom.xml
=> [type:chore] delete duplicate maven in shenyu-registry-eureka.xml

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/AbstractLoggingPlugin.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-console/src/main/java/org/apache/shenyu/plugin/logging/console/LoggingConsolePlugin.java
=> [type:fix] fix LoggingPlugin error log catch .

shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/SpringCloudPlugin.java
=> [type:bugfix] springCloud ruleData path setting didn't used #5840

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ConfigsServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/ExportImportConstants.java
config export support plugin template data
=> [type:feature] config export support plugin template data

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/NamespacePluginService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/PluginService.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/ConfigsServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/NamespacePluginServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/ConfigsServiceTest.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/ExportImportConstants.java
=> [type:feature] namespace export operation

shenyu-dist/shenyu-bootstrap-dist/src/main/release-docs/LICENSE
=> [type:release] fix license

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/collector/AbstractLogCollector.java
=> [type:fix] Fix the issue of potential OutOfMemoryError in the logging plugin developed based on logging-common.

shenyu-client/shenyu-client-autoconfig/src/main/java/org/apache/shenyu/client/auto/config/ClientRegisterConfiguration.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientApiDocExecutorSubscriber.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientMetadataExecutorSubscriber.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/exception/ShenyuClientIllegalArgumentException.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/ClientApiRefreshedEventListener.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/extractor/BaseApiBeansExtractor.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/registrar/ApiRegistrar.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/registrar/BaseApiRegistrarImpl.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/shutdown/ShutdownHookManager.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/init/SpringCloudClientEventListener.java, shenyu-client/shenyu-client-http/shenyu-client-springcloud/src/main/java/org/apache/shenyu/client/springcloud/register/SpringCloudApiMetaRegister.java, shenyu-client/shenyu-client-http/shenyu-client-springmvc/src/main/java/org/apache/shenyu/client/springmvc/init/SpringMvcClientEventListener.java, shenyu-client/shenyu-client-websocket/shenyu-client-spring-websocket/src/main/java/org/apache/shenyu/client/spring/websocket/init/ShenyuServerEndpointerExporter.java
=> [type:refactor] Optimize code for shenyu-client

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/NamespacePluginServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/NamespacePluginServiceTest.java
=> [type:fix] active plugin filtered by enable

shenyu-discovery/shenyu-discovery-nacos/src/main/java/org/apache/shenyu/discovery/nacos/NacosDiscoveryService.java, shenyu-disruptor/src/main/java/org/apache/shenyu/disruptor/consumer/QueueConsumer.java, shenyu-loadbalancer/src/main/java/org/apache/shenyu/loadbalancer/entity/Upstream.java, shenyu-plugin/shenyu-plugin-api/src/main/java/org/apache/shenyu/plugin/api/exception/ResponsiveException.java
=> [type:refactor] Optimize code style

shenyu-admin/src/main/resources/sql-script/h2/schema.sql
=> [type:bugfix] fix h2 sql

README.md
modify README.md  jdk1.8 -> jdk17
=> [release] modify README.md

shenyu-web/src/main/java/org/apache/shenyu/web/configuration/RestTemplateConfiguration.java, shenyu-web/src/test/java/org/apache/shenyu/web/configuration/RestTemplateConfigurationTest.java
=> [type:refactor]Add test case for RestTemplateConfiguration

shenyu-web/src/test/java/org/apache/shenyu/web/endpoint/ShenyuControllerEndpointTest.java
=> [type:refactor]Add test case for ShenyuControllerEndpoint

shenyu-web/src/test/java/org/apache/shenyu/web/filter/CollapseSlashesFilterTest.java
=> [type:refactor]Add test case for CollapseSlashesFilter

db/upgrade/2.6.1-upgrade-2.7.0-mysql.sql
[type:fix] remove duplicate entry '1792749362445840479' for key resource.PRIMARY from resource table https://github.com/apache/shenyu/issues/5895
=> [type:fix] remove duplicate entry '1792749362445840479' for key resource.PRIMARY from resource table 

db/upgrade/2.6.1-upgrade-2.7.0-mysql.sql
=> Revert "[type:fix] remove duplicate entry '1792749362445840479' for key resource.PRIMARY from resource table "

shenyu-web/src/test/java/org/apache/shenyu/web/loader/ShenyuPluginClassLoaderHolderTest.java
=> [type:refactor]Add test case for ShenyuPluginClassLoaderHolder

.github/workflows/e2e-k8s.yml
=> upgrede upload/dowmload-artifact version v3 to v4

db/upgrade/2.6.1-upgrade-2.7.0-mysql.sql
=> [type:fix]Fix upgrade sql

db/upgrade/2.6.1-upgrade-2.7.0-mysql.sql, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/body/LoggingServerHttpRequest.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/body/LoggingServerHttpResponse.java, shenyu-sync-data-center/shenyu-sync-data-api/src/main/java/org/apache/shenyu/sync/data/core/AbstractNodeDataSyncService.java
=> [type:fix]fix 2.6.1 to 2.7.0 upgrade.sql

pom.xml, shenyu-infra/pom.xml, shenyu-infra/shenyu-infra-redis/pom.xml, shenyu-infra/shenyu-infra-redis/src/main/java/org/apache/shenyu/infra/redis/RedisProperties.java, shenyu-infra/shenyu-infra-redis/src/test/java/org/apache/shenyu/infra/redis/RedisPropertiesTest.java
=> [type:feat] add shenyu infra module

shenyu-client/shenyu-client-dubbo/shenyu-client-apache-dubbo/src/main/java/org/apache/shenyu/client/apache/dubbo/ApacheDubboServiceBeanListener.java, shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/dto/DubboRpcExt.java, shenyu-client/shenyu-client-dubbo/shenyu-client-dubbo-common/src/main/java/org/apache/shenyu/client/dubbo/common/dto/DubboRpcMethodExt.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/cache/ApacheDubboConfigCache.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-apache-dubbo/src/main/java/org/apache/shenyu/plugin/apache/dubbo/proxy/ApacheDubboGrayLoadBalance.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboMethodParam.java, shenyu-plugin/shenyu-plugin-proxy/shenyu-plugin-rpc/shenyu-plugin-dubbo/shenyu-plugin-dubbo-common/src/main/java/org/apache/shenyu/plugin/dubbo/common/cache/DubboParam.java
=> [type:fix] set dubbo method config in reference

shenyu-admin/src/main/resources/sql-script/h2/schema.sql
=> [type:fix] fix h2 database wrong json

shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/client/AbstractContextRefreshedEventListener.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/registrar/AbstractApiDocRegistrar.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/register/registrar/ApiDocRegistrarImpl.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/utils/OpenApiUtils.java
=> [type:feature] parse return type when build api doc

shenyu-plugin/shenyu-plugin-ai-proxy/src/main/java/org/apache/shenyu/plugin/ai/proxy/AiProxyPlugin.java, shenyu-plugin/shenyu-plugin-ai-proxy/src/main/java/org/apache/shenyu/plugin/ai/proxy/strategy/openai/OpenAI.java
=> [refactor] ai proxy plugin refactor

shenyu-admin/src/main/resources/application-mysql.yml
add jdbc properties, for mysql 8+ 
=> [feat] add jdbc properties

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-common/src/main/java/org/apache/shenyu/common/constant/AdminConstants.java
fix upload jar checkfile
fix: https://github.com/apache/shenyu/issues/5854
=> [fix] fix upload jar checkfile

shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/ShenyuClientHttpRegistryController.java
[fix] fix shenyu-client-2.6.1 register to shenyu-admin  failed
=> [type:fix] fix 2.6.1 shenyu-client register failed

db/upgrade/2.5.1-upgrade-2.6.0-mysql.sql, db/upgrade/2.5.1-upgrade-2.6.0-oracle.sql, db/upgrade/2.5.1-upgrade-2.6.0-pg.sql, db/upgrade/2.6.1-upgrade-2.7.0-mysql.sql, db/upgrade/2.6.1-upgrade-2.7.0-og.sql, db/upgrade/2.6.1-upgrade-2.7.0-oracle.sql, db/upgrade/2.6.1-upgrade-2.7.0-pg.sql
fix upgrade sql bug
link: https://github.com/apache/shenyu/issues/5961
=> [fix] fix upgrade sql bug

shenyu-admin/src/main/java/org/apache/shenyu/admin/disruptor/subscriber/URIRegisterExecutorSubscriber.java, shenyu-client/shenyu-client-core/src/main/java/org/apache/shenyu/client/core/disruptor/subcriber/ShenyuClientURIExecutorSubscriber.java
=> [fix] fix heartbeat logic

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/main/java/org/apache/shenyu/plugin/logging/clickhouse/config/ClickHouseLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-clickhouse/src/test/java/org/apache/shenyu/plugin/logging/clickhouse/handler/LoggingClickHousePluginDataHandlerTest.java
fix(logging-clickhouse): avoid unnecessary config refresh when clickhouse config unchanged.
=> fix(logging-clickhouse): avoid unnecessary config refresh when clickhouse config unchanged.

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/DiscoveryServiceImpl.java, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/MetaDataServiceImpl.java
Ensure data consistency by adding @Transactional
=> [type:fix] fix(admin): Ensure data consistency by adding @Transactional

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AppAuthServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/AppAuthServiceTest.java
- Refactor original flawed condition check.
- Extract validation method to resolve operator precedence issue.
=> [type:fix] (admin-appAuth): Fix path validation logic defects

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/AlertReceiverServiceImpl.java
Fix the problem where deleting cache first might load stale data in matchReceiverByRules.
=> [type:fix] fix(admin): Fix dirty data issue caused by cache deletion order in AlertDispatchServiceImpl.

db/init/mysql/schema.sql, db/init/ob/schema.sql, db/init/og/create-table.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, db/upgrade/2.7.0-upgrade-2.7.1-mysql.sql, db/upgrade/2.7.0-upgrade-2.7.1-ob.sql, db/upgrade/2.7.0-upgrade-2.7.1-og.sql, db/upgrade/2.7.0-upgrade-2.7.1-oracle.sql, db/upgrade/2.7.0-upgrade-2.7.1-pg.sql, shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginHandleServiceImpl.java, shenyu-admin/src/main/resources/sql-script/h2/schema.sql
Fixed configuration import issue caused by deletion of SpringCloud plugin_handle
=> fix admin:import comfig error.

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/main/java/org/apache/shenyu/plugin/logging/elasticsearch/config/ElasticSearchLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-elasticsearch/src/test/java/org/apache/shenyu/plugin/logging/elasticsearch/handler/LoggingElasticSearchPluginDataHandlerTest.java
Problem Description: When updating the username, password, or authCache configurations, the program failed to correctly detect the changes and refresh the configuration, causing the new values to not take effect.
=> [type:fix] (logging-elasticsearch): Fixed the issue where Elasticsearch log configuration was not refreshed correctly after modification.

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-tencent-cls/src/main/java/org/apache/shenyu/plugin/tencent/cls/config/TencentLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-tencent-cls/src/test/java/org/apache/shenyu/plugin/tencent/cls/handler/LoggingTencentClsPluginDataHandlerTest.java
Problem Description: When updating the SampleRate configurations, the program failed to correctly detect the changes and refresh the configuration, causing the new values to not take effect.
=> [type:fix] (logging-tencent): Fixed the issue where Tencent log configuration was not refreshed correctly after modification.

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/main/java/org/apache/shenyu/plugin/aliyun/sls/config/AliyunLogCollectConfig.java, shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-aliyun-sls/src/test/java/org/apache/shenyu/plugin/aliyun/sls/handler/LoggingAliyunSlsPluginDataHandlerTest.java
Problem Description: When updating the `SampleRate`, `BufferQueueSize`, `MaxRequestBody`, or `MaxResponseBody` configurations, the program failed to correctly detect the changes and refresh the configuration, causing the new values to not take effect.
=> [type:fix] (logging-aliyun): Fixed the issue where Aliyun log configuration was not refreshed correctly after modification.

shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/DefaultRetryStrategy.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/ExponentialRetryBackoffStrategy.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/FixedRetryStrategy.java, shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/RetryStrategy.java
=> [fix] fix java doc

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/manager/impl/LoadServiceDocEntryImpl.java
fix doc pulling error 
https://github.com/apache/shenyu/issues/6015
=> [fix] fix doc pulling error

README.md
=> [feat] update badge

db/init/mysql/schema.sql, db/init/ob/schema.sql, db/init/og/create-table.sql, db/init/pg/create-table.sql, db/upgrade/2.7.0-upgrade-2.7.1-mysql.sql, db/upgrade/2.7.0-upgrade-2.7.1-ob.sql, db/upgrade/2.7.0-upgrade-2.7.1-og.sql, db/upgrade/2.7.0-upgrade-2.7.1-oracle.sql, db/upgrade/2.7.0-upgrade-2.7.1-pg.sql
fix sql fields to not required
=> fix：update ai proxy plugin_handle to not required

README.md
fix readme.md quickstart by docker
=> [fix] fix README.md quickstart(docker)

.github/workflows/e2e-k8s.yml, db/init/mysql/schema.sql, db/init/ob/schema.sql, db/init/og/create-table.sql, db/init/oracle/schema.sql, db/init/pg/create-table.sql, db/upgrade/2.7.0-upgrade-2.7.1-mysql.sql, db/upgrade/2.7.0-upgrade-2.7.1-ob.sql, db/upgrade/2.7.0-upgrade-2.7.1-og.sql, db/upgrade/2.7.0-upgrade-2.7.1-oracle.sql, db/upgrade/2.7.0-upgrade-2.7.1-pg.sql, shenyu-admin/src/main/resources/sql-script/h2/schema.sql, shenyu-plugin/shenyu-plugin-ai/shenyu-plugin-ai-request-transformer/src/main/java/org/apache/shenyu/plugin/ai/transformer/request/handler/AiRequestTransformerPluginHandler.java
=> fix plugin-ai-request-transformer :fix UI error

RELEASE-NOTES.md, shenyu-examples/shenyu-examples-motan/shenyu-examples-motan-service/src/main/resources/application.yml, shenyu-plugin/shenyu-plugin-mock/src/test/java/org/apache/shenyu/plugin/mock/generator/RandomDoubleGeneratorTest.java
Summary
fix motan-examples application name
fix spelling in release notes
fix typo in RandomDoubleGeneratorTest
Testing
mvn -version (fails: command not found)
from chatgpt codex
=> Fix spelling errors and code issues.

shenyu-e2e/shenyu-e2e-case/shenyu-e2e-case-logging-kafka/compose/shenyu-kafka-compose.yml
=> [fix] fix ci modify kafka version

shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/AbstractShenyuPlugin.java, shenyu-spring-boot-starter/shenyu-spring-boot-starter-plugin/shenyu-spring-boot-starter-plugin-ai-request-transformer/src/main/java/org/apache/shenyu/springboot/starter/plugin/ai/transformer/request/AiRequestTransformerPluginConfiguration.java
=> [fix] ai request transformer plugin

shenyu-admin/src/main/resources/application-mysql.yml, shenyu-admin/src/main/resources/application.yml
=> [fix] fix application.xml

shenyu-infra/shenyu-infra-nacos/src/test/java/org/apache/shenyu/infra/nacos/config/NacosConfigTest.java
fix bug: NacosConfig Test error. #6114 
=> Bugfix:NacosConfig Test error

shenyu-registry/shenyu-registry-etcd/src/test/java/org/apache/shenyu/registry/etcd/EtcdInstanceRegisterRepositoryTest.java
fix:EtcdInstanceRegisterRepositoryTest run error. #6125 
=> [fix] EtcdInstanceRegisterRepositoryTest run error

shenyu-plugin/shenyu-plugin-mcp-server/src/main/java/org/apache/shenyu/plugin/mcp/server/callback/ShenyuToolCallback.java, shenyu-plugin/shenyu-plugin-mcp-server/src/main/java/org/apache/shenyu/plugin/mcp/server/manager/ShenyuMcpServerManager.java, shenyu-plugin/shenyu-plugin-mcp-server/src/main/java/org/apache/shenyu/plugin/mcp/server/response/ShenyuMcpResponseDecorator.java, shenyu-plugin/shenyu-plugin-mcp-server/src/test/java/org/apache/shenyu/plugin/mcp/server/McpServerPluginIntegrationTest.java, shenyu-plugin/shenyu-plugin-mcp-server/src/test/java/org/apache/shenyu/plugin/mcp/server/McpServerPluginTest.java, shenyu-plugin/shenyu-plugin-mcp-server/src/test/java/org/apache/shenyu/plugin/mcp/server/callback/ShenyuToolCallbackTest.java, shenyu-plugin/shenyu-plugin-mcp-server/src/test/java/org/apache/shenyu/plugin/mcp/server/handler/McpServerPluginDataHandlerTest.java, shenyu-plugin/shenyu-plugin-mcp-server/src/test/java/org/apache/shenyu/plugin/mcp/server/manager/ShenyuMcpServerManagerTest.java, shenyu-plugin/shenyu-plugin-mcp-server/src/test/java/org/apache/shenyu/plugin/mcp/server/request/RequestConfigHelperTest.java, shenyu-plugin/shenyu-plugin-mcp-server/src/test/java/org/apache/shenyu/plugin/mcp/server/utils/JsonSchemaUtilTest.java, shenyu-plugin/shenyu-plugin-mcp-server/src/test/resources/application-test.yml
fix: increase default timeout and improve error handling in MCP tools
=> fix: increase default timeout and improve error handling in MCP tools

shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/PluginServiceImpl.java, shenyu-admin/src/test/java/org/apache/shenyu/admin/service/PluginServiceTest.java
replace deprecated Base64 class with java.util.Base64 
close: #6129 
=> fix: replace deprecated Base64 class with java.util.Base64 

shenyu-integrated-test/shenyu-integrated-test-motan/src/test/java/org/apache/shenyu/integrated/test/motan/MotanPluginTest.java
=> Modify the test data of the sample test MotanPluginTest

shenyu-sync-data-center/shenyu-sync-data-http/src/main/java/org/apache/shenyu/sync/data/http/AccessTokenManager.java, shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/AccessTokenManagerFixTest.java, shenyu-sync-data-center/shenyu-sync-data-http/src/test/java/org/apache/shenyu/sync/data/http/AccessTokenManagerTest.java
=> fix: fix shenyu-sync-data-http sync password error

shenyu-plugin/shenyu-plugin-logging/shenyu-plugin-logging-common/src/main/java/org/apache/shenyu/plugin/logging/common/utils/LogCollectUtils.java
=> [type:optimize] Optimize LogCollectUtils
